.include "macro.inc"
/* W64-A18: residual segment of data_8010CCD4 -- labels no recon TU defines
 * (or a record tail a recon TU's section stops short of).
 * Linked by BOTH lanes. */

.section .data, "wa"

/* Generated by spimdisasm 1.40.2 */

nonmatching AIHigh_Player_kNumArrestsByLap

dlabel AIHigh_Player_kNumArrestsByLap
    /* FD698 8010CE98 03000000 */ .word 0x00000003
    /* FD69C 8010CE9C 05000000 */ .word 0x00000005
    /* FD6A0 8010CEA0 08000000 */ .word 0x00000008
enddlabel AIHigh_Player_kNumArrestsByLap

.align 2