.include "macro.inc"
/* ============================================================
 * W64-A18  BLOB-vs-TU OWNERSHIP SWEEP -- SPLAT-LANE FILLER ONLY
 *
 * This segment's data is OWNED by
 *     build/recon/eaclib/psx/eacpsxz/matrix.c.o
 * (section .rodata, retail 0x801237ec..0x80123820), whose own bytes were
 * proved byte-identical to retail before the cut (ownmap2 E1-E5, with
 * R_MIPS_32 relocations RESOLVED against the retail VA map).
 *
 * The RECON-lane linker script must link that object's .rodata here and must
 * NOT link this file -- otherwise every label below is multiply defined.
 * It stays in the tree only so the legacy splat-lane script
 * (linkers/nfs4.ld, which links build/src/**, where no recon object exists)
 * keeps producing a byte-identical image.
 *
 * NOTE: the retail run's last blob record was SPLIT at 0x80123820;
 * the residual tail is the next _rNN piece.
 * ============================================================ */

.section .data, "wa"

/* Generated by spimdisasm 1.40.2 */

nonmatching identitymatrix

dlabel identitymatrix
    /* 113FEC 801237EC 00000100 */ .word 0x00010000
    /* 113FF0 801237F0 00000000 */ .word 0x00000000
    /* 113FF4 801237F4 00000000 */ .word 0x00000000
    /* 113FF8 801237F8 00000000 */ .word 0x00000000
    /* 113FFC 801237FC 00000100 */ .word 0x00010000
    /* 114000 80123800 00000000 */ .word 0x00000000
    /* 114004 80123804 00000000 */ .word 0x00000000
    /* 114008 80123808 00000000 */ .word 0x00000000
    /* 11400C 8012380C 00000100 */ .word 0x00010000
enddlabel identitymatrix

nonmatching D_80123810

dlabel D_80123810
    /* 114010 80123810 00400000 */ .word 0x00004000
    /* 114014 80123814 00E0FFFF */ .word 0xFFFFE000
    /* 114018 80123818 00180000 */ .word 0x00001800
    /* 11401C 8012381C 00ECFFFF */ .word 0xFFFFEC00
enddlabel D_80123810
