.include "macro.inc"
/* W63-A19: residual segment of data_8010CCD4 -- labels no recon TU defines.
 * Linked by BOTH lanes. */

.section .data, "wa"

/* Generated by spimdisasm 1.40.2 */

nonmatching roadSurfaceFrictionCoeff

dlabel roadSurfaceFrictionCoeff
    /* 106D30 80116530 99190100 */ .word 0x00011999
    /* 106D34 80116534 CC0C0100 */ .word 0x00010CCC
    /* 106D38 80116538 00000100 */ .word 0x00010000
    /* 106D3C 8011653C 33F30000 */ .word 0x0000F333
    /* 106D40 80116540 66E60000 */ .word 0x0000E666
    /* 106D44 80116544 99D90000 */ .word 0x0000D999
    /* 106D48 80116548 CCCC0000 */ .word 0x0000CCCC
    /* 106D4C 8011654C 00C00000 */ .word 0x0000C000
    /* 106D50 80116550 33B30000 */ .word 0x0000B333
    /* 106D54 80116554 00800000 */ .word 0x00008000
enddlabel roadSurfaceFrictionCoeff

nonmatching ReverseRoadSurfaceFrictionCoeff

dlabel ReverseRoadSurfaceFrictionCoeff
    /* 106D58 80116558 F5E80000 */ .word 0x0000E8F5
    /* 106D5C 8011655C 33F30000 */ .word 0x0000F333
    /* 106D60 80116560 00000100 */ .word 0x00010000
    /* 106D64 80116564 910D0100 */ .word 0x00010D91
    /* 106D68 80116568 281C0100 */ .word 0x00011C28
    /* 106D6C 8011656C 0E2D0100 */ .word 0x00012D0E
    /* 106D70 80116570 00400100 */ .word 0x00014000
    /* 106D74 80116574 7A540100 */ .word 0x0001547A
    /* 106D78 80116578 146E0100 */ .word 0x00016E14
    /* 106D7C 8011657C 00000200 */ .word 0x00020000
enddlabel ReverseRoadSurfaceFrictionCoeff

nonmatching roadSurfaceIndex

dlabel roadSurfaceIndex
    /* 106D80 80116580 07030303 */ .word 0x03030307
    /* 106D84 80116584 03030403 */ .word 0x03040303
    /* 106D88 80116588 03030303 */ .word 0x03030303
    /* 106D8C 8011658C 03030503 */ .word 0x03050303
    /* 106D90 80116590 05050505 */ .word 0x05050505
    /* 106D94 80116594 07020404 */ .word 0x04040207
    /* 106D98 80116598 02040502 */ .word 0x02050402
    /* 106D9C 8011659C 02040203 */ .word 0x03020402
    /* 106DA0 801165A0 03040504 */ .word 0x04050403
    /* 106DA4 801165A4 05050505 */ .word 0x05050505
    /* 106DA8 801165A8 07000202 */ .word 0x02020007
    /* 106DAC 801165AC 01030301 */ .word 0x01030301
    /* 106DB0 801165B0 00030001 */ .word 0x01000300
    /* 106DB4 801165B4 01030505 */ .word 0x05050301
    /* 106DB8 801165B8 05050505 */ .word 0x05050505
enddlabel roadSurfaceIndex

.align 2
nonmatching gripLossTable

dlabel gripLossTable
    /* 106DBC 801165BC */ .asciz " "
    /* 20000000 */
.align 2
    /* 106DC0 801165C0 08000000 */ .word 0x00000008
    /* 106DC4 801165C4 08000000 */ .word 0x00000008
enddlabel gripLossTable

nonmatching gripLossTableWet

dlabel gripLossTableWet
    /* 106DC8 801165C8 10000000 */ .word 0x00000010
    /* 106DCC 801165CC 06000000 */ .word 0x00000006
    /* 106DD0 801165D0 04000000 */ .word 0x00000004
enddlabel gripLossTableWet

nonmatching gravity_ch

dlabel gravity_ch
    /* 106DD4 801165D4 00000000 */ .word 0x00000000
enddlabel gravity_ch

nonmatching D_801165D8

dlabel D_801165D8
    /* 106DD8 801165D8 00000000 */ .word 0x00000000
enddlabel D_801165D8

nonmatching D_801165DC

dlabel D_801165DC
    /* 106DDC 801165DC 00000000 */ .word 0x00000000
enddlabel D_801165DC
