.include "macro.inc"
/* W64-A18: residual segment of data_8010CCD4 -- labels no recon TU defines
 * (or a record tail a recon TU's section stops short of).
 * Linked by BOTH lanes. */

.section .data, "wa"

/* Generated by spimdisasm 1.40.2 */

nonmatching D_8010F07C

dlabel D_8010F07C
    /* FF87C 8010F07C 01000000 */ .word 0x00000001
    /* FF880 8010F080 FEFFFFFF */ .word 0xFFFFFFFE
    /* FF884 8010F084 03000000 */ .word 0x00000003
    /* FF888 8010F088 FCFFFFFF */ .word 0xFFFFFFFC
    /* FF88C 8010F08C 05000000 */ .word 0x00000005
    /* FF890 8010F090 FAFFFFFF */ .word 0xFFFFFFFA
    /* FF894 8010F094 07000000 */ .word 0x00000007
    /* FF898 8010F098 F8FFFFFF */ .word 0xFFFFFFF8
    /* FF89C 8010F09C 09000000 */ .word 0x00000009
    /* FF8A0 8010F0A0 F6FFFFFF */ .word 0xFFFFFFF6
    /* FF8A4 8010F0A4 0B000000 */ .word 0x0000000B
    /* FF8A8 8010F0A8 F4FFFFFF */ .word 0xFFFFFFF4
enddlabel D_8010F07C
