.include "macro.inc"
/* ============================================================
 * W64-A18  BLOB-vs-TU OWNERSHIP SWEEP -- SPLAT-LANE FILLER ONLY
 *
 * This segment's data is OWNED by
 *     build/recon/game/common/aih_btccop.cpp.o
 * (section .data, retail 0x8010cd98..0x8010ce7c), whose own bytes were
 * proved byte-identical to retail before the cut (ownmap2 E1-E5, with
 * R_MIPS_32 relocations RESOLVED against the retail VA map).
 *
 * The RECON-lane linker script must link that object's .data here and must
 * NOT link this file -- otherwise every label below is multiply defined.
 * It stays in the tree only so the legacy splat-lane script
 * (linkers/nfs4.ld, which links build/src/**, where no recon object exists)
 * keeps producing a byte-identical image.
 * ============================================================ */

.section .data, "wa"

/* Generated by spimdisasm 1.40.2 */

nonmatching AIH_BTC_Cop_1HC1HP_StageTimes

dlabel AIH_BTC_Cop_1HC1HP_StageTimes
    /* FD598 8010CD98 */ .asciz "<"
    /* 3C000000 */
.align 2
.align 2
    /* FD59C 8010CD9C */ .asciz "<"
    /* 3C000000 */
.align 2
.align 2
    /* FD5A0 8010CDA0 */ .asciz "<"
    /* 3C000000 */
.align 2
enddlabel AIH_BTC_Cop_1HC1HP_StageTimes

nonmatching AIH_BTCCop_chasePositions

dlabel AIH_BTCCop_chasePositions
    /* FD5A4 8010CDA4 00000000 */ .word 0x00000000
    /* FD5A8 8010CDA8 00000000 */ .word 0x00000000
    /* FD5AC 8010CDAC 00000B00 */ .word 0x000B0000
    /* FD5B0 8010CDB0 0000F8FF */ .word 0xFFF80000
    /* FD5B4 8010CDB4 00000000 */ .word 0x00000000
    /* FD5B8 8010CDB8 00000000 */ .word 0x00000000
    /* FD5BC 8010CDBC 00000000 */ .word 0x00000000
    /* FD5C0 8010CDC0 00000000 */ .word 0x00000000
    /* FD5C4 8010CDC4 0000F1FF */ .word 0xFFF10000
    /* FD5C8 8010CDC8 00000000 */ .word 0x00000000
    /* FD5CC 8010CDCC 00000000 */ .word 0x00000000
    /* FD5D0 8010CDD0 0000F1FF */ .word 0xFFF10000
    /* FD5D4 8010CDD4 00000000 */ .word 0x00000000
    /* FD5D8 8010CDD8 00000000 */ .word 0x00000000
    /* FD5DC 8010CDDC 0000F1FF */ .word 0xFFF10000
    /* FD5E0 8010CDE0 00000000 */ .word 0x00000000
    /* FD5E4 8010CDE4 00000000 */ .word 0x00000000
    /* FD5E8 8010CDE8 0000F1FF */ .word 0xFFF10000
    /* FD5EC 8010CDEC 00000000 */ .word 0x00000000
    /* FD5F0 8010CDF0 00000000 */ .word 0x00000000
    /* FD5F4 8010CDF4 00000800 */ .word 0x00080000
    /* FD5F8 8010CDF8 0000FAFF */ .word 0xFFFA0000
    /* FD5FC 8010CDFC 00000000 */ .word 0x00000000
    /* FD600 8010CE00 00000800 */ .word 0x00080000
    /* FD604 8010CE04 00000600 */ .word 0x00060000
    /* FD608 8010CE08 00000000 */ .word 0x00000000
    /* FD60C 8010CE0C 00000000 */ .word 0x00000000
    /* FD610 8010CE10 00000000 */ .word 0x00000000
    /* FD614 8010CE14 00000000 */ .word 0x00000000
    /* FD618 8010CE18 0000F6FF */ .word 0xFFF60000
    /* FD61C 8010CE1C 00000000 */ .word 0x00000000
    /* FD620 8010CE20 00000000 */ .word 0x00000000
    /* FD624 8010CE24 0000F6FF */ .word 0xFFF60000
    /* FD628 8010CE28 00000000 */ .word 0x00000000
    /* FD62C 8010CE2C 00000000 */ .word 0x00000000
    /* FD630 8010CE30 0000F6FF */ .word 0xFFF60000
    /* FD634 8010CE34 00000000 */ .word 0x00000000
    /* FD638 8010CE38 00000000 */ .word 0x00000000
    /* FD63C 8010CE3C 00000500 */ .word 0x00050000
    /* FD640 8010CE40 0000FCFF */ .word 0xFFFC0000
    /* FD644 8010CE44 00000000 */ .word 0x00000000
    /* FD648 8010CE48 00000500 */ .word 0x00050000
    /* FD64C 8010CE4C 00000400 */ .word 0x00040000
    /* FD650 8010CE50 00000000 */ .word 0x00000000
    /* FD654 8010CE54 00000500 */ .word 0x00050000
    /* FD658 8010CE58 00000000 */ .word 0x00000000
    /* FD65C 8010CE5C 00000000 */ .word 0x00000000
    /* FD660 8010CE60 0000FBFF */ .word 0xFFFB0000
    /* FD664 8010CE64 00000000 */ .word 0x00000000
    /* FD668 8010CE68 00000000 */ .word 0x00000000
    /* FD66C 8010CE6C 0000FBFF */ .word 0xFFFB0000
    /* FD670 8010CE70 00000000 */ .word 0x00000000
    /* FD674 8010CE74 00000000 */ .word 0x00000000
    /* FD678 8010CE78 0000FBFF */ .word 0xFFFB0000
enddlabel AIH_BTCCop_chasePositions
