.include "macro.inc"
/* W63-A19: residual segment of data_8010CCD4 -- labels no recon TU defines.
 * Linked by BOTH lanes. */

.section .data, "wa"

/* Generated by spimdisasm 1.40.2 */

nonmatching __data_obj

dlabel __data_obj
    /* FD4D4 8010CCD4 00000000 */ .word 0x00000000
    /* FD4D8 8010CCD8 0A000000 */ .word 0x0000000A
enddlabel __data_obj

nonmatching D_8010CCDC

dlabel D_8010CCDC
    /* FD4DC 8010CCDC 0F000000 */ .word 0x0000000F
    /* FD4E0 8010CCE0 19000000 */ .word 0x00000019
enddlabel D_8010CCDC

nonmatching CarLogic_gObs

dlabel CarLogic_gObs
    /* FD4E4 8010CCE4 00000000 */ .word 0x00000000
    /* FD4E8 8010CCE8 00000000 */ .word 0x00000000
    /* FD4EC 8010CCEC 00000000 */ .word 0x00000000
enddlabel CarLogic_gObs

nonmatching AI_Info

dlabel AI_Info
    /* FD4F0 8010CCF0 00000000 */ .word 0x00000000
enddlabel AI_Info

nonmatching D_8010CCF4

dlabel D_8010CCF4
    /* FD4F4 8010CCF4 00000000 */ .word 0x00000000
    /* FD4F8 8010CCF8 00000000 */ .word 0x00000000
    /* FD4FC 8010CCFC 00000000 */ .word 0x00000000
    /* FD500 8010CD00 00000000 */ .word 0x00000000
    /* FD504 8010CD04 00000000 */ .word 0x00000000
    /* FD508 8010CD08 00000000 */ .word 0x00000000
enddlabel D_8010CCF4

nonmatching D_8010CD0C

dlabel D_8010CD0C
    /* FD50C 8010CD0C 00000000 */ .word 0x00000000
    /* FD510 8010CD10 00000000 */ .word 0x00000000
    /* FD514 8010CD14 00000000 */ .word 0x00000000
    /* FD518 8010CD18 00000000 */ .word 0x00000000
    /* FD51C 8010CD1C 00000000 */ .word 0x00000000
    /* FD520 8010CD20 00000000 */ .word 0x00000000
    /* FD524 8010CD24 00000000 */ .word 0x00000000
    /* FD528 8010CD28 00000000 */ .word 0x00000000
enddlabel D_8010CD0C

nonmatching D_8010CD2C

dlabel D_8010CD2C
    /* FD52C 8010CD2C 00000000 */ .word 0x00000000
    /* FD530 8010CD30 00000000 */ .word 0x00000000
enddlabel D_8010CD2C

nonmatching D_8010CD34

dlabel D_8010CD34
    /* FD534 8010CD34 00000000 */ .word 0x00000000
enddlabel D_8010CD34

nonmatching highLevelAIObjs

dlabel highLevelAIObjs
    /* FD538 8010CD38 00000000 */ .word 0x00000000
    /* FD53C 8010CD3C 00000000 */ .word 0x00000000
    /* FD540 8010CD40 00000000 */ .word 0x00000000
    /* FD544 8010CD44 00000000 */ .word 0x00000000
    /* FD548 8010CD48 00000000 */ .word 0x00000000
    /* FD54C 8010CD4C 00000000 */ .word 0x00000000
    /* FD550 8010CD50 00000000 */ .word 0x00000000
    /* FD554 8010CD54 00000000 */ .word 0x00000000
    /* FD558 8010CD58 00000000 */ .word 0x00000000
enddlabel highLevelAIObjs
