.include "macro.inc"
/* ============================================================
 * W63-A19  BLOB-vs-TU OWNERSHIP SWEEP -- SPLAT-LANE FILLER ONLY
 *
 * This segment's data is OWNED by
 *     build/recon/game/common/paths.cpp.o
 * (section .data, retail 0x80116468..0x80116530), whose own bytes were
 * proved byte-identical to retail before the cut (ownmap.py E5).
 *
 * The RECON-lane linker script must link that object's .data here and must
 * NOT link this file -- otherwise every label below is multiply defined.
 * It stays in the tree only so the legacy splat-lane script
 * (linkers/nfs4.ld, which links build/src/**, where no recon object exists)
 * keeps producing a byte-identical .sdata image.
 * ============================================================ */

.section .data, "wa"

/* Generated by spimdisasm 1.40.2 */

nonmatching Paths_Paths

dlabel Paths_Paths
    /* 106C68 80116468 00000000 */ .word 0x00000000
    /* 106C6C 8011646C 00000000 */ .word 0x00000000
enddlabel Paths_Paths

nonmatching D_80116470

dlabel D_80116470
    /* 106C70 80116470 00000000 */ .word 0x00000000
enddlabel D_80116470

nonmatching D_80116474

dlabel D_80116474
    /* 106C74 80116474 00000000 */ .word 0x00000000
enddlabel D_80116474

nonmatching D_80116478

dlabel D_80116478
    /* 106C78 80116478 00000000 */ .word 0x00000000
enddlabel D_80116478

nonmatching D_8011647C

dlabel D_8011647C
    /* 106C7C 8011647C 00000000 */ .word 0x00000000
enddlabel D_8011647C

nonmatching D_80116480

dlabel D_80116480
    /* 106C80 80116480 00000000 */ .word 0x00000000
    /* 106C84 80116484 00000000 */ .word 0x00000000
enddlabel D_80116480

nonmatching D_80116488

dlabel D_80116488
    /* 106C88 80116488 00000000 */ .word 0x00000000
    /* 106C8C 8011648C 00000000 */ .word 0x00000000
enddlabel D_80116488

nonmatching D_80116490

dlabel D_80116490
    /* 106C90 80116490 00000000 */ .word 0x00000000
enddlabel D_80116490

nonmatching D_80116494

dlabel D_80116494
    /* 106C94 80116494 00000000 */ .word 0x00000000
enddlabel D_80116494

nonmatching D_80116498

dlabel D_80116498
    /* 106C98 80116498 00000000 */ .word 0x00000000
enddlabel D_80116498

nonmatching D_8011649C

dlabel D_8011649C
    /* 106C9C 8011649C 00000000 */ .word 0x00000000
    /* 106CA0 801164A0 00000000 */ .word 0x00000000
    /* 106CA4 801164A4 00000000 */ .word 0x00000000
    /* 106CA8 801164A8 00000000 */ .word 0x00000000
    /* 106CAC 801164AC 00000000 */ .word 0x00000000
enddlabel D_8011649C

nonmatching D_801164B0

dlabel D_801164B0
    /* 106CB0 801164B0 00000000 */ .word 0x00000000
    /* 106CB4 801164B4 00000000 */ .word 0x00000000
    /* 106CB8 801164B8 00000000 */ .word 0x00000000
    /* 106CBC 801164BC 00000000 */ .word 0x00000000
enddlabel D_801164B0

nonmatching D_801164C0

dlabel D_801164C0
    /* 106CC0 801164C0 00000000 */ .word 0x00000000
    /* 106CC4 801164C4 00000000 */ .word 0x00000000
enddlabel D_801164C0

nonmatching D_801164C8

dlabel D_801164C8
    /* 106CC8 801164C8 00000000 */ .word 0x00000000
enddlabel D_801164C8

nonmatching D_801164CC

dlabel D_801164CC
    /* 106CCC 801164CC 00000000 */ .word 0x00000000
enddlabel D_801164CC

nonmatching D_801164D0

dlabel D_801164D0
    /* 106CD0 801164D0 00000000 */ .word 0x00000000
enddlabel D_801164D0

nonmatching D_801164D4

dlabel D_801164D4
    /* 106CD4 801164D4 00000000 */ .word 0x00000000
enddlabel D_801164D4

nonmatching D_801164D8

dlabel D_801164D8
    /* 106CD8 801164D8 00000000 */ .word 0x00000000
enddlabel D_801164D8

nonmatching D_801164DC

dlabel D_801164DC
    /* 106CDC 801164DC 00000000 */ .word 0x00000000
    /* 106CE0 801164E0 00000000 */ .word 0x00000000
    /* 106CE4 801164E4 00000000 */ .word 0x00000000
enddlabel D_801164DC

nonmatching D_801164E8

dlabel D_801164E8
    /* 106CE8 801164E8 00000000 */ .word 0x00000000
    /* 106CEC 801164EC 00000000 */ .word 0x00000000
enddlabel D_801164E8

nonmatching D_801164F0

dlabel D_801164F0
    /* 106CF0 801164F0 00000000 */ .word 0x00000000
enddlabel D_801164F0

nonmatching D_801164F4

dlabel D_801164F4
    /* 106CF4 801164F4 00000000 */ .word 0x00000000
enddlabel D_801164F4

nonmatching D_801164F8

dlabel D_801164F8
    /* 106CF8 801164F8 00000000 */ .word 0x00000000
enddlabel D_801164F8

nonmatching D_801164FC

dlabel D_801164FC
    /* 106CFC 801164FC 00000000 */ .word 0x00000000
enddlabel D_801164FC

nonmatching D_80116500

dlabel D_80116500
    /* 106D00 80116500 00000000 */ .word 0x00000000
    /* 106D04 80116504 00000000 */ .word 0x00000000
    /* 106D08 80116508 00000000 */ .word 0x00000000
enddlabel D_80116500

nonmatching D_8011650C

dlabel D_8011650C
    /* 106D0C 8011650C 00000000 */ .word 0x00000000
    /* 106D10 80116510 00000000 */ .word 0x00000000
    /* 106D14 80116514 00000000 */ .word 0x00000000
    /* 106D18 80116518 00000000 */ .word 0x00000000
    /* 106D1C 8011651C 00000000 */ .word 0x00000000
    /* 106D20 80116520 00000000 */ .word 0x00000000
    /* 106D24 80116524 00000000 */ .word 0x00000000
    /* 106D28 80116528 00000000 */ .word 0x00000000
    /* 106D2C 8011652C 00000000 */ .word 0x00000000
enddlabel D_8011650C
