.include "macro.inc"
/* ============================================================
 * W64-A18  BLOB-vs-TU OWNERSHIP SWEEP -- SPLAT-LANE FILLER ONLY
 *
 * This segment's data is OWNED by
 *     build/recon/game/common/aih_basicperp.cpp.o
 * (section .data, retail 0x8010cd5c..0x8010cd98), whose own bytes were
 * proved byte-identical to retail before the cut (ownmap2 E1-E5, with
 * R_MIPS_32 relocations RESOLVED against the retail VA map).
 *
 * The RECON-lane linker script must link that object's .data here and must
 * NOT link this file -- otherwise every label below is multiply defined.
 * It stays in the tree only so the legacy splat-lane script
 * (linkers/nfs4.ld, which links build/src/**, where no recon object exists)
 * keeps producing a byte-identical image.
 * ============================================================ */

.section .data, "wa"

/* Generated by spimdisasm 1.40.2 */

nonmatching AIHigh_BasicPerp_PlayerCaughtSpeed

dlabel AIHigh_BasicPerp_PlayerCaughtSpeed
    /* FD55C 8010CD5C 388E0F00 */ .word 0x000F8E38
    /* FD560 8010CD60 1CC71100 */ .word 0x0011C71C
    /* FD564 8010CD64 00001400 */ .word 0x00140000
enddlabel AIHigh_BasicPerp_PlayerCaughtSpeed

nonmatching AIHigh_BasicPerp_PlayerCaughtDeltaY

dlabel AIHigh_BasicPerp_PlayerCaughtDeltaY
    /* FD568 8010CD68 00000500 */ .word 0x00050000
    /* FD56C 8010CD6C 00800600 */ .word 0x00068000
    /* FD570 8010CD70 00000800 */ .word 0x00080000
enddlabel AIHigh_BasicPerp_PlayerCaughtDeltaY

nonmatching AIHigh_BasicPerp_MinDeltaSpeed

dlabel AIHigh_BasicPerp_MinDeltaSpeed
    /* FD574 8010CD74 8EE30800 */ .word 0x0008E38E
    /* FD578 8010CD78 711C0B00 */ .word 0x000B1C71
    /* FD57C 8010CD7C 55550D00 */ .word 0x000D5555
enddlabel AIHigh_BasicPerp_MinDeltaSpeed

nonmatching AIHigh_BasicPerp_CopCaughtSpeed

dlabel AIHigh_BasicPerp_CopCaughtSpeed
    /* FD580 8010CD80 711C0B00 */ .word 0x000B1C71
    /* FD584 8010CD84 E3380E00 */ .word 0x000E38E3
    /* FD588 8010CD88 1CC71100 */ .word 0x0011C71C
enddlabel AIHigh_BasicPerp_CopCaughtSpeed

nonmatching AIHigh_BasicPerp_CaughtDistance

dlabel AIHigh_BasicPerp_CaughtDistance
    /* FD58C 8010CD8C 00001E00 */ .word 0x001E0000
    /* FD590 8010CD90 00002D00 */ .word 0x002D0000
    /* FD594 8010CD94 00003C00 */ .word 0x003C0000
enddlabel AIHigh_BasicPerp_CaughtDistance

.align 2