.include "macro.inc"
/* ============================================================
 * W64-A18  BLOB-vs-TU OWNERSHIP SWEEP -- SPLAT-LANE FILLER ONLY
 *
 * This segment's data is OWNED by
 *     build/recon/eaclib/psx/eacpsxz/isqrt.c.o
 * (section .data, retail 0x8013be10..0x8013bf10), whose own bytes were
 * proved byte-identical to retail before the cut (ownmap2 E1-E5, with
 * R_MIPS_32 relocations RESOLVED against the retail VA map).
 *
 * The RECON-lane linker script must link that object's .data here and must
 * NOT link this file -- otherwise every label below is multiply defined.
 * It stays in the tree only so the legacy splat-lane script
 * (linkers/nfs4.ld, which links build/src/**, where no recon object exists)
 * keeps producing a byte-identical image.
 *
 * NOTE: the retail run's last blob record was SPLIT at 0x8013bf10;
 * the residual tail is the next _rNN piece.
 * ============================================================ */

.section .data, "wa"

/* Generated by spimdisasm 1.40.2 */

nonmatching isqrttbl

dlabel isqrttbl
    /* 12C610 8013BE10 10161B20 */ .word 0x201B1610
    /* 12C614 8013BE14 23272A2D */ .word 0x2D2A2723
    /* 12C618 8013BE18 30323537 */ .word 0x37353230
    /* 12C61C 8013BE1C 393B3D40 */ .word 0x403D3B39
    /* 12C620 8013BE20 41434547 */ .word 0x47454341
    /* 12C624 8013BE24 494B4C4E */ .word 0x4E4C4B49
    /* 12C628 8013BE28 50515354 */ .word 0x54535150
    /* 12C62C 8013BE2C 5657595A */ .word 0x5A595756
    /* 12C630 8013BE30 5B5D5E60 */ .word 0x605E5D5B
    /* 12C634 8013BE34 61626365 */ .word 0x65636261
    /* 12C638 8013BE38 6667686A */ .word 0x6A686766
    /* 12C63C 8013BE3C 6B6C6D6E */ .word 0x6E6D6C6B
    /* 12C640 8013BE40 70717273 */ .word 0x73727170
    /* 12C644 8013BE44 74757677 */ .word 0x77767574
    /* 12C648 8013BE48 78797A7B */ .word 0x7B7A7978
    /* 12C64C 8013BE4C 7C7D7E80 */ .word 0x807E7D7C
    /* 12C650 8013BE50 80818283 */ .word 0x83828180
    /* 12C654 8013BE54 84858687 */ .word 0x87868584
    /* 12C658 8013BE58 88898A8B */ .word 0x8B8A8988
    /* 12C65C 8013BE5C 8C8D8E8F */ .word 0x8F8E8D8C
    /* 12C660 8013BE60 90909192 */ .word 0x92919090
    /* 12C664 8013BE64 93949596 */ .word 0x96959493
    /* 12C668 8013BE68 96979899 */ .word 0x99989796
    /* 12C66C 8013BE6C 9A9B9B9C */ .word 0x9C9B9B9A
    /* 12C670 8013BE70 9D9E9FA0 */ .word 0xA09F9E9D
    /* 12C674 8013BE74 A0A1A2A3 */ .word 0xA3A2A1A0
    /* 12C678 8013BE78 A3A4A5A6 */ .word 0xA6A5A4A3
    /* 12C67C 8013BE7C A7A7A8A9 */ .word 0xA9A8A7A7
    /* 12C680 8013BE80 AAAAABAC */ .word 0xACABAAAA
    /* 12C684 8013BE84 ADADAEAF */ .word 0xAFAEADAD
    /* 12C688 8013BE88 B0B0B1B2 */ .word 0xB2B1B0B0
    /* 12C68C 8013BE8C B2B3B4B5 */ .word 0xB5B4B3B2
    /* 12C690 8013BE90 B5B6B7B7 */ .word 0xB7B7B6B5
    /* 12C694 8013BE94 B8B9B9BA */ .word 0xBAB9B9B8
    /* 12C698 8013BE98 BBBBBCBD */ .word 0xBDBCBBBB
    /* 12C69C 8013BE9C BDBEBFC0 */ .word 0xC0BFBEBD
    /* 12C6A0 8013BEA0 C0C1C1C2 */ .word 0xC2C1C1C0
    /* 12C6A4 8013BEA4 C3C3C4C5 */ .word 0xC5C4C3C3
    /* 12C6A8 8013BEA8 C5C6C7C7 */ .word 0xC7C7C6C5
    /* 12C6AC 8013BEAC C8C9C9CA */ .word 0xCAC9C9C8
    /* 12C6B0 8013BEB0 CBCBCCCC */ .word 0xCCCCCBCB
    /* 12C6B4 8013BEB4 CDCECECF */ .word 0xCFCECECD
    /* 12C6B8 8013BEB8 D0D0D1D1 */ .word 0xD1D1D0D0
    /* 12C6BC 8013BEBC D2D3D3D4 */ .word 0xD4D3D3D2
    /* 12C6C0 8013BEC0 D4D5D6D6 */ .word 0xD6D6D5D4
    /* 12C6C4 8013BEC4 D7D7D8D9 */ .word 0xD9D8D7D7
    /* 12C6C8 8013BEC8 D9DADADB */ .word 0xDBDADAD9
    /* 12C6CC 8013BECC DBDCDDDD */ .word 0xDDDDDCDB
    /* 12C6D0 8013BED0 DEDEDFE0 */ .word 0xE0DFDEDE
    /* 12C6D4 8013BED4 E0E1E1E2 */ .word 0xE2E1E1E0
    /* 12C6D8 8013BED8 E2E3E3E4 */ .word 0xE4E3E3E2
    /* 12C6DC 8013BEDC E5E5E6E6 */ .word 0xE6E6E5E5
    /* 12C6E0 8013BEE0 E7E7E8E8 */ .word 0xE8E8E7E7
    /* 12C6E4 8013BEE4 E9EAEAEB */ .word 0xEBEAEAE9
    /* 12C6E8 8013BEE8 EBECECED */ .word 0xEDECECEB
    /* 12C6EC 8013BEEC EDEEEEEF */ .word 0xEFEEEEED
    /* 12C6F0 8013BEF0 F0F0F1F1 */ .word 0xF1F1F0F0
    /* 12C6F4 8013BEF4 F2F2F3F3 */ .word 0xF3F3F2F2
    /* 12C6F8 8013BEF8 F4F4F5F5 */ .word 0xF5F5F4F4
    /* 12C6FC 8013BEFC F6F6F7F7 */ .word 0xF7F7F6F6
    /* 12C700 8013BF00 F8F8F9F9 */ .word 0xF9F9F8F8
    /* 12C704 8013BF04 FAFAFBFB */ .word 0xFBFBFAFA
    /* 12C708 8013BF08 FCFCFDFD */ .word 0xFDFDFCFC
    /* 12C70C 8013BF0C FEFEFFFF */ .word 0xFFFFFEFE
enddlabel isqrttbl
