.include "macro.inc"
/* ============================================================
 * W64-A18  BLOB-vs-TU OWNERSHIP SWEEP -- SPLAT-LANE FILLER ONLY
 *
 * This segment's data is OWNED by
 *     build/recon/eaclib/psx/sndpsxz/slib.c.o
 * (section .data, retail 0x80136df0..0x80136e00), whose own bytes were
 * proved byte-identical to retail before the cut (ownmap2 E1-E5, with
 * R_MIPS_32 relocations RESOLVED against the retail VA map).
 *
 * The RECON-lane linker script must link that object's .data here and must
 * NOT link this file -- otherwise every label below is multiply defined.
 * It stays in the tree only so the legacy splat-lane script
 * (linkers/nfs4.ld, which links build/src/**, where no recon object exists)
 * keeps producing a byte-identical image.
 * ============================================================ */

.section .data, "wa"

/* Generated by spimdisasm 1.40.2 */

nonmatching sndpdsafeloop

dlabel sndpdsafeloop
    /* 1275F0 80136DF0 00070000 */ .word 0x00000700
    /* 1275F4 80136DF4 00000000 */ .word 0x00000000
    /* 1275F8 80136DF8 00000000 */ .word 0x00000000
    /* 1275FC 80136DFC 00000000 */ .word 0x00000000
enddlabel sndpdsafeloop
