.include "macro.inc"
/* ============================================================
 * W64-A18  BLOB-vs-TU OWNERSHIP SWEEP -- SPLAT-LANE FILLER ONLY
 *
 * This segment's data is OWNED by
 *     build/recon/game/common/aiinit.cpp.o
 * (section .data, retail 0x8010d560..0x8010d5cc), whose own bytes were
 * proved byte-identical to retail before the cut (ownmap2 E1-E5, with
 * R_MIPS_32 relocations RESOLVED against the retail VA map).
 *
 * The RECON-lane linker script must link that object's .data here and must
 * NOT link this file -- otherwise every label below is multiply defined.
 * It stays in the tree only so the legacy splat-lane script
 * (linkers/nfs4.ld, which links build/src/**, where no recon object exists)
 * keeps producing a byte-identical image.
 * ============================================================ */

.section .data, "wa"

/* Generated by spimdisasm 1.40.2 */

nonmatching trafcfg

dlabel trafcfg
    /* FDD60 8010D560 04000000 */ .word 0x00000004
    /* FDD64 8010D564 0C000000 */ .word 0x0000000C
    /* FDD68 8010D568 1E000000 */ .word 0x0000001E
    /* FDD6C 8010D56C 33B30000 */ .word 0x0000B333
    /* FDD70 8010D570 00000B00 */ .word 0x000B0000
    /* FDD74 8010D574 00000800 */ .word 0x00080000
    /* FDD78 8010D578 00002000 */ .word 0x00200000
    /* FDD7C 8010D57C 00000800 */ .word 0x00080000
    /* FDD80 8010D580 00001800 */ .word 0x00180000
    /* FDD84 8010D584 00400100 */ .word 0x00014000
    /* FDD88 8010D588 CCCC0000 */ .word 0x0000CCCC
    /* FDD8C 8010D58C 00000500 */ .word 0x00050000
    /* FDD90 8010D590 CCCC0000 */ .word 0x0000CCCC
    /* FDD94 8010D594 00001400 */ .word 0x00140000
    /* FDD98 8010D598 47210000 */ .word 0x00002147
    /* FDD9C 8010D59C 53030000 */ .word 0x00000353
    /* FDDA0 8010D5A0 00000000 */ .word 0x00000000
    /* FDDA4 8010D5A4 00001000 */ .word 0x00100000
    /* FDDA8 8010D5A8 00000800 */ .word 0x00080000
    /* FDDAC 8010D5AC 00001800 */ .word 0x00180000
    /* FDDB0 8010D5B0 00A00000 */ .word 0x0000A000
    /* FDDB4 8010D5B4 CCCC0000 */ .word 0x0000CCCC
    /* FDDB8 8010D5B8 00000A00 */ .word 0x000A0000
    /* FDDBC 8010D5BC CCCC0000 */ .word 0x0000CCCC
    /* FDDC0 8010D5C0 00000A00 */ .word 0x000A0000
    /* FDDC4 8010D5C4 EB510000 */ .word 0x000051EB
    /* FDDC8 8010D5C8 53030000 */ .word 0x00000353
enddlabel trafcfg
