.include "macro.inc"
/* ============================================================
 * W64-A18  BLOB-vs-TU OWNERSHIP SWEEP -- SPLAT-LANE FILLER ONLY
 *
 * This segment's data is OWNED by
 *     build/recon/syslib/psx/libmath/FERR.c.o
 * (section .data, retail 0x8013bf18..0x8013bf20), whose own bytes were
 * proved byte-identical to retail before the cut (ownmap2 E1-E5, with
 * R_MIPS_32 relocations RESOLVED against the retail VA map).
 *
 * The RECON-lane linker script must link that object's .data here and must
 * NOT link this file -- otherwise every label below is multiply defined.
 * It stays in the tree only so the legacy splat-lane script
 * (linkers/nfs4.ld, which links build/src/**, where no recon object exists)
 * keeps producing a byte-identical image.
 * ============================================================ */

.section .data, "wa"

/* Generated by spimdisasm 1.40.2 */

nonmatching math_errno

dlabel math_errno
    /* 12C718 8013BF18 00000000 */ .word 0x00000000
enddlabel math_errno

nonmatching math_err_point

dlabel math_err_point
    /* 12C71C 8013BF1C 00000000 */ .word 0x00000000
enddlabel math_err_point
