.include "macro.inc"
/* P912: exact native Collide_gRegistry[16] transport oracle,64 CPE-loaded bytes.
 * The reconstruction selects the validated source .data owner instead.
 * Retained unchanged for src/oracle; proof and backup: p912_collide_owner. */

.section .data, "wa"

/* Generated by spimdisasm 1.40.2 */

nonmatching Collide_gRegistry

dlabel Collide_gRegistry
    /* 101430 80110C30 00000000 */ .word 0x00000000
    /* 101434 80110C34 00000000 */ .word 0x00000000
    /* 101438 80110C38 00000000 */ .word 0x00000000
    /* 10143C 80110C3C 00000000 */ .word 0x00000000
    /* 101440 80110C40 00000000 */ .word 0x00000000
    /* 101444 80110C44 00000000 */ .word 0x00000000
    /* 101448 80110C48 00000000 */ .word 0x00000000
    /* 10144C 80110C4C 00000000 */ .word 0x00000000
    /* 101450 80110C50 00000000 */ .word 0x00000000
    /* 101454 80110C54 00000000 */ .word 0x00000000
    /* 101458 80110C58 00000000 */ .word 0x00000000
    /* 10145C 80110C5C 00000000 */ .word 0x00000000
    /* 101460 80110C60 00000000 */ .word 0x00000000
    /* 101464 80110C64 00000000 */ .word 0x00000000
    /* 101468 80110C68 00000000 */ .word 0x00000000
    /* 10146C 80110C6C 00000000 */ .word 0x00000000
enddlabel Collide_gRegistry
