.include "macro.inc"
/* ============================================================
 * W64-A18  BLOB-vs-TU OWNERSHIP SWEEP -- SPLAT-LANE FILLER ONLY
 *
 * This segment's data is OWNED by
 *     build/recon/eaclib/psx/sndpsxz/snddata.c.o
 * (section .data, retail 0x8013c2f0..0x8013c308), whose own bytes were
 * proved byte-identical to retail before the cut (ownmap2 E1-E5, with
 * R_MIPS_32 relocations RESOLVED against the retail VA map).
 *
 * The RECON-lane linker script must link that object's .data here and must
 * NOT link this file -- otherwise every label below is multiply defined.
 * It stays in the tree only so the legacy splat-lane script
 * (linkers/nfs4.ld, which links build/src/**, where no recon object exists)
 * keeps producing a byte-identical image.
 * ============================================================ */

.section .data, "wa"

/* Generated by spimdisasm 1.40.2 */

nonmatching sndseed

dlabel sndseed
    /* 12CAF0 8013C2F0 560E2DF2 */ .word 0xF22D0E56
    /* 12CAF4 8013C2F4 E9263188 */ .word 0x883126E9
    /* 12CAF8 8013C2F8 2FDD24C6 */ .word 0xC624DD2F
    /* 12CAFC 8013C2FC 9CC40207 */ .word 0x0702C49C
    /* 12CB00 8013C300 7D3F359E */ .word 0x9E353F7D
    /* 12CB04 8013C304 643BDF6F */ .word 0x6FDF3B64
enddlabel sndseed
