.include "macro.inc"
/* W64-A18: residual segment of data_8010CCD4 -- labels no recon TU defines
 * (or a record tail a recon TU's section stops short of).
 * Linked by BOTH lanes. */

.section .data, "wa"

/* Generated by spimdisasm 1.40.2 */

nonmatching colourRGB

dlabel colourRGB
    /* 110570 8011FD70 00000000 */ .word 0x00000000
    /* 110574 8011FD74 85858500 */ .word 0x00858585
    /* 110578 8011FD78 AAAAAA00 */ .word 0x00AAAAAA
    /* 11057C 8011FD7C 00BEBE00 */ .word 0x00BEBE00
    /* 110580 8011FD80 A0A0A000 */ .word 0x00A0A0A0
    /* 110584 8011FD84 B5420000 */ .word 0x000042B5
    /* 110588 8011FD88 00BEBEFF */ .word 0xFFBEBE00
    /* 11058C 8011FD8C 000FBF00 */ .word 0x00BF0F00
    /* 110590 8011FD90 5BE6A500 */ .word 0x00A5E65B
    /* 110594 8011FD94 4A63A500 */ .word 0x00A5634A
    /* 110598 8011FD98 AAAAAAFF */ .word 0xFFAAAAAA
    /* 11059C 8011FD9C E62C0000 */ .word 0x00002CE6
    /* 1105A0 8011FDA0 D2AC1100 */ .word 0x0011ACD2
    /* 1105A4 8011FDA4 622B0C00 */ .word 0x000C2B62
    /* 1105A8 8011FDA8 001F5F00 */ .word 0x005F1F00
    /* 1105AC 8011FDAC 60606C00 */ .word 0x006C6060
enddlabel colourRGB

nonmatching shpfontclut

dlabel shpfontclut
    /* 1105B0 8011FDB0 00000000 */ .word 0x00000000
    /* 1105B4 8011FDB4 00000000 */ .word 0x00000000
    /* 1105B8 8011FDB8 00000000 */ .word 0x00000000
    /* 1105BC 8011FDBC 00000000 */ .word 0x00000000
    /* 1105C0 8011FDC0 00000000 */ .word 0x00000000
    /* 1105C4 8011FDC4 00000000 */ .word 0x00000000
    /* 1105C8 8011FDC8 00000000 */ .word 0x00000000
    /* 1105CC 8011FDCC 00000000 */ .word 0x00000000
    /* 1105D0 8011FDD0 00000000 */ .word 0x00000000
    /* 1105D4 8011FDD4 00000000 */ .word 0x00000000
    /* 1105D8 8011FDD8 00000000 */ .word 0x00000000
    /* 1105DC 8011FDDC 00000000 */ .word 0x00000000
enddlabel shpfontclut
