.include "macro.inc"
/* ============================================================
 * W63-A19  BLOB-vs-TU OWNERSHIP SWEEP -- SPLAT-LANE FILLER ONLY
 *
 * This segment's data is OWNED by
 *     build/recon/game/psx/texture.cpp.o
 * (section .data, retail 0x80120fd0..0x80121070), whose own bytes were
 * proved byte-identical to retail before the cut (ownmap.py E5).
 *
 * The RECON-lane linker script must link that object's .data here and must
 * NOT link this file -- otherwise every label below is multiply defined.
 * It stays in the tree only so the legacy splat-lane script
 * (linkers/nfs4.ld, which links build/src/**, where no recon object exists)
 * keeps producing a byte-identical .sdata image.
 * ============================================================ */

.section .data, "wa"

/* Generated by spimdisasm 1.40.2 */

nonmatching gMenuPixmap

dlabel gMenuPixmap
    /* 1117D0 80120FD0 00000000 */ .word 0x00000000
enddlabel gMenuPixmap

nonmatching D_80120FD4

dlabel D_80120FD4
    /* 1117D4 80120FD4 00000000 */ .word 0x00000000
    /* 1117D8 80120FD8 00000000 */ .word 0x00000000
enddlabel D_80120FD4

nonmatching D_80120FDC

dlabel D_80120FDC
    /* 1117DC 80120FDC 00000000 */ .word 0x00000000
    /* 1117E0 80120FE0 00000000 */ .word 0x00000000
    /* 1117E4 80120FE4 00000000 */ .word 0x00000000
    /* 1117E8 80120FE8 00000000 */ .word 0x00000000
    /* 1117EC 80120FEC 00000000 */ .word 0x00000000
enddlabel D_80120FDC

nonmatching gMenuPixmapAlloc

dlabel gMenuPixmapAlloc
    /* 1117F0 80120FF0 00000000 */ .word 0x00000000
    /* 1117F4 80120FF4 00000000 */ .word 0x00000000
    /* 1117F8 80120FF8 00000000 */ .word 0x00000000
    /* 1117FC 80120FFC 00000000 */ .word 0x00000000
    /* 111800 80121000 00000000 */ .word 0x00000000
    /* 111804 80121004 00000000 */ .word 0x00000000
    /* 111808 80121008 00000000 */ .word 0x00000000
    /* 11180C 8012100C 00000000 */ .word 0x00000000
    /* 111810 80121010 00000000 */ .word 0x00000000
    /* 111814 80121014 00000000 */ .word 0x00000000
    /* 111818 80121018 00000000 */ .word 0x00000000
    /* 11181C 8012101C 00000000 */ .word 0x00000000
    /* 111820 80121020 00000000 */ .word 0x00000000
    /* 111824 80121024 00000000 */ .word 0x00000000
    /* 111828 80121028 00000000 */ .word 0x00000000
    /* 11182C 8012102C 00000000 */ .word 0x00000000
    /* 111830 80121030 00000000 */ .word 0x00000000
    /* 111834 80121034 00000000 */ .word 0x00000000
    /* 111838 80121038 00000000 */ .word 0x00000000
    /* 11183C 8012103C 00000000 */ .word 0x00000000
    /* 111840 80121040 00000000 */ .word 0x00000000
    /* 111844 80121044 00000000 */ .word 0x00000000
    /* 111848 80121048 00000000 */ .word 0x00000000
    /* 11184C 8012104C 00000000 */ .word 0x00000000
    /* 111850 80121050 00000000 */ .word 0x00000000
    /* 111854 80121054 00000000 */ .word 0x00000000
    /* 111858 80121058 00000000 */ .word 0x00000000
    /* 11185C 8012105C 00000000 */ .word 0x00000000
    /* 111860 80121060 00000000 */ .word 0x00000000
    /* 111864 80121064 00000000 */ .word 0x00000000
    /* 111868 80121068 00000000 */ .word 0x00000000
    /* 11186C 8012106C 00000000 */ .word 0x00000000
enddlabel gMenuPixmapAlloc
