.include "macro.inc"
/* ============================================================
 * W63-A19  BLOB-vs-TU OWNERSHIP SWEEP -- SPLAT-LANE FILLER ONLY
 *
 * This segment's data is OWNED by
 *     build/recon/game/common/dashhud.cpp.o
 * (section .data, retail 0x80112730..0x8011279c), whose own bytes were
 * proved byte-identical to retail before the cut (ownmap.py E5).
 *
 * The RECON-lane linker script must link that object's .data here and must
 * NOT link this file -- otherwise every label below is multiply defined.
 * It stays in the tree only so the legacy splat-lane script
 * (linkers/nfs4.ld, which links build/src/**, where no recon object exists)
 * keeps producing a byte-identical .sdata image.
 * ============================================================ */

.section .data, "wa"

/* Generated by spimdisasm 1.40.2 */

nonmatching DashHUD_gInfo

dlabel DashHUD_gInfo
    /* 102F30 80112730 00000000 */ .word 0x00000000
    /* 102F34 80112734 00000000 */ .word 0x00000000
    /* 102F38 80112738 00000000 */ .word 0x00000000
    /* 102F3C 8011273C 00000000 */ .word 0x00000000
    /* 102F40 80112740 00000000 */ .word 0x00000000
    /* 102F44 80112744 00000000 */ .word 0x00000000
enddlabel DashHUD_gInfo

nonmatching D_80112748

dlabel D_80112748
    /* 102F48 80112748 00000000 */ .word 0x00000000
enddlabel D_80112748

nonmatching D_8011274C

dlabel D_8011274C
    /* 102F4C 8011274C 00000000 */ .word 0x00000000
    /* 102F50 80112750 00000000 */ .word 0x00000000
    /* 102F54 80112754 00000000 */ .word 0x00000000
    /* 102F58 80112758 00000000 */ .word 0x00000000
    /* 102F5C 8011275C 00000000 */ .word 0x00000000
    /* 102F60 80112760 00000000 */ .word 0x00000000
    /* 102F64 80112764 00000000 */ .word 0x00000000
    /* 102F68 80112768 00000000 */ .word 0x00000000
    /* 102F6C 8011276C 00000000 */ .word 0x00000000
enddlabel D_8011274C

nonmatching D_80112770

dlabel D_80112770
    /* 102F70 80112770 00000000 */ .word 0x00000000
    /* 102F74 80112774 00000000 */ .word 0x00000000
enddlabel D_80112770

nonmatching D_80112778

dlabel D_80112778
    /* 102F78 80112778 00000000 */ .word 0x00000000
enddlabel D_80112778

nonmatching D_8011277C

dlabel D_8011277C
    /* 102F7C 8011277C 00000000 */ .word 0x00000000
    /* 102F80 80112780 00000000 */ .word 0x00000000
    /* 102F84 80112784 00000000 */ .word 0x00000000
    /* 102F88 80112788 00000000 */ .word 0x00000000
enddlabel D_8011277C

nonmatching D_8011278C

dlabel D_8011278C
    /* 102F8C 8011278C 00000000 */ .word 0x00000000
    /* 102F90 80112790 00000000 */ .word 0x00000000
    /* 102F94 80112794 00000000 */ .word 0x00000000
    /* 102F98 80112798 00000000 */ .word 0x00000000
enddlabel D_8011278C
