.include "macro.inc"
/* ============================================================
 * W64-A18  BLOB-vs-TU OWNERSHIP SWEEP -- SPLAT-LANE FILLER ONLY
 *
 * This segment's data is OWNED by
 *     build/recon/game/common/aih_cop.cpp.o
 * (section .data, retail 0x8010cea4..0x8010cfd4), whose own bytes were
 * proved byte-identical to retail before the cut (ownmap2 E1-E5, with
 * R_MIPS_32 relocations RESOLVED against the retail VA map).
 *
 * The RECON-lane linker script must link that object's .data here and must
 * NOT link this file -- otherwise every label below is multiply defined.
 * It stays in the tree only so the legacy splat-lane script
 * (linkers/nfs4.ld, which links build/src/**, where no recon object exists)
 * keeps producing a byte-identical image.
 * ============================================================ */

.section .data, "wa"

/* Generated by spimdisasm 1.40.2 */

nonmatching AIHigh_Cop_AggressionData

dlabel AIHigh_Cop_AggressionData
    /* FD6A4 8010CEA4 */ .asciz "\n"
    /* 0A000000 */
.align 2
    /* FD6A8 8010CEA8 00000A00 */ .word 0x000A0000
    /* FD6AC 8010CEAC 00000D00 */ .word 0x000D0000
    /* FD6B0 8010CEB0 00020000 */ .word 0x00000200
    /* FD6B4 8010CEB4 00020000 */ .word 0x00000200
    /* FD6B8 8010CEB8 08000000 */ .word 0x00000008
    /* FD6BC 8010CEBC 00000E00 */ .word 0x000E0000
    /* FD6C0 8010CEC0 00000F00 */ .word 0x000F0000
    /* FD6C4 8010CEC4 00030000 */ .word 0x00000300
    /* FD6C8 8010CEC8 00020000 */ .word 0x00000200
    /* FD6CC 8010CECC 04000000 */ .word 0x00000004
    /* FD6D0 8010CED0 00001200 */ .word 0x00120000
    /* FD6D4 8010CED4 00001200 */ .word 0x00120000
    /* FD6D8 8010CED8 80040000 */ .word 0x00000480
    /* FD6DC 8010CEDC 00040000 */ .word 0x00000400
enddlabel AIHigh_Cop_AggressionData

nonmatching AICop_skillDelay

dlabel AICop_skillDelay
    /* FD6E0 8010CEE0 CC0C0000 */ .word 0x00000CCC
    /* FD6E4 8010CEE4 99190000 */ .word 0x00001999
    /* FD6E8 8010CEE8 00000100 */ .word 0x00010000
enddlabel AICop_skillDelay

nonmatching AIH_Cop_chasePositions

dlabel AIH_Cop_chasePositions
    /* FD6EC 8010CEEC 00000000 */ .word 0x00000000
    /* FD6F0 8010CEF0 00000000 */ .word 0x00000000
    /* FD6F4 8010CEF4 00000800 */ .word 0x00080000
    /* FD6F8 8010CEF8 0000FAFF */ .word 0xFFFA0000
    /* FD6FC 8010CEFC 00000000 */ .word 0x00000000
    /* FD700 8010CF00 00000800 */ .word 0x00080000
    /* FD704 8010CF04 00000600 */ .word 0x00060000
    /* FD708 8010CF08 00000000 */ .word 0x00000000
    /* FD70C 8010CF0C 00000000 */ .word 0x00000000
    /* FD710 8010CF10 00000000 */ .word 0x00000000
    /* FD714 8010CF14 00000000 */ .word 0x00000000
    /* FD718 8010CF18 0000F6FF */ .word 0xFFF60000
    /* FD71C 8010CF1C 00000000 */ .word 0x00000000
    /* FD720 8010CF20 00000000 */ .word 0x00000000
    /* FD724 8010CF24 0000F6FF */ .word 0xFFF60000
    /* FD728 8010CF28 00000000 */ .word 0x00000000
    /* FD72C 8010CF2C 00000000 */ .word 0x00000000
    /* FD730 8010CF30 0000F6FF */ .word 0xFFF60000
    /* FD734 8010CF34 00000000 */ .word 0x00000000
    /* FD738 8010CF38 00000000 */ .word 0x00000000
    /* FD73C 8010CF3C 00000500 */ .word 0x00050000
    /* FD740 8010CF40 0000FCFF */ .word 0xFFFC0000
    /* FD744 8010CF44 00000000 */ .word 0x00000000
    /* FD748 8010CF48 00000500 */ .word 0x00050000
    /* FD74C 8010CF4C 00000400 */ .word 0x00040000
    /* FD750 8010CF50 00000000 */ .word 0x00000000
    /* FD754 8010CF54 00000500 */ .word 0x00050000
    /* FD758 8010CF58 00000000 */ .word 0x00000000
    /* FD75C 8010CF5C 00000000 */ .word 0x00000000
    /* FD760 8010CF60 0000FBFF */ .word 0xFFFB0000
    /* FD764 8010CF64 00000000 */ .word 0x00000000
    /* FD768 8010CF68 00000000 */ .word 0x00000000
    /* FD76C 8010CF6C 0000FBFF */ .word 0xFFFB0000
    /* FD770 8010CF70 00000000 */ .word 0x00000000
    /* FD774 8010CF74 00000000 */ .word 0x00000000
    /* FD778 8010CF78 0000FBFF */ .word 0xFFFB0000
    /* FD77C 8010CF7C 00000000 */ .word 0x00000000
    /* FD780 8010CF80 00000000 */ .word 0x00000000
    /* FD784 8010CF84 00000500 */ .word 0x00050000
    /* FD788 8010CF88 0000FCFF */ .word 0xFFFC0000
    /* FD78C 8010CF8C 00000000 */ .word 0x00000000
    /* FD790 8010CF90 00000500 */ .word 0x00050000
    /* FD794 8010CF94 00000400 */ .word 0x00040000
    /* FD798 8010CF98 00000000 */ .word 0x00000000
    /* FD79C 8010CF9C 00000500 */ .word 0x00050000
    /* FD7A0 8010CFA0 00000000 */ .word 0x00000000
    /* FD7A4 8010CFA4 00000000 */ .word 0x00000000
    /* FD7A8 8010CFA8 0000FBFF */ .word 0xFFFB0000
    /* FD7AC 8010CFAC 00000000 */ .word 0x00000000
    /* FD7B0 8010CFB0 00000000 */ .word 0x00000000
    /* FD7B4 8010CFB4 0000FBFF */ .word 0xFFFB0000
    /* FD7B8 8010CFB8 00000000 */ .word 0x00000000
    /* FD7BC 8010CFBC 00000000 */ .word 0x00000000
    /* FD7C0 8010CFC0 0000FBFF */ .word 0xFFFB0000
enddlabel AIH_Cop_chasePositions

nonmatching NitroDistanceMeters

dlabel NitroDistanceMeters
    /* FD7C4 8010CFC4 00003C00 */ .word 0x003C0000
    /* FD7C8 8010CFC8 00001900 */ .word 0x00190000
    /* FD7CC 8010CFCC 00003C00 */ .word 0x003C0000
    /* FD7D0 8010CFD0 00001900 */ .word 0x00190000
enddlabel NitroDistanceMeters
