.include "macro.inc"
/* ============================================================
 * W64-A18  BLOB-vs-TU OWNERSHIP SWEEP -- SPLAT-LANE FILLER ONLY
 *
 * This segment's data is OWNED by
 *     build/recon/game/common/anim.cpp.o
 * (section .data, retail 0x8010e14c..0x8010e274), whose own bytes were
 * proved byte-identical to retail before the cut (ownmap2 E1-E5, with
 * R_MIPS_32 relocations RESOLVED against the retail VA map).
 *
 * The RECON-lane linker script must link that object's .data here and must
 * NOT link this file -- otherwise every label below is multiply defined.
 * It stays in the tree only so the legacy splat-lane script
 * (linkers/nfs4.ld, which links build/src/**, where no recon object exists)
 * keeps producing a byte-identical image.
 * ============================================================ */

.section .data, "wa"

/* Generated by spimdisasm 1.40.2 */

nonmatching animSlots

dlabel animSlots
    /* FE94C 8010E14C 00000000 */ .word 0x00000000
    /* FE950 8010E150 00000000 */ .word 0x00000000
    /* FE954 8010E154 00000000 */ .word 0x00000000
    /* FE958 8010E158 00000000 */ .word 0x00000000
    /* FE95C 8010E15C 00000000 */ .word 0x00000000
    /* FE960 8010E160 00000000 */ .word 0x00000000
    /* FE964 8010E164 00000000 */ .word 0x00000000
    /* FE968 8010E168 00000000 */ .word 0x00000000
    /* FE96C 8010E16C 00000000 */ .word 0x00000000
    /* FE970 8010E170 00000000 */ .word 0x00000000
    /* FE974 8010E174 00000000 */ .word 0x00000000
    /* FE978 8010E178 00000000 */ .word 0x00000000
    /* FE97C 8010E17C 00000000 */ .word 0x00000000
    /* FE980 8010E180 00000000 */ .word 0x00000000
    /* FE984 8010E184 00000000 */ .word 0x00000000
    /* FE988 8010E188 00000000 */ .word 0x00000000
    /* FE98C 8010E18C 00000000 */ .word 0x00000000
    /* FE990 8010E190 00000000 */ .word 0x00000000
    /* FE994 8010E194 00000000 */ .word 0x00000000
    /* FE998 8010E198 00000000 */ .word 0x00000000
    /* FE99C 8010E19C 00000000 */ .word 0x00000000
    /* FE9A0 8010E1A0 00000000 */ .word 0x00000000
    /* FE9A4 8010E1A4 00000000 */ .word 0x00000000
    /* FE9A8 8010E1A8 00000000 */ .word 0x00000000
    /* FE9AC 8010E1AC 00000000 */ .word 0x00000000
    /* FE9B0 8010E1B0 00000000 */ .word 0x00000000
    /* FE9B4 8010E1B4 00000000 */ .word 0x00000000
    /* FE9B8 8010E1B8 00000000 */ .word 0x00000000
    /* FE9BC 8010E1BC 00000000 */ .word 0x00000000
    /* FE9C0 8010E1C0 00000000 */ .word 0x00000000
    /* FE9C4 8010E1C4 00000000 */ .word 0x00000000
    /* FE9C8 8010E1C8 00000000 */ .word 0x00000000
enddlabel animSlots

nonmatching Anim_gInstanceFromIndex

dlabel Anim_gInstanceFromIndex
    /* FE9CC 8010E1CC 00000000 */ .word 0x00000000
    /* FE9D0 8010E1D0 00000000 */ .word 0x00000000
    /* FE9D4 8010E1D4 00000000 */ .word 0x00000000
    /* FE9D8 8010E1D8 00000000 */ .word 0x00000000
    /* FE9DC 8010E1DC 00000000 */ .word 0x00000000
    /* FE9E0 8010E1E0 00000000 */ .word 0x00000000
    /* FE9E4 8010E1E4 00000000 */ .word 0x00000000
    /* FE9E8 8010E1E8 00000000 */ .word 0x00000000
    /* FE9EC 8010E1EC 00000000 */ .word 0x00000000
    /* FE9F0 8010E1F0 00000000 */ .word 0x00000000
    /* FE9F4 8010E1F4 00000000 */ .word 0x00000000
    /* FE9F8 8010E1F8 00000000 */ .word 0x00000000
    /* FE9FC 8010E1FC 00000000 */ .word 0x00000000
    /* FEA00 8010E200 00000000 */ .word 0x00000000
    /* FEA04 8010E204 00000000 */ .word 0x00000000
    /* FEA08 8010E208 00000000 */ .word 0x00000000
    /* FEA0C 8010E20C 00000000 */ .word 0x00000000
    /* FEA10 8010E210 00000000 */ .word 0x00000000
    /* FEA14 8010E214 00000000 */ .word 0x00000000
    /* FEA18 8010E218 00000000 */ .word 0x00000000
    /* FEA1C 8010E21C 00000000 */ .word 0x00000000
    /* FEA20 8010E220 00000000 */ .word 0x00000000
    /* FEA24 8010E224 00000000 */ .word 0x00000000
    /* FEA28 8010E228 00000000 */ .word 0x00000000
    /* FEA2C 8010E22C 00000000 */ .word 0x00000000
    /* FEA30 8010E230 00000000 */ .word 0x00000000
    /* FEA34 8010E234 00000000 */ .word 0x00000000
    /* FEA38 8010E238 00000000 */ .word 0x00000000
    /* FEA3C 8010E23C 00000000 */ .word 0x00000000
    /* FEA40 8010E240 00000000 */ .word 0x00000000
    /* FEA44 8010E244 00000000 */ .word 0x00000000
    /* FEA48 8010E248 00000000 */ .word 0x00000000
enddlabel Anim_gInstanceFromIndex

nonmatching animScripts

dlabel animScripts
    /* FEA4C 8010E24C 00000000 */ .word 0x00000000
    /* FEA50 8010E250 00000000 */ .word 0x00000000
    /* FEA54 8010E254 00000000 */ .word 0x00000000
    /* FEA58 8010E258 00000000 */ .word 0x00000000
    /* FEA5C 8010E25C 00000000 */ .word 0x00000000
    /* FEA60 8010E260 00000000 */ .word 0x00000000
    /* FEA64 8010E264 00000000 */ .word 0x00000000
    /* FEA68 8010E268 00000000 */ .word 0x00000000
    /* FEA6C 8010E26C 00000000 */ .word 0x00000000
    /* FEA70 8010E270 00000000 */ .word 0x00000000
enddlabel animScripts
