.include "macro.inc"
/* ============================================================
 * W64-A18  BLOB-vs-TU OWNERSHIP SWEEP -- SPLAT-LANE FILLER ONLY
 *
 * This segment's data is OWNED by
 *     build/recon/frontend/common/screenaudio.cpp.o
 * (section .data, retail 0x800528e8..0x800528ec), whose own bytes were
 * proved byte-identical to retail before the cut (ownmap2 E1-E5, with
 * R_MIPS_32 relocations RESOLVED against the retail VA map).
 *
 * The RECON-lane linker script must link that object's .data here and must
 * NOT link this file -- otherwise every label below is multiply defined.
 * It stays in the tree only so the legacy splat-lane script
 * (linkers/nfs4.ld, which links build/src/**, where no recon object exists)
 * keeps producing a byte-identical image.
 *
 * NOTE: the retail run's last blob record was SPLIT at 0x800528ec;
 * the residual tail is the next _rNN piece.
 * ============================================================ */

.section .data, "wa"

/* Generated by spimdisasm 1.40.2 */

nonmatching screenAudio

dlabel screenAudio
    /* 430E8 800528E8 00000000 */ .word 0x00000000
enddlabel screenAudio
