.include "macro.inc"
/* ============================================================
 * W64-A18  BLOB-vs-TU OWNERSHIP SWEEP -- SPLAT-LANE FILLER ONLY
 *
 * This segment's data is OWNED by
 *     build/recon/frontend/common/feinput.cpp.o
 * (section .data, retail 0x8005173c..0x800517bc), whose own bytes were
 * proved byte-identical to retail before the cut (ownmap2 E1-E5, with
 * R_MIPS_32 relocations RESOLVED against the retail VA map).
 *
 * The RECON-lane linker script must link that object's .data here and must
 * NOT link this file -- otherwise every label below is multiply defined.
 * It stays in the tree only so the legacy splat-lane script
 * (linkers/nfs4.ld, which links build/src/**, where no recon object exists)
 * keeps producing a byte-identical image.
 *
 * NOTE: the retail run's last blob record was SPLIT at 0x800517bc;
 * the residual tail is the next _rNN piece.
 * ============================================================ */

.section .data, "wa"

/* Generated by spimdisasm 1.40.2 */

nonmatching getKeyMappings

dlabel getKeyMappings
    /* 41F3C 8005173C 10000000 */ .word 0x00000010
    /* 41F40 80051740 00020000 */ .word 0x00000200
    /* 41F44 80051744 80000000 */ .word 0x00000080
    /* 41F48 80051748 00080000 */ .word 0x00000800
    /* 41F4C 8005174C 20000000 */ .word 0x00000020
    /* 41F50 80051750 00100000 */ .word 0x00001000
    /* 41F54 80051754 40000000 */ .word 0x00000040
    /* 41F58 80051758 00040000 */ .word 0x00000400
    /* 41F5C 8005175C 00040000 */ .word 0x00000400
    /* 41F60 80051760 20000000 */ .word 0x00000020
    /* 41F64 80051764 00010000 */ .word 0x00000100
    /* 41F68 80051768 40000000 */ .word 0x00000040
    /* 41F6C 8005176C 00080000 */ .word 0x00000800
    /* 41F70 80051770 80000000 */ .word 0x00000080
    /* 41F74 80051774 00020000 */ .word 0x00000200
    /* 41F78 80051778 00010000 */ .word 0x00000100
    /* 41F7C 8005177C 00001000 */ .word 0x00100000
    /* 41F80 80051780 00020000 */ .word 0x00000200
    /* 41F84 80051784 00008000 */ .word 0x00800000
    /* 41F88 80051788 00080000 */ .word 0x00000800
    /* 41F8C 8005178C 00002000 */ .word 0x00200000
    /* 41F90 80051790 00100000 */ .word 0x00001000
    /* 41F94 80051794 00004000 */ .word 0x00400000
    /* 41F98 80051798 00040000 */ .word 0x00000400
    /* 41F9C 8005179C 00000010 */ .word 0x10000000
    /* 41FA0 800517A0 00020000 */ .word 0x00000200
    /* 41FA4 800517A4 00000080 */ .word 0x80000000
    /* 41FA8 800517A8 00080000 */ .word 0x00000800
    /* 41FAC 800517AC 00000020 */ .word 0x20000000
    /* 41FB0 800517B0 00100000 */ .word 0x00001000
    /* 41FB4 800517B4 00000040 */ .word 0x40000000
    /* 41FB8 800517B8 00040000 */ .word 0x00000400
enddlabel getKeyMappings
