.include "macro.inc"
/* W64-A18: residual segment of front_data -- labels no recon TU defines
 * (or a record tail a recon TU's section stops short of).
 * Linked by BOTH lanes. */

.section .data, "wa"

/* Generated by spimdisasm 1.40.2 */

nonmatching D_800528EC

dlabel D_800528EC
    /* 430EC 800528EC 00000000 */ .word 0x00000000
enddlabel D_800528EC

nonmatching screenMemcard

dlabel screenMemcard
    /* 430F0 800528F0 00000000 */ .word 0x00000000
enddlabel screenMemcard

nonmatching GRIDMEMCARD_STARTX

dlabel GRIDMEMCARD_STARTX
    /* 430F4 800528F4 */ .short 0x0000
    /* 430F6 800528F6 */ .short 0x0000
enddlabel GRIDMEMCARD_STARTX

nonmatching GRIDMEMCARD_STARTY

dlabel GRIDMEMCARD_STARTY
    /* 430F8 800528F8 */ .short 0x0000
    /* 430FA 800528FA */ .short 0x0000
enddlabel GRIDMEMCARD_STARTY

nonmatching MEMCARD_DELTAX

dlabel MEMCARD_DELTAX
    /* 430FC 800528FC 00000000 */ .word 0x00000000
enddlabel MEMCARD_DELTAX

nonmatching MEMCARD_DELTAY

dlabel MEMCARD_DELTAY
    /* 43100 80052900 00000000 */ .word 0x00000000
enddlabel MEMCARD_DELTAY

nonmatching kMemCardMessageH

dlabel kMemCardMessageH
    /* 43104 80052904 00000000 */ .word 0x00000000
enddlabel kMemCardMessageH

nonmatching kMemCardMessageH1

dlabel kMemCardMessageH1
    /* 43108 80052908 00000000 */ .word 0x00000000
enddlabel kMemCardMessageH1

nonmatching EXTRAYATTOP

dlabel EXTRAYATTOP
    /* 4310C 8005290C */ .short 0x0000
    /* 4310E 8005290E */ .short 0x0000
enddlabel EXTRAYATTOP

nonmatching GRIDMEMCARD_WIDTH

dlabel GRIDMEMCARD_WIDTH
    /* 43110 80052910 */ .short 0x0000
    /* 43112 80052912 */ .short 0x0000
enddlabel GRIDMEMCARD_WIDTH

nonmatching GRIDMEMCARD_HEIGHT

dlabel GRIDMEMCARD_HEIGHT
    /* 43114 80052914 */ .short 0x0000
    /* 43116 80052916 */ .short 0x0000
enddlabel GRIDMEMCARD_HEIGHT

nonmatching GRIDMEMCARDGOURAUDBIT_X

dlabel GRIDMEMCARDGOURAUDBIT_X
    /* 43118 80052918 */ .short 0x0000
    /* 4311A 8005291A */ .short 0x0000
enddlabel GRIDMEMCARDGOURAUDBIT_X

nonmatching GRIDMEMCARDGOURAUDBIT_Y

dlabel GRIDMEMCARDGOURAUDBIT_Y
    /* 4311C 8005291C */ .short 0x0000
    /* 4311E 8005291E */ .short 0x0000
enddlabel GRIDMEMCARDGOURAUDBIT_Y

nonmatching MEMCARDICONOFFX

dlabel MEMCARDICONOFFX
    /* 43120 80052920 00000000 */ .word 0x00000000
enddlabel MEMCARDICONOFFX

nonmatching MEMCARDICONOFFY

dlabel MEMCARDICONOFFY
    /* 43124 80052924 00000000 */ .word 0x00000000
enddlabel MEMCARDICONOFFY

nonmatching kMemCardMessage1X

dlabel kMemCardMessage1X
    /* 43128 80052928 */ .short 0x0000
    /* 4312A 8005292A */ .short 0x0000
enddlabel kMemCardMessage1X

nonmatching kMemCardMessage1Y

dlabel kMemCardMessage1Y
    /* 4312C 8005292C 00000000 */ .word 0x00000000
enddlabel kMemCardMessage1Y

nonmatching kMemCardMessageX

dlabel kMemCardMessageX
    /* 43130 80052930 */ .short 0x0000
    /* 43132 80052932 */ .short 0x0000
enddlabel kMemCardMessageX

nonmatching kMemCardMessageY

dlabel kMemCardMessageY
    /* 43134 80052934 */ .short 0x0000
    /* 43136 80052936 */ .short 0x0000
enddlabel kMemCardMessageY

nonmatching fMemIcon

dlabel fMemIcon
    /* 43138 80052938 00000000 */ .word 0x00000000
    /* 4313C 8005293C 00000000 */ .word 0x00000000
enddlabel fMemIcon

nonmatching D_80052940

dlabel D_80052940
    /* 43140 80052940 00000000 */ .word 0x00000000
enddlabel D_80052940

nonmatching screenPinkSlipCongrats

dlabel screenPinkSlipCongrats
    /* 43144 80052944 00000000 */ .word 0x00000000
enddlabel screenPinkSlipCongrats

nonmatching screenTournamentTrophy

dlabel screenTournamentTrophy
    /* 43148 80052948 00000000 */ .word 0x00000000
enddlabel screenTournamentTrophy

nonmatching screenBeTheCopCongrats

dlabel screenBeTheCopCongrats
    /* 4314C 8005294C 00000000 */ .word 0x00000000
enddlabel screenBeTheCopCongrats

nonmatching screenTournamentCongrats

dlabel screenTournamentCongrats
    /* 43150 80052950 00000000 */ .word 0x00000000
enddlabel screenTournamentCongrats

nonmatching congratsSwapFileName

dlabel congratsSwapFileName
    /* 43154 80052954 00000000 */ .word 0x00000000
    /* 43158 80052958 00000000 */ .word 0x00000000
    /* 4315C 8005295C 00000000 */ .word 0x00000000
    /* 43160 80052960 00000000 */ .word 0x00000000
enddlabel congratsSwapFileName

nonmatching fPermFileNameBuf

dlabel fPermFileNameBuf
    /* 43164 80052964 00000000 */ .word 0x00000000
    /* 43168 80052968 00000000 */ .word 0x00000000
    /* 4316C 8005296C 00000000 */ .word 0x00000000
    /* 43170 80052970 00000000 */ .word 0x00000000
    /* 43174 80052974 00000000 */ .word 0x00000000
enddlabel fPermFileNameBuf

nonmatching NewRecords

dlabel NewRecords
    /* 43178 80052978 00000000 */ .word 0x00000000
    /* 4317C 8005297C 00000000 */ .word 0x00000000
    /* 43180 80052980 00000000 */ .word 0x00000000
    /* 43184 80052984 00000000 */ .word 0x00000000
    /* 43188 80052988 00000000 */ .word 0x00000000
    /* 4318C 8005298C 00000000 */ .word 0x00000000
    /* 43190 80052990 00000000 */ .word 0x00000000
    /* 43194 80052994 00000000 */ .word 0x00000000
enddlabel NewRecords

nonmatching NewBestLap

dlabel NewBestLap
    /* 43198 80052998 00000000 */ .word 0x00000000
    /* 4319C 8005299C 00000000 */ .word 0x00000000
enddlabel NewBestLap

.align 2