.include "macro.inc"
/* W64-A18: residual segment of front_data -- labels no recon TU defines
 * (or a record tail a recon TU's section stops short of).
 * Linked by BOTH lanes. */

.section .data, "wa"

/* Generated by spimdisasm 1.40.2 */

nonmatching D_80052074

dlabel D_80052074
    /* 42874 80052074 00000000 */ .word 0x00000000
enddlabel D_80052074

.align 2
nonmatching kBannerColors

dlabel kBannerColors
    /* 42878 80052078 */ .asciz "\nA<"
    /* 0A413C00 */
.align 2
.align 2
    /* 4287C 8005207C */ .asciz "D>"
    /* 443E0000 */
.align 2
.align 2
    /* 42880 80052080 */ .asciz "!!!"
    /* 21212100 */
.align 2
.align 2
    /* 42884 80052084 */ .asciz "D0"
    /* 44300000 */
.align 2
enddlabel kBannerColors

nonmatching screenTrophyInfo

dlabel screenTrophyInfo
    /* 42888 80052088 00000000 */ .word 0x00000000
enddlabel screenTrophyInfo

nonmatching gSwapFileNameTI

dlabel gSwapFileNameTI
    /* 4288C 8005208C 00000000 */ .word 0x00000000
    /* 42890 80052090 00000000 */ .word 0x00000000
    /* 42894 80052094 00000000 */ .word 0x00000000
    /* 42898 80052098 00000000 */ .word 0x00000000
    /* 4289C 8005209C 00000000 */ .word 0x00000000
enddlabel gSwapFileNameTI
