.include "macro.inc"
/* W64-A18: residual segment of front_data -- labels no recon TU defines
 * (or a record tail a recon TU's section stops short of).
 * Linked by BOTH lanes. */

.section .data, "wa"

/* Generated by spimdisasm 1.40.2 */

nonmatching D_800517BC

dlabel D_800517BC
    /* 41FBC 800517BC 00000000 */ .word 0x00000000
enddlabel D_800517BC

nonmatching gMenu_SubMenuPlayer

dlabel gMenu_SubMenuPlayer
    /* 41FC0 800517C0 FFFFFFFF */ .word 0xFFFFFFFF
    /* 41FC4 800517C4 00000000 */ .word 0x00000000
enddlabel gMenu_SubMenuPlayer

nonmatching _7tScreen_fSuppressLoadingText

dlabel _7tScreen_fSuppressLoadingText
    /* 41FC8 800517C8 00000000 */ .word 0x00000000
enddlabel _7tScreen_fSuppressLoadingText

nonmatching gCurrentShapes

dlabel gCurrentShapes
    /* 41FCC 800517CC 00000000 */ .word 0x00000000
enddlabel gCurrentShapes

nonmatching FeTools_gScrollTicksOut

dlabel FeTools_gScrollTicksOut
    /* 41FD0 800517D0 1E000000 */ .word 0x0000001E
enddlabel FeTools_gScrollTicksOut

nonmatching font12

dlabel font12
    /* 41FD4 800517D4 00000000 */ .word 0x00000000
enddlabel font12

nonmatching font18

dlabel font18
    /* 41FD8 800517D8 00000000 */ .word 0x00000000
enddlabel font18

nonmatching fontTitle

dlabel fontTitle
    /* 41FDC 800517DC 00000000 */ .word 0x00000000
enddlabel fontTitle

nonmatching currentSize

dlabel currentSize
    /* 41FE0 800517E0 */ .short 0x0000
    /* 41FE2 800517E2 */ .short 0x0000
    /* 41FE4 800517E4 */ .short 0x0000
    /* 41FE6 800517E6 */ .short 0x0000
enddlabel currentSize

nonmatching overRide

dlabel overRide
    /* 41FE8 800517E8 00000000 */ .word 0x00000000
enddlabel overRide

nonmatching ComingIntoTheFrontEndTheVeryFirstTime

dlabel ComingIntoTheFrontEndTheVeryFirstTime
    /* 41FEC 800517EC 00000000 */ .word 0x00000000
enddlabel ComingIntoTheFrontEndTheVeryFirstTime

nonmatching D_800517F0

dlabel D_800517F0
    /* 41FF0 800517F0 18000000 */ .word 0x00000018
    /* 41FF4 800517F4 18000000 */ .word 0x00000018
    /* 41FF8 800517F8 18000000 */ .word 0x00000018
    /* 41FFC 800517FC 17000000 */ .word 0x00000017
    /* 42000 80051800 16000000 */ .word 0x00000016
    /* 42004 80051804 18000000 */ .word 0x00000018
    /* 42008 80051808 18000000 */ .word 0x00000018
    /* 4200C 8005180C 18000000 */ .word 0x00000018
    /* 42010 80051810 17000000 */ .word 0x00000017
    /* 42014 80051814 16000000 */ .word 0x00000016
    /* 42018 80051818 18000000 */ .word 0x00000018
    /* 4201C 8005181C 18000000 */ .word 0x00000018
    /* 42020 80051820 18000000 */ .word 0x00000018
    /* 42024 80051824 18000000 */ .word 0x00000018
    /* 42028 80051828 16000000 */ .word 0x00000016
    /* 4202C 8005182C 18000000 */ .word 0x00000018
    /* 42030 80051830 18000000 */ .word 0x00000018
    /* 42034 80051834 18000000 */ .word 0x00000018
    /* 42038 80051838 18000000 */ .word 0x00000018
    /* 4203C 8005183C 19000000 */ .word 0x00000019
    /* 42040 80051840 1A000000 */ .word 0x0000001A
    /* 42044 80051844 1A000000 */ .word 0x0000001A
    /* 42048 80051848 1A000000 */ .word 0x0000001A
    /* 4204C 8005184C 18000000 */ .word 0x00000018
    /* 42050 80051850 19000000 */ .word 0x00000019
    /* 42054 80051854 1A000000 */ .word 0x0000001A
    /* 42058 80051858 1A000000 */ .word 0x0000001A
    /* 4205C 8005185C 1A000000 */ .word 0x0000001A
    /* 42060 80051860 18000000 */ .word 0x00000018
    /* 42064 80051864 19000000 */ .word 0x00000019
    /* 42068 80051868 1B000000 */ .word 0x0000001B
    /* 4206C 8005186C 1B000000 */ .word 0x0000001B
    /* 42070 80051870 1B000000 */ .word 0x0000001B
    /* 42074 80051874 1B000000 */ .word 0x0000001B
    /* 42078 80051878 1B000000 */ .word 0x0000001B
enddlabel D_800517F0

.align 2
nonmatching D_8005187C

dlabel D_8005187C
    /* 4207C 8005187C */ .asciz "\x1A"
    /* 1A000000 */
.align 2
.align 2
    /* 42080 80051880 */ .asciz "\x1A"
    /* 1A000000 */
.align 2
.align 2
    /* 42084 80051884 */ .asciz "\x1A"
    /* 1A000000 */
.align 2
    /* 42088 80051888 18000000 */ .word 0x00000018
    /* 4208C 8005188C 19000000 */ .word 0x00000019
    /* 42090 80051890 1A000000 */ .word 0x0000001A
    /* 42094 80051894 1A000000 */ .word 0x0000001A
    /* 42098 80051898 1A000000 */ .word 0x0000001A
    /* 4209C 8005189C 18000000 */ .word 0x00000018
    /* 420A0 800518A0 19000000 */ .word 0x00000019
    /* 420A4 800518A4 1A000000 */ .word 0x0000001A
    /* 420A8 800518A8 1A000000 */ .word 0x0000001A
    /* 420AC 800518AC 1A000000 */ .word 0x0000001A
    /* 420B0 800518B0 18000000 */ .word 0x00000018
    /* 420B4 800518B4 19000000 */ .word 0x00000019
    /* 420B8 800518B8 1A000000 */ .word 0x0000001A
    /* 420BC 800518BC 1A000000 */ .word 0x0000001A
    /* 420C0 800518C0 1A000000 */ .word 0x0000001A
    /* 420C4 800518C4 1B000000 */ .word 0x0000001B
    /* 420C8 800518C8 1B000000 */ .word 0x0000001B
    /* 420CC 800518CC 1B000000 */ .word 0x0000001B
    /* 420D0 800518D0 1B000000 */ .word 0x0000001B
    /* 420D4 800518D4 1B000000 */ .word 0x0000001B
    /* 420D8 800518D8 1B000000 */ .word 0x0000001B
    /* 420DC 800518DC 1B000000 */ .word 0x0000001B
    /* 420E0 800518E0 1B000000 */ .word 0x0000001B
    /* 420E4 800518E4 1B000000 */ .word 0x0000001B
    /* 420E8 800518E8 1B000000 */ .word 0x0000001B
    /* 420EC 800518EC 1B000000 */ .word 0x0000001B
    /* 420F0 800518F0 1B000000 */ .word 0x0000001B
    /* 420F4 800518F4 1B000000 */ .word 0x0000001B
    /* 420F8 800518F8 1B000000 */ .word 0x0000001B
    /* 420FC 800518FC 1B000000 */ .word 0x0000001B
    /* 42100 80051900 1B000000 */ .word 0x0000001B
    /* 42104 80051904 1B000000 */ .word 0x0000001B
enddlabel D_8005187C

nonmatching gFE_Cheats

dlabel gFE_Cheats
    /* 42108 80051908 00000000 */ .word 0x00000000
    /* 4210C 8005190C 00000000 */ .word 0x00000000
enddlabel gFE_Cheats

nonmatching gPSXMemCardFull

dlabel gPSXMemCardFull
    /* 42110 80051910 00000000 */ .word 0x00000000
enddlabel gPSXMemCardFull

nonmatching colourChosen

dlabel colourChosen
    /* 42114 80051914 00000000 */ .word 0x00000000
    /* 42118 80051918 00000000 */ .word 0x00000000
    /* 4211C 8005191C 00000000 */ .word 0x00000000
    /* 42120 80051920 00000000 */ .word 0x00000000
    /* 42124 80051924 00000000 */ .word 0x00000000
    /* 42128 80051928 00000000 */ .word 0x00000000
    /* 4212C 8005192C 00000000 */ .word 0x00000000
    /* 42130 80051930 00000000 */ .word 0x00000000
enddlabel colourChosen

nonmatching gAllScreens

dlabel gAllScreens
    /* 42134 80051934 00000000 */ .word 0x00000000
enddlabel gAllScreens

nonmatching memCardReadOK

dlabel memCardReadOK
    /* 42138 80051938 00000000 */ .word 0x00000000
enddlabel memCardReadOK

nonmatching CarLineup

dlabel CarLineup
    /* 4213C 8005193C 00000000 */ .word 0x00000000
    /* 42140 80051940 00000000 */ .word 0x00000000
    /* 42144 80051944 00000000 */ .word 0x00000000
    /* 42148 80051948 00000000 */ .word 0x00000000
    /* 4214C 8005194C 00000000 */ .word 0x00000000
    /* 42150 80051950 00000000 */ .word 0x00000000
    /* 42154 80051954 00000000 */ .word 0x00000000
    /* 42158 80051958 00000000 */ .word 0x00000000
    /* 4215C 8005195C 00000000 */ .word 0x00000000
enddlabel CarLineup

nonmatching picked

dlabel picked
    /* 42160 80051960 00000000 */ .word 0x00000000
    /* 42164 80051964 00000000 */ .word 0x00000000
    /* 42168 80051968 00000000 */ .word 0x00000000
    /* 4216C 8005196C 00000000 */ .word 0x00000000
enddlabel picked

nonmatching SelectListNull

dlabel SelectListNull
    /* 42170 80051970 00000000 */ .word 0x00000000
enddlabel SelectListNull

nonmatching SelectListOffOn

dlabel SelectListOffOn
    /* 42174 80051974 67006600 */ .word 0x00660067
    /* 42178 80051978 00000000 */ .word 0x00000000
enddlabel SelectListOffOn

nonmatching SelectListNormal

dlabel SelectListNormal
    /* 4217C 8005197C E300E100 */ .word 0x00E100E3
    /* 42180 80051980 00000000 */ .word 0x00000000
enddlabel SelectListNormal

nonmatching SelectListOpponentUpgrades

dlabel SelectListOpponentUpgrades
    /* 42184 80051984 0F011001 */ .word 0x0110010F
    /* 42188 80051988 00000000 */ .word 0x00000000
enddlabel SelectListOpponentUpgrades

nonmatching SelectListTrackDirection

dlabel SelectListTrackDirection
    /* 4218C 8005198C E400E500 */ .word 0x00E500E4
    /* 42190 80051990 00000000 */ .word 0x00000000
enddlabel SelectListTrackDirection

nonmatching SelectListTransmission

dlabel SelectListTransmission
    /* 42194 80051994 14011301 */ .word 0x01130114
    /* 42198 80051998 00000000 */ .word 0x00000000
enddlabel SelectListTransmission

nonmatching SelectListDisplaySpeed

dlabel SelectListDisplaySpeed
    /* 4219C 8005199C F401F201 */ .word 0x01F201F4
    /* 421A0 800519A0 F3016700 */ .word 0x006701F3
    /* 421A4 800519A4 00000000 */ .word 0x00000000
enddlabel SelectListDisplaySpeed

nonmatching SelectListDisplayMap

dlabel SelectListDisplayMap
    /* 421A8 800519A8 6700E801 */ .word 0x01E80067
    /* 421AC 800519AC E9010000 */ .word 0x000001E9
enddlabel SelectListDisplayMap

nonmatching SelectListDisplayOpponentID

dlabel SelectListDisplayOpponentID
    /* 421B0 800519B0 6700F501 */ .word 0x01F50067
    /* 421B4 800519B4 F6010000 */ .word 0x000001F6
enddlabel SelectListDisplayOpponentID

nonmatching SelectListSplitTime

dlabel SelectListSplitTime
    /* 421B8 800519B8 6700EA01 */ .word 0x01EA0067
    /* 421BC 800519BC EB010000 */ .word 0x000001EB
enddlabel SelectListSplitTime

nonmatching SelectListSplitDisplay

dlabel SelectListSplitDisplay
    /* 421C0 800519C0 EC01ED01 */ .word 0x01ED01EC
    /* 421C4 800519C4 00000000 */ .word 0x00000000
enddlabel SelectListSplitDisplay

nonmatching SelectListUpgrades

dlabel SelectListUpgrades
    /* 421C8 800519C8 96009700 */ .word 0x00970096
    /* 421CC 800519CC 98000000 */ .word 0x00000098
enddlabel SelectListUpgrades

nonmatching SelectListControllerConfig

dlabel SelectListControllerConfig
    /* 421D0 800519D0 1B021C02 */ .word 0x021C021B
    /* 421D4 800519D4 1D020000 */ .word 0x0000021D
enddlabel SelectListControllerConfig

nonmatching SelectListAudioMode

dlabel SelectListAudioMode
    /* 421D8 800519D8 D201D301 */ .word 0x01D301D2
    /* 421DC 800519DC D4010000 */ .word 0x000001D4
enddlabel SelectListAudioMode

nonmatching D_800519E0

dlabel D_800519E0
    /* 421E0 800519E0 19000000 */ .word 0x00000019
    /* 421E4 800519E4 19000000 */ .word 0x00000019
    /* 421E8 800519E8 19000000 */ .word 0x00000019
    /* 421EC 800519EC 19000000 */ .word 0x00000019
    /* 421F0 800519F0 19000000 */ .word 0x00000019
    /* 421F4 800519F4 18000000 */ .word 0x00000018
    /* 421F8 800519F8 18000000 */ .word 0x00000018
    /* 421FC 800519FC 18000000 */ .word 0x00000018
    /* 42200 80051A00 18000000 */ .word 0x00000018
    /* 42204 80051A04 18000000 */ .word 0x00000018
    /* 42208 80051A08 1A000000 */ .word 0x0000001A
    /* 4220C 80051A0C 1A000000 */ .word 0x0000001A
    /* 42210 80051A10 1A000000 */ .word 0x0000001A
    /* 42214 80051A14 1B000000 */ .word 0x0000001B
    /* 42218 80051A18 1A000000 */ .word 0x0000001A
    /* 4221C 80051A1C 1B000000 */ .word 0x0000001B
    /* 42220 80051A20 1B000000 */ .word 0x0000001B
    /* 42224 80051A24 1B000000 */ .word 0x0000001B
    /* 42228 80051A28 1B000000 */ .word 0x0000001B
    /* 4222C 80051A2C 1B000000 */ .word 0x0000001B
    /* 42230 80051A30 1B000000 */ .word 0x0000001B
    /* 42234 80051A34 1B000000 */ .word 0x0000001B
    /* 42238 80051A38 1B000000 */ .word 0x0000001B
    /* 4223C 80051A3C 1B000000 */ .word 0x0000001B
    /* 42240 80051A40 1B000000 */ .word 0x0000001B
    /* 42244 80051A44 1C000000 */ .word 0x0000001C
    /* 42248 80051A48 1C000000 */ .word 0x0000001C
    /* 4224C 80051A4C 1C000000 */ .word 0x0000001C
    /* 42250 80051A50 1C000000 */ .word 0x0000001C
    /* 42254 80051A54 1C000000 */ .word 0x0000001C
enddlabel D_800519E0

nonmatching menuDefs

dlabel menuDefs
    /* 42258 80051A58 00000000 */ .word 0x00000000
    /* 4225C 80051A5C 00000000 */ .word 0x00000000
enddlabel menuDefs

nonmatching D_80051A60

dlabel D_80051A60
    /* 42260 80051A60 00000000 */ .word 0x00000000
enddlabel D_80051A60

nonmatching D_80051A64

dlabel D_80051A64
    /* 42264 80051A64 00000000 */ .word 0x00000000
enddlabel D_80051A64

nonmatching CURRENTPLAYER

dlabel CURRENTPLAYER
    /* 42268 80051A68 00000000 */ .word 0x00000000
enddlabel CURRENTPLAYER

.align 2
nonmatching productCode

dlabel productCode
    /* 4226C 80051A6C */ .asciz "SLUS-00826"
    /* 534C55532D30303832360000 */
.align 2
enddlabel productCode

nonmatching nomessage

dlabel nomessage
    /* 42278 80051A78 00000000 */ .word 0x00000000
enddlabel nomessage

nonmatching CURRENTLYUSINGMEMCARD

dlabel CURRENTLYUSINGMEMCARD
    /* 4227C 80051A7C 00000000 */ .word 0x00000000
enddlabel CURRENTLYUSINGMEMCARD

nonmatching MEMCARD_INITIALIZED

dlabel MEMCARD_INITIALIZED
    /* 42280 80051A80 00000000 */ .word 0x00000000
enddlabel MEMCARD_INITIALIZED

nonmatching textSysMemCardFail_Index

dlabel textSysMemCardFail_Index
    /* 42284 80051A84 00000000 */ .word 0x00000000
    /* 42288 80051A88 A5020000 */ .word 0x000002A5
    /* 4228C 80051A8C AD020000 */ .word 0x000002AD
    /* 42290 80051A90 A3020000 */ .word 0x000002A3
    /* 42294 80051A94 2B030000 */ .word 0x0000032B
    /* 42298 80051A98 9F020000 */ .word 0x0000029F
    /* 4229C 80051A9C 9D020000 */ .word 0x0000029D
enddlabel textSysMemCardFail_Index
