.include "macro.inc"
/* W65-A5: residual segment of rdata_80010000 -- the non-jump-table blob records.
 * Linked by BOTH lanes. */

.section .rodata, "a"

/* Generated by spimdisasm 1.40.2 */

.align 2

nonmatching _vt_25tScreenPinkSlipsCarSelect

dlabel _vt_25tScreenPinkSlipsCarSelect
    /* 2360 80011B60 00000000 */ .word 0x00000000
    /* 2364 80011B64 00000000 */ .word 0x00000000
    /* 2368 80011B68 00000000 */ .word 0x00000000
    /* 236C 80011B6C 38F60380 */ .word GetShapeInfo__25tScreenPinkSlipsCarSelectRsT1PPcT3
    /* 2370 80011B70 00000000 */ .word 0x00000000
    /* 2374 80011B74 D0EE0380 */ .word DrawBackground__25tScreenPinkSlipsCarSelect
    /* 2378 80011B78 00000000 */ .word 0x00000000
    /* 237C 80011B7C 2CF20380 */ .word DrawForeground__25tScreenPinkSlipsCarSelect
    /* 2380 80011B80 00000000 */ .word 0x00000000
    /* 2384 80011B84 D0F60380 */ .word ___25tScreenPinkSlipsCarSelect
    /* 2388 80011B88 00000000 */ .word 0x00000000
    /* 238C 80011B8C 80670280 */ .word PreLoad__7tScreen
    /* 2390 80011B90 00000000 */ .word 0x00000000
    /* 2394 80011B94 4CF20380 */ .word Initialize__25tScreenPinkSlipsCarSelect
    /* 2398 80011B98 00000000 */ .word 0x00000000
    /* 239C 80011B9C ACF20380 */ .word Cleanup__25tScreenPinkSlipsCarSelect
    /* 23A0 80011BA0 00000000 */ .word 0x00000000
    /* 23A4 80011BA4 C0680280 */ .word TransitionIsFinished__7tScreen
    /* 23A8 80011BA8 00000000 */ .word 0x00000000
    /* 23AC 80011BAC 90F50380 */ .word ProcessInput__25tScreenPinkSlipsCarSelect7tPlayerR13tInputKeyTypeR12tMenuCommand
    /* 23B0 80011BB0 00000000 */ .word 0x00000000
    /* 23B4 80011BB4 90E10380 */ .word DrawVideoWall__25tScreenCarSelectTwoPlayers
    /* 23B8 80011BB8 00000000 */ .word 0x00000000
    /* 23BC 80011BBC 44ED0380 */ .word InitializeVideoWall__25tScreenCarSelectTwoPlayer
    /* 23C0 80011BC0 00000000 */ .word 0x00000000
    /* 23C4 80011BC4 C8E30380 */ .word UpdateVideoWall__25tScreenCarSelectTwoPlayerR8tCarInfo
    /* 23C8 80011BC8 00000000 */ .word 0x00000000
    /* 23CC 80011BCC 40EE0380 */ .word GetCar__25tScreenPinkSlipsCarSelectR8tCarInfo
    /* 23D0 80011BD0 00000000 */ .word 0x00000000
    /* 23D4 80011BD4 10ED0380 */ .word AllocateAsyncBuffer__25tScreenCarSelectTwoPlayer
    /* 23D8 80011BD8 00000000 */ .word 0x00000000
    /* 23DC 80011BDC A8BC0380 */ .word FreeAsyncBuffer__16tScreenCarSelect
    /* 23E0 80011BE0 00000000 */ .word 0x00000000
    /* 23E4 80011BE4 9CE40380 */ .word TurnOffVideoWall__25tScreenCarSelectTwoPlayer
    /* 23E8 80011BE8 00000000 */ .word 0x00000000
    /* 23EC 80011BEC 00F30380 */ .word SetDialog__25tScreenPinkSlipsCarSelect
enddlabel _vt_25tScreenPinkSlipsCarSelect

nonmatching _vt_25tScreenCarSelectTwoPlayer

dlabel _vt_25tScreenCarSelectTwoPlayer
    /* 23F0 80011BF0 00000000 */ .word 0x00000000
    /* 23F4 80011BF4 00000000 */ .word 0x00000000
    /* 23F8 80011BF8 00000000 */ .word 0x00000000
    /* 23FC 80011BFC 30E30380 */ .word GetShapeInfo__25tScreenCarSelectTwoPlayerRsT1PPcT3
    /* 2400 80011C00 00000000 */ .word 0x00000000
    /* 2404 80011C04 BCE40380 */ .word DrawBackground__25tScreenCarSelectTwoPlayer
    /* 2408 80011C08 00000000 */ .word 0x00000000
    /* 240C 80011C0C 14EA0380 */ .word DrawForeground__25tScreenCarSelectTwoPlayer
    /* 2410 80011C10 00000000 */ .word 0x00000000
    /* 2414 80011C14 14F70380 */ .word ___25tScreenCarSelectTwoPlayer
    /* 2418 80011C18 00000000 */ .word 0x00000000
    /* 241C 80011C1C 80670280 */ .word PreLoad__7tScreen
    /* 2420 80011C20 00000000 */ .word 0x00000000
    /* 2424 80011C24 C0ED0380 */ .word Initialize__25tScreenCarSelectTwoPlayer
    /* 2428 80011C28 00000000 */ .word 0x00000000
    /* 242C 80011C2C 10EE0380 */ .word Cleanup__25tScreenCarSelectTwoPlayer
    /* 2430 80011C30 00000000 */ .word 0x00000000
    /* 2434 80011C34 C0680280 */ .word TransitionIsFinished__7tScreen
    /* 2438 80011C38 00000000 */ .word 0x00000000
    /* 243C 80011C3C 90BF0380 */ .word ProcessInput__16tScreenCarSelect7tPlayerR13tInputKeyTypeR12tMenuCommand
    /* 2440 80011C40 00000000 */ .word 0x00000000
    /* 2444 80011C44 90E10380 */ .word DrawVideoWall__25tScreenCarSelectTwoPlayers
    /* 2448 80011C48 00000000 */ .word 0x00000000
    /* 244C 80011C4C 44ED0380 */ .word InitializeVideoWall__25tScreenCarSelectTwoPlayer
    /* 2450 80011C50 00000000 */ .word 0x00000000
    /* 2454 80011C54 C8E30380 */ .word UpdateVideoWall__25tScreenCarSelectTwoPlayerR8tCarInfo
    /* 2458 80011C58 00000000 */ .word 0x00000000
    /* 245C 80011C5C 40E00380 */ .word GetCar__25tScreenCarSelectTwoPlayerR8tCarInfo
    /* 2460 80011C60 00000000 */ .word 0x00000000
    /* 2464 80011C64 10ED0380 */ .word AllocateAsyncBuffer__25tScreenCarSelectTwoPlayer
    /* 2468 80011C68 00000000 */ .word 0x00000000
    /* 246C 80011C6C A8BC0380 */ .word FreeAsyncBuffer__16tScreenCarSelect
    /* 2470 80011C70 00000000 */ .word 0x00000000
    /* 2474 80011C74 9CE40380 */ .word TurnOffVideoWall__25tScreenCarSelectTwoPlayer
    /* 2478 80011C78 00000000 */ .word 0x00000000
    /* 247C 80011C7C 50EC0380 */ .word SetDialog__25tScreenCarSelectTwoPlayer
enddlabel _vt_25tScreenCarSelectTwoPlayer

nonmatching _vt_20tScreenCarSelectDuel

dlabel _vt_20tScreenCarSelectDuel
    /* 2480 80011C80 00000000 */ .word 0x00000000
    /* 2484 80011C84 00000000 */ .word 0x00000000
    /* 2488 80011C88 00000000 */ .word 0x00000000
    /* 248C 80011C8C E0D50380 */ .word GetShapeInfo__20tScreenCarSelectDuelRsT1PPcT3
    /* 2490 80011C90 00000000 */ .word 0x00000000
    /* 2494 80011C94 F0D70380 */ .word DrawBackground__20tScreenCarSelectDuel
    /* 2498 80011C98 00000000 */ .word 0x00000000
    /* 249C 80011C9C 68DE0380 */ .word DrawForeground__20tScreenCarSelectDuel
    /* 24A0 80011CA0 00000000 */ .word 0x00000000
    /* 24A4 80011CA4 58F70380 */ .word ___20tScreenCarSelectDuel
    /* 24A8 80011CA8 00000000 */ .word 0x00000000
    /* 24AC 80011CAC 8CD00380 */ .word PreLoad__20tScreenCarSelectDuel
    /* 24B0 80011CB0 00000000 */ .word 0x00000000
    /* 24B4 80011CB4 04D30380 */ .word Initialize__20tScreenCarSelectDuel
    /* 24B8 80011CB8 00000000 */ .word 0x00000000
    /* 24BC 80011CBC 34D30380 */ .word Cleanup__20tScreenCarSelectDuel
    /* 24C0 80011CC0 00000000 */ .word 0x00000000
    /* 24C4 80011CC4 C0680280 */ .word TransitionIsFinished__7tScreen
    /* 24C8 80011CC8 00000000 */ .word 0x00000000
    /* 24CC 80011CCC 90BF0380 */ .word ProcessInput__16tScreenCarSelect7tPlayerR13tInputKeyTypeR12tMenuCommand
    /* 24D0 80011CD0 00000000 */ .word 0x00000000
    /* 24D4 80011CD4 64D30380 */ .word DrawVideoWall__20tScreenCarSelectDuels
    /* 24D8 80011CD8 00000000 */ .word 0x00000000
    /* 24DC 80011CDC E8D10380 */ .word InitializeVideoWall__20tScreenCarSelectDuel
    /* 24E0 80011CE0 00000000 */ .word 0x00000000
    /* 24E4 80011CE4 9CD60380 */ .word UpdateVideoWall__20tScreenCarSelectDuelR8tCarInfo
    /* 24E8 80011CE8 00000000 */ .word 0x00000000
    /* 24EC 80011CEC 24C20380 */ .word GetCar__16tScreenCarSelectR8tCarInfo
    /* 24F0 80011CF0 00000000 */ .word 0x00000000
    /* 24F4 80011CF4 B4D10380 */ .word AllocateAsyncBuffer__20tScreenCarSelectDuel
    /* 24F8 80011CF8 00000000 */ .word 0x00000000
    /* 24FC 80011CFC BCD10380 */ .word FreeAsyncBuffer__20tScreenCarSelectDuel
    /* 2500 80011D00 00000000 */ .word 0x00000000
    /* 2504 80011D04 BCD40380 */ .word DrawOpponentVideoWall__20tScreenCarSelectDuels
enddlabel _vt_20tScreenCarSelectDuel

nonmatching _vt_16tScreenCarSelect

dlabel _vt_16tScreenCarSelect
    /* 2508 80011D08 00000000 */ .word 0x00000000
    /* 250C 80011D0C 00000000 */ .word 0x00000000
    /* 2510 80011D10 00000000 */ .word 0x00000000
    /* 2514 80011D14 E0BA0380 */ .word GetShapeInfo__16tScreenCarSelectRsT1PPcT3
    /* 2518 80011D18 00000000 */ .word 0x00000000
    /* 251C 80011D1C 3CC50380 */ .word DrawBackground__16tScreenCarSelect
    /* 2520 80011D20 00000000 */ .word 0x00000000
    /* 2524 80011D24 D8C70380 */ .word DrawForeground__16tScreenCarSelect
    /* 2528 80011D28 00000000 */ .word 0x00000000
    /* 252C 80011D2C 90AC0380 */ .word ___16tScreenCarSelect
    /* 2530 80011D30 00000000 */ .word 0x00000000
    /* 2534 80011D34 80670280 */ .word PreLoad__7tScreen
    /* 2538 80011D38 00000000 */ .word 0x00000000
    /* 253C 80011D3C 88BD0380 */ .word Initialize__16tScreenCarSelect
    /* 2540 80011D40 00000000 */ .word 0x00000000
    /* 2544 80011D44 B8AC0380 */ .word Cleanup__16tScreenCarSelect
    /* 2548 80011D48 00000000 */ .word 0x00000000
    /* 254C 80011D4C C0680280 */ .word TransitionIsFinished__7tScreen
    /* 2550 80011D50 00000000 */ .word 0x00000000
    /* 2554 80011D54 90BF0380 */ .word ProcessInput__16tScreenCarSelect7tPlayerR13tInputKeyTypeR12tMenuCommand
    /* 2558 80011D58 00000000 */ .word 0x00000000
    /* 255C 80011D5C 18C10380 */ .word DrawVideoWall__16tScreenCarSelects
    /* 2560 80011D60 00000000 */ .word 0x00000000
    /* 2564 80011D64 D0BC0380 */ .word InitializeVideoWall__16tScreenCarSelect
    /* 2568 80011D68 00000000 */ .word 0x00000000
    /* 256C 80011D6C A4BB0380 */ .word UpdateVideoWall__16tScreenCarSelectR8tCarInfo
    /* 2570 80011D70 00000000 */ .word 0x00000000
    /* 2574 80011D74 24C20380 */ .word GetCar__16tScreenCarSelectR8tCarInfo
    /* 2578 80011D78 00000000 */ .word 0x00000000
    /* 257C 80011D7C 74BC0380 */ .word AllocateAsyncBuffer__16tScreenCarSelect
    /* 2580 80011D80 00000000 */ .word 0x00000000
    /* 2584 80011D84 A8BC0380 */ .word FreeAsyncBuffer__16tScreenCarSelect
    /* 2588 80011D88 53696D70 */ .word 0x706D6953
    /* 258C 80011D8C 6C654D65 */ .word 0x654D656C
    /* 2590 80011D90 6D000000 */ .word 0x0000006D
enddlabel _vt_16tScreenCarSelect

.align 2
nonmatching D_80011D94

dlabel D_80011D94
    /* 2594 80011D94 */ .asciz "ztourn"
    /* 7A746F75726E0000 */
.align 2
enddlabel D_80011D94

nonmatching D_80011D9C

dlabel D_80011D9C
    /* 259C 80011D9C 25737A7A */ .word 0x7A7A7325
    /* 25A0 80011DA0 7A54524E */ .word 0x4E52547A
    /* 25A4 80011DA4 2E646374 */ .word 0x7463642E
    /* 25A8 80011DA8 00000000 */ .word 0x00000000
    /* 25AC 80011DAC 00000000 */ .word 0x00000000
enddlabel D_80011D9C

nonmatching _vt_18tScreenTournSelect

dlabel _vt_18tScreenTournSelect
    /* 25B0 80011DB0 00000000 */ .word 0x00000000
    /* 25B4 80011DB4 00000000 */ .word 0x00000000
    /* 25B8 80011DB8 00000000 */ .word 0x00000000
    /* 25BC 80011DBC D4F70380 */ .word GetShapeInfo__18tScreenTournSelectRsT1PPcT3
    /* 25C0 80011DC0 00000000 */ .word 0x00000000
    /* 25C4 80011DC4 5CFE0380 */ .word DrawBackground__18tScreenTournSelect
    /* 25C8 80011DC8 00000000 */ .word 0x00000000
    /* 25CC 80011DCC D8040480 */ .word DrawForeground__18tScreenTournSelect
    /* 25D0 80011DD0 00000000 */ .word 0x00000000
    /* 25D4 80011DD4 ACF70380 */ .word ___18tScreenTournSelect
    /* 25D8 80011DD8 00000000 */ .word 0x00000000
    /* 25DC 80011DDC 80670280 */ .word PreLoad__7tScreen
    /* 25E0 80011DE0 00000000 */ .word 0x00000000
    /* 25E4 80011DE4 A0F80380 */ .word Initialize__18tScreenTournSelect
    /* 25E8 80011DE8 00000000 */ .word 0x00000000
    /* 25EC 80011DEC E8FA0380 */ .word Cleanup__18tScreenTournSelect
    /* 25F0 80011DF0 00000000 */ .word 0x00000000
    /* 25F4 80011DF4 C0680280 */ .word TransitionIsFinished__7tScreen
    /* 25F8 80011DF8 00000000 */ .word 0x00000000
    /* 25FC 80011DFC D8680280 */ .word ProcessInput__7tScreen7tPlayerR13tInputKeyTypeR12tMenuCommand
    /* 2600 80011E00 53696D70 */ .word 0x706D6953
    /* 2604 80011E04 6C654D65 */ .word 0x654D656C
    /* 2608 80011E08 6D000000 */ .word 0x0000006D
enddlabel _vt_18tScreenTournSelect

.align 2
nonmatching D_80011E0C

dlabel D_80011E0C
    /* 260C 80011E0C */ .asciz "zTrophy"
    /* 7A54726F70687900 */
.align 2
enddlabel D_80011E0C

.align 2
nonmatching D_80011E14

dlabel D_80011E14
    /* 2614 80011E14 */ .asciz "zCase2"
    /* 7A43617365320000 */
.align 2
enddlabel D_80011E14

.align 2
nonmatching D_80011E1C

dlabel D_80011E1C
    /* 261C 80011E1C */ .asciz "zCase"
    /* 7A43617365000000 */
.align 2
.align 2
    /* 2624 80011E24 */ .asciz ""
    /* 00000000 */
.align 2
enddlabel D_80011E1C

nonmatching _vt_17tScreenTrophyRoom

dlabel _vt_17tScreenTrophyRoom
    /* 2628 80011E28 00000000 */ .word 0x00000000
    /* 262C 80011E2C 00000000 */ .word 0x00000000
    /* 2630 80011E30 00000000 */ .word 0x00000000
    /* 2634 80011E34 D8050480 */ .word GetShapeInfo__17tScreenTrophyRoomRsT1PPcT3
    /* 2638 80011E38 00000000 */ .word 0x00000000
    /* 263C 80011E3C 180B0480 */ .word DrawBackground__17tScreenTrophyRoom
    /* 2640 80011E40 00000000 */ .word 0x00000000
    /* 2644 80011E44 E0680280 */ .word DrawForeground__7tScreen
    /* 2648 80011E48 00000000 */ .word 0x00000000
    /* 264C 80011E4C B0050480 */ .word ___17tScreenTrophyRoom
    /* 2650 80011E50 00000000 */ .word 0x00000000
    /* 2654 80011E54 A8080480 */ .word PreLoad__17tScreenTrophyRoom
    /* 2658 80011E58 00000000 */ .word 0x00000000
    /* 265C 80011E5C 10090480 */ .word Initialize__17tScreenTrophyRoom
    /* 2660 80011E60 00000000 */ .word 0x00000000
    /* 2664 80011E64 E80A0480 */ .word Cleanup__17tScreenTrophyRoom
    /* 2668 80011E68 00000000 */ .word 0x00000000
    /* 266C 80011E6C C0680280 */ .word TransitionIsFinished__7tScreen
    /* 2670 80011E70 00000000 */ .word 0x00000000
    /* 2674 80011E74 98060480 */ .word ProcessInput__17tScreenTrophyRoom7tPlayerR13tInputKeyTypeR12tMenuCommand
    /* 2678 80011E78 53696D70 */ .word 0x706D6953
    /* 267C 80011E7C 6C654D65 */ .word 0x654D656C
    /* 2680 80011E80 6D000000 */ .word 0x0000006D
enddlabel _vt_17tScreenTrophyRoom

.align 2
nonmatching D_80011E84

dlabel D_80011E84
    /* 2684 80011E84 */ .asciz "zSTI"
    /* 7A53544900000000 */
.align 2
.align 2
    /* 268C 80011E8C */ .asciz ""
    /* 00000000 */
.align 2
enddlabel D_80011E84

nonmatching _vt_17tScreenTrophyInfo

dlabel _vt_17tScreenTrophyInfo
    /* 2690 80011E90 00000000 */ .word 0x00000000
    /* 2694 80011E94 00000000 */ .word 0x00000000
    /* 2698 80011E98 00000000 */ .word 0x00000000
    /* 269C 80011E9C 08100480 */ .word GetShapeInfo__17tScreenTrophyInfoRsT1PPcT3
    /* 26A0 80011EA0 00000000 */ .word 0x00000000
    /* 26A4 80011EA4 38110480 */ .word DrawBackground__17tScreenTrophyInfo
    /* 26A8 80011EA8 00000000 */ .word 0x00000000
    /* 26AC 80011EAC E0680280 */ .word DrawForeground__7tScreen
    /* 26B0 80011EB0 00000000 */ .word 0x00000000
    /* 26B4 80011EB4 E0150480 */ .word ___17tScreenTrophyInfo
    /* 26B8 80011EB8 00000000 */ .word 0x00000000
    /* 26BC 80011EBC 80670280 */ .word PreLoad__7tScreen
    /* 26C0 80011EC0 00000000 */ .word 0x00000000
    /* 26C4 80011EC4 AC600280 */ .word Initialize__7tScreen
    /* 26C8 80011EC8 00000000 */ .word 0x00000000
    /* 26CC 80011ECC A0610280 */ .word Cleanup__7tScreen
    /* 26D0 80011ED0 00000000 */ .word 0x00000000
    /* 26D4 80011ED4 C0680280 */ .word TransitionIsFinished__7tScreen
    /* 26D8 80011ED8 00000000 */ .word 0x00000000
    /* 26DC 80011EDC D8680280 */ .word ProcessInput__7tScreen7tPlayerR13tInputKeyTypeR12tMenuCommand
    /* 26E0 80011EE0 53696D70 */ .word 0x706D6953
    /* 26E4 80011EE4 6C654D65 */ .word 0x654D656C
    /* 26E8 80011EE8 6D000000 */ .word 0x0000006D
enddlabel _vt_17tScreenTrophyInfo

nonmatching D_80011EEC

dlabel D_80011EEC
    /* 26EC 80011EEC 25737A7A */ .word 0x7A7A7325
    /* 26F0 80011EF0 7A545225 */ .word 0x2552547A
    /* 26F4 80011EF4 3032642E */ .word 0x2E643230
    /* 26F8 80011EF8 64637400 */ .word 0x00746364
enddlabel D_80011EEC

.align 2
nonmatching D_80011EFC

dlabel D_80011EFC
    /* 26FC 80011EFC */ .asciz "ztrack"
    /* 7A747261636B0000 */
.align 2
enddlabel D_80011EFC

.align 2
nonmatching D_80011F04

dlabel D_80011F04
    /* 2704 80011F04 */ .asciz "%s"
    /* 25730000 */
.align 2
enddlabel D_80011F04

nonmatching _vt_18tScreenTrackSelect

dlabel _vt_18tScreenTrackSelect
    /* 2708 80011F08 00000000 */ .word 0x00000000
    /* 270C 80011F0C 00000000 */ .word 0x00000000
    /* 2710 80011F10 00000000 */ .word 0x00000000
    /* 2714 80011F14 AC1A0480 */ .word GetShapeInfo__18tScreenTrackSelectRsT1PPcT3
    /* 2718 80011F18 00000000 */ .word 0x00000000
    /* 271C 80011F1C 00160480 */ .word DrawBackground__18tScreenTrackSelect
    /* 2720 80011F20 00000000 */ .word 0x00000000
    /* 2724 80011F24 E0680280 */ .word DrawForeground__7tScreen
    /* 2728 80011F28 00000000 */ .word 0x00000000
    /* 272C 80011F2C D4210480 */ .word ___18tScreenTrackSelect
    /* 2730 80011F30 00000000 */ .word 0x00000000
    /* 2734 80011F34 80670280 */ .word PreLoad__7tScreen
    /* 2738 80011F38 00000000 */ .word 0x00000000
    /* 273C 80011F3C 6C1B0480 */ .word Initialize__18tScreenTrackSelect
    /* 2740 80011F40 00000000 */ .word 0x00000000
    /* 2744 80011F44 281D0480 */ .word Cleanup__18tScreenTrackSelect
    /* 2748 80011F48 00000000 */ .word 0x00000000
    /* 274C 80011F4C C0680280 */ .word TransitionIsFinished__7tScreen
    /* 2750 80011F50 00000000 */ .word 0x00000000
    /* 2754 80011F54 0C200480 */ .word ProcessInput__18tScreenTrackSelect7tPlayerR13tInputKeyTypeR12tMenuCommand
enddlabel _vt_18tScreenTrackSelect

.align 2
nonmatching D_80011F58

dlabel D_80011F58
    /* 2758 80011F58 */ .asciz "zInfo"
    /* 7A496E666F000000 */
.align 2
enddlabel D_80011F58

.align 2
nonmatching D_80011F60

dlabel D_80011F60
    /* 2760 80011F60 */ .asciz "TR%02d%c"
    /* 545225303264256300000000 */
.align 2
enddlabel D_80011F60

nonmatching D_80011F6C

dlabel D_80011F6C
    /* 276C 80011F6C CC00CD00 */ .word 0x00CD00CC
    /* 2770 80011F70 CE00CF00 */ .word 0x00CF00CE
    /* 2774 80011F74 00000000 */ .word 0x00000000
enddlabel D_80011F6C

nonmatching _vt_16tScreenTrackInfo

dlabel _vt_16tScreenTrackInfo
    /* 2778 80011F78 00000000 */ .word 0x00000000
    /* 277C 80011F7C 00000000 */ .word 0x00000000
    /* 2780 80011F80 00000000 */ .word 0x00000000
    /* 2784 80011F84 F8210480 */ .word GetShapeInfo__16tScreenTrackInfoRsT1PPcT3
    /* 2788 80011F88 00000000 */ .word 0x00000000
    /* 278C 80011F8C 98220480 */ .word DrawBackground__16tScreenTrackInfo
    /* 2790 80011F90 00000000 */ .word 0x00000000
    /* 2794 80011F94 E0680280 */ .word DrawForeground__7tScreen
    /* 2798 80011F98 00000000 */ .word 0x00000000
    /* 279C 80011F9C 28260480 */ .word ___16tScreenTrackInfo
    /* 27A0 80011FA0 00000000 */ .word 0x00000000
    /* 27A4 80011FA4 80670280 */ .word PreLoad__7tScreen
    /* 27A8 80011FA8 00000000 */ .word 0x00000000
    /* 27AC 80011FAC 20250480 */ .word Initialize__16tScreenTrackInfo
    /* 27B0 80011FB0 00000000 */ .word 0x00000000
    /* 27B4 80011FB4 A0610280 */ .word Cleanup__7tScreen
    /* 27B8 80011FB8 00000000 */ .word 0x00000000
    /* 27BC 80011FBC C0680280 */ .word TransitionIsFinished__7tScreen
    /* 27C0 80011FC0 00000000 */ .word 0x00000000
    /* 27C4 80011FC4 8C250480 */ .word ProcessInput__16tScreenTrackInfo7tPlayerR13tInputKeyTypeR12tMenuCommand
    /* 27C8 80011FC8 53696D70 */ .word 0x706D6953
    /* 27CC 80011FCC 6C654D65 */ .word 0x654D656C
    /* 27D0 80011FD0 6D000000 */ .word 0x0000006D
enddlabel _vt_16tScreenTrackInfo

.align 2
nonmatching D_80011FD4

dlabel D_80011FD4
    /* 27D4 80011FD4 */ .asciz "zRec"
    /* 7A52656300000000 */
.align 2
enddlabel D_80011FD4

.align 2
nonmatching D_80011FDC

dlabel D_80011FDC
    /* 27DC 80011FDC */ .asciz "trkrcrds"
    /* 74726B726372647300000000 */
.align 2
enddlabel D_80011FDC

.align 2
nonmatching D_80011FE8

dlabel D_80011FE8
    /* 27E8 80011FE8 */ .asciz "%s %s"
    /* 2573202573000000 */
.align 2
enddlabel D_80011FE8

nonmatching _vt_19tScreenTrackRecords

dlabel _vt_19tScreenTrackRecords
    /* 27F0 80011FF0 00000000 */ .word 0x00000000
    /* 27F4 80011FF4 00000000 */ .word 0x00000000
    /* 27F8 80011FF8 00000000 */ .word 0x00000000
    /* 27FC 80011FFC 48260480 */ .word GetShapeInfo__19tScreenTrackRecordsRsT1PPcT3
    /* 2800 80012000 00000000 */ .word 0x00000000
    /* 2804 80012004 482B0480 */ .word DrawBackground__19tScreenTrackRecords
    /* 2808 80012008 00000000 */ .word 0x00000000
    /* 280C 8001200C E0680280 */ .word DrawForeground__7tScreen
    /* 2810 80012010 00000000 */ .word 0x00000000
    /* 2814 80012014 F8300480 */ .word ___19tScreenTrackRecords
    /* 2818 80012018 00000000 */ .word 0x00000000
    /* 281C 8001201C 80670280 */ .word PreLoad__7tScreen
    /* 2820 80012020 00000000 */ .word 0x00000000
    /* 2824 80012024 6C260480 */ .word Initialize__19tScreenTrackRecords
    /* 2828 80012028 00000000 */ .word 0x00000000
    /* 282C 8001202C C4260480 */ .word Cleanup__19tScreenTrackRecords
    /* 2830 80012030 00000000 */ .word 0x00000000
    /* 2834 80012034 C0680280 */ .word TransitionIsFinished__7tScreen
    /* 2838 80012038 00000000 */ .word 0x00000000
    /* 283C 8001203C D8680280 */ .word ProcessInput__7tScreen7tPlayerR13tInputKeyTypeR12tMenuCommand
    /* 2840 80012040 53696D70 */ .word 0x706D6953
    /* 2844 80012044 6C654D65 */ .word 0x654D656C
    /* 2848 80012048 6D000000 */ .word 0x0000006D
    /* 284C 8001204C 4E6F6E65 */ .word 0x656E6F4E
    /* 2850 80012050 00000000 */ .word 0x00000000
    /* 2854 80012054 4E656700 */ .word 0x0067654E
    /* 2858 80012058 57686C00 */ .word 0x006C6857
    /* 285C 8001205C 4374726C */ .word 0x6C727443
    /* 2860 80012060 00000000 */ .word 0x00000000
enddlabel _vt_19tScreenTrackRecords

.align 2
nonmatching D_80012064

dlabel D_80012064
    /* 2864 80012064 */ .asciz "aCtrl"
    /* 614374726C000000 */
.align 2
enddlabel D_80012064

.align 2
nonmatching D_8001206C

dlabel D_8001206C
    /* 286C 8001206C */ .asciz "zpCtrl"
    /* 7A704374726C0000 */
.align 2
.align 2
    /* 2874 80012074 */ .asciz ""
    /* 00000000 */
.align 2
enddlabel D_8001206C

nonmatching _vt_23tScreenControllerConfig

dlabel _vt_23tScreenControllerConfig
    /* 2878 80012078 00000000 */ .word 0x00000000
    /* 287C 8001207C 00000000 */ .word 0x00000000
    /* 2880 80012080 00000000 */ .word 0x00000000
    /* 2884 80012084 CC560480 */ .word GetShapeInfo__23tScreenControllerConfigRsT1PPcT3
    /* 2888 80012088 00000000 */ .word 0x00000000
    /* 288C 8001208C 404E0480 */ .word DrawBackground__23tScreenControllerConfig
    /* 2890 80012090 00000000 */ .word 0x00000000
    /* 2894 80012094 64500480 */ .word DrawForeground__23tScreenControllerConfig
    /* 2898 80012098 00000000 */ .word 0x00000000
    /* 289C 8001209C 0C590480 */ .word ___23tScreenControllerConfig
    /* 28A0 800120A0 00000000 */ .word 0x00000000
    /* 28A4 800120A4 80670280 */ .word PreLoad__7tScreen
    /* 28A8 800120A8 00000000 */ .word 0x00000000
    /* 28AC 800120AC FC560480 */ .word Initialize__23tScreenControllerConfig
    /* 28B0 800120B0 00000000 */ .word 0x00000000
    /* 28B4 800120B4 20580480 */ .word Cleanup__23tScreenControllerConfig
    /* 28B8 800120B8 00000000 */ .word 0x00000000
    /* 28BC 800120BC C0680280 */ .word TransitionIsFinished__7tScreen
    /* 28C0 800120C0 00000000 */ .word 0x00000000
    /* 28C4 800120C4 D8680280 */ .word ProcessInput__7tScreen7tPlayerR13tInputKeyTypeR12tMenuCommand
enddlabel _vt_23tScreenControllerConfig

.align 2
nonmatching D_800120C8

dlabel D_800120C8
    /* 28C8 800120C8 */ .asciz "zDsply"
    /* 7A4473706C790000 */
.align 2
enddlabel D_800120C8

nonmatching _vt_14tScreenDisplay

dlabel _vt_14tScreenDisplay
    /* 28D0 800120D0 00000000 */ .word 0x00000000
    /* 28D4 800120D4 00000000 */ .word 0x00000000
    /* 28D8 800120D8 00000000 */ .word 0x00000000
    /* 28DC 800120DC DC590480 */ .word GetShapeInfo__14tScreenDisplayRsT1PPcT3
    /* 28E0 800120E0 00000000 */ .word 0x00000000
    /* 28E4 800120E4 50590480 */ .word DrawBackground__14tScreenDisplay
    /* 28E8 800120E8 00000000 */ .word 0x00000000
    /* 28EC 800120EC E0680280 */ .word DrawForeground__7tScreen
    /* 28F0 800120F0 00000000 */ .word 0x00000000
    /* 28F4 800120F4 045A0480 */ .word ___14tScreenDisplay
    /* 28F8 800120F8 00000000 */ .word 0x00000000
    /* 28FC 800120FC 80670280 */ .word PreLoad__7tScreen
    /* 2900 80012100 00000000 */ .word 0x00000000
    /* 2904 80012104 AC600280 */ .word Initialize__7tScreen
    /* 2908 80012108 00000000 */ .word 0x00000000
    /* 290C 8001210C A0610280 */ .word Cleanup__7tScreen
    /* 2910 80012110 00000000 */ .word 0x00000000
    /* 2914 80012114 C0680280 */ .word TransitionIsFinished__7tScreen
    /* 2918 80012118 00000000 */ .word 0x00000000
    /* 291C 8001211C D8680280 */ .word ProcessInput__7tScreen7tPlayerR13tInputKeyTypeR12tMenuCommand
    /* 2920 80012120 53696D70 */ .word 0x706D6953
    /* 2924 80012124 6C654D65 */ .word 0x654D656C
    /* 2928 80012128 6D000000 */ .word 0x0000006D
enddlabel _vt_14tScreenDisplay

.align 2
nonmatching D_8001212C

dlabel D_8001212C
    /* 292C 8001212C */ .asciz "%d%%"
    /* 2564252500000000 */
.align 2
.align 2
    /* 2934 80012134 */ .asciz ""
    /* 00000000 */
.align 2
enddlabel D_8001212C