.include "macro.inc"
/* W65-A5: residual segment of rdata_80054548 -- the non-jump-table blob records.
 * Linked by BOTH lanes. */

.section .rodata, "a"

/* Generated by spimdisasm 1.40.2 */


.align 2
nonmatching D_80056534

dlabel D_80056534
    /* 46D34 80056534 */ .asciz "SimpleMem"
    /* 53696D706C654D656D000000 */
.align 2
.align 2
    /* 46D40 80056540 */ .asciz "SimpleMem"
    /* 53696D706C654D656D000000 */
.align 2
enddlabel D_80056534

.align 2
nonmatching D_8005654C

dlabel D_8005654C
    /* 46D4C 8005654C */ .asciz "%scamera.viv"
    /* 257363616D6572612E76697600000000 */
.align 2
enddlabel D_8005654C

.align 2
nonmatching D_8005655C

dlabel D_8005655C
    /* 46D5C 8005655C */ .asciz "tr%02dr.rho"
    /* 747225303264722E72686F00 */
.align 2
enddlabel D_8005655C

.align 2
nonmatching D_80056568

dlabel D_80056568
    /* 46D68 80056568 */ .asciz "tr%02d.rho"
    /* 7472253032642E72686F0000 */
.align 2
.align 2
    /* 46D74 80056574 */ .asciz ""
    /* 00000000 */
.align 2
enddlabel D_80056568