.include "macro.inc"
/* ============================================================
 * W65-A5  THE .L LOCALIZE CUT -- SPLAT-LANE FILLER ONLY
 *
 * jtbl_80012870: the retail jump table of a switch inside
 *     build/recon/frontend/psx/memcard.c.o
 * (retail 0x80012870..0x80012884, 5 entries).
 *
 * OWNERSHIP PROOF: word-for-word identical to the owner's own .rodata run at +0x18 (E5)
 *
 * The `.word .L<VA>` operands below are the SRC lane's local labels.  The
 * RECON lane must NOT link this file: the recon TU emits this very table into
 * its own `.rodata`, and no recon object defines a `.L<VA>` symbol, so
 * linking it here is exactly the 350-name undefined `.L` class.
 * It stays in the tree so the legacy splat-lane script (linkers/nfs4.ld,
 * which links build/src/**) keeps producing a byte-identical image.
 * ============================================================ */

.section .rodata, "a"

/* Generated by spimdisasm 1.40.2 */

.align 2

.align 3
nonmatching jtbl_80012870

dlabel jtbl_80012870
    /* 3070 80012870 94000580 */ .word .L80050094
    /* 3074 80012874 E0000580 */ .word .L800500E0
    /* 3078 80012878 14010580 */ .word .L80050114
    /* 307C 8001287C 48010580 */ .word .L80050148
    /* 3080 80012880 7C010580 */ .word .L8005017C
enddlabel jtbl_80012870