.include "macro.inc"
/* ============================================================
 * W65-A5  THE .L LOCALIZE CUT -- SPLAT-LANE FILLER ONLY
 *
 * jtbl_80056FBC: the retail jump table of a switch inside
 *     build/recon/eaclib/psx/eacpsxz/fileroot.c.o
 * (retail 0x80056fbc..0x80056fd8, 7 entries).
 *
 * OWNERSHIP PROOF: word-for-word identical to the owner's own .rodata run at +0x0 (E5)
 *
 * The `.word .L<VA>` operands below are the SRC lane's local labels.  The
 * RECON lane must NOT link this file: the recon TU emits this very table into
 * its own `.rodata`, and no recon object defines a `.L<VA>` symbol, so
 * linking it here is exactly the 350-name undefined `.L` class.
 * It stays in the tree so the legacy splat-lane script (linkers/nfs4.ld,
 * which links build/src/**) keeps producing a byte-identical image.
 * ============================================================ */

.section .rodata, "a"

/* Generated by spimdisasm 1.40.2 */


nonmatching jtbl_80056FBC

dlabel jtbl_80056FBC
    /* 477BC 80056FBC 943D0F80 */ .word .L800F3D94
    /* 477C0 80056FC0 AC3D0F80 */ .word .L800F3DAC
    /* 477C4 80056FC4 C43D0F80 */ .word .L800F3DC4
    /* 477C8 80056FC8 383E0F80 */ .word .L800F3E38
    /* 477CC 80056FCC F03D0F80 */ .word .L800F3DF0
    /* 477D0 80056FD0 383E0F80 */ .word .L800F3E38
    /* 477D4 80056FD4 243E0F80 */ .word .L800F3E24
enddlabel jtbl_80056FBC