.include "macro.inc"
/* ============================================================
 * W65-A5  THE .L LOCALIZE CUT -- SPLAT-LANE FILLER ONLY
 *
 * jtbl_80056894: the retail jump table of a switch inside
 *     build/recon/game/psx/flare.cpp.o
 * (retail 0x80056894..0x800568a8, 5 entries).
 *
 * OWNERSHIP PROOF: word-for-word identical to the owner's own .rodata run at +0x0 (E5)
 *
 * The `.word .L<VA>` operands below are the SRC lane's local labels.  The
 * RECON lane must NOT link this file: the recon TU emits this very table into
 * its own `.rodata`, and no recon object defines a `.L<VA>` symbol, so
 * linking it here is exactly the 350-name undefined `.L` class.
 * It stays in the tree so the legacy splat-lane script (linkers/nfs4.ld,
 * which links build/src/**) keeps producing a byte-identical image.
 * ============================================================ */

.section .rodata, "a"

/* Generated by spimdisasm 1.40.2 */


nonmatching jtbl_80056894

dlabel jtbl_80056894
    /* 47094 80056894 C8F00C80 */ .word .L800CF0C8
    /* 47098 80056898 C8F00C80 */ .word .L800CF0C8
    /* 4709C 8005689C E8F00C80 */ .word .L800CF0E8
    /* 470A0 800568A0 00F10C80 */ .word .L800CF100
    /* 470A4 800568A4 18F10C80 */ .word .L800CF118
enddlabel jtbl_80056894