.include "macro.inc"
/* W65-A5: residual segment of rdata_80054548 -- the non-jump-table blob records.
 * Linked by BOTH lanes. */

.section .rodata, "a"

/* Generated by spimdisasm 1.40.2 */


.align 2
nonmatching D_80057100

dlabel D_80057100
    /* 47900 80057100 */ .asciz "none"
    /* 6E6F6E6500000000 */
.align 2
.align 2
    /* 47908 80057108 */ .asciz ""
    /* 00000000 */
.align 2
.align 2
    /* 4790C 8005710C */ .asciz ""
    /* 00000000 */
.align 2
enddlabel D_80057100

.align 2
nonmatching D_80057110

dlabel D_80057110
    /* 47910 80057110 */ .asciz "DMA STATUS ERROR %x\n"
    /* 444D4120535441545553204552524F522025780A00000000 */
.align 2
.align 2
    /* 47928 80057128 */ .asciz ""
    /* 00000000 */
.align 2
.align 2
    /* 4792C 8005712C */ .asciz ""
    /* 00000000 */
.align 2
enddlabel D_80057110

.align 2
nonmatching D_80057130

dlabel D_80057130
    /* 47930 80057130 */ .asciz "MDEC_rest:bad option(%d)\n"
    /* 4D4445435F726573743A626164206F7074696F6E282564290A000000 */
.align 2
enddlabel D_80057130

.align 2
nonmatching D_8005714C

dlabel D_8005714C
    /* 4794C 8005714C */ .asciz "MDEC_in_sync"
    /* 4D4445435F696E5F73796E6300000000 */
.align 2
enddlabel D_8005714C

.align 2
nonmatching D_8005715C

dlabel D_8005715C
    /* 4795C 8005715C */ .asciz "MDEC_out_sync"
    /* 4D4445435F6F75745F73796E63000000 */
.align 2
enddlabel D_8005715C

.align 2
nonmatching D_8005716C

dlabel D_8005716C
    /* 4796C 8005716C */ .asciz "%s timeout:\n"
    /* 25732074696D656F75743A0A00000000 */
.align 2
.align 2
    /* 4797C 8005717C */ .asciz ""
    /* 00000000 */
.align 2
enddlabel D_8005716C

.align 2
nonmatching D_80057180

dlabel D_80057180
    /* 47980 80057180 */ .asciz "%s: path level (%d) error\n"
    /* 25733A2070617468206C6576656C2028256429206572726F720A0000 */
.align 2
enddlabel D_80057180

.align 2
nonmatching D_8005719C

dlabel D_8005719C
    /* 4799C 8005719C */ .asciz "%s: dir was not found\n"
    /* 25733A2064697220776173206E6F7420666F756E640A0000 */
.align 2
enddlabel D_8005719C

.align 2
nonmatching D_800571B4

dlabel D_800571B4
    /* 479B4 800571B4 */ .asciz "CdSearchFile: disc error\n"
    /* 436453656172636846696C653A2064697363206572726F720A000000 */
.align 2
enddlabel D_800571B4

.align 2
nonmatching D_800571D0

dlabel D_800571D0
    /* 479D0 800571D0 */ .asciz "CdSearchFile: searching %s...\n"
    /* 436453656172636846696C653A20736561726368696E672025732E2E2E0A0000 */
.align 2
enddlabel D_800571D0

.align 2
nonmatching D_800571F0

dlabel D_800571F0
    /* 479F0 800571F0 */ .asciz "%s:  found\n"
    /* 25733A2020666F756E640A00 */
.align 2
enddlabel D_800571F0

.align 2
nonmatching D_800571FC

dlabel D_800571FC
    /* 479FC 800571FC */ .asciz "%s: not found\n"
    /* 25733A206E6F7420666F756E640A0000 */
.align 2
enddlabel D_800571FC

.align 2
nonmatching D_8005720C

dlabel D_8005720C
    /* 47A0C 8005720C */ .asciz "CD_newmedia: Read error in cd_read(PVD)\n"
    /* 43445F6E65776D656469613A2052656164206572726F7220696E2063645F7265616428505644290A00000000 */
.align 2
enddlabel D_8005720C

.align 2
nonmatching D_80057238

dlabel D_80057238
    /* 47A38 80057238 */ .asciz "CD001"
    /* 4344303031000000 */
.align 2
enddlabel D_80057238

.align 2
nonmatching D_80057240

dlabel D_80057240
    /* 47A40 80057240 */ .asciz "CD_newmedia: Disc format error in cd_read(PVD)\n"
    /* 43445F6E65776D656469613A204469736320666F726D6174206572726F7220696E2063645F7265616428505644290A00 */
.align 2
enddlabel D_80057240

.align 2
nonmatching D_80057270

dlabel D_80057270
    /* 47A70 80057270 */ .asciz "CD_newmedia: Read error (PT:%08x)\n"
    /* 43445F6E65776D656469613A2052656164206572726F72202850543A25303878290A0000 */
.align 2
enddlabel D_80057270

.align 2
nonmatching D_80057294

dlabel D_80057294
    /* 47A94 80057294 */ .asciz "CD_newmedia: sarching dir..\n"
    /* 43445F6E65776D656469613A207361726368696E67206469722E2E0A00000000 */
.align 2
enddlabel D_80057294

.align 2
nonmatching D_800572B4

dlabel D_800572B4
    /* 47AB4 800572B4 */ .asciz "\t%08x,%04x,%04x,%s\n"
    /* 09253038782C253034782C253034782C25730A00 */
.align 2
enddlabel D_800572B4

.align 2
nonmatching D_800572C8

dlabel D_800572C8
    /* 47AC8 800572C8 */ .asciz "CD_newmedia: %d dir entries found\n"
    /* 43445F6E65776D656469613A2025642064697220656E747269657320666F756E640A0000 */
.align 2
enddlabel D_800572C8

.align 2
nonmatching D_800572EC

dlabel D_800572EC
    /* 47AEC 800572EC */ .asciz "CD_cachefile: dir not found\n"
    /* 43445F636163686566696C653A20646972206E6F7420666F756E640A00000000 */
.align 2
enddlabel D_800572EC

.align 2
nonmatching D_8005730C

dlabel D_8005730C
    /* 47B0C 8005730C */ .asciz "CD_cachefile: searching...\n"
    /* 43445F636163686566696C653A20736561726368696E672E2E2E0A00 */
.align 2
enddlabel D_8005730C

nonmatching D_80057328

dlabel D_80057328
    /* 47B28 80057328 */ .short 0x002E
    /* 47B2A 8005732A */ .short 0x0000
enddlabel D_80057328

nonmatching D_8005732C

dlabel D_8005732C
    /* 47B2C 8005732C */ .short 0x2E2E
enddlabel D_8005732C

nonmatching D_8005732E

dlabel D_8005732E
    /* 47B2E 8005732E */ .byte 0x00
    /* 47B2F 8005732F */ .byte 0x00
enddlabel D_8005732E

.align 2
nonmatching D_80057330

dlabel D_80057330
    /* 47B30 80057330 */ .asciz "\t(%02x:%02x:%02x) %8d %s\n"
    /* 0928253032783A253032783A2530327829202538642025730A000000 */
.align 2
enddlabel D_80057330

.align 2
nonmatching D_8005734C

dlabel D_8005734C
    /* 47B4C 8005734C */ .asciz "CD_cachefile: %d files found\n"
    /* 43445F636163686566696C653A2025642066696C657320666F756E640A000000 */
.align 2
.align 2
    /* 47B6C 8005736C */ .asciz ""
    /* 00000000 */
.align 2
enddlabel D_8005734C

nonmatching D_80057370

dlabel D_80057370
    /* 47B70 80057370 41636365 */ .word 0x65636341
    /* 47B74 80057374 73732044 */ .word 0x44207373
    /* 47B78 80057378 656E6965 */ .word 0x65696E65
    /* 47B7C 8005737C 642E203A */ .word 0x3A202E64
    /* 47B80 80057380 20657665 */ .word 0x65766520
    /* 47B84 80057384 6E74206D */ .word 0x6D20746E
    /* 47B88 80057388 756C7469 */ .word 0x69746C75
    /* 47B8C 8005738C 706C6520 */ .word 0x20656C70
    /* 47B90 80057390 6F70656E */ .word 0x6E65706F
    /* 47B94 80057394 0A000000 */ .word 0x0000000A
enddlabel D_80057370