.include "macro.inc"
/* ============================================================
 * W65-A5  THE .L LOCALIZE CUT -- SPLAT-LANE FILLER ONLY
 *
 * jtbl_80011B38: the retail jump table of a switch inside
 *     build/recon/frontend/common/screencarselect.cpp.o
 * (retail 0x80011b38..0x80011b60, 9 entries).
 *
 * OWNERSHIP PROOF: word-for-word identical to the owner's own .rodata run at +0x90 (E5)
 *
 * The `.word .L<VA>` operands below are the SRC lane's local labels.  The
 * RECON lane must NOT link this file: the recon TU emits this very table into
 * its own `.rodata`, and no recon object defines a `.L<VA>` symbol, so
 * linking it here is exactly the 350-name undefined `.L` class.
 * It stays in the tree so the legacy splat-lane script (linkers/nfs4.ld,
 * which links build/src/**) keeps producing a byte-identical image.
 * ============================================================ */

.section .rodata, "a"

/* Generated by spimdisasm 1.40.2 */

.align 2

.align 3
nonmatching jtbl_80011B38

dlabel jtbl_80011B38
    /* 2338 80011B38 5CF40380 */ .word .L8003F45C
    /* 233C 80011B3C 1CF50380 */ .word .L8003F51C
    /* 2340 80011B40 0CF50380 */ .word .L8003F50C
    /* 2344 80011B44 14F50380 */ .word .L8003F514
    /* 2348 80011B48 44F50380 */ .word .L8003F544
    /* 234C 80011B4C 4CF50380 */ .word .L8003F54C
    /* 2350 80011B50 CCF30380 */ .word .L8003F3CC
    /* 2354 80011B54 BCF30380 */ .word .L8003F3BC
    /* 2358 80011B58 54F50380 */ .word .L8003F554
    /* 235C 80011B5C 00000000 */ .word 0x00000000
enddlabel jtbl_80011B38