.include "macro.inc"
/* ============================================================
 * W65-A5  THE .L LOCALIZE CUT -- SPLAT-LANE FILLER ONLY
 *
 * jtbl_80056488: the retail jump table of a switch inside
 *     build/recon/game/common/r3dcar.cpp.o
 * (retail 0x80056488..0x800564e0, 22 entries).
 *
 * OWNERSHIP PROOF: word-for-word identical to the owner's own .rodata run at +0xd0 (E5)
 *
 * The `.word .L<VA>` operands below are the SRC lane's local labels.  The
 * RECON lane must NOT link this file: the recon TU emits this very table into
 * its own `.rodata`, and no recon object defines a `.L<VA>` symbol, so
 * linking it here is exactly the 350-name undefined `.L` class.
 * It stays in the tree so the legacy splat-lane script (linkers/nfs4.ld,
 * which links build/src/**) keeps producing a byte-identical image.
 * ============================================================ */

.section .rodata, "a"

/* Generated by spimdisasm 1.40.2 */


.align 3
nonmatching jtbl_80056488

dlabel jtbl_80056488
    /* 46C88 80056488 B80A0B80 */ .word .L800B0AB8
    /* 46C8C 8005648C B80A0B80 */ .word .L800B0AB8
    /* 46C90 80056490 C40A0B80 */ .word .L800B0AC4
    /* 46C94 80056494 F40A0B80 */ .word .L800B0AF4
    /* 46C98 80056498 3C0B0B80 */ .word .L800B0B3C
    /* 46C9C 8005649C 3C0B0B80 */ .word .L800B0B3C
    /* 46CA0 800564A0 D00B0B80 */ .word .L800B0BD0
    /* 46CA4 800564A4 D00B0B80 */ .word .L800B0BD0
    /* 46CA8 800564A8 D00B0B80 */ .word .L800B0BD0
    /* 46CAC 800564AC D00B0B80 */ .word .L800B0BD0
    /* 46CB0 800564B0 D00B0B80 */ .word .L800B0BD0
    /* 46CB4 800564B4 D00B0B80 */ .word .L800B0BD0
    /* 46CB8 800564B8 3C0A0B80 */ .word .L800B0A3C
    /* 46CBC 800564BC 640A0B80 */ .word .L800B0A64
    /* 46CC0 800564C0 640A0B80 */ .word .L800B0A64
    /* 46CC4 800564C4 640A0B80 */ .word .L800B0A64
    /* 46CC8 800564C8 640A0B80 */ .word .L800B0A64
    /* 46CCC 800564CC 640A0B80 */ .word .L800B0A64
    /* 46CD0 800564D0 700A0B80 */ .word .L800B0A70
    /* 46CD4 800564D4 880A0B80 */ .word .L800B0A88
    /* 46CD8 800564D8 940A0B80 */ .word .L800B0A94
    /* 46CDC 800564DC AC0A0B80 */ .word .L800B0AAC
enddlabel jtbl_80056488