.include "macro.inc"
/* ============================================================
 * W65-A5  THE .L LOCALIZE CUT -- SPLAT-LANE FILLER ONLY
 *
 * jtbl_80055070: the retail jump table of a switch inside
 *     build/recon/game/common/aih_btcperp.cpp.o
 * (retail 0x80055070..0x80055088, 6 entries).
 *
 * OWNERSHIP PROOF: word-for-word identical to the owner's own .rodata run at +0x30 (E5)
 *
 * The `.word .L<VA>` operands below are the SRC lane's local labels.  The
 * RECON lane must NOT link this file: the recon TU emits this very table into
 * its own `.rodata`, and no recon object defines a `.L<VA>` symbol, so
 * linking it here is exactly the 350-name undefined `.L` class.
 * It stays in the tree so the legacy splat-lane script (linkers/nfs4.ld,
 * which links build/src/**) keeps producing a byte-identical image.
 * ============================================================ */

.section .rodata, "a"

/* Generated by spimdisasm 1.40.2 */


.align 3
nonmatching jtbl_80055070

dlabel jtbl_80055070
    /* 45870 80055070 300B0680 */ .word .L80060B30
    /* 45874 80055074 54090680 */ .word .L80060954
    /* 45878 80055078 EC090680 */ .word .L800609EC
    /* 4587C 8005507C 300B0680 */ .word .L80060B30
    /* 45880 80055080 F8090680 */ .word .L800609F8
    /* 45884 80055084 300B0680 */ .word .L80060B30
enddlabel jtbl_80055070