.include "macro.inc"
/* ============================================================
 * W65-A5  THE .L LOCALIZE CUT -- SPLAT-LANE FILLER ONLY
 *
 * jtbl_80056418: the retail jump table of a switch inside
 *     build/recon/game/common/r3dcar.cpp.o
 * (retail 0x80056418..0x80056470, 21 entries).
 *
 * OWNERSHIP PROOF: word-for-word identical to the owner's own .rodata run at +0x60 (E5)
 *
 * The `.word .L<VA>` operands below are the SRC lane's local labels.  The
 * RECON lane must NOT link this file: the recon TU emits this very table into
 * its own `.rodata`, and no recon object defines a `.L<VA>` symbol, so
 * linking it here is exactly the 350-name undefined `.L` class.
 * It stays in the tree so the legacy splat-lane script (linkers/nfs4.ld,
 * which links build/src/**) keeps producing a byte-identical image.
 * ============================================================ */

.section .rodata, "a"

/* Generated by spimdisasm 1.40.2 */


.align 3
nonmatching jtbl_80056418

dlabel jtbl_80056418
    /* 46C18 80056418 F4030B80 */ .word .L800B03F4
    /* 46C1C 8005641C 00040B80 */ .word .L800B0400
    /* 46C20 80056420 00040B80 */ .word .L800B0400
    /* 46C24 80056424 AC040B80 */ .word .L800B04AC
    /* 46C28 80056428 B8040B80 */ .word .L800B04B8
    /* 46C2C 8005642C 40040B80 */ .word .L800B0440
    /* 46C30 80056430 4C040B80 */ .word .L800B044C
    /* 46C34 80056434 F4030B80 */ .word .L800B03F4
    /* 46C38 80056438 D0050B80 */ .word .L800B05D0
    /* 46C3C 8005643C 18040B80 */ .word .L800B0418
    /* 46C40 80056440 24040B80 */ .word .L800B0424
    /* 46C44 80056444 A0040B80 */ .word .L800B04A0
    /* 46C48 80056448 84040B80 */ .word .L800B0484
    /* 46C4C 8005644C A0050B80 */ .word .L800B05A0
    /* 46C50 80056450 B0050B80 */ .word .L800B05B0
    /* 46C54 80056454 CC050B80 */ .word .L800B05CC
    /* 46C58 80056458 C4040B80 */ .word .L800B04C4
    /* 46C5C 8005645C DC040B80 */ .word .L800B04DC
    /* 46C60 80056460 10050B80 */ .word .L800B0510
    /* 46C64 80056464 34050B80 */ .word .L800B0534
    /* 46C68 80056468 68040B80 */ .word .L800B0468
    /* 46C6C 8005646C 00000000 */ .word 0x00000000
enddlabel jtbl_80056418