.include "macro.inc"
/* ============================================================
 * W65-A5  THE .L LOCALIZE CUT -- SPLAT-LANE FILLER ONLY
 *
 * jtbl_80012138: the retail jump table of a switch inside
 *     build/recon/frontend/common/screenaudio.cpp.o
 * (retail 0x80012138..0x8001214c, 5 entries).
 *
 * OWNERSHIP PROOF: word-for-word identical to the owner's own .rodata run at +0x8 (E5)
 *
 * The `.word .L<VA>` operands below are the SRC lane's local labels.  The
 * RECON lane must NOT link this file: the recon TU emits this very table into
 * its own `.rodata`, and no recon object defines a `.L<VA>` symbol, so
 * linking it here is exactly the 350-name undefined `.L` class.
 * It stays in the tree so the legacy splat-lane script (linkers/nfs4.ld,
 * which links build/src/**) keeps producing a byte-identical image.
 * ============================================================ */

.section .rodata, "a"

/* Generated by spimdisasm 1.40.2 */

.align 2

.align 3
nonmatching jtbl_80012138

dlabel jtbl_80012138
    /* 2938 80012138 605F0480 */ .word .L80045F60
    /* 293C 8001213C 705F0480 */ .word .L80045F70
    /* 2940 80012140 805F0480 */ .word .L80045F80
    /* 2944 80012144 905F0480 */ .word .L80045F90
    /* 2948 80012148 A05F0480 */ .word .L80045FA0
enddlabel jtbl_80012138