.include "macro.inc"
/* W65-A5: residual segment of rdata_80010000 -- the non-jump-table blob records.
 * Linked by BOTH lanes. */

.section .rodata, "a"

/* Generated by spimdisasm 1.40.2 */

.align 2

.align 2
nonmatching D_800125AC

dlabel D_800125AC
    /* 2DAC 800125AC */ .asciz "records"
    /* 7265636F72647300 */
.align 2
enddlabel D_800125AC

.align 2
nonmatching D_800125B4

dlabel D_800125B4
    /* 2DB4 800125B4 */ .asciz "%sznfsrec.dat"
    /* 25737A6E66737265632E646174000000 */
.align 2
enddlabel D_800125B4

.align 2
nonmatching D_800125C4

dlabel D_800125C4
    /* 2DC4 800125C4 */ .asciz "%szrecord.dat"
    /* 25737A7265636F72642E646174000000 */
.align 2
enddlabel D_800125C4

.align 2
nonmatching D_800125D4

dlabel D_800125D4
    /* 2DD4 800125D4 */ .asciz "trkrcrds"
    /* 74726B726372647300000000 */
.align 2
enddlabel D_800125D4

.align 2
nonmatching D_800125E0

dlabel D_800125E0
    /* 2DE0 800125E0 */ .asciz "zUser%d"
    /* 7A55736572256400 */
.align 2
enddlabel D_800125E0

.align 2
nonmatching D_800125E8

dlabel D_800125E8
    /* 2DE8 800125E8 */ .asciz " "
    /* 20000000 */
.align 2
.align 2
    /* 2DEC 800125EC */ .asciz ""
    /* 00000000 */
.align 2
enddlabel D_800125E8