.include "macro.inc"
/* W65-A5: residual segment of rdata_80054548 -- the non-jump-table blob records.
 * Linked by BOTH lanes. */

.section .rodata, "a"

/* Generated by spimdisasm 1.40.2 */

/* 2026-09-20: the head 0x80054548..0x80054D98 (bigbuf.obj tail + address.obj) lives in rdata_bigbuf_address_legacy.rodata.s */

/* The following `SimpleMem` literal begins the next object's read-only data.
 * address.obj owns only the two four-byte overlay boundary words above. */
    /* 45598 80054D98 53696D70 */ .word 0x706D6953
    /* 4559C 80054D9C 6C654D65 */ .word 0x654D656C
    /* 455A0 80054DA0 6D000000 */ .word 0x0000006D

nonmatching D_80054DA4

dlabel D_80054DA4
    /* 455A4 80054DA4 01000000 */ .word 0x00000001
    /* 455A8 80054DA8 01000000 */ .word 0x00000001
    /* 455AC 80054DAC 01000000 */ .word 0x00000001
    /* 455B0 80054DB0 53696D70 */ .word 0x706D6953
    /* 455B4 80054DB4 6C654D65 */ .word 0x654D656C
    /* 455B8 80054DB8 6D000000 */ .word 0x0000006D
    /* 455BC 80054DBC 53696D70 */ .word 0x706D6953
    /* 455C0 80054DC0 6C654D65 */ .word 0x654D656C
    /* 455C4 80054DC4 6D000000 */ .word 0x0000006D
    /* 455C8 80054DC8 00000000 */ .word 0x00000000
enddlabel D_80054DA4

nonmatching D_80054DCC

dlabel D_80054DCC
    /* 455CC 80054DCC 00000000 */ .word 0x00000000
    /* 455D0 80054DD0 00000000 */ .word 0x00000000
    /* 455D4 80054DD4 00000000 */ .word 0x00000000
    /* 455D8 80054DD8 54430E80 */ .word __pure_virtual
    /* 455DC 80054DDC 00000000 */ .word 0x00000000
    /* 455E0 80054DE0 38B40580 */ .word ___15AIHigh_BTC_Perp
    /* 455E4 80054DE4 00000000 */ .word 0x00000000
    /* 455E8 80054DE8 00B50580 */ .word CheckForCrimes__16AIHigh_BasicPerp
enddlabel D_80054DCC

nonmatching D_80054DEC

dlabel D_80054DEC
    /* 455EC 80054DEC 00000000 */ .word 0x00000000
    /* 455F0 80054DF0 00000000 */ .word 0x00000000
    /* 455F4 80054DF4 00000000 */ .word 0x00000000
    /* 455F8 80054DF8 60B40580 */ .word HighExecute__11AIHigh_None
    /* 455FC 80054DFC 00000000 */ .word 0x00000000
    /* 45600 80054E00 68B40580 */ .word ___11AIHigh_None
enddlabel D_80054DEC

nonmatching _vt_11AIHigh_Base

dlabel _vt_11AIHigh_Base
    /* 45604 80054E04 00000000 */ .word 0x00000000
    /* 45608 80054E08 00000000 */ .word 0x00000000
    /* 4560C 80054E0C 00000000 */ .word 0x00000000
    /* 45610 80054E10 54430E80 */ .word __pure_virtual
    /* 45614 80054E14 00000000 */ .word 0x00000000
    /* 45618 80054E18 C4B30580 */ .word ___11AIHigh_Base
enddlabel _vt_11AIHigh_Base

nonmatching D_80054E1C

dlabel D_80054E1C
    /* 4561C 80054E1C 00000000 */ .word 0x00000000
    /* 45620 80054E20 00000000 */ .word 0x00000000
    /* 45624 80054E24 00000000 */ .word 0x00000000
    /* 45628 80054E28 88B40580 */ .word Execute__12AIState_None
    /* 4562C 80054E2C 00000000 */ .word 0x00000000
    /* 45630 80054E30 90B40580 */ .word ___12AIState_None
    /* 45634 80054E34 00000000 */ .word 0x00000000
    /* 45638 80054E38 C4B40580 */ .word TestForRelease__12AIState_Base
enddlabel D_80054E1C

nonmatching D_80054E3C

dlabel D_80054E3C
    /* 4563C 80054E3C 00000000 */ .word 0x00000000
    /* 45640 80054E40 00000000 */ .word 0x00000000
    /* 45644 80054E44 00000000 */ .word 0x00000000
    /* 45648 80054E48 54430E80 */ .word __pure_virtual
    /* 4564C 80054E4C 00000000 */ .word 0x00000000
    /* 45650 80054E50 CCB40580 */ .word ___12AIState_Base
    /* 45654 80054E54 00000000 */ .word 0x00000000
    /* 45658 80054E58 C4B40580 */ .word TestForRelease__12AIState_Base
    /* 4565C 80054E5C 53696D70 */ .word 0x706D6953
    /* 45660 80054E60 6C654D65 */ .word 0x654D656C
    /* 45664 80054E64 6D000000 */ .word 0x0000006D
    /* 45668 80054E68 00000000 */ .word 0x00000000
enddlabel D_80054E3C

nonmatching _vt_16AIHigh_BasicPerp

dlabel _vt_16AIHigh_BasicPerp
    /* 4566C 80054E6C 00000000 */ .word 0x00000000
    /* 45670 80054E70 00000000 */ .word 0x00000000
    /* 45674 80054E74 00000000 */ .word 0x00000000
    /* 45678 80054E78 54430E80 */ .word __pure_virtual
    /* 4567C 80054E7C 00000000 */ .word 0x00000000
    /* 45680 80054E80 3CC10580 */ .word ___16AIHigh_BasicPerp
    /* 45684 80054E84 00000000 */ .word 0x00000000
    /* 45688 80054E88 00B50580 */ .word CheckForCrimes__16AIHigh_BasicPerp
    /* 4568C 80054E8C 53696D70 */ .word 0x706D6953
    /* 45690 80054E90 6C654D65 */ .word 0x654D656C
    /* 45694 80054E94 6D000000 */ .word 0x0000006D
    /* 45698 80054E98 00000000 */ .word 0x00000000
enddlabel _vt_16AIHigh_BasicPerp

nonmatching D_80054E9C

dlabel D_80054E9C
    /* 4569C 80054E9C 00000000 */ .word 0x00000000
    /* 456A0 80054EA0 00000000 */ .word 0x00000000
    /* 456A4 80054EA4 00000000 */ .word 0x00000000
    /* 456A8 80054EA8 54430E80 */ .word __pure_virtual
    /* 456AC 80054EAC 00000000 */ .word 0x00000000
    /* 456B0 80054EB0 4CCB0580 */ .word ___15AIHigh_BasicCop
    /* 456B4 80054EB4 53696D70 */ .word 0x706D6953
    /* 456B8 80054EB8 6C654D65 */ .word 0x654D656C
    /* 456BC 80054EBC 6D000000 */ .word 0x0000006D
    /* 456C0 80054EC0 00000000 */ .word 0x00000000
enddlabel D_80054E9C

nonmatching _vt_18AIHigh_BTC_Wingman

dlabel _vt_18AIHigh_BTC_Wingman
    /* 456C4 80054EC4 00000000 */ .word 0x00000000
    /* 456C8 80054EC8 00000000 */ .word 0x00000000
    /* 456CC 80054ECC 00000000 */ .word 0x00000000
    /* 456D0 80054ED0 3CE30580 */ .word HighExecute__18AIHigh_BTC_Wingman
    /* 456D4 80054ED4 00000000 */ .word 0x00000000
    /* 456D8 80054ED8 C4F50580 */ .word ___18AIHigh_BTC_Wingman
    /* 456DC 80054EDC 00000000 */ .word 0x00000000
    /* 456E0 80054EE0 FCCE0580 */ .word FreezeAndEndChase__14AIHigh_BTC_Cop
enddlabel _vt_18AIHigh_BTC_Wingman

nonmatching _vt_19AIHigh_BTC_HumanCop

dlabel _vt_19AIHigh_BTC_HumanCop
    /* 456E4 80054EE4 00000000 */ .word 0x00000000
    /* 456E8 80054EE8 00000000 */ .word 0x00000000
    /* 456EC 80054EEC 00000000 */ .word 0x00000000
    /* 456F0 80054EF0 ACE00580 */ .word HighExecute__19AIHigh_BTC_HumanCop
    /* 456F4 80054EF4 00000000 */ .word 0x00000000
    /* 456F8 80054EF8 E4F50580 */ .word ___19AIHigh_BTC_HumanCop
    /* 456FC 80054EFC 00000000 */ .word 0x00000000
    /* 45700 80054F00 90D30580 */ .word FreezeAndEndChase__19AIHigh_BTC_HumanCop
enddlabel _vt_19AIHigh_BTC_HumanCop

nonmatching _vt_14AIHigh_BTC_Cop

dlabel _vt_14AIHigh_BTC_Cop
    /* 45704 80054F04 00000000 */ .word 0x00000000
    /* 45708 80054F08 00000000 */ .word 0x00000000
    /* 4570C 80054F0C 00000000 */ .word 0x00000000
    /* 45710 80054F10 54430E80 */ .word __pure_virtual
    /* 45714 80054F14 00000000 */ .word 0x00000000
    /* 45718 80054F18 04F60580 */ .word ___14AIHigh_BTC_Cop
    /* 4571C 80054F1C 00000000 */ .word 0x00000000
    /* 45720 80054F20 FCCE0580 */ .word FreezeAndEndChase__14AIHigh_BTC_Cop
enddlabel _vt_14AIHigh_BTC_Cop

nonmatching D_80054F24

dlabel D_80054F24
    /* 45724 80054F24 00000000 */ .word 0x00000000
    /* 45728 80054F28 00000000 */ .word 0x00000000
    /* 4572C 80054F2C 00000000 */ .word 0x00000000
    /* 45730 80054F30 24F60580 */ .word Execute__17AIState_NonActive
    /* 45734 80054F34 00000000 */ .word 0x00000000
    /* 45738 80054F38 2CF60580 */ .word ___17AIState_NonActive
    /* 4573C 80054F3C 00000000 */ .word 0x00000000
    /* 45740 80054F40 78F60580 */ .word TestForRelease__12AIState_Base_8005F678
enddlabel D_80054F24

nonmatching D_80054F44

dlabel D_80054F44
    /* 45744 80054F44 00000000 */ .word 0x00000000
    /* 45748 80054F48 00000000 */ .word 0x00000000
    /* 4574C 80054F4C 00000000 */ .word 0x00000000
    /* 45750 80054F50 54430E80 */ .word __pure_virtual
    /* 45754 80054F54 00000000 */ .word 0x00000000
    /* 45758 80054F58 80F60580 */ .word ___12AIState_Base_8005F680
    /* 4575C 80054F5C 00000000 */ .word 0x00000000
    /* 45760 80054F60 78F60580 */ .word TestForRelease__12AIState_Base_8005F678
enddlabel D_80054F44
