.include "macro.inc"
/* W65-A5: residual segment of rdata_80054548 -- the non-jump-table blob records.
 * Linked by BOTH lanes. */

.section .rodata, "a"

/* Generated by spimdisasm 1.40.2 */


nonmatching D_80055A54

dlabel D_80055A54
    /* 46254 80055A54 4CC81380 */ .word D_8013C84C
    /* 46258 80055A58 54C81380 */ .word D_8013C854
    /* 4625C 80055A5C 5CC81380 */ .word D_8013C85C
    /* 46260 80055A60 64C81380 */ .word D_8013C864
    /* 46264 80055A64 6CC81380 */ .word D_8013C86C
    /* 46268 80055A68 74C81380 */ .word D_8013C874
    /* 4626C 80055A6C 7CC81380 */ .word D_8013C87C
    /* 46270 80055A70 84C81380 */ .word D_8013C884
    /* 46274 80055A74 8CC81380 */ .word D_8013C88C
    /* 46278 80055A78 94C81380 */ .word D_8013C894
    /* 4627C 80055A7C 9CC81380 */ .word D_8013C89C
    /* 46280 80055A80 A4C81380 */ .word D_8013C8A4
    /* 46284 80055A84 ACC81380 */ .word D_8013C8AC
    /* 46288 80055A88 B4C81380 */ .word D_8013C8B4
    /* 4628C 80055A8C BCC81380 */ .word D_8013C8BC
    /* 46290 80055A90 C4C81380 */ .word D_8013C8C4
    /* 46294 80055A94 A4C81380 */ .word D_8013C8A4
    /* 46298 80055A98 5CC81380 */ .word D_8013C85C
    /* 4629C 80055A9C 94C81380 */ .word D_8013C894
    /* 462A0 80055AA0 CCC81380 */ .word D_8013C8CC
    /* 462A4 80055AA4 CCC81380 */ .word D_8013C8CC
    /* 462A8 80055AA8 CCC81380 */ .word D_8013C8CC
    /* 462AC 80055AAC D4C81380 */ .word D_8013C8D4
    /* 462B0 80055AB0 5CC81380 */ .word D_8013C85C
    /* 462B4 80055AB4 8CC81380 */ .word D_8013C88C
    /* 462B8 80055AB8 94C81380 */ .word D_8013C894
    /* 462BC 80055ABC A4C81380 */ .word D_8013C8A4
    /* 462C0 80055AC0 B4C81380 */ .word D_8013C8B4
    /* 462C4 80055AC4 CCC81380 */ .word D_8013C8CC
enddlabel D_80055A54

nonmatching D_80055AC8

dlabel D_80055AC8
    /* 462C8 80055AC8 DCC81380 */ .word D_8013C8DC
    /* 462CC 80055ACC E4C81380 */ .word D_8013C8E4
    /* 462D0 80055AD0 ECC81380 */ .word D_8013C8EC
    /* 462D4 80055AD4 F4C81380 */ .word D_8013C8F4
    /* 462D8 80055AD8 FCC81380 */ .word D_8013C8FC
    /* 462DC 80055ADC 04C91380 */ .word D_8013C904
    /* 462E0 80055AE0 0CC91380 */ .word D_8013C90C
    /* 462E4 80055AE4 14C91380 */ .word D_8013C914
    /* 462E8 80055AE8 1CC91380 */ .word D_8013C91C
    /* 462EC 80055AEC 24C91380 */ .word D_8013C924
    /* 462F0 80055AF0 2CC91380 */ .word D_8013C92C
    /* 462F4 80055AF4 34C91380 */ .word D_8013C934
    /* 462F8 80055AF8 3CC91380 */ .word D_8013C93C
    /* 462FC 80055AFC B4C81380 */ .word D_8013C8B4
    /* 46300 80055B00 BCC81380 */ .word D_8013C8BC
    /* 46304 80055B04 44C91380 */ .word D_8013C944
    /* 46308 80055B08 34C91380 */ .word D_8013C934
    /* 4630C 80055B0C ECC81380 */ .word D_8013C8EC
    /* 46310 80055B10 24C91380 */ .word D_8013C924
    /* 46314 80055B14 4CC91380 */ .word D_8013C94C
    /* 46318 80055B18 4CC91380 */ .word D_8013C94C
    /* 4631C 80055B1C 4CC91380 */ .word D_8013C94C
    /* 46320 80055B20 54C91380 */ .word D_8013C954
    /* 46324 80055B24 ECC81380 */ .word D_8013C8EC
    /* 46328 80055B28 1CC91380 */ .word D_8013C91C
    /* 4632C 80055B2C 24C91380 */ .word D_8013C924
    /* 46330 80055B30 34C91380 */ .word D_8013C934
    /* 46334 80055B34 B4C81380 */ .word D_8013C8B4
    /* 46338 80055B38 4CC91380 */ .word D_8013C94C
enddlabel D_80055AC8

.align 2
nonmatching D_80055B3C

dlabel D_80055B3C
    /* 4633C 80055B3C */ .asciz "%sfont.pfn"
    /* 2573666F6E742E70666E0000 */
.align 2
enddlabel D_80055B3C

.align 2
nonmatching D_80055B48

dlabel D_80055B48
    /* 46348 80055B48 */ .asciz "%shud.psh"
    /* 25736875642E707368000000 */
.align 2
.align 2
    /* 46354 80055B54 */ .asciz "SimpleMem"
    /* 53696D706C654D656D000000 */
.align 2
enddlabel D_80055B48

.align 2
nonmatching D_80055B60

dlabel D_80055B60
    /* 46360 80055B60 */ .asciz "j:location\\"
    /* 6A3A6C6F636174696F6E5C00 */
.align 2
enddlabel D_80055B60

.align 2
nonmatching D_80055B6C

dlabel D_80055B6C
    /* 4636C 80055B6C */ .asciz "j:ccars\\"
    /* 6A3A63636172735C00000000 */
.align 2
enddlabel D_80055B6C

.align 2
nonmatching D_80055B78

dlabel D_80055B78
    /* 46378 80055B78 */ .asciz "j:clocaton\\"
    /* 6A3A636C6F6361746F6E5C00 */
.align 2
enddlabel D_80055B78

.align 2
nonmatching D_80055B84

dlabel D_80055B84
    /* 46384 80055B84 */ .asciz "j:silenc."
    /* 6A3A73696C656E632E000000 */
.align 2
enddlabel D_80055B84

nonmatching D_80055B90

dlabel D_80055B90
    /* 46390 80055B90 6A3A6576 */ .word 0x76653A6A
    /* 46394 80055B94 656E7464 */ .word 0x64746E65
    /* 46398 80055B98 61745C65 */ .word 0x655C7461
    /* 4639C 80055B9C 76656E74 */ .word 0x746E6576
    /* 463A0 80055BA0 2E646174 */ .word 0x7461642E
    /* 463A4 80055BA4 00000000 */ .word 0x00000000
enddlabel D_80055B90

.align 2
nonmatching D_80055BA8

dlabel D_80055BA8
    /* 463A8 80055BA8 */ .asciz "spch temp"
    /* 737063682074656D70000000 */
.align 2
enddlabel D_80055BA8

.align 2
nonmatching D_80055BB4

dlabel D_80055BB4
    /* 463B4 80055BB4 */ .asciz "%szzzz%s.viv"
    /* 25737A7A7A7A25732E76697600000000 */
.align 2
enddlabel D_80055BB4

.align 2
nonmatching D_80055BC4

dlabel D_80055BC4
    /* 463C4 80055BC4 */ .asciz "spch index"
    /* 7370636820696E6465780000 */
.align 2
.align 2
    /* 463D0 80055BD0 */ .asciz ""
    /* 00000000 */
.align 2
enddlabel D_80055BC4

nonmatching _vt_Q26Speech13MobileSpeaker

dlabel _vt_Q26Speech13MobileSpeaker
    /* 463D4 80055BD4 00000000 */ .word 0x00000000
    /* 463D8 80055BD8 00000000 */ .word 0x00000000
    /* 463DC 80055BDC 00000000 */ .word 0x00000000
    /* 463E0 80055BE0 FC7B0980 */ .word Report__Q26Speech13MobileSpeakerP8Car_tObj
    /* 463E4 80055BE4 00000000 */ .word 0x00000000
    /* 463E8 80055BE8 886B0980 */ .word Status__Q26Speech13MobileSpeaker
    /* 463EC 80055BEC 00000000 */ .word 0x00000000
    /* 463F0 80055BF0 1C5D0980 */ .word Deny__Q26Speech7Speaker
    /* 463F4 80055BF4 00000000 */ .word 0x00000000
    /* 463F8 80055BF8 245D0980 */ .word Grant__Q26Speech7Speaker
    /* 463FC 80055BFC 00000000 */ .word 0x00000000
    /* 46400 80055C00 2C5D0980 */ .word Ready__Q26Speech7SpeakerP8Car_tObj
    /* 46404 80055C04 00000000 */ .word 0x00000000
    /* 46408 80055C08 E87C0980 */ .word Engage__Q26Speech13MobileSpeakerP8Car_tObj
    /* 4640C 80055C0C 00000000 */ .word 0x00000000
    /* 46410 80055C10 34840980 */ .word Lose__Q26Speech13MobileSpeaker
    /* 46414 80055C14 00000000 */ .word 0x00000000
    /* 46418 80055C18 88870980 */ .word Accident__Q26Speech13MobileSpeakeri
    /* 4641C 80055C1C 00000000 */ .word 0x00000000
    /* 46420 80055C20 90870980 */ .word Catch__Q26Speech13MobileSpeakeri
    /* 46424 80055C24 00000000 */ .word 0x00000000
    /* 46428 80055C28 4C8A0980 */ .word RoadBlock__Q26Speech13MobileSpeaker
    /* 4642C 80055C2C 00000000 */ .word 0x00000000
    /* 46430 80055C30 608B0980 */ .word SpikeBelt__Q26Speech13MobileSpeaker
    /* 46434 80055C34 00000000 */ .word 0x00000000
    /* 46438 80055C38 748C0980 */ .word Backup__Q26Speech13MobileSpeaker
    /* 4643C 80055C3C 00000000 */ .word 0x00000000
    /* 46440 80055C40 6C910980 */ .word ReportBlockade__Q26Speech13MobileSpeaker
    /* 46444 80055C44 00000000 */ .word 0x00000000
    /* 46448 80055C48 6C8D0980 */ .word Roger__Q26Speech13MobileSpeaker
    /* 4644C 80055C4C 00000000 */ .word 0x00000000
    /* 46450 80055C50 E48E0980 */ .word Bullhorn__Q26Speech13MobileSpeaker
    /* 46454 80055C54 00000000 */ .word 0x00000000
    /* 46458 80055C58 188F0980 */ .word Purge__Q26Speech13MobileSpeaker
    /* 4645C 80055C5C 00000000 */ .word 0x00000000
    /* 46460 80055C60 74920980 */ .word Unit__Q26Speech13MobileSpeaker
    /* 46464 80055C64 00000000 */ .word 0x00000000
    /* 46468 80055C68 C4930980 */ .word KnownPerp__Q26Speech7SpeakerP8Car_tObj
    /* 4646C 80055C6C 00000000 */ .word 0x00000000
    /* 46470 80055C70 BC930980 */ .word ClearPerp__Q26Speech7SpeakerP8Car_tObj
    /* 46474 80055C74 00000000 */ .word 0x00000000
    /* 46478 80055C78 D8920980 */ .word IsSuper__Q26Speech13MobileSpeaker
    /* 4647C 80055C7C 00000000 */ .word 0x00000000
    /* 46480 80055C80 AC930980 */ .word StatusCount__Q26Speech7Speaker
    /* 46484 80055C84 00000000 */ .word 0x00000000
    /* 46488 80055C88 A4930980 */ .word StatusSub__Q26Speech7Speaker
    /* 4648C 80055C8C 00000000 */ .word 0x00000000
    /* 46490 80055C90 9C930980 */ .word PurgeStatusSub__Q26Speech7Speaker
    /* 46494 80055C94 00000000 */ .word 0x00000000
    /* 46498 80055C98 187A0980 */ .word DistToPerp__Q26Speech13MobileSpeaker
    /* 4649C 80055C9C 00000000 */ .word 0x00000000
    /* 464A0 80055CA0 CC920980 */ .word CarObj__Q26Speech13MobileSpeaker
    /* 464A4 80055CA4 00000000 */ .word 0x00000000
    /* 464A8 80055CA8 0C770980 */ .word ReActivate__Q26Speech13MobileSpeaker
    /* 464AC 80055CAC 00000000 */ .word 0x00000000
    /* 464B0 80055CB0 68920980 */ .word Perp__Q26Speech13MobileSpeaker
    /* 464B4 80055CB4 00000000 */ .word 0x00000000
    /* 464B8 80055CB8 B4920980 */ .word GetCarBank__Q26Speech13MobileSpeakeri
    /* 464BC 80055CBC 00000000 */ .word 0x00000000
    /* 464C0 80055CC0 8C920980 */ .word FindClosestLocationTo__Q26Speech13MobileSpeakeri
    /* 464C4 80055CC4 00000000 */ .word 0x00000000
    /* 464C8 80055CC8 80920980 */ .word CallSign__Q26Speech13MobileSpeaker
enddlabel _vt_Q26Speech13MobileSpeaker

nonmatching _vt_Q26Speech15DispatchSpeaker

dlabel _vt_Q26Speech15DispatchSpeaker
    /* 464CC 80055CCC 00000000 */ .word 0x00000000
    /* 464D0 80055CD0 00000000 */ .word 0x00000000
    /* 464D4 80055CD4 00000000 */ .word 0x00000000
    /* 464D8 80055CD8 B0710980 */ .word Report__Q26Speech15DispatchSpeakerP8Car_tObj
    /* 464DC 80055CDC 00000000 */ .word 0x00000000
    /* 464E0 80055CE0 D0650980 */ .word Status__Q26Speech15DispatchSpeaker
    /* 464E4 80055CE4 00000000 */ .word 0x00000000
    /* 464E8 80055CE8 58730980 */ .word Deny__Q26Speech15DispatchSpeaker
    /* 464EC 80055CEC 00000000 */ .word 0x00000000
    /* 464F0 80055CF0 4C740980 */ .word Grant__Q26Speech15DispatchSpeaker
    /* 464F4 80055CF4 00000000 */ .word 0x00000000
    /* 464F8 80055CF8 B0740980 */ .word Ready__Q26Speech15DispatchSpeakerP8Car_tObj
    /* 464FC 80055CFC 00000000 */ .word 0x00000000
    /* 46500 80055D00 345D0980 */ .word Engage__Q26Speech7SpeakerP8Car_tObj
    /* 46504 80055D04 00000000 */ .word 0x00000000
    /* 46508 80055D08 3C5D0980 */ .word Lose__Q26Speech7Speaker
    /* 4650C 80055D0C 00000000 */ .word 0x00000000
    /* 46510 80055D10 50730980 */ .word Accident__Q26Speech15DispatchSpeakeri
    /* 46514 80055D14 00000000 */ .word 0x00000000
    /* 46518 80055D18 4C5D0980 */ .word Catch__Q26Speech7Speakeri
    /* 4651C 80055D1C 00000000 */ .word 0x00000000
    /* 46520 80055D20 545D0980 */ .word RoadBlock__Q26Speech7Speaker
    /* 46524 80055D24 00000000 */ .word 0x00000000
    /* 46528 80055D28 5C5D0980 */ .word SpikeBelt__Q26Speech7Speaker
    /* 4652C 80055D2C 00000000 */ .word 0x00000000
    /* 46530 80055D30 645D0980 */ .word Backup__Q26Speech7Speaker
    /* 46534 80055D34 00000000 */ .word 0x00000000
    /* 46538 80055D38 6C5D0980 */ .word ReportBlockade__Q26Speech7Speaker
    /* 4653C 80055D3C 00000000 */ .word 0x00000000
    /* 46540 80055D40 285F0980 */ .word Roger__Q26Speech15DispatchSpeaker
    /* 46544 80055D44 00000000 */ .word 0x00000000
    /* 46548 80055D48 7C5D0980 */ .word Bullhorn__Q26Speech7Speaker
    /* 4654C 80055D4C 00000000 */ .word 0x00000000
    /* 46550 80055D50 845D0980 */ .word Purge__Q26Speech7Speaker
    /* 46554 80055D54 00000000 */ .word 0x00000000
    /* 46558 80055D58 CC930980 */ .word Unit__Q26Speech7Speaker
    /* 4655C 80055D5C 00000000 */ .word 0x00000000
    /* 46560 80055D60 50710980 */ .word KnownPerp__Q26Speech15DispatchSpeakerP8Car_tObj
    /* 46564 80055D64 00000000 */ .word 0x00000000
    /* 46568 80055D68 20710980 */ .word ClearPerp__Q26Speech15DispatchSpeakerP8Car_tObj
    /* 4656C 80055D6C 00000000 */ .word 0x00000000
    /* 46570 80055D70 B4930980 */ .word IsSuper__Q26Speech7Speaker
    /* 46574 80055D74 00000000 */ .word 0x00000000
    /* 46578 80055D78 58930980 */ .word StatusCount__Q26Speech15DispatchSpeaker
    /* 4657C 80055D7C 00000000 */ .word 0x00000000
    /* 46580 80055D80 4C930980 */ .word StatusSub__Q26Speech15DispatchSpeaker
    /* 46584 80055D84 00000000 */ .word 0x00000000
    /* 46588 80055D88 44930980 */ .word PurgeStatusSub__Q26Speech15DispatchSpeaker
    /* 4658C 80055D8C 00000000 */ .word 0x00000000
    /* 46590 80055D90 94930980 */ .word DistToPerp__Q26Speech7Speaker
    /* 46594 80055D94 00000000 */ .word 0x00000000
    /* 46598 80055D98 8C930980 */ .word CarObj__Q26Speech7Speaker
    /* 4659C 80055D9C 00000000 */ .word 0x00000000
    /* 465A0 80055DA0 84930980 */ .word ReActivate__Q26Speech7Speaker
    /* 465A4 80055DA4 00000000 */ .word 0x00000000
    /* 465A8 80055DA8 7C930980 */ .word Perp__Q26Speech7Speaker
    /* 465AC 80055DAC 00000000 */ .word 0x00000000
    /* 465B0 80055DB0 28930980 */ .word GetCarBank__Q26Speech15DispatchSpeakeri
    /* 465B4 80055DB4 00000000 */ .word 0x00000000
    /* 465B8 80055DB8 00930980 */ .word FindClosestLocationTo__Q26Speech15DispatchSpeakeri
    /* 465BC 80055DBC 00000000 */ .word 0x00000000
    /* 465C0 80055DC0 F4920980 */ .word CallSign__Q26Speech15DispatchSpeaker
enddlabel _vt_Q26Speech15DispatchSpeaker

nonmatching _vt_Q26Speech7Speaker

dlabel _vt_Q26Speech7Speaker
    /* 465C4 80055DC4 00000000 */ .word 0x00000000
    /* 465C8 80055DC8 00000000 */ .word 0x00000000
    /* 465CC 80055DCC 00000000 */ .word 0x00000000
    /* 465D0 80055DD0 145D0980 */ .word Report__Q26Speech7SpeakerP8Car_tObj
    /* 465D4 80055DD4 00000000 */ .word 0x00000000
    /* 465D8 80055DD8 D4930980 */ .word Status__Q26Speech7Speaker
    /* 465DC 80055DDC 00000000 */ .word 0x00000000
    /* 465E0 80055DE0 1C5D0980 */ .word Deny__Q26Speech7Speaker
    /* 465E4 80055DE4 00000000 */ .word 0x00000000
    /* 465E8 80055DE8 245D0980 */ .word Grant__Q26Speech7Speaker
    /* 465EC 80055DEC 00000000 */ .word 0x00000000
    /* 465F0 80055DF0 2C5D0980 */ .word Ready__Q26Speech7SpeakerP8Car_tObj
    /* 465F4 80055DF4 00000000 */ .word 0x00000000
    /* 465F8 80055DF8 345D0980 */ .word Engage__Q26Speech7SpeakerP8Car_tObj
    /* 465FC 80055DFC 00000000 */ .word 0x00000000
    /* 46600 80055E00 3C5D0980 */ .word Lose__Q26Speech7Speaker
    /* 46604 80055E04 00000000 */ .word 0x00000000
    /* 46608 80055E08 445D0980 */ .word Accident__Q26Speech7Speakeri
    /* 4660C 80055E0C 00000000 */ .word 0x00000000
    /* 46610 80055E10 4C5D0980 */ .word Catch__Q26Speech7Speakeri
    /* 46614 80055E14 00000000 */ .word 0x00000000
    /* 46618 80055E18 545D0980 */ .word RoadBlock__Q26Speech7Speaker
    /* 4661C 80055E1C 00000000 */ .word 0x00000000
    /* 46620 80055E20 5C5D0980 */ .word SpikeBelt__Q26Speech7Speaker
    /* 46624 80055E24 00000000 */ .word 0x00000000
    /* 46628 80055E28 645D0980 */ .word Backup__Q26Speech7Speaker
    /* 4662C 80055E2C 00000000 */ .word 0x00000000
    /* 46630 80055E30 6C5D0980 */ .word ReportBlockade__Q26Speech7Speaker
    /* 46634 80055E34 00000000 */ .word 0x00000000
    /* 46638 80055E38 745D0980 */ .word Roger__Q26Speech7Speaker
    /* 4663C 80055E3C 00000000 */ .word 0x00000000
    /* 46640 80055E40 7C5D0980 */ .word Bullhorn__Q26Speech7Speaker
    /* 46644 80055E44 00000000 */ .word 0x00000000
    /* 46648 80055E48 845D0980 */ .word Purge__Q26Speech7Speaker
    /* 4664C 80055E4C 00000000 */ .word 0x00000000
    /* 46650 80055E50 CC930980 */ .word Unit__Q26Speech7Speaker
    /* 46654 80055E54 00000000 */ .word 0x00000000
    /* 46658 80055E58 C4930980 */ .word KnownPerp__Q26Speech7SpeakerP8Car_tObj
    /* 4665C 80055E5C 00000000 */ .word 0x00000000
    /* 46660 80055E60 BC930980 */ .word ClearPerp__Q26Speech7SpeakerP8Car_tObj
    /* 46664 80055E64 00000000 */ .word 0x00000000
    /* 46668 80055E68 B4930980 */ .word IsSuper__Q26Speech7Speaker
    /* 4666C 80055E6C 00000000 */ .word 0x00000000
    /* 46670 80055E70 AC930980 */ .word StatusCount__Q26Speech7Speaker
    /* 46674 80055E74 00000000 */ .word 0x00000000
    /* 46678 80055E78 A4930980 */ .word StatusSub__Q26Speech7Speaker
    /* 4667C 80055E7C 00000000 */ .word 0x00000000
    /* 46680 80055E80 9C930980 */ .word PurgeStatusSub__Q26Speech7Speaker
    /* 46684 80055E84 00000000 */ .word 0x00000000
    /* 46688 80055E88 94930980 */ .word DistToPerp__Q26Speech7Speaker
    /* 4668C 80055E8C 00000000 */ .word 0x00000000
    /* 46690 80055E90 8C930980 */ .word CarObj__Q26Speech7Speaker
    /* 46694 80055E94 00000000 */ .word 0x00000000
    /* 46698 80055E98 84930980 */ .word ReActivate__Q26Speech7Speaker
    /* 4669C 80055E9C 00000000 */ .word 0x00000000
    /* 466A0 80055EA0 7C930980 */ .word Perp__Q26Speech7Speaker
    /* 466A4 80055EA4 00000000 */ .word 0x00000000
    /* 466A8 80055EA8 74930980 */ .word GetCarBank__Q26Speech7Speakeri
    /* 466AC 80055EAC 00000000 */ .word 0x00000000
    /* 466B0 80055EB0 6C930980 */ .word FindClosestLocationTo__Q26Speech7Speakeri
    /* 466B4 80055EB4 00000000 */ .word 0x00000000
    /* 466B8 80055EB8 64930980 */ .word CallSign__Q26Speech7Speaker
    /* 466BC 80055EBC 53696D70 */ .word 0x706D6953
    /* 466C0 80055EC0 6C654D65 */ .word 0x654D656C
    /* 466C4 80055EC4 6D000000 */ .word 0x0000006D
enddlabel _vt_Q26Speech7Speaker

.align 2
nonmatching D_80055EC8

dlabel D_80055EC8
    /* 466C8 80055EC8 */ .asciz "%szzzwzzz.viv"
    /* 25737A7A7A777A7A7A2E766976000000 */
.align 2
enddlabel D_80055EC8

.align 2
nonmatching D_80055ED8

dlabel D_80055ED8
    /* 466D8 80055ED8 */ .asciz "ocar index"
    /* 6F63617220696E6465780000 */
.align 2
enddlabel D_80055ED8

.align 2
nonmatching D_80055EE4

dlabel D_80055EE4
    /* 466E4 80055EE4 */ .asciz "rain.bnk"
    /* 7261696E2E626E6B00000000 */
.align 2
enddlabel D_80055EE4

.align 2
nonmatching D_80055EF0

dlabel D_80055EF0
    /* 466F0 80055EF0 */ .asciz "%.4s%.4s.bnk"
    /* 252E3473252E34732E626E6B00000000 */
.align 2
enddlabel D_80055EF0

.align 2
nonmatching D_80055F00

dlabel D_80055F00
    /* 46700 80055F00 */ .asciz "%szzzw%s.viv"
    /* 25737A7A7A7725732E76697600000000 */
.align 2
enddlabel D_80055F00

.align 2
nonmatching D_80055F10

dlabel D_80055F10
    /* 46710 80055F10 */ .asciz "%szzzwcst.viv"
    /* 25737A7A7A776373742E766976000000 */
.align 2
enddlabel D_80055F10

.align 2
nonmatching D_80055F20

dlabel D_80055F20
    /* 46720 80055F20 */ .asciz "trck index"
    /* 7472636B20696E6465780000 */
.align 2
enddlabel D_80055F20

.align 2
nonmatching D_80055F2C

dlabel D_80055F2C
    /* 4672C 80055F2C */ .asciz "%szzzx%s.viv"
    /* 25737A7A7A7825732E76697600000000 */
.align 2
enddlabel D_80055F2C

.align 2
nonmatching D_80055F3C

dlabel D_80055F3C
    /* 4673C 80055F3C */ .asciz "oneshots.txt"
    /* 6F6E6573686F74732E74787400000000 */
.align 2
enddlabel D_80055F3C

.align 2
nonmatching D_80055F4C

dlabel D_80055F4C
    /* 4674C 80055F4C */ .asciz "copspeak temp"
    /* 636F70737065616B2074656D70000000 */
.align 2
enddlabel D_80055F4C

.align 2
nonmatching D_80055F5C

dlabel D_80055F5C
    /* 4675C 80055F5C */ .asciz "1sht index"
    /* 3173687420696E6465780000 */
.align 2
enddlabel D_80055F5C

.align 2
nonmatching D_80055F68

dlabel D_80055F68
    /* 46768 80055F68 */ .asciz "CopSpeakBuf"
    /* 436F70537065616B42756600 */
.align 2
.align 2
    /* 46774 80055F74 */ .asciz "%2d:%02d.%02d"
    /* 2532643A253032642E25303264000000 */
.align 2
enddlabel D_80055F68

nonmatching D_80055F84

dlabel D_80055F84
    /* 46784 80055F84 00000000 */ .word 0x00000000
    /* 46788 80055F88 53696D70 */ .word 0x706D6953
    /* 4678C 80055F8C 6C654D65 */ .word 0x654D656C
    /* 46790 80055F90 6D000000 */ .word 0x0000006D
enddlabel D_80055F84

.align 2
nonmatching D_80055F94

dlabel D_80055F94
    /* 46794 80055F94 */ .asciz "%sSfx4w.psh"
    /* 257353667834772E70736800 */
.align 2
enddlabel D_80055F94

.align 2
nonmatching D_80055FA0

dlabel D_80055FA0
    /* 467A0 80055FA0 */ .asciz "%sSfx4.psh"
    /* 2573536678342E7073680000 */
.align 2
enddlabel D_80055FA0

.align 2
nonmatching D_80055FAC

dlabel D_80055FAC
    /* 467AC 80055FAC */ .asciz "%sSfx.psh"
    /* 25735366782E707368000000 */
.align 2
.align 2
    /* 467B8 80055FB8 */ .asciz "SimpleMem"
    /* 53696D706C654D656D000000 */
.align 2
.align 2
    /* 467C4 80055FC4 */ .asciz "SimpleMem"
    /* 53696D706C654D656D000000 */
.align 2
.align 2
    /* 467D0 80055FD0 */ .asciz "SimpleMem"
    /* 53696D706C654D656D000000 */
.align 2
.align 2
    /* 467DC 80055FDC */ .asciz "SimpleMem"
    /* 53696D706C654D656D000000 */
.align 2
.align 2
    /* 467E8 80055FE8 */ .asciz "SimpleMem"
    /* 53696D706C654D656D000000 */
.align 2
.align 2
    /* 467F4 80055FF4 */ .asciz "SimpleMem"
    /* 53696D706C654D656D000000 */
.align 2
enddlabel D_80055FAC

.align 2
nonmatching D_80056000

dlabel D_80056000
    /* 46800 80056000 */ .asciz "zHPurs.mis"
    /* 7A48507572732E6D69730000 */
.align 2
enddlabel D_80056000

.align 2
nonmatching D_8005600C

dlabel D_8005600C
    /* 4680C 8005600C */ .asciz "zHPurs2.mis"
    /* 7A4850757273322E6D697300 */
.align 2
enddlabel D_8005600C

.align 2
nonmatching D_80056018

dlabel D_80056018
    /* 46818 80056018 */ .asciz "fecars.car"
    /* 6665636172732E6361720000 */
.align 2
enddlabel D_80056018

.align 2
nonmatching D_80056024

dlabel D_80056024
    /* 46824 80056024 */ .asciz "front.bin"
    /* 66726F6E742E62696E000000 */
.align 2
enddlabel D_80056024

.align 2
nonmatching D_80056030

dlabel D_80056030
    /* 46830 80056030 */ .asciz "%sDCT.BIN"
    /* 25734443542E42494E000000 */
.align 2
enddlabel D_80056030

.align 2
nonmatching D_8005603C

dlabel D_8005603C
    /* 4683C 8005603C */ .asciz "%sldic.psh"
    /* 25736C6469632E7073680000 */
.align 2
.align 2
    /* 46848 80056048 */ .asciz "SimpleMem"
    /* 53696D706C654D656D000000 */
.align 2
enddlabel D_8005603C

.align 2
nonmatching D_80056054

dlabel D_80056054
    /* 46854 80056054 */ .asciz "Custom Objects"
    /* 437573746F6D204F626A656374730000 */
.align 2
enddlabel D_80056054

.align 2
nonmatching D_80056064

dlabel D_80056064
    /* 46864 80056064 */ .asciz "Custom SimObjects"
    /* 437573746F6D2053696D4F626A65637473000000 */
.align 2
enddlabel D_80056064

.align 2
nonmatching D_80056078

dlabel D_80056078
    /* 46878 80056078 */ .asciz "IMObj info"
    /* 494D4F626A20696E666F0000 */
.align 2
.align 2
    /* 46884 80056084 */ .asciz ""
    /* 00000000 */
.align 2
enddlabel D_80056078

nonmatching _vt_14ObjectSignAnim

dlabel _vt_14ObjectSignAnim
    /* 46888 80056088 00000000 */ .word 0x00000000
    /* 4688C 8005608C 00000000 */ .word 0x00000000
    /* 46890 80056090 00000000 */ .word 0x00000000
    /* 46894 80056094 106C0A80 */ .word ___14ObjectSignAnim
    /* 46898 80056098 00000000 */ .word 0x00000000
    /* 4689C 8005609C 386A0A80 */ .word Draw__14ObjectSignAnimP13DRender_tViewP11Draw_DCachei
enddlabel _vt_14ObjectSignAnim

nonmatching _vt_22ObjectFinishedSignAnim

dlabel _vt_22ObjectFinishedSignAnim
    /* 468A0 800560A0 00000000 */ .word 0x00000000
    /* 468A4 800560A4 00000000 */ .word 0x00000000
    /* 468A8 800560A8 00000000 */ .word 0x00000000
    /* 468AC 800560AC C46C0A80 */ .word ___22ObjectFinishedSignAnim
    /* 468B0 800560B0 00000000 */ .word 0x00000000
    /* 468B4 800560B4 1C670A80 */ .word Draw__22ObjectFinishedSignAnimP13DRender_tViewP11Draw_DCachei
enddlabel _vt_22ObjectFinishedSignAnim

nonmatching _vt_15ObjectMultiAnim

dlabel _vt_15ObjectMultiAnim
    /* 468B8 800560B8 00000000 */ .word 0x00000000
    /* 468BC 800560BC 00000000 */ .word 0x00000000
    /* 468C0 800560C0 00000000 */ .word 0x00000000
    /* 468C4 800560C4 F86C0A80 */ .word ___15ObjectMultiAnim
    /* 468C8 800560C8 00000000 */ .word 0x00000000
    /* 468CC 800560CC F8620A80 */ .word Draw__15ObjectMultiAnimP13DRender_tViewP11Draw_DCachei
enddlabel _vt_15ObjectMultiAnim

nonmatching _vt_23ObjectFinishedMultiAnim

dlabel _vt_23ObjectFinishedMultiAnim
    /* 468D0 800560D0 00000000 */ .word 0x00000000
    /* 468D4 800560D4 00000000 */ .word 0x00000000
    /* 468D8 800560D8 00000000 */ .word 0x00000000
    /* 468DC 800560DC AC6D0A80 */ .word ___23ObjectFinishedMultiAnim
    /* 468E0 800560E0 00000000 */ .word 0x00000000
    /* 468E4 800560E4 F8610A80 */ .word Draw__23ObjectFinishedMultiAnimP13DRender_tViewP11Draw_DCachei
enddlabel _vt_23ObjectFinishedMultiAnim

nonmatching D_800560E8

dlabel D_800560E8
    /* 468E8 800560E8 00000000 */ .word 0x00000000
    /* 468EC 800560EC 00000000 */ .word 0x00000000
    /* 468F0 800560F0 00000000 */ .word 0x00000000
    /* 468F4 800560F4 E06D0A80 */ .word ___10ObjectAnim
    /* 468F8 800560F8 00000000 */ .word 0x00000000
    /* 468FC 800560FC 54430E80 */ .word __pure_virtual
    /* 46900 80056100 696E7374 */ .word 0x74736E69
    /* 46904 80056104 616C6C2E */ .word 0x2E6C6C61
    /* 46908 80056108 70737800 */ .word 0x00787370
    /* 4690C 8005610C 53696D70 */ .word 0x706D6953
    /* 46910 80056110 6C654D65 */ .word 0x654D656C
    /* 46914 80056114 6D000000 */ .word 0x0000006D
    /* 46918 80056118 00000000 */ .word 0x00000000
enddlabel D_800560E8

nonmatching _vt_6tPMenu

dlabel _vt_6tPMenu
    /* 4691C 8005611C 00000000 */ .word 0x00000000
    /* 46920 80056120 00000000 */ .word 0x00000000
    /* 46924 80056124 00000000 */ .word 0x00000000
    /* 46928 80056128 14800A80 */ .word ___6tPMenu
    /* 4692C 8005612C 00000000 */ .word 0x00000000
    /* 46930 80056130 48800A80 */ .word Initialize__6tPMenu
    /* 46934 80056134 00000000 */ .word 0x00000000
    /* 46938 80056138 9C820A80 */ .word ProcessInput__6tPMenuR13tInputKeyTypeR13tPMenuCommand
    /* 4693C 8005613C 00000000 */ .word 0x00000000
    /* 46940 80056140 10850A80 */ .word Draw__6tPMenu
enddlabel _vt_6tPMenu

nonmatching _vt_23tPMenuItemCommandButton

dlabel _vt_23tPMenuItemCommandButton
    /* 46944 80056144 00000000 */ .word 0x00000000
    /* 46948 80056148 00000000 */ .word 0x00000000
    /* 4694C 8005614C 00000000 */ .word 0x00000000
    /* 46950 80056150 F47E0A80 */ .word ___23tPMenuItemCommandButton
    /* 46954 80056154 00000000 */ .word 0x00000000
    /* 46958 80056158 38740A80 */ .word NextMenu__10tPMenuItem
    /* 4695C 8005615C 00000000 */ .word 0x00000000
    /* 46960 80056160 40740A80 */ .word Debounce__10tPMenuItem
    /* 46964 80056164 00000000 */ .word 0x00000000
    /* 46968 80056168 1C7F0A80 */ .word ProcessInput__23tPMenuItemCommandButtonR13tInputKeyTypeR13tPMenuCommand
    /* 4696C 8005616C 00000000 */ .word 0x00000000
    /* 46970 80056170 98860A80 */ .word IsNavigable__21tPMenuItemInteractive
    /* 46974 80056174 00000000 */ .word 0x00000000
    /* 46978 80056178 30750A80 */ .word Draw__21tPMenuItemInteractiveb
enddlabel _vt_23tPMenuItemCommandButton

nonmatching _vt_24tPMenuItemGoToMenuButton

dlabel _vt_24tPMenuItemGoToMenuButton
    /* 4697C 8005617C 00000000 */ .word 0x00000000
    /* 46980 80056180 00000000 */ .word 0x00000000
    /* 46984 80056184 00000000 */ .word 0x00000000
    /* 46988 80056188 C87D0A80 */ .word ___24tPMenuItemGoToMenuButton
    /* 4698C 8005618C 00000000 */ .word 0x00000000
    /* 46990 80056190 F07D0A80 */ .word NextMenu__24tPMenuItemGoToMenuButton
    /* 46994 80056194 00000000 */ .word 0x00000000
    /* 46998 80056198 40740A80 */ .word Debounce__10tPMenuItem
    /* 4699C 8005619C 00000000 */ .word 0x00000000
    /* 469A0 800561A0 FC7D0A80 */ .word ProcessInput__24tPMenuItemGoToMenuButtonR13tInputKeyTypeR13tPMenuCommand
    /* 469A4 800561A4 00000000 */ .word 0x00000000
    /* 469A8 800561A8 98860A80 */ .word IsNavigable__21tPMenuItemInteractive
    /* 469AC 800561AC 00000000 */ .word 0x00000000
    /* 469B0 800561B0 30750A80 */ .word Draw__21tPMenuItemInteractiveb
enddlabel _vt_24tPMenuItemGoToMenuButton

nonmatching _vt_32tPMenuItemLeftRightSliderIndexed

dlabel _vt_32tPMenuItemLeftRightSliderIndexed
    /* 469B4 800561B4 00000000 */ .word 0x00000000
    /* 469B8 800561B8 00000000 */ .word 0x00000000
    /* 469BC 800561BC 00000000 */ .word 0x00000000
    /* 469C0 800561C0 B47C0A80 */ .word ___32tPMenuItemLeftRightSliderIndexed
    /* 469C4 800561C4 00000000 */ .word 0x00000000
    /* 469C8 800561C8 38740A80 */ .word NextMenu__10tPMenuItem
    /* 469CC 800561CC 00000000 */ .word 0x00000000
    /* 469D0 800561D0 A4780A80 */ .word Debounce__25tPMenuItemLeftRightSlider
    /* 469D4 800561D4 00000000 */ .word 0x00000000
    /* 469D8 800561D8 DC7C0A80 */ .word ProcessInput__32tPMenuItemLeftRightSliderIndexedR13tInputKeyTypeR13tPMenuCommand
    /* 469DC 800561DC 00000000 */ .word 0x00000000
    /* 469E0 800561E0 98860A80 */ .word IsNavigable__21tPMenuItemInteractive
    /* 469E4 800561E4 00000000 */ .word 0x00000000
    /* 469E8 800561E8 287D0A80 */ .word Draw__32tPMenuItemLeftRightSliderIndexedb
enddlabel _vt_32tPMenuItemLeftRightSliderIndexed

nonmatching _vt_25tPMenuItemLeftRightSlider

dlabel _vt_25tPMenuItemLeftRightSlider
    /* 469EC 800561EC 00000000 */ .word 0x00000000
    /* 469F0 800561F0 00000000 */ .word 0x00000000
    /* 469F4 800561F4 00000000 */ .word 0x00000000
    /* 469F8 800561F8 7C780A80 */ .word ___25tPMenuItemLeftRightSlider
    /* 469FC 800561FC 00000000 */ .word 0x00000000
    /* 46A00 80056200 38740A80 */ .word NextMenu__10tPMenuItem
    /* 46A04 80056204 00000000 */ .word 0x00000000
    /* 46A08 80056208 A4780A80 */ .word Debounce__25tPMenuItemLeftRightSlider
    /* 46A0C 8005620C 00000000 */ .word 0x00000000
    /* 46A10 80056210 AC780A80 */ .word ProcessInput__25tPMenuItemLeftRightSliderR13tInputKeyTypeR13tPMenuCommand
    /* 46A14 80056214 00000000 */ .word 0x00000000
    /* 46A18 80056218 98860A80 */ .word IsNavigable__21tPMenuItemInteractive
    /* 46A1C 8005621C 00000000 */ .word 0x00000000
    /* 46A20 80056220 C8790A80 */ .word Draw__25tPMenuItemLeftRightSliderb
enddlabel _vt_25tPMenuItemLeftRightSlider

nonmatching _vt_25tPMenuItemLeftRightChoice

dlabel _vt_25tPMenuItemLeftRightChoice
    /* 46A24 80056224 00000000 */ .word 0x00000000
    /* 46A28 80056228 00000000 */ .word 0x00000000
    /* 46A2C 8005622C 00000000 */ .word 0x00000000
    /* 46A30 80056230 9C750A80 */ .word ___25tPMenuItemLeftRightChoice
    /* 46A34 80056234 00000000 */ .word 0x00000000
    /* 46A38 80056238 38740A80 */ .word NextMenu__10tPMenuItem
    /* 46A3C 8005623C 00000000 */ .word 0x00000000
    /* 46A40 80056240 40740A80 */ .word Debounce__10tPMenuItem
    /* 46A44 80056244 00000000 */ .word 0x00000000
    /* 46A48 80056248 C4750A80 */ .word ProcessInput__25tPMenuItemLeftRightChoiceR13tInputKeyTypeR13tPMenuCommand
    /* 46A4C 8005624C 00000000 */ .word 0x00000000
    /* 46A50 80056250 98860A80 */ .word IsNavigable__21tPMenuItemInteractive
    /* 46A54 80056254 00000000 */ .word 0x00000000
    /* 46A58 80056258 50760A80 */ .word Draw__25tPMenuItemLeftRightChoiceb
enddlabel _vt_25tPMenuItemLeftRightChoice

nonmatching _vt_21tPMenuItemInteractive

dlabel _vt_21tPMenuItemInteractive
    /* 46A5C 8005625C 00000000 */ .word 0x00000000
    /* 46A60 80056260 00000000 */ .word 0x00000000
    /* 46A64 80056264 00000000 */ .word 0x00000000
    /* 46A68 80056268 08750A80 */ .word ___21tPMenuItemInteractive
    /* 46A6C 8005626C 00000000 */ .word 0x00000000
    /* 46A70 80056270 38740A80 */ .word NextMenu__10tPMenuItem
    /* 46A74 80056274 00000000 */ .word 0x00000000
    /* 46A78 80056278 40740A80 */ .word Debounce__10tPMenuItem
    /* 46A7C 8005627C 00000000 */ .word 0x00000000
    /* 46A80 80056280 48740A80 */ .word ProcessInput__10tPMenuItemR13tInputKeyTypeR13tPMenuCommand
    /* 46A84 80056284 00000000 */ .word 0x00000000
    /* 46A88 80056288 98860A80 */ .word IsNavigable__21tPMenuItemInteractive
    /* 46A8C 8005628C 00000000 */ .word 0x00000000
    /* 46A90 80056290 30750A80 */ .word Draw__21tPMenuItemInteractiveb
enddlabel _vt_21tPMenuItemInteractive

nonmatching _vt_28tPMenuItemNonInteractiveText

dlabel _vt_28tPMenuItemNonInteractiveText
    /* 46A94 80056294 00000000 */ .word 0x00000000
    /* 46A98 80056298 00000000 */ .word 0x00000000
    /* 46A9C 8005629C 00000000 */ .word 0x00000000
    /* 46AA0 800562A0 84740A80 */ .word ___28tPMenuItemNonInteractiveText
    /* 46AA4 800562A4 00000000 */ .word 0x00000000
    /* 46AA8 800562A8 38740A80 */ .word NextMenu__10tPMenuItem
    /* 46AAC 800562AC 00000000 */ .word 0x00000000
    /* 46AB0 800562B0 40740A80 */ .word Debounce__10tPMenuItem
    /* 46AB4 800562B4 00000000 */ .word 0x00000000
    /* 46AB8 800562B8 48740A80 */ .word ProcessInput__10tPMenuItemR13tInputKeyTypeR13tPMenuCommand
    /* 46ABC 800562BC 00000000 */ .word 0x00000000
    /* 46AC0 800562C0 A0860A80 */ .word IsNavigable__28tPMenuItemNonInteractiveText
    /* 46AC4 800562C4 00000000 */ .word 0x00000000
    /* 46AC8 800562C8 AC740A80 */ .word Draw__28tPMenuItemNonInteractiveTextb
enddlabel _vt_28tPMenuItemNonInteractiveText

nonmatching _vt_10tPMenuItem

dlabel _vt_10tPMenuItem
    /* 46ACC 800562CC 00000000 */ .word 0x00000000
    /* 46AD0 800562D0 00000000 */ .word 0x00000000
    /* 46AD4 800562D4 00000000 */ .word 0x00000000
    /* 46AD8 800562D8 04740A80 */ .word ___10tPMenuItem
    /* 46ADC 800562DC 00000000 */ .word 0x00000000
    /* 46AE0 800562E0 38740A80 */ .word NextMenu__10tPMenuItem
    /* 46AE4 800562E4 00000000 */ .word 0x00000000
    /* 46AE8 800562E8 40740A80 */ .word Debounce__10tPMenuItem
    /* 46AEC 800562EC 00000000 */ .word 0x00000000
    /* 46AF0 800562F0 48740A80 */ .word ProcessInput__10tPMenuItemR13tInputKeyTypeR13tPMenuCommand
    /* 46AF4 800562F4 00000000 */ .word 0x00000000
    /* 46AF8 800562F8 54430E80 */ .word __pure_virtual
    /* 46AFC 800562FC 00000000 */ .word 0x00000000
    /* 46B00 80056300 54430E80 */ .word __pure_virtual
enddlabel _vt_10tPMenuItem

nonmatching _vt_21tPListIteratorIndexed

dlabel _vt_21tPListIteratorIndexed
    /* 46B04 80056304 00000000 */ .word 0x00000000
    /* 46B08 80056308 00000000 */ .word 0x00000000
    /* 46B0C 8005630C 00000000 */ .word 0x00000000
    /* 46B10 80056310 F4710A80 */ .word ___21tPListIteratorIndexed
    /* 46B14 80056314 00000000 */ .word 0x00000000
    /* 46B18 80056318 1C720A80 */ .word Value__21tPListIteratorIndexed7tPlayer
    /* 46B1C 8005631C 00000000 */ .word 0x00000000
    /* 46B20 80056320 40720A80 */ .word TextValue__21tPListIteratorIndexed7tPlayer
    /* 46B24 80056324 00000000 */ .word 0x00000000
    /* 46B28 80056328 90720A80 */ .word Increment__21tPListIteratorIndexed7tPlayer
    /* 46B2C 8005632C 00000000 */ .word 0x00000000
    /* 46B30 80056330 1C730A80 */ .word Decrement__21tPListIteratorIndexed7tPlayer
enddlabel _vt_21tPListIteratorIndexed

nonmatching _vt_14tPListIterator

dlabel _vt_14tPListIterator
    /* 46B34 80056334 00000000 */ .word 0x00000000
    /* 46B38 80056338 00000000 */ .word 0x00000000
    /* 46B3C 8005633C 00000000 */ .word 0x00000000
    /* 46B40 80056340 0C700A80 */ .word ___14tPListIterator
    /* 46B44 80056344 00000000 */ .word 0x00000000
    /* 46B48 80056348 40700A80 */ .word Value__14tPListIterator7tPlayer
    /* 46B4C 8005634C 00000000 */ .word 0x00000000
    /* 46B50 80056350 54700A80 */ .word TextValue__14tPListIterator7tPlayer
    /* 46B54 80056354 00000000 */ .word 0x00000000
    /* 46B58 80056358 A4700A80 */ .word Increment__14tPListIterator7tPlayer
    /* 46B5C 8005635C 00000000 */ .word 0x00000000
    /* 46B60 80056360 10710A80 */ .word Decrement__14tPListIterator7tPlayer
    /* 46B64 80056364 53696D70 */ .word 0x706D6953
    /* 46B68 80056368 6C654D65 */ .word 0x654D656C
    /* 46B6C 8005636C 6D000000 */ .word 0x0000006D
enddlabel _vt_14tPListIterator

nonmatching D_80056370

dlabel D_80056370
    /* 46B70 80056370 00000000 */ .word 0x00000000
    /* 46B74 80056374 00000000 */ .word 0x00000000
    /* 46B78 80056378 FA000000 */ .word 0x000000FA
    /* 46B7C 8005637C C8000000 */ .word 0x000000C8
    /* 46B80 80056380 AF000000 */ .word 0x000000AF
    /* 46B84 80056384 96000000 */ .word 0x00000096
    /* 46B88 80056388 7D000000 */ .word 0x0000007D
    /* 46B8C 8005638C 00000000 */ .word 0x00000000
enddlabel D_80056370

nonmatching D_80056390

dlabel D_80056390
    /* 46B90 80056390 00000000 */ .word 0x00000000
    /* 46B94 80056394 00000000 */ .word 0x00000000
    /* 46B98 80056398 C8000000 */ .word 0x000000C8
    /* 46B9C 8005639C AF000000 */ .word 0x000000AF
    /* 46BA0 800563A0 96000000 */ .word 0x00000096
    /* 46BA4 800563A4 7D000000 */ .word 0x0000007D
    /* 46BA8 800563A8 64000000 */ .word 0x00000064
    /* 46BAC 800563AC 00000000 */ .word 0x00000000
    /* 46BB0 800563B0 53696D70 */ .word 0x706D6953
    /* 46BB4 800563B4 6C654D65 */ .word 0x654D656C
    /* 46BB8 800563B8 6D000000 */ .word 0x0000006D
enddlabel D_80056390

.align 2
nonmatching D_800563BC

dlabel D_800563BC
    /* 46BBC 800563BC */ .asciz "orientMat"
    /* 6F7269656E744D6174000000 */
.align 2
enddlabel D_800563BC

.align 2
nonmatching D_800563C8

dlabel D_800563C8
    /* 46BC8 800563C8 */ .asciz "position"
    /* 706F736974696F6E00000000 */
.align 2
enddlabel D_800563C8

.align 2
nonmatching D_800563D4

dlabel D_800563D4
    /* 46BD4 800563D4 */ .asciz "%slicense.psh"
    /* 25736C6963656E73652E707368000000 */
.align 2
enddlabel D_800563D4

.align 2
nonmatching D_800563E4

dlabel D_800563E4
    /* 46BE4 800563E4 */ .asciz "sub_ot0m"
    /* 7375625F6F74306D00000000 */
.align 2
enddlabel D_800563E4

.align 2
nonmatching D_800563F0

dlabel D_800563F0
    /* 46BF0 800563F0 */ .asciz "sub_ot1m"
    /* 7375625F6F74316D00000000 */
.align 2
enddlabel D_800563F0

.align 2
nonmatching D_800563FC

dlabel D_800563FC
    /* 46BFC 800563FC */ .asciz "%scarmap.dat"
    /* 25736361726D61702E64617400000000 */
.align 2
enddlabel D_800563FC

.align 2
nonmatching D_8005640C

dlabel D_8005640C
    /* 46C0C 8005640C */ .asciz "%strack.dat"
    /* 2573747261636B2E64617400 */
.align 2
enddlabel D_8005640C