.include "macro.inc"
/* W65-A5: residual segment of rdata_80010000 -- the non-jump-table blob records.
 * Linked by BOTH lanes. */

.section .rodata, "a"

/* Generated by spimdisasm 1.40.2 */

.align 2

.align 2
nonmatching D_80011AD4

dlabel D_80011AD4
    /* 22D4 80011AD4 */ .asciz "zcars"
    /* 7A63617273000000 */
.align 2
enddlabel D_80011AD4

nonmatching D_80011ADC

dlabel D_80011ADC
    /* 22DC 80011ADC 25730000 */ .word 0x00007325
enddlabel D_80011ADC

nonmatching D_80011AE0

dlabel D_80011AE0
    /* 22E0 80011AE0 56696465 */ .word 0x65646956
    /* 22E4 80011AE4 6F57616C */ .word 0x6C61576F
    /* 22E8 80011AE8 6C000000 */ .word 0x0000006C
    /* 22EC 80011AEC 25642C25 */ .word 0x252C6425
    /* 22F0 80011AF0 30336400 */ .word 0x00643330
    /* 22F4 80011AF4 25640000 */ .word 0x00006425
enddlabel D_80011AE0