.include "macro.inc"
/* W65-A5: residual segment of rdata_80054548 -- the non-jump-table blob records.
 * Linked by BOTH lanes. */

.section .rodata, "a"

/* Generated by spimdisasm 1.40.2 */


.align 2
nonmatching D_80056724

dlabel D_80056724
    /* 46F24 80056724 */ .asciz "SimpleMem"
    /* 53696D706C654D656D000000 */
.align 2
enddlabel D_80056724

.align 2
nonmatching D_80056730

dlabel D_80056730
    /* 46F30 80056730 */ .asciz "udffhandle"
    /* 7564666668616E646C650000 */
.align 2
.align 2
    /* 46F3C 8005673C */ .asciz "SimpleMem"
    /* 53696D706C654D656D000000 */
.align 2
.align 2
    /* 46F48 80056748 */ .asciz "SimpleMem"
    /* 53696D706C654D656D000000 */
.align 2
enddlabel D_80056730

.align 2
nonmatching D_80056754

dlabel D_80056754
    /* 46F54 80056754 */ .asciz "audio heap"
    /* 617564696F20686561700000 */
.align 2
.align 2
    /* 46F60 80056760 */ .asciz "SimpleMem"
    /* 53696D706C654D656D000000 */
.align 2
enddlabel D_80056754

.align 2
nonmatching D_8005676C

dlabel D_8005676C
    /* 46F6C 8005676C */ .asciz "carPixMap"
    /* 6361725069784D6170000000 */
.align 2
enddlabel D_8005676C

.align 2
nonmatching D_80056778

dlabel D_80056778
    /* 46F78 80056778 */ .asciz "theplate"
    /* 746865706C61746500000000 */
.align 2
.align 2
    /* 46F84 80056784 */ .asciz ""
    /* 00000000 */
.align 2
enddlabel D_80056778