.include "macro.inc"
/* ============================================================
 * W65-A5  THE .L LOCALIZE CUT -- SPLAT-LANE FILLER ONLY
 *
 * jtbl_80056C94: the retail jump table of a switch inside
 *     build/recon/eaclib/psx/eacpsxz/nfile.c.o
 * (retail 0x80056c94..0x80056cb8, 9 entries).
 *
 * OWNERSHIP PROOF: word-for-word identical to the owner's own .rodata run at +0x50 (E5)
 *
 * The `.word .L<VA>` operands below are the SRC lane's local labels.  The
 * RECON lane must NOT link this file: the recon TU emits this very table into
 * its own `.rodata`, and no recon object defines a `.L<VA>` symbol, so
 * linking it here is exactly the 350-name undefined `.L` class.
 * It stays in the tree so the legacy splat-lane script (linkers/nfs4.ld,
 * which links build/src/**) keeps producing a byte-identical image.
 * ============================================================ */

.section .rodata, "a"

/* Generated by spimdisasm 1.40.2 */


nonmatching jtbl_80056C94

dlabel jtbl_80056C94
    /* 47494 80056C94 04CD0E80 */ .word .L800ECD04
    /* 47498 80056C98 08CF0E80 */ .word .L800ECF08
    /* 4749C 80056C9C 4CCF0E80 */ .word .L800ECF4C
    /* 474A0 80056CA0 B4CF0E80 */ .word .L800ECFB4
    /* 474A4 80056CA4 D8CF0E80 */ .word .L800ECFD8
    /* 474A8 80056CA8 F0CF0E80 */ .word .L800ECFF0
    /* 474AC 80056CAC 04CD0E80 */ .word .L800ECD04
    /* 474B0 80056CB0 F0CF0E80 */ .word .L800ECFF0
    /* 474B4 80056CB4 F0CF0E80 */ .word .L800ECFF0
enddlabel jtbl_80056C94