.include "macro.inc"
/* ============================================================
 * W65-A5  THE .L LOCALIZE CUT -- SPLAT-LANE FILLER ONLY
 *
 * jtbl_80011AF8: the retail jump table of a switch inside
 *     build/recon/frontend/common/screencarselect.cpp.o
 * (retail 0x80011af8..0x80011b18, 8 entries).
 *
 * OWNERSHIP PROOF: word-for-word identical to the owner's own .rodata run at +0x48 (E5)
 *
 * The `.word .L<VA>` operands below are the SRC lane's local labels.  The
 * RECON lane must NOT link this file: the recon TU emits this very table into
 * its own `.rodata`, and no recon object defines a `.L<VA>` symbol, so
 * linking it here is exactly the 350-name undefined `.L` class.
 * It stays in the tree so the legacy splat-lane script (linkers/nfs4.ld,
 * which links build/src/**) keeps producing a byte-identical image.
 * ============================================================ */

.section .rodata, "a"

/* Generated by spimdisasm 1.40.2 */

.align 2

.align 3
nonmatching jtbl_80011AF8

dlabel jtbl_80011AF8
    /* 22F8 80011AF8 70C20380 */ .word .L8003C270
    /* 22FC 80011AFC B8C30380 */ .word .L8003C3B8
    /* 2300 80011B00 D4C20380 */ .word .L8003C2D4
    /* 2304 80011B04 B8C30380 */ .word .L8003C3B8
    /* 2308 80011B08 B8C30380 */ .word .L8003C3B8
    /* 230C 80011B0C 70C20380 */ .word .L8003C270
    /* 2310 80011B10 D4C20380 */ .word .L8003C2D4
    /* 2314 80011B14 10C30380 */ .word .L8003C310
enddlabel jtbl_80011AF8