.include "macro.inc"
/* W65-A5: residual segment of rdata_80054548 -- the non-jump-table blob records.
 * Linked by BOTH lanes. */

.section .rodata, "a"

/* Generated by spimdisasm 1.40.2 */


.align 2
nonmatching D_80054F90

dlabel D_80054F90
    /* 45790 80054F90 */ .asciz "SimpleMem"
    /* 53696D706C654D656D000000 */
.align 2
.align 2
    /* 4579C 80054F9C */ .asciz ""
    /* 00000000 */
.align 2
enddlabel D_80054F90

nonmatching _vt_17AIHigh_BTC_AIPerp

dlabel _vt_17AIHigh_BTC_AIPerp
    /* 457A0 80054FA0 00000000 */ .word 0x00000000
    /* 457A4 80054FA4 00000000 */ .word 0x00000000
    /* 457A8 80054FA8 00000000 */ .word 0x00000000
    /* 457AC 80054FAC B4080680 */ .word HighExecute__17AIHigh_BTC_AIPerp
    /* 457B0 80054FB0 00000000 */ .word 0x00000000
    /* 457B4 80054FB4 7C030680 */ .word ___17AIHigh_BTC_AIPerp
    /* 457B8 80054FB8 00000000 */ .word 0x00000000
    /* 457BC 80054FBC 00B50580 */ .word CheckForCrimes__16AIHigh_BasicPerp
enddlabel _vt_17AIHigh_BTC_AIPerp

nonmatching _vt_20AIHigh_BTC_HumanPerp

dlabel _vt_20AIHigh_BTC_HumanPerp
    /* 457C0 80054FC0 00000000 */ .word 0x00000000
    /* 457C4 80054FC4 00000000 */ .word 0x00000000
    /* 457C8 80054FC8 00000000 */ .word 0x00000000
    /* 457CC 80054FCC 9C020680 */ .word HighExecute__20AIHigh_BTC_HumanPerp
    /* 457D0 80054FD0 00000000 */ .word 0x00000000
    /* 457D4 80054FD4 20130680 */ .word ___20AIHigh_BTC_HumanPerp
    /* 457D8 80054FD8 00000000 */ .word 0x00000000
    /* 457DC 80054FDC 00B50580 */ .word CheckForCrimes__16AIHigh_BasicPerp
enddlabel _vt_20AIHigh_BTC_HumanPerp

nonmatching D_80054FE0

dlabel D_80054FE0
    /* 457E0 80054FE0 00000000 */ .word 0x00000000
    /* 457E4 80054FE4 00000000 */ .word 0x00000000
    /* 457E8 80054FE8 00000000 */ .word 0x00000000
    /* 457EC 80054FEC 54430E80 */ .word __pure_virtual
    /* 457F0 80054FF0 00000000 */ .word 0x00000000
    /* 457F4 80054FF4 48130680 */ .word ___15AIHigh_BTC_Perp
    /* 457F8 80054FF8 00000000 */ .word 0x00000000
    /* 457FC 80054FFC 00B50580 */ .word CheckForCrimes__16AIHigh_BasicPerp
enddlabel D_80054FE0

nonmatching D_80055000

dlabel D_80055000
    /* 45800 80055000 00000000 */ .word 0x00000000
    /* 45804 80055004 00000000 */ .word 0x00000000
    /* 45808 80055008 00000000 */ .word 0x00000000
    /* 4580C 8005500C 70130680 */ .word Execute__17AIState_NonActive_80061370
    /* 45810 80055010 00000000 */ .word 0x00000000
    /* 45814 80055014 78130680 */ .word ___17AIState_NonActive_80061378
    /* 45818 80055018 00000000 */ .word 0x00000000
    /* 4581C 8005501C C4130680 */ .word TestForRelease__12AIState_Base_800613C4
enddlabel D_80055000

nonmatching D_80055020

dlabel D_80055020
    /* 45820 80055020 00000000 */ .word 0x00000000
    /* 45824 80055024 00000000 */ .word 0x00000000
    /* 45828 80055028 00000000 */ .word 0x00000000
    /* 4582C 8005502C 54430E80 */ .word __pure_virtual
    /* 45830 80055030 00000000 */ .word 0x00000000
    /* 45834 80055034 CC130680 */ .word ___12AIState_Base_800613CC
    /* 45838 80055038 00000000 */ .word 0x00000000
    /* 4583C 8005503C C4130680 */ .word TestForRelease__12AIState_Base_800613C4
enddlabel D_80055020