.include "macro.inc"
/* ============================================================
 * W65-A5  THE .L LOCALIZE CUT -- SPLAT-LANE FILLER ONLY
 *
 * jtbl_80055918: the retail jump table of a switch inside
 *     build/recon/game/common/camera.cpp.o
 * (retail 0x80055918..0x80055930, 6 entries).
 *
 * OWNERSHIP PROOF: word-for-word identical to the owner's own .rodata run at +0x78 (E5)
 *
 * The `.word .L<VA>` operands below are the SRC lane's local labels.  The
 * RECON lane must NOT link this file: the recon TU emits this very table into
 * its own `.rodata`, and no recon object defines a `.L<VA>` symbol, so
 * linking it here is exactly the 350-name undefined `.L` class.
 * It stays in the tree so the legacy splat-lane script (linkers/nfs4.ld,
 * which links build/src/**) keeps producing a byte-identical image.
 * ============================================================ */

.section .rodata, "a"

/* Generated by spimdisasm 1.40.2 */


.align 3
nonmatching jtbl_80055918

dlabel jtbl_80055918
    /* 46118 80055918 744F0880 */ .word .L80084F74
    /* 4611C 8005591C 744F0880 */ .word .L80084F74
    /* 46120 80055920 744F0880 */ .word .L80084F74
    /* 46124 80055924 944F0880 */ .word .L80084F94
    /* 46128 80055928 944F0880 */ .word .L80084F94
    /* 4612C 8005592C 844F0880 */ .word .L80084F84
enddlabel jtbl_80055918