.include "macro.inc"
/* W65-A5: residual segment of rdata_80010000 -- the non-jump-table blob records.
 * Linked by BOTH lanes. */

.section .rodata, "a"

/* Generated by spimdisasm 1.40.2 */

.align 2
nonmatching _front_obj

dlabel _front_obj
/* W66-A3 (link): `bigBuf` is the recon lane's spelling for this same address --
 * the front overlay's load buffer, referenced from 5 TUs (feapp/feaudio/minfront/
 * nfs3/fe3dmenu) as `bigBuf + <offset>` and defined nowhere.  A second GLOBAL
 * LABEL at offset 0 resolves it without a byte moving and without touching any
 * recon TU (`dlabel` = `.global` + label only; no `.size`, so the unsized-array
 * declarations the consumers use stay honest).  Never `bigBuf = _front_obj` --
 * ASPSX 2.77 has no symbol-assignment form (catalog 15E). */
dlabel bigBuf
    /* 800 80010000 */ .asciz "SimpleMem"
    /* 53696D706C654D656D000000 */
.align 2
enddlabel _front_obj

.align 2
nonmatching D_8001000C

dlabel D_8001000C
    /* 80C 8001000C */ .asciz "FE Data Stream"
    /* 464520446174612053747265616D0000 */
.align 2
.align 2
    /* 81C 8001001C */ .asciz ""
    /* 00000000 */
.align 2
.align 2
    /* 820 80010020 */ .asciz "SimpleMem"
    /* 53696D706C654D656D000000 */
.align 2
enddlabel D_8001000C

nonmatching D_8001002C

dlabel D_8001002C
    /* 82C 8001002C 00000000 */ .word 0x00000000
    /* 830 80010030 00000100 */ .word 0x00010000
    /* 834 80010034 00000000 */ .word 0x00000000
    /* 838 80010038 53696D70 */ .word 0x706D6953
    /* 83C 8001003C 6C654D65 */ .word 0x654D656C
    /* 840 80010040 6D000000 */ .word 0x0000006D
enddlabel D_8001002C

.align 2
nonmatching D_80010044

dlabel D_80010044
    /* 844 80010044 */ .asciz "%ld"
    /* 256C6400 */
.align 2
enddlabel D_80010044

.align 2
nonmatching D_80010048

dlabel D_80010048
    /* 848 80010048 */ .asciz "%d/%d"
    /* 25642F2564000000 */
.align 2
enddlabel D_80010048

.align 2
nonmatching D_80010050

dlabel D_80010050
    /* 850 80010050 */ .asciz "zmenu*"
    /* 7A6D656E752A0000 */
.align 2
enddlabel D_80010050

.align 2
nonmatching D_80010058

dlabel D_80010058
    /* 858 80010058 */ .asciz "garage*"
    /* 6761726167652A00 */
.align 2
enddlabel D_80010058

.align 2
nonmatching D_80010060

dlabel D_80010060
    /* 860 80010060 */ .asciz "showcase*"
    /* 73686F77636173652A000000 */
.align 2
enddlabel D_80010060

.align 2
nonmatching D_8001006C

dlabel D_8001006C
    /* 86C 8001006C */ .asciz "victory*"
    /* 766963746F72792A00000000 */
.align 2
enddlabel D_8001006C