.include "macro.inc"
/* ============================================================
 * W65-A5  THE .L LOCALIZE CUT -- SPLAT-LANE FILLER ONLY
 *
 * jtbl_80012858: the retail jump table of a switch inside
 *     build/recon/frontend/psx/memcard.c.o
 * (retail 0x80012858..0x80012870, 5 entries).
 *
 * OWNERSHIP PROOF: word-for-word identical to the owner's own .rodata run at +0x0 (E5)
 *
 * The `.word .L<VA>` operands below are the SRC lane's local labels.  The
 * RECON lane must NOT link this file: the recon TU emits this very table into
 * its own `.rodata`, and no recon object defines a `.L<VA>` symbol, so
 * linking it here is exactly the 350-name undefined `.L` class.
 * It stays in the tree so the legacy splat-lane script (linkers/nfs4.ld,
 * which links build/src/**) keeps producing a byte-identical image.
 * ============================================================ */

.section .rodata, "a"

/* Generated by spimdisasm 1.40.2 */

.align 2

.align 3
nonmatching jtbl_80012858

dlabel jtbl_80012858
    /* 3058 80012858 0C000580 */ .word .L8005000C
    /* 305C 8001285C 28000580 */ .word .L80050028
    /* 3060 80012860 40000580 */ .word .L80050040
    /* 3064 80012864 0C000580 */ .word .L8005000C
    /* 3068 80012868 50000580 */ .word .L80050050
    /* 306C 8001286C 00000000 */ .word 0x00000000
enddlabel jtbl_80012858