.include "macro.inc"
/* ============================================================
 * W65-A5  THE .L LOCALIZE CUT -- SPLAT-LANE FILLER ONLY
 *
 * jtbl_800117A8: the retail jump table of a switch inside
 *     build/recon/frontend/common/fememcard.cpp.o
 * (retail 0x800117a8..0x80011800, 22 entries).
 *
 * OWNERSHIP PROOF: the owner's text window CONTAINS every target; its own table has drifted because the owning function is a near-miss (per-word diff: scratchpad/w65a5/jtbl_diag.txt)
 *
 * The `.word .L<VA>` operands below are the SRC lane's local labels.  The
 * RECON lane must NOT link this file: the recon TU emits this very table into
 * its own `.rodata`, and no recon object defines a `.L<VA>` symbol, so
 * linking it here is exactly the 350-name undefined `.L` class.
 * It stays in the tree so the legacy splat-lane script (linkers/nfs4.ld,
 * which links build/src/**) keeps producing a byte-identical image.
 * ============================================================ */

.section .rodata, "a"

/* Generated by spimdisasm 1.40.2 */

.align 2

.align 3
nonmatching jtbl_800117A8

dlabel jtbl_800117A8
    /* 1FA8 800117A8 C0560380 */ .word .L800356C0
    /* 1FAC 800117AC F4560380 */ .word .L800356F4
    /* 1FB0 800117B0 E8540380 */ .word .L800354E8
    /* 1FB4 800117B4 E8540380 */ .word .L800354E8
    /* 1FB8 800117B8 E8540380 */ .word .L800354E8
    /* 1FBC 800117BC F4560380 */ .word .L800356F4
    /* 1FC0 800117C0 E8540380 */ .word .L800354E8
    /* 1FC4 800117C4 E8540380 */ .word .L800354E8
    /* 1FC8 800117C8 F4560380 */ .word .L800356F4
    /* 1FCC 800117CC F4560380 */ .word .L800356F4
    /* 1FD0 800117D0 E8540380 */ .word .L800354E8
    /* 1FD4 800117D4 E8540380 */ .word .L800354E8
    /* 1FD8 800117D8 E8540380 */ .word .L800354E8
    /* 1FDC 800117DC 50550380 */ .word .L80035550
    /* 1FE0 800117E0 C0560380 */ .word .L800356C0
    /* 1FE4 800117E4 E8540380 */ .word .L800354E8
    /* 1FE8 800117E8 E8540380 */ .word .L800354E8
    /* 1FEC 800117EC E8540380 */ .word .L800354E8
    /* 1FF0 800117F0 E8540380 */ .word .L800354E8
    /* 1FF4 800117F4 E8540380 */ .word .L800354E8
    /* 1FF8 800117F8 38550380 */ .word .L80035538
    /* 1FFC 800117FC F4560380 */ .word .L800356F4
enddlabel jtbl_800117A8