.include "macro.inc"
/* ============================================================
 * W65-A5  THE .L LOCALIZE CUT -- SPLAT-LANE FILLER ONLY
 *
 * jtbl_80011750: the retail jump table of a switch inside
 *     build/recon/frontend/common/fememcard.cpp.o
 * (retail 0x80011750..0x800117a8, 22 entries).
 *
 * OWNERSHIP PROOF: word-for-word identical to the owner's own .rodata run at +0x78 (E5)
 *
 * The `.word .L<VA>` operands below are the SRC lane's local labels.  The
 * RECON lane must NOT link this file: the recon TU emits this very table into
 * its own `.rodata`, and no recon object defines a `.L<VA>` symbol, so
 * linking it here is exactly the 350-name undefined `.L` class.
 * It stays in the tree so the legacy splat-lane script (linkers/nfs4.ld,
 * which links build/src/**) keeps producing a byte-identical image.
 * ============================================================ */

.section .rodata, "a"

/* Generated by spimdisasm 1.40.2 */

.align 2

.align 3
nonmatching jtbl_80011750

dlabel jtbl_80011750
    /* 1F50 80011750 DC510380 */ .word .L800351DC
    /* 1F54 80011754 DC510380 */ .word .L800351DC
    /* 1F58 80011758 0C500380 */ .word .L8003500C
    /* 1F5C 8001175C 0C500380 */ .word .L8003500C
    /* 1F60 80011760 0C500380 */ .word .L8003500C
    /* 1F64 80011764 DC510380 */ .word .L800351DC
    /* 1F68 80011768 0C500380 */ .word .L8003500C
    /* 1F6C 8001176C 0C500380 */ .word .L8003500C
    /* 1F70 80011770 DC510380 */ .word .L800351DC
    /* 1F74 80011774 DC510380 */ .word .L800351DC
    /* 1F78 80011778 0C500380 */ .word .L8003500C
    /* 1F7C 8001177C 0C500380 */ .word .L8003500C
    /* 1F80 80011780 0C500380 */ .word .L8003500C
    /* 1F84 80011784 74500380 */ .word .L80035074
    /* 1F88 80011788 DC510380 */ .word .L800351DC
    /* 1F8C 8001178C 0C500380 */ .word .L8003500C
    /* 1F90 80011790 0C500380 */ .word .L8003500C
    /* 1F94 80011794 0C500380 */ .word .L8003500C
    /* 1F98 80011798 0C500380 */ .word .L8003500C
    /* 1F9C 8001179C 0C500380 */ .word .L8003500C
    /* 1FA0 800117A0 5C500380 */ .word .L8003505C
    /* 1FA4 800117A4 DC510380 */ .word .L800351DC
enddlabel jtbl_80011750