.include "macro.inc"
/* ============================================================
 * W65-A5  THE .L LOCALIZE CUT -- SPLAT-LANE FILLER ONLY
 *
 * jtbl_80055118: the retail jump table of a switch inside
 *     build/recon/game/common/aih_opp.cpp.o
 * (retail 0x80055118..0x80055144, 11 entries).
 *
 * OWNERSHIP PROOF: word-for-word identical to the owner's own .rodata run at +0x0 (E5)
 *
 * The `.word .L<VA>` operands below are the SRC lane's local labels.  The
 * RECON lane must NOT link this file: the recon TU emits this very table into
 * its own `.rodata`, and no recon object defines a `.L<VA>` symbol, so
 * linking it here is exactly the 350-name undefined `.L` class.
 * It stays in the tree so the legacy splat-lane script (linkers/nfs4.ld,
 * which links build/src/**) keeps producing a byte-identical image.
 * ============================================================ */

.section .rodata, "a"

/* Generated by spimdisasm 1.40.2 */


.align 3
nonmatching jtbl_80055118

dlabel jtbl_80055118
    /* 45918 80055118 08380680 */ .word .L80063808
    /* 4591C 8005511C C03A0680 */ .word .L80063AC0
    /* 45920 80055120 58380680 */ .word .L80063858
    /* 45924 80055124 C03A0680 */ .word .L80063AC0
    /* 45928 80055128 88390680 */ .word .L80063988
    /* 4592C 8005512C C03A0680 */ .word .L80063AC0
    /* 45930 80055130 C03A0680 */ .word .L80063AC0
    /* 45934 80055134 C03A0680 */ .word .L80063AC0
    /* 45938 80055138 C03A0680 */ .word .L80063AC0
    /* 4593C 8005513C C03A0680 */ .word .L80063AC0
    /* 45940 80055140 C03A0680 */ .word .L80063AC0
enddlabel jtbl_80055118