.include "macro.inc"
/* W65-A5: residual segment of rdata_80010000 -- the non-jump-table blob records.
 * Linked by BOTH lanes. */

.section .rodata, "a"

/* Generated by spimdisasm 1.40.2 */

.align 2

nonmatching _vt_15tScreenUserName

dlabel _vt_15tScreenUserName
    /* 2EE8 800126E8 00000000 */ .word 0x00000000
    /* 2EEC 800126EC 00000000 */ .word 0x00000000
    /* 2EF0 800126F0 00000000 */ .word 0x00000000
    /* 2EF4 800126F4 48B00480 */ .word GetShapeInfo__15tScreenUserNameRsT1PPcT3
    /* 2EF8 800126F8 00000000 */ .word 0x00000000
    /* 2EFC 800126FC ACB10480 */ .word DrawBackground__15tScreenUserName
    /* 2F00 80012700 00000000 */ .word 0x00000000
    /* 2F04 80012704 E0680280 */ .word DrawForeground__7tScreen
    /* 2F08 80012708 00000000 */ .word 0x00000000
    /* 2F0C 8001270C D4B70480 */ .word ___15tScreenUserName
    /* 2F10 80012710 00000000 */ .word 0x00000000
    /* 2F14 80012714 80670280 */ .word PreLoad__7tScreen
    /* 2F18 80012718 00000000 */ .word 0x00000000
    /* 2F1C 8001271C 88AF0480 */ .word Initialize__15tScreenUserName
    /* 2F20 80012720 00000000 */ .word 0x00000000
    /* 2F24 80012724 A0610280 */ .word Cleanup__7tScreen
    /* 2F28 80012728 00000000 */ .word 0x00000000
    /* 2F2C 8001272C C0680280 */ .word TransitionIsFinished__7tScreen
    /* 2F30 80012730 00000000 */ .word 0x00000000
    /* 2F34 80012734 D8680280 */ .word ProcessInput__7tScreen7tPlayerR13tInputKeyTypeR12tMenuCommand
    /* 2F38 80012738 53696D70 */ .word 0x706D6953
    /* 2F3C 8001273C 6C654D65 */ .word 0x654D656C
    /* 2F40 80012740 6D000000 */ .word 0x0000006D
    /* 2F44 80012744 00000000 */ .word 0x00000000
    /* 2F48 80012748 53696D70 */ .word 0x706D6953
    /* 2F4C 8001274C 6C654D65 */ .word 0x654D656C
    /* 2F50 80012750 6D000000 */ .word 0x0000006D
    /* 2F54 80012754 4E465334 */ .word 0x3453464E
    /* 2F58 80012758 5449544C */ .word 0x4C544954
    /* 2F5C 8001275C 2E584100 */ .word 0x0041582E
    /* 2F60 80012760 44454D4F */ .word 0x4F4D4544
    /* 2F64 80012764 3141562E */ .word 0x2E564131
    /* 2F68 80012768 58410000 */ .word 0x00004158
    /* 2F6C 8001276C 44454D4F */ .word 0x4F4D4544
    /* 2F70 80012770 3241562E */ .word 0x2E564132
    /* 2F74 80012774 58410000 */ .word 0x00004158
    /* 2F78 80012778 44454D4F */ .word 0x4F4D4544
    /* 2F7C 8001277C 3341562E */ .word 0x2E564133
    /* 2F80 80012780 58410000 */ .word 0x00004158
    /* 2F84 80012784 4541444F */ .word 0x4F444145
    /* 2F88 80012788 4C42592E */ .word 0x2E59424C
    /* 2F8C 8001278C 58410000 */ .word 0x00004158
enddlabel _vt_15tScreenUserName

.align 2
nonmatching D_80012790

dlabel D_80012790
    /* 2F90 80012790 */ .asciz "vlcbuf0"
    /* 766C636275663000 */
.align 2
enddlabel D_80012790

.align 2
nonmatching D_80012798

dlabel D_80012798
    /* 2F98 80012798 */ .asciz "vlcbuf1"
    /* 766C636275663100 */
.align 2
enddlabel D_80012798

.align 2
nonmatching D_800127A0

dlabel D_800127A0
    /* 2FA0 800127A0 */ .asciz "imgbuf"
    /* 696D676275660000 */
.align 2
enddlabel D_800127A0

.align 2
nonmatching D_800127A8

dlabel D_800127A8
    /* 2FA8 800127A8 */ .asciz "sect_buff"
    /* 736563745F62756666000000 */
.align 2
enddlabel D_800127A8

.align 2
nonmatching D_800127B4

dlabel D_800127B4
    /* 2FB4 800127B4 */ .asciz "\\MOVIES\\%s;1"
    /* 5C4D4F564945535C25733B3100000000 */
.align 2
.align 2
    /* 2FC4 800127C4 */ .asciz ""
    /* 00000000 */
.align 2
.align 2
    /* 2FC8 800127C8 */ .asciz "SimpleMem"
    /* 53696D706C654D656D000000 */
.align 2
.align 2
    /* 2FD4 800127D4 */ .asciz ""
    /* 00000000 */
.align 2
.align 2
    /* 2FD8 800127D8 */ .asciz "SimpleMem"
    /* 53696D706C654D656D000000 */
.align 2
.align 2
    /* 2FE4 800127E4 */ .asciz "%sz%s"
    /* 25737A2573000000 */
.align 2
enddlabel D_800127B4

.align 2
nonmatching D_800127EC

dlabel D_800127EC
    /* 2FEC 800127EC */ .asciz "ps0"
    /* 70733000 */
.align 2
enddlabel D_800127EC

.align 2
nonmatching D_800127F0

dlabel D_800127F0
    /* 2FF0 800127F0 */ .asciz "ps1"
    /* 70733100 */
.align 2
enddlabel D_800127F0

.align 2
nonmatching D_800127F4

dlabel D_800127F4
    /* 2FF4 800127F4 */ .asciz "carObj"
    /* 6361724F626A0000 */
.align 2
enddlabel D_800127F4

.align 2
nonmatching D_800127FC

dlabel D_800127FC
    /* 2FFC 800127FC */ .asciz "%sDCT.BIN"
    /* 25734443542E42494E000000 */
.align 2
enddlabel D_800127FC

.align 2
nonmatching D_80012808

dlabel D_80012808
    /* 3008 80012808 */ .asciz "title.psh"
    /* 7469746C652E707368000000 */
.align 2
enddlabel D_80012808

.align 2
nonmatching D_80012814

dlabel D_80012814
    /* 3014 80012814 */ .asciz "back"
    /* 6261636B00000000 */
.align 2
.align 2
    /* 301C 8001281C */ .asciz "main"
    /* 6D61696E00000000 */
.align 2
.align 2
    /* 3024 80012824 */ .asciz "load.psh"
    /* 6C6F61642E70736800000000 */
.align 2
enddlabel D_80012814

.align 2
nonmatching D_80012830

dlabel D_80012830
    /* 3030 80012830 */ .asciz "gHelpShapes"
    /* 6748656C7053686170657300 */
.align 2
enddlabel D_80012830

.align 2
nonmatching D_8001283C

dlabel D_8001283C
    /* 303C 8001283C */ .asciz "%szperm.psh"
    /* 25737A7065726D2E70736800 */
.align 2
enddlabel D_8001283C

.align 2
nonmatching D_80012848

dlabel D_80012848
    /* 3048 80012848 */ .asciz "unpacked"
    /* 756E7061636B656400000000 */
.align 2
.align 2
    /* 3054 80012854 */ .asciz ""
    /* 00000000 */
.align 2
enddlabel D_80012848