.include "macro.inc"
/* W65-A5: residual segment of rdata_80010000 -- the non-jump-table blob records.
 * Linked by BOTH lanes. */

.section .rodata, "a"

/* Generated by spimdisasm 1.40.2 */

.align 2

nonmatching D_80012884

dlabel D_80012884
    /* 3084 80012884 2A000000 */ .word 0x0000002A
enddlabel D_80012884