.include "macro.inc"
/* W65-A5: residual segment of rdata_80010000 -- the non-jump-table blob records.
 * Linked by BOTH lanes. */

.section .rodata, "a"

/* Generated by spimdisasm 1.40.2 */

.align 2

.align 2
nonmatching D_80012218

dlabel D_80012218
    /* 2A18 80012218 */ .asciz "NFS4"
    /* 4E46533400000000 */
.align 2
enddlabel D_80012218

.align 2
nonmatching D_80012220

dlabel D_80012220
    /* 2A20 80012220 */ .asciz "records"
    /* 7265636F72647300 */
.align 2
enddlabel D_80012220

nonmatching _vt_14tScreenMemcard

dlabel _vt_14tScreenMemcard
    /* 2A28 80012228 00000000 */ .word 0x00000000
    /* 2A2C 8001222C 00000000 */ .word 0x00000000
    /* 2A30 80012230 00000000 */ .word 0x00000000
    /* 2A34 80012234 20630480 */ .word GetShapeInfo__14tScreenMemcardRsT1PPcT3
    /* 2A38 80012238 00000000 */ .word 0x00000000
    /* 2A3C 8001223C 70740480 */ .word DrawBackground__14tScreenMemcard
    /* 2A40 80012240 00000000 */ .word 0x00000000
    /* 2A44 80012244 D87A0480 */ .word DrawForeground__14tScreenMemcard
    /* 2A48 80012248 00000000 */ .word 0x00000000
    /* 2A4C 8001224C 3C7E0480 */ .word ___14tScreenMemcard
    /* 2A50 80012250 00000000 */ .word 0x00000000
    /* 2A54 80012254 80670280 */ .word PreLoad__7tScreen
    /* 2A58 80012258 00000000 */ .word 0x00000000
    /* 2A5C 8001225C 307C0480 */ .word Initialize__14tScreenMemcard
    /* 2A60 80012260 00000000 */ .word 0x00000000
    /* 2A64 80012264 D87D0480 */ .word Cleanup__14tScreenMemcard
    /* 2A68 80012268 00000000 */ .word 0x00000000
    /* 2A6C 8001226C C0680280 */ .word TransitionIsFinished__7tScreen
    /* 2A70 80012270 00000000 */ .word 0x00000000
    /* 2A74 80012274 D8680280 */ .word ProcessInput__7tScreen7tPlayerR13tInputKeyTypeR12tMenuCommand
    /* 2A78 80012278 53696D70 */ .word 0x706D6953
    /* 2A7C 8001227C 6C654D65 */ .word 0x654D656C
    /* 2A80 80012280 6D000000 */ .word 0x0000006D
enddlabel _vt_14tScreenMemcard

.align 2
nonmatching D_80012284

dlabel D_80012284
    /* 2A84 80012284 */ .asciz "%s%d"
    /* 2573256400000000 */
.align 2
enddlabel D_80012284

.align 2
nonmatching D_8001228C

dlabel D_8001228C
    /* 2A8C 8001228C */ .asciz "zcong"
    /* 7A636F6E67000000 */
.align 2
enddlabel D_8001228C

.align 2
nonmatching D_80012294

dlabel D_80012294
    /* 2A94 80012294 */ .asciz "zelim"
    /* 7A656C696D000000 */
.align 2
enddlabel D_80012294

.align 2
nonmatching D_8001229C

dlabel D_8001229C
    /* 2A9C 8001229C */ .asciz "congb"
    /* 636F6E6762000000 */
.align 2
enddlabel D_8001229C

nonmatching D_800122A4

dlabel D_800122A4
    /* 2AA4 800122A4 00000000 */ .word 0x00000000
enddlabel D_800122A4

nonmatching _vt_25tScreenTournamentCongrats

dlabel _vt_25tScreenTournamentCongrats
    /* 2AA8 800122A8 00000000 */ .word 0x00000000
    /* 2AAC 800122AC 00000000 */ .word 0x00000000
    /* 2AB0 800122B0 00000000 */ .word 0x00000000
    /* 2AB4 800122B4 8C7E0480 */ .word GetShapeInfo__15tScreenCongratsRsT1PPcT3
    /* 2AB8 800122B8 00000000 */ .word 0x00000000
    /* 2ABC 800122BC 3C810480 */ .word DrawBackground__15tScreenCongrats
    /* 2AC0 800122C0 00000000 */ .word 0x00000000
    /* 2AC4 800122C4 B0890480 */ .word DrawForeground__15tScreenCongrats
    /* 2AC8 800122C8 00000000 */ .word 0x00000000
    /* 2ACC 800122CC A0970480 */ .word ___25tScreenTournamentCongrats
    /* 2AD0 800122D0 00000000 */ .word 0x00000000
    /* 2AD4 800122D4 80670280 */ .word PreLoad__7tScreen
    /* 2AD8 800122D8 00000000 */ .word 0x00000000
    /* 2ADC 800122DC 2C8A0480 */ .word Initialize__15tScreenCongrats
    /* 2AE0 800122E0 00000000 */ .word 0x00000000
    /* 2AE4 800122E4 607E0480 */ .word Cleanup__15tScreenCongrats
    /* 2AE8 800122E8 00000000 */ .word 0x00000000
    /* 2AEC 800122EC C0680280 */ .word TransitionIsFinished__7tScreen
    /* 2AF0 800122F0 00000000 */ .word 0x00000000
    /* 2AF4 800122F4 F08A0480 */ .word ProcessInput__15tScreenCongrats7tPlayerR13tInputKeyTypeR12tMenuCommand
    /* 2AF8 800122F8 00000000 */ .word 0x00000000
    /* 2AFC 800122FC 3C960480 */ .word CalculatePrizes__25tScreenTournamentCongrats
    /* 2B00 80012300 00000000 */ .word 0x00000000
    /* 2B04 80012304 D4960480 */ .word DrawCongratsMessage__25tScreenTournamentCongrats
    /* 2B08 80012308 00000000 */ .word 0x00000000
    /* 2B0C 8001230C E8950480 */ .word GetCar__25tScreenTournamentCongratsR8tCarInfo
enddlabel _vt_25tScreenTournamentCongrats

nonmatching _vt_23tScreenBeTheCopCongrats

dlabel _vt_23tScreenBeTheCopCongrats
    /* 2B10 80012310 00000000 */ .word 0x00000000
    /* 2B14 80012314 00000000 */ .word 0x00000000
    /* 2B18 80012318 00000000 */ .word 0x00000000
    /* 2B1C 8001231C 8C7E0480 */ .word GetShapeInfo__15tScreenCongratsRsT1PPcT3
    /* 2B20 80012320 00000000 */ .word 0x00000000
    /* 2B24 80012324 3C810480 */ .word DrawBackground__15tScreenCongrats
    /* 2B28 80012328 00000000 */ .word 0x00000000
    /* 2B2C 8001232C B0890480 */ .word DrawForeground__15tScreenCongrats
    /* 2B30 80012330 00000000 */ .word 0x00000000
    /* 2B34 80012334 C0970480 */ .word ___23tScreenBeTheCopCongrats
    /* 2B38 80012338 00000000 */ .word 0x00000000
    /* 2B3C 8001233C 80670280 */ .word PreLoad__7tScreen
    /* 2B40 80012340 00000000 */ .word 0x00000000
    /* 2B44 80012344 2C8A0480 */ .word Initialize__15tScreenCongrats
    /* 2B48 80012348 00000000 */ .word 0x00000000
    /* 2B4C 8001234C 607E0480 */ .word Cleanup__15tScreenCongrats
    /* 2B50 80012350 00000000 */ .word 0x00000000
    /* 2B54 80012354 C0680280 */ .word TransitionIsFinished__7tScreen
    /* 2B58 80012358 00000000 */ .word 0x00000000
    /* 2B5C 8001235C F08A0480 */ .word ProcessInput__15tScreenCongrats7tPlayerR13tInputKeyTypeR12tMenuCommand
    /* 2B60 80012360 00000000 */ .word 0x00000000
    /* 2B64 80012364 DC940480 */ .word CalculatePrizes__23tScreenBeTheCopCongrats
    /* 2B68 80012368 00000000 */ .word 0x00000000
    /* 2B6C 8001236C 2C950480 */ .word DrawCongratsMessage__23tScreenBeTheCopCongrats
    /* 2B70 80012370 00000000 */ .word 0x00000000
    /* 2B74 80012374 7C940480 */ .word GetCar__23tScreenBeTheCopCongratsR8tCarInfo
enddlabel _vt_23tScreenBeTheCopCongrats

nonmatching _vt_23tScreenPinkSlipCongrats

dlabel _vt_23tScreenPinkSlipCongrats
    /* 2B78 80012378 00000000 */ .word 0x00000000
    /* 2B7C 8001237C 00000000 */ .word 0x00000000
    /* 2B80 80012380 00000000 */ .word 0x00000000
    /* 2B84 80012384 8C7E0480 */ .word GetShapeInfo__15tScreenCongratsRsT1PPcT3
    /* 2B88 80012388 00000000 */ .word 0x00000000
    /* 2B8C 8001238C 3C810480 */ .word DrawBackground__15tScreenCongrats
    /* 2B90 80012390 00000000 */ .word 0x00000000
    /* 2B94 80012394 B0890480 */ .word DrawForeground__15tScreenCongrats
    /* 2B98 80012398 00000000 */ .word 0x00000000
    /* 2B9C 8001239C E0970480 */ .word ___23tScreenPinkSlipCongrats
    /* 2BA0 800123A0 00000000 */ .word 0x00000000
    /* 2BA4 800123A4 80670280 */ .word PreLoad__7tScreen
    /* 2BA8 800123A8 00000000 */ .word 0x00000000
    /* 2BAC 800123AC EC8D0480 */ .word Initialize__23tScreenPinkSlipCongrats
    /* 2BB0 800123B0 00000000 */ .word 0x00000000
    /* 2BB4 800123B4 448E0480 */ .word Cleanup__23tScreenPinkSlipCongrats
    /* 2BB8 800123B8 00000000 */ .word 0x00000000
    /* 2BBC 800123BC C0680280 */ .word TransitionIsFinished__7tScreen
    /* 2BC0 800123C0 00000000 */ .word 0x00000000
    /* 2BC4 800123C4 F08A0480 */ .word ProcessInput__15tScreenCongrats7tPlayerR13tInputKeyTypeR12tMenuCommand
    /* 2BC8 800123C8 00000000 */ .word 0x00000000
    /* 2BCC 800123CC DC8C0480 */ .word CalculatePrizes__23tScreenPinkSlipCongrats
    /* 2BD0 800123D0 00000000 */ .word 0x00000000
    /* 2BD4 800123D4 488B0480 */ .word DrawCongratsMessage__23tScreenPinkSlipCongrats
    /* 2BD8 800123D8 00000000 */ .word 0x00000000
    /* 2BDC 800123DC 648C0480 */ .word GetCar__23tScreenPinkSlipCongratsR8tCarInfo
enddlabel _vt_23tScreenPinkSlipCongrats

nonmatching _vt_23tScreenTournamentTrophy

dlabel _vt_23tScreenTournamentTrophy
    /* 2BE0 800123E0 00000000 */ .word 0x00000000
    /* 2BE4 800123E4 00000000 */ .word 0x00000000
    /* 2BE8 800123E8 00000000 */ .word 0x00000000
    /* 2BEC 800123EC 8C7E0480 */ .word GetShapeInfo__15tScreenCongratsRsT1PPcT3
    /* 2BF0 800123F0 00000000 */ .word 0x00000000
    /* 2BF4 800123F4 3C810480 */ .word DrawBackground__15tScreenCongrats
    /* 2BF8 800123F8 00000000 */ .word 0x00000000
    /* 2BFC 800123FC B0890480 */ .word DrawForeground__15tScreenCongrats
    /* 2C00 80012400 00000000 */ .word 0x00000000
    /* 2C04 80012404 00980480 */ .word ___23tScreenTournamentTrophy
    /* 2C08 80012408 00000000 */ .word 0x00000000
    /* 2C0C 8001240C 80670280 */ .word PreLoad__7tScreen
    /* 2C10 80012410 00000000 */ .word 0x00000000
    /* 2C14 80012414 2C8A0480 */ .word Initialize__15tScreenCongrats
    /* 2C18 80012418 00000000 */ .word 0x00000000
    /* 2C1C 8001241C 607E0480 */ .word Cleanup__15tScreenCongrats
    /* 2C20 80012420 00000000 */ .word 0x00000000
    /* 2C24 80012424 C0680280 */ .word TransitionIsFinished__7tScreen
    /* 2C28 80012428 00000000 */ .word 0x00000000
    /* 2C2C 8001242C 708E0480 */ .word ProcessInput__23tScreenTournamentTrophy7tPlayerR13tInputKeyTypeR12tMenuCommand
    /* 2C30 80012430 00000000 */ .word 0x00000000
    /* 2C34 80012434 3C920480 */ .word CalculatePrizes__23tScreenTournamentTrophy
    /* 2C38 80012438 00000000 */ .word 0x00000000
    /* 2C3C 8001243C 648F0480 */ .word DrawCongratsMessage__23tScreenTournamentTrophy
    /* 2C40 80012440 00000000 */ .word 0x00000000
    /* 2C44 80012444 B88E0480 */ .word GetCar__23tScreenTournamentTrophyR8tCarInfo
enddlabel _vt_23tScreenTournamentTrophy

nonmatching _vt_15tScreenCongrats

dlabel _vt_15tScreenCongrats
    /* 2C48 80012448 00000000 */ .word 0x00000000
    /* 2C4C 8001244C 00000000 */ .word 0x00000000
    /* 2C50 80012450 00000000 */ .word 0x00000000
    /* 2C54 80012454 8C7E0480 */ .word GetShapeInfo__15tScreenCongratsRsT1PPcT3
    /* 2C58 80012458 00000000 */ .word 0x00000000
    /* 2C5C 8001245C 3C810480 */ .word DrawBackground__15tScreenCongrats
    /* 2C60 80012460 00000000 */ .word 0x00000000
    /* 2C64 80012464 B0890480 */ .word DrawForeground__15tScreenCongrats
    /* 2C68 80012468 00000000 */ .word 0x00000000
    /* 2C6C 8001246C 20980480 */ .word ___15tScreenCongrats
    /* 2C70 80012470 00000000 */ .word 0x00000000
    /* 2C74 80012474 80670280 */ .word PreLoad__7tScreen
    /* 2C78 80012478 00000000 */ .word 0x00000000
    /* 2C7C 8001247C 2C8A0480 */ .word Initialize__15tScreenCongrats
    /* 2C80 80012480 00000000 */ .word 0x00000000
    /* 2C84 80012484 607E0480 */ .word Cleanup__15tScreenCongrats
    /* 2C88 80012488 00000000 */ .word 0x00000000
    /* 2C8C 8001248C C0680280 */ .word TransitionIsFinished__7tScreen
    /* 2C90 80012490 00000000 */ .word 0x00000000
    /* 2C94 80012494 F08A0480 */ .word ProcessInput__15tScreenCongrats7tPlayerR13tInputKeyTypeR12tMenuCommand
    /* 2C98 80012498 00000000 */ .word 0x00000000
    /* 2C9C 8001249C B8890480 */ .word CalculatePrizes__15tScreenCongrats
    /* 2CA0 800124A0 00000000 */ .word 0x00000000
    /* 2CA4 800124A4 54430E80 */ .word __pure_virtual
    /* 2CA8 800124A8 00000000 */ .word 0x00000000
    /* 2CAC 800124AC E4800480 */ .word GetCar__15tScreenCongratsR8tCarInfo
    /* 2CB0 800124B0 53696D70 */ .word 0x706D6953
    /* 2CB4 800124B4 6C654D65 */ .word 0x654D656C
    /* 2CB8 800124B8 6D000000 */ .word 0x0000006D
enddlabel _vt_15tScreenCongrats

.align 2
nonmatching D_800124BC

dlabel D_800124BC
    /* 2CBC 800124BC */ .asciz "ranklap"
    /* 72616E6B6C617000 */
.align 2
enddlabel D_800124BC

.align 2
nonmatching D_800124C4

dlabel D_800124C4
    /* 2CC4 800124C4 */ .asciz "rankbst"
    /* 72616E6B62737400 */
.align 2
enddlabel D_800124C4

nonmatching D_800124CC

dlabel D_800124CC
    /* 2CCC 800124CC 74726B72 */ .word 0x726B7274
    /* 2CD0 800124D0 63726473 */ .word 0x73647263
    /* 2CD4 800124D4 00000000 */ .word 0x00000000
enddlabel D_800124CC

nonmatching D_800124D8

dlabel D_800124D8
    /* 2CD8 800124D8 746F7072 */ .word 0x72706F74
    /* 2CDC 800124DC 63726473 */ .word 0x73647263
    /* 2CE0 800124E0 00000000 */ .word 0x00000000
enddlabel D_800124D8

nonmatching D_800124E4

dlabel D_800124E4
    /* 2CE4 800124E4 63617274 */ .word 0x74726163
    /* 2CE8 800124E8 74696D65 */ .word 0x656D6974
    /* 2CEC 800124EC 00000000 */ .word 0x00000000
enddlabel D_800124E4

nonmatching D_800124F0

dlabel D_800124F0
    /* 2CF0 800124F0 63617274 */ .word 0x74726163
    /* 2CF4 800124F4 74726E6B */ .word 0x6B6E7274
    /* 2CF8 800124F8 00000000 */ .word 0x00000000
enddlabel D_800124F0

.align 2
nonmatching D_800124FC

dlabel D_800124FC
    /* 2CFC 800124FC */ .asciz "records"
    /* 7265636F72647300 */
.align 2
.align 2
    /* 2D04 80012504 */ .asciz ""
    /* 00000000 */
.align 2
.align 2
    /* 2D08 80012508 */ .asciz "SimpleMem"
    /* 53696D706C654D656D000000 */
.align 2
enddlabel D_800124FC

.align 2
nonmatching D_80012514

dlabel D_80012514
    /* 2D14 80012514 */ .asciz "TempSort"
    /* 54656D70536F727400000000 */
.align 2
enddlabel D_80012514

.align 2
nonmatching D_80012520

dlabel D_80012520
    /* 2D20 80012520 */ .asciz "%02d%c%02d%c%02d"
    /* 2530326425632530326425632530326400000000 */
.align 2
.align 2
    /* 2D34 80012534 */ .asciz ""
    /* 00000000 */
.align 2
enddlabel D_80012520