.include "macro.inc"
/* W65-A5: residual segment of rdata_80054548 -- the non-jump-table blob records.
 * Linked by BOTH lanes. */

.section .rodata, "a"

/* Generated by spimdisasm 1.40.2 */


.align 2
nonmatching D_80056AAC

dlabel D_80056AAC
    /* 472AC 80056AAC */ .asciz "SimpleMem"
    /* 53696D706C654D656D000000 */
.align 2
enddlabel D_80056AAC

.align 2
nonmatching D_80056AB8

dlabel D_80056AB8
    /* 472B8 80056AB8 */ .asciz "%sTr%02d%s"
    /* 257354722530326425730000 */
.align 2
enddlabel D_80056AB8

.align 2
nonmatching D_80056AC4

dlabel D_80056AC4
    /* 472C4 80056AC4 */ .asciz "%sTr%02d.bin"
    /* 25735472253032642E62696E00000000 */
.align 2
enddlabel D_80056AC4

nonmatching D_80056AD4

dlabel D_80056AD4
    /* 472D4 80056AD4 00000000 */ .word 0x00000000
    /* 472D8 80056AD8 01000000 */ .word 0x00000001
    /* 472DC 80056ADC 02000000 */ .word 0x00000002
    /* 472E0 80056AE0 03000000 */ .word 0x00000003
    /* 472E4 80056AE4 53696D70 */ .word 0x706D6953
    /* 472E8 80056AE8 6C654D65 */ .word 0x654D656C
    /* 472EC 80056AEC 6D000000 */ .word 0x0000006D
    /* 472F0 80056AF0 53696D70 */ .word 0x706D6953
    /* 472F4 80056AF4 6C654D65 */ .word 0x654D656C
    /* 472F8 80056AF8 6D000000 */ .word 0x0000006D
enddlabel D_80056AD4

.align 2
nonmatching D_80056AFC

dlabel D_80056AFC
    /* 472FC 80056AFC */ .asciz "raindrop"
    /* 7261696E64726F7000000000 */
.align 2
enddlabel D_80056AFC

.align 2
nonmatching D_80056B08

dlabel D_80056B08
    /* 47308 80056B08 */ .asciz "weather1"
    /* 776561746865723100000000 */
.align 2
enddlabel D_80056B08

.align 2
nonmatching D_80056B14

dlabel D_80056B14
    /* 47314 80056B14 */ .asciz "weather2"
    /* 776561746865723200000000 */
.align 2
enddlabel D_80056B14

.align 2
nonmatching D_80056B20

dlabel D_80056B20
    /* 47320 80056B20 */ .asciz "weather3"
    /* 776561746865723300000000 */
.align 2
enddlabel D_80056B20

nonmatching D_80056B2C

dlabel D_80056B2C
    /* 4732C 80056B2C 00000000 */ .word 0x00000000
    /* 47330 80056B30 00000100 */ .word 0x00010000
    /* 47334 80056B34 00000000 */ .word 0x00000000
enddlabel D_80056B2C

.align 2
nonmatching D_80056B38

dlabel D_80056B38
    /* 47338 80056B38 */ .asciz "0123456789ABCDEF"
    /* 3031323334353637383941424344454600000000 */
.align 2
enddlabel D_80056B38

.align 2
nonmatching D_80056B4C

dlabel D_80056B4C
    /* 4734C 80056B4C */ .asciz "0123456789abcdef"
    /* 3031323334353637383961626364656600000000 */
.align 2
enddlabel D_80056B4C