.include "macro.inc"
/* ============================================================
 * W65-A5  THE .L LOCALIZE CUT -- SPLAT-LANE FILLER ONLY
 *
 * jtbl_8005699C: the retail jump table of a switch inside
 *     build/recon/game/psx/sfx.cpp.o
 * (retail 0x8005699c..0x800569d4, 14 entries).
 *
 * OWNERSHIP PROOF: word-for-word identical to the owner's own .rodata run at +0x0 (E5)
 *
 * The `.word .L<VA>` operands below are the SRC lane's local labels.  The
 * RECON lane must NOT link this file: the recon TU emits this very table into
 * its own `.rodata`, and no recon object defines a `.L<VA>` symbol, so
 * linking it here is exactly the 350-name undefined `.L` class.
 * It stays in the tree so the legacy splat-lane script (linkers/nfs4.ld,
 * which links build/src/**) keeps producing a byte-identical image.
 * ============================================================ */

.section .rodata, "a"

/* Generated by spimdisasm 1.40.2 */


nonmatching jtbl_8005699C

dlabel jtbl_8005699C
    /* 4719C 8005699C E8D70D80 */ .word .L800DD7E8
    /* 471A0 800569A0 04D80D80 */ .word .L800DD804
    /* 471A4 800569A4 50D80D80 */ .word .L800DD850
    /* 471A8 800569A8 74D80D80 */ .word .L800DD874
    /* 471AC 800569AC 1CE60D80 */ .word .L800DE61C
    /* 471B0 800569B0 0CDD0D80 */ .word .L800DDD0C
    /* 471B4 800569B4 ECDD0D80 */ .word .L800DDDEC
    /* 471B8 800569B8 30E10D80 */ .word .L800DE130
    /* 471BC 800569BC F4DE0D80 */ .word .L800DDEF4
    /* 471C0 800569C0 74DA0D80 */ .word .L800DDA74
    /* 471C4 800569C4 FCDF0D80 */ .word .L800DDFFC
    /* 471C8 800569C8 1CE60D80 */ .word .L800DE61C
    /* 471CC 800569CC C8E30D80 */ .word .L800DE3C8
    /* 471D0 800569D0 C8E30D80 */ .word .L800DE3C8
enddlabel jtbl_8005699C