.include "macro.inc"
/* ============================================================
 * W65-A5  THE .L LOCALIZE CUT -- SPLAT-LANE FILLER ONLY
 *
 * jtbl_800574F0: the retail jump table of a switch inside
 *     build/recon/eaclib/psx/eacpsxz/cluttype.c.o
 * (retail 0x800574f0..0x80057538, 18 entries).
 *
 * OWNERSHIP PROOF: word-for-word identical to the owner's own .rodata run at +0x0 (E5)
 *
 * The `.word .L<VA>` operands below are the SRC lane's local labels.  The
 * RECON lane must NOT link this file: the recon TU emits this very table into
 * its own `.rodata`, and no recon object defines a `.L<VA>` symbol, so
 * linking it here is exactly the 350-name undefined `.L` class.
 * It stays in the tree so the legacy splat-lane script (linkers/nfs4.ld,
 * which links build/src/**) keeps producing a byte-identical image.
 * ============================================================ */

.section .rodata, "a"

/* Generated by spimdisasm 1.40.2 */


.align 3
nonmatching jtbl_800574F0

dlabel jtbl_800574F0
    /* 47CF0 800574F0 80C20F80 */ .word .L800FC280
    /* 47CF4 800574F4 80C20F80 */ .word .L800FC280
    /* 47CF8 800574F8 8CC20F80 */ .word .L800FC28C
    /* 47CFC 800574FC 88C20F80 */ .word .L800FC288
    /* 47D00 80057500 8CC20F80 */ .word .L800FC28C
    /* 47D04 80057504 8CC20F80 */ .word .L800FC28C
    /* 47D08 80057508 8CC20F80 */ .word .L800FC28C
    /* 47D0C 8005750C 8CC20F80 */ .word .L800FC28C
    /* 47D10 80057510 8CC20F80 */ .word .L800FC28C
    /* 47D14 80057514 88C20F80 */ .word .L800FC288
    /* 47D18 80057518 8CC20F80 */ .word .L800FC28C
    /* 47D1C 8005751C 8CC20F80 */ .word .L800FC28C
    /* 47D20 80057520 8CC20F80 */ .word .L800FC28C
    /* 47D24 80057524 8CC20F80 */ .word .L800FC28C
    /* 47D28 80057528 8CC20F80 */ .word .L800FC28C
    /* 47D2C 8005752C 8CC20F80 */ .word .L800FC28C
    /* 47D30 80057530 8CC20F80 */ .word .L800FC28C
    /* 47D34 80057534 88C20F80 */ .word .L800FC288
enddlabel jtbl_800574F0