.include "macro.inc"
/* ============================================================
 * W65-A5  THE .L LOCALIZE CUT -- SPLAT-LANE FILLER ONLY
 *
 * jtbl_8005516C: the retail jump table of a switch inside
 *     build/recon/game/common/aih_cop.cpp.o
 * (retail 0x8005516c..0x80055198, 11 entries).
 *
 * OWNERSHIP PROOF: the owner's text window CONTAINS every target; its own table has drifted because the owning function is a near-miss (per-word diff: scratchpad/w65a5/jtbl_diag.txt)
 *
 * The `.word .L<VA>` operands below are the SRC lane's local labels.  The
 * RECON lane must NOT link this file: the recon TU emits this very table into
 * its own `.rodata`, and no recon object defines a `.L<VA>` symbol, so
 * linking it here is exactly the 350-name undefined `.L` class.
 * It stays in the tree so the legacy splat-lane script (linkers/nfs4.ld,
 * which links build/src/**) keeps producing a byte-identical image.
 * ============================================================ */

.section .rodata, "a"

/* Generated by spimdisasm 1.40.2 */


nonmatching jtbl_8005516C

dlabel jtbl_8005516C
    /* 4596C 8005516C 383D0680 */ .word .L80063D38
    /* 45970 80055170 283E0680 */ .word .L80063E28
    /* 45974 80055174 2C420680 */ .word .L8006422C
    /* 45978 80055178 D8480680 */ .word .L800648D8
    /* 4597C 8005517C 40440680 */ .word .L80064440
    /* 45980 80055180 18510680 */ .word .L80065118
    /* 45984 80055184 6C530680 */ .word .L8006536C
    /* 45988 80055188 6C530680 */ .word .L8006536C
    /* 4598C 8005518C 6C530680 */ .word .L8006536C
    /* 45990 80055190 FC520680 */ .word .L800652FC
    /* 45994 80055194 6C530680 */ .word .L8006536C
enddlabel jtbl_8005516C