.include "macro.inc"
/* ============================================================
 * W65-A5  THE .L LOCALIZE CUT -- SPLAT-LANE FILLER ONLY
 *
 * jtbl_80057968: the retail jump table of a switch inside
 *     build/recon/eaclib/psx/spchpsxz/spchrule.c.o
 * (retail 0x80057968..0x8005797c, 5 entries).
 *
 * OWNERSHIP PROOF: word-for-word identical to the owner's own .rodata run at +0x0 (E5)
 *
 * The `.word .L<VA>` operands below are the SRC lane's local labels.  The
 * RECON lane must NOT link this file: the recon TU emits this very table into
 * its own `.rodata`, and no recon object defines a `.L<VA>` symbol, so
 * linking it here is exactly the 350-name undefined `.L` class.
 * It stays in the tree so the legacy splat-lane script (linkers/nfs4.ld,
 * which links build/src/**) keeps producing a byte-identical image.
 * ============================================================ */

.section .rodata, "a"

/* Generated by spimdisasm 1.40.2 */


.align 3
nonmatching jtbl_80057968

dlabel jtbl_80057968
    /* 48168 80057968 58B31080 */ .word .L8010B358
    /* 4816C 8005796C 8CB31080 */ .word .L8010B38C
    /* 48170 80057970 8CB31080 */ .word .L8010B38C
    /* 48174 80057974 58B31080 */ .word .L8010B358
    /* 48178 80057978 8CB31080 */ .word .L8010B38C
enddlabel jtbl_80057968
