.include "macro.inc"
/* ============================================================
 * W65-A5  THE .L LOCALIZE CUT -- SPLAT-LANE FILLER ONLY
 *
 * jtbl_80055930: the retail jump table of a switch inside
 *     build/recon/game/common/camera.cpp.o
 * (retail 0x80055930..0x8005597c, 19 entries).
 *
 * OWNERSHIP PROOF: word-for-word identical to the owner's own .rodata run at +0x90 (E5)
 *
 * The `.word .L<VA>` operands below are the SRC lane's local labels.  The
 * RECON lane must NOT link this file: the recon TU emits this very table into
 * its own `.rodata`, and no recon object defines a `.L<VA>` symbol, so
 * linking it here is exactly the 350-name undefined `.L` class.
 * It stays in the tree so the legacy splat-lane script (linkers/nfs4.ld,
 * which links build/src/**) keeps producing a byte-identical image.
 * ============================================================ */

.section .rodata, "a"

/* Generated by spimdisasm 1.40.2 */


.align 3
nonmatching jtbl_80055930

dlabel jtbl_80055930
    /* 46130 80055930 2C550880 */ .word .L8008552C
    /* 46134 80055934 2C550880 */ .word .L8008552C
    /* 46138 80055938 2C550880 */ .word .L8008552C
    /* 4613C 8005593C 2C550880 */ .word .L8008552C
    /* 46140 80055940 2C550880 */ .word .L8008552C
    /* 46144 80055944 2C550880 */ .word .L8008552C
    /* 46148 80055948 2C550880 */ .word .L8008552C
    /* 4614C 8005594C 2C550880 */ .word .L8008552C
    /* 46150 80055950 2C550880 */ .word .L8008552C
    /* 46154 80055954 2C550880 */ .word .L8008552C
    /* 46158 80055958 2C550880 */ .word .L8008552C
    /* 4615C 8005595C 2C550880 */ .word .L8008552C
    /* 46160 80055960 24550880 */ .word .L80085524
    /* 46164 80055964 2C550880 */ .word .L8008552C
    /* 46168 80055968 24550880 */ .word .L80085524
    /* 4616C 8005596C 2C550880 */ .word .L8008552C
    /* 46170 80055970 2C550880 */ .word .L8008552C
    /* 46174 80055974 2C550880 */ .word .L8008552C
    /* 46178 80055978 2C550880 */ .word .L8008552C
enddlabel jtbl_80055930