.include "macro.inc"
/* W65-A5: residual segment of rdata_80010000 -- the non-jump-table blob records.
 * Linked by BOTH lanes. */

.section .rodata, "a"

/* Generated by spimdisasm 1.40.2 */

.align 2

nonmatching D_80010098

dlabel D_80010098
    /* 898 80010098 00000000 */ .word 0x00000000
    /* 89C 8001009C 00000000 */ .word 0x00000000
    /* 8A0 800100A0 00000000 */ .word 0x00000000
    /* 8A4 800100A4 08600280 */ .word GetShapeInfo__7tScreenRsT1PPcT3
    /* 8A8 800100A8 00000000 */ .word 0x00000000
    /* 8AC 800100AC E8680280 */ .word DrawBackground__7tScreen
    /* 8B0 800100B0 00000000 */ .word 0x00000000
    /* 8B4 800100B4 E0680280 */ .word DrawForeground__7tScreen
    /* 8B8 800100B8 00000000 */ .word 0x00000000
    /* 8BC 800100BC 60570180 */ .word ___31tDialogMessageStringWithTimeout
    /* 8C0 800100C0 00000000 */ .word 0x00000000
    /* 8C4 800100C4 80670280 */ .word PreLoad__7tScreen
    /* 8C8 800100C8 00000000 */ .word 0x00000000
    /* 8CC 800100CC AC600280 */ .word Initialize__7tScreen
    /* 8D0 800100D0 00000000 */ .word 0x00000000
    /* 8D4 800100D4 A0610280 */ .word Cleanup__7tScreen
    /* 8D8 800100D8 00000000 */ .word 0x00000000
    /* 8DC 800100DC C0680280 */ .word TransitionIsFinished__7tScreen
    /* 8E0 800100E0 00000000 */ .word 0x00000000
    /* 8E4 800100E4 C88A0180 */ .word ProcessInput__11tDialogBase7tPlayerR13tInputKeyTypeR12tMenuCommand
    /* 8E8 800100E8 00000000 */ .word 0x00000000
    /* 8EC 800100EC 18940180 */ .word CalculateDimensions__20tDialogMessageString
    /* 8F0 800100F0 00000000 */ .word 0x00000000
    /* 8F4 800100F4 2C960180 */ .word Draw__20tDialogMessageString
    /* 8F8 800100F8 53696D70 */ .word 0x706D6953
    /* 8FC 800100FC 6C654D65 */ .word 0x654D656C
    /* 900 80010100 6D000000 */ .word 0x0000006D
enddlabel D_80010098

.align 2
nonmatching D_80010104

dlabel D_80010104
    /* 904 80010104 */ .asciz "comHeader"
    /* 636F6D486561646572000000 */
.align 2
enddlabel D_80010104

.align 2
nonmatching D_80010110

dlabel D_80010110
    /* 910 80010110 */ .asciz "%c%02d"
    /* 2563253032640000 */
.align 2
enddlabel D_80010110

nonmatching D_80010118

dlabel D_80010118
    /* 918 80010118 25632563 */ .word 0x63256325
    /* 91C 8001011C 61000000 */ .word 0x00000061
enddlabel D_80010118

.align 2
nonmatching D_80010120

dlabel D_80010120
    /* 920 80010120 */ .asciz "streamBuffer"
    /* 73747265616D42756666657200000000 */
.align 2
enddlabel D_80010120

.align 2
nonmatching D_80010130

dlabel D_80010130
    /* 930 80010130 */ .asciz "lumpyhead"
    /* 6C756D707968656164000000 */
.align 2
.align 2
    /* 93C 8001013C */ .asciz "zEngl"
    /* 7A456E676C000000 */
.align 2
.align 2
    /* 944 80010144 */ .asciz "zGerm"
    /* 7A4765726D000000 */
.align 2
.align 2
    /* 94C 8001014C */ .asciz "zFren"
    /* 7A4672656E000000 */
.align 2
.align 2
    /* 954 80010154 */ .asciz "zSpan"
    /* 7A5370616E000000 */
.align 2
.align 2
    /* 95C 8001015C */ .asciz "zItal"
    /* 7A4974616C000000 */
.align 2
.align 2
    /* 964 80010164 */ .asciz "zSwed"
    /* 7A53776564000000 */
.align 2
enddlabel D_80010130

nonmatching D_8001016C

dlabel D_8001016C
    /* 96C 8001016C 30303000 */ .word 0x00303030
enddlabel D_8001016C

.align 2
nonmatching D_80010170

dlabel D_80010170
    /* 970 80010170 */ .asciz "%s%s.viv"
    /* 257325732E76697600000000 */
.align 2
.align 2
    /* 97C 8001017C */ .asciz ""
    /* 00000000 */
.align 2
enddlabel D_80010170

nonmatching D_80010180

dlabel D_80010180
    /* 980 80010180 21015301 */ .word 0x01530121
    /* 984 80010184 85010000 */ .word 0x00000185
    /* 988 80010188 16000000 */ .word 0x00000016
    /* 98C 8001018C 16000000 */ .word 0x00000016
    /* 990 80010190 19000000 */ .word 0x00000019
    /* 994 80010194 19000000 */ .word 0x00000019
    /* 998 80010198 1A000000 */ .word 0x0000001A
    /* 99C 8001019C 1B000000 */ .word 0x0000001B
    /* 9A0 800101A0 1B000000 */ .word 0x0000001B
    /* 9A4 800101A4 16000000 */ .word 0x00000016
    /* 9A8 800101A8 16000000 */ .word 0x00000016
    /* 9AC 800101AC 16000000 */ .word 0x00000016
    /* 9B0 800101B0 00000000 */ .word 0x00000000
enddlabel D_80010180

.align 2
nonmatching D_800101B4

dlabel D_800101B4
    /* 9B4 800101B4 */ .asciz "%s%s"
    /* 2573257300000000 */
.align 2
enddlabel D_800101B4

.align 2
nonmatching D_800101BC

dlabel D_800101BC
    /* 9BC 800101BC */ .asciz "fecars.car"
    /* 6665636172732E6361720000 */
.align 2
enddlabel D_800101BC

.align 2
nonmatching D_800101C8

dlabel D_800101C8
    /* 9C8 800101C8 */ .asciz "Car List"
    /* 436172204C69737400000000 */
.align 2
.align 2
    /* 9D4 800101D4 */ .asciz ""
    /* 00000000 */
.align 2
enddlabel D_800101C8

nonmatching _vt_21tListIteratorCarColor

dlabel _vt_21tListIteratorCarColor
    /* 9D8 800101D8 00000000 */ .word 0x00000000
    /* 9DC 800101DC 00000000 */ .word 0x00000000
    /* 9E0 800101E0 00000000 */ .word 0x00000000
    /* 9E4 800101E4 20850180 */ .word ___21tListIteratorCarColor
    /* 9E8 800101E8 00000000 */ .word 0x00000000
    /* 9EC 800101EC 48850180 */ .word Value__21tListIteratorCarColor7tPlayer
    /* 9F0 800101F0 00000000 */ .word 0x00000000
    /* 9F4 800101F4 A8850180 */ .word TextValue__21tListIteratorCarColor7tPlayer
    /* 9F8 800101F8 00000000 */ .word 0x00000000
    /* 9FC 800101FC B0850180 */ .word Increment__21tListIteratorCarColor7tPlayer
    /* A00 80010200 00000000 */ .word 0x00000000
    /* A04 80010204 48860180 */ .word Decrement__21tListIteratorCarColor7tPlayer
enddlabel _vt_21tListIteratorCarColor

nonmatching _vt_16tListIteratorCar

dlabel _vt_16tListIteratorCar
    /* A08 80010208 00000000 */ .word 0x00000000
    /* A0C 8001020C 00000000 */ .word 0x00000000
    /* A10 80010210 00000000 */ .word 0x00000000
    /* A14 80010214 28790180 */ .word ___16tListIteratorCar
    /* A18 80010218 00000000 */ .word 0x00000000
    /* A1C 8001021C 50790180 */ .word Value__16tListIteratorCar7tPlayer
    /* A20 80010220 00000000 */ .word 0x00000000
    /* A24 80010224 7C790180 */ .word TextValue__16tListIteratorCar7tPlayer
    /* A28 80010228 00000000 */ .word 0x00000000
    /* A2C 8001022C 94800180 */ .word Increment__16tListIteratorCar7tPlayer
    /* A30 80010230 00000000 */ .word 0x00000000
    /* A34 80010234 B4800180 */ .word Decrement__16tListIteratorCar7tPlayer
    /* A38 80010238 53696D70 */ .word 0x706D6953
    /* A3C 8001023C 6C654D65 */ .word 0x654D656C
    /* A40 80010240 6D000000 */ .word 0x0000006D
enddlabel _vt_16tListIteratorCar

nonmatching D_80010244

dlabel D_80010244
    /* A44 80010244 01000000 */ .word 0x00000001
    /* A48 80010248 00000000 */ .word 0x00000000
    /* A4C 8001024C 00000000 */ .word 0x00000000
    /* A50 80010250 00000000 */ .word 0x00000000
    /* A54 80010254 00000000 */ .word 0x00000000
enddlabel D_80010244