.include "macro.inc"
/* W65-A5: residual segment of rdata_80054548 -- the non-jump-table blob records.
 * Linked by BOTH lanes. */

.section .rodata, "a"

/* Generated by spimdisasm 1.40.2 */


.align 2
nonmatching D_800575B8

dlabel D_800575B8
    /* 47DB8 800575B8 */ .asciz "lockmutex - MUTEX IS ALREADY LOCKED.\n"
    /* 6C6F636B6D75746578202D204D5554455820495320414C5245414459204C4F434B45442E0A000000 */
.align 2
.align 2
    /* 47DE0 800575E0 */ .asciz "unlockmutex - MUTEX WAS NOT LOCKED.\n"
    /* 756E6C6F636B6D75746578202D204D5554455820574153204E4F54204C4F434B45442E0A00000000 */
.align 2
enddlabel D_800575B8

.align 2
nonmatching D_80057608

dlabel D_80057608
    /* 47E08 80057608 */ .asciz "DMA bus error: code=%08x\n"
    /* 444D4120627573206572726F723A20636F64653D253038780A000000 */
.align 2
enddlabel D_80057608

.align 2
nonmatching D_80057624

dlabel D_80057624
    /* 47E24 80057624 */ .asciz "MADR[%d]=%08x\n"
    /* 4D4144525B25645D3D253038780A0000 */
.align 2
.align 2
    /* 47E34 80057634 */ .asciz ""
    /* 00000000 */
.align 2
.align 2
    /* 47E38 80057638 */ .asciz "CdlReadS"
    /* 43646C526561645300000000 */
.align 2
.align 2
    /* 47E44 80057644 */ .asciz "CdlSeekP"
    /* 43646C5365656B5000000000 */
.align 2
.align 2
    /* 47E50 80057650 */ .asciz "CdlSeekL"
    /* 43646C5365656B4C00000000 */
.align 2
.align 2
    /* 47E5C 8005765C */ .asciz "CdlGetTD"
    /* 43646C476574544400000000 */
.align 2
.align 2
    /* 47E68 80057668 */ .asciz "CdlGetTN"
    /* 43646C476574544E00000000 */
.align 2
.align 2
    /* 47E74 80057674 */ .asciz "CdlGetlocP"
    /* 43646C4765746C6F63500000 */
.align 2
.align 2
    /* 47E80 80057680 */ .asciz "CdlGetlocL"
    /* 43646C4765746C6F634C0000 */
.align 2
.align 2
    /* 47E8C 8005768C */ .asciz "?"
    /* 3F000000 */
.align 2
.align 2
    /* 47E90 80057690 */ .asciz "CdlSetmode"
    /* 43646C5365746D6F64650000 */
.align 2
.align 2
    /* 47E9C 8005769C */ .asciz "CdlSetfilter"
    /* 43646C53657466696C74657200000000 */
.align 2
.align 2
    /* 47EAC 800576AC */ .asciz "CdlDemute"
    /* 43646C44656D757465000000 */
.align 2
.align 2
    /* 47EB8 800576B8 */ .asciz "CdlMute"
    /* 43646C4D75746500 */
.align 2
.align 2
    /* 47EC0 800576C0 */ .asciz "CdlReset"
    /* 43646C526573657400000000 */
.align 2
.align 2
    /* 47ECC 800576CC */ .asciz "CdlPause"
    /* 43646C506175736500000000 */
.align 2
.align 2
    /* 47ED8 800576D8 */ .asciz "CdlStop"
    /* 43646C53746F7000 */
.align 2
.align 2
    /* 47EE0 800576E0 */ .asciz "CdlStandby"
    /* 43646C5374616E6462790000 */
.align 2
.align 2
    /* 47EEC 800576EC */ .asciz "CdlReadN"
    /* 43646C526561644E00000000 */
.align 2
.align 2
    /* 47EF8 800576F8 */ .asciz "CdlBackward"
    /* 43646C4261636B7761726400 */
.align 2
.align 2
    /* 47F04 80057704 */ .asciz "CdlForward"
    /* 43646C466F72776172640000 */
.align 2
.align 2
    /* 47F10 80057710 */ .asciz "CdlPlay"
    /* 43646C506C617900 */
.align 2
.align 2
    /* 47F18 80057718 */ .asciz "CdlSetloc"
    /* 43646C5365746C6F63000000 */
.align 2
.align 2
    /* 47F24 80057724 */ .asciz "CdlNop"
    /* 43646C4E6F700000 */
.align 2
.align 2
    /* 47F2C 8005772C */ .asciz "CdlSync"
    /* 43646C53796E6300 */
.align 2
.align 2
    /* 47F34 80057734 */ .asciz "DiskError"
    /* 4469736B4572726F72000000 */
.align 2
.align 2
    /* 47F40 80057740 */ .asciz "DataEnd"
    /* 44617461456E6400 */
.align 2
.align 2
    /* 47F48 80057748 */ .asciz "Acknowledge"
    /* 41636B6E6F776C6564676500 */
.align 2
.align 2
    /* 47F54 80057754 */ .asciz "Complete"
    /* 436F6D706C65746500000000 */
.align 2
.align 2
    /* 47F60 80057760 */ .asciz "DataReady"
    /* 446174615265616479000000 */
.align 2
.align 2
    /* 47F6C 8005776C */ .asciz "NoIntr"
    /* 4E6F496E74720000 */
.align 2
enddlabel D_80057624

nonmatching D_80057774

dlabel D_80057774
    /* 47F74 80057774 43442074 */ .word 0x74204443
    /* 47F78 80057778 696D656F */ .word 0x6F656D69
    /* 47F7C 8005777C 75743A20 */ .word 0x203A7475
    /* 47F80 80057780 00000000 */ .word 0x00000000
enddlabel D_80057774

nonmatching D_80057784

dlabel D_80057784
    /* 47F84 80057784 25733A28 */ .word 0x283A7325
    /* 47F88 80057788 25732920 */ .word 0x20297325
    /* 47F8C 8005778C 53796E63 */ .word 0x636E7953
    /* 47F90 80057790 3D25732C */ .word 0x2C73253D
    /* 47F94 80057794 20526561 */ .word 0x61655220
    /* 47F98 80057798 64793D25 */ .word 0x253D7964
    /* 47F9C 8005779C 730A0000 */ .word 0x00000A73
enddlabel D_80057784

.align 2
nonmatching D_800577A0

dlabel D_800577A0
    /* 47FA0 800577A0 */ .asciz "DiskError: "
    /* 4469736B4572726F723A2000 */
.align 2
enddlabel D_800577A0

.align 2
nonmatching D_800577AC

dlabel D_800577AC
    /* 47FAC 800577AC */ .asciz "com=%s,code=(%02x:%02x)\n"
    /* 636F6D3D25732C636F64653D28253032783A25303278290A00000000 */
.align 2
enddlabel D_800577AC

.align 2
nonmatching D_800577C8

dlabel D_800577C8
    /* 47FC8 800577C8 */ .asciz "CDROM: unknown intr"
    /* 4344524F4D3A20756E6B6E6F776E20696E747200 */
.align 2
enddlabel D_800577C8

.align 2
nonmatching D_800577DC

dlabel D_800577DC
    /* 47FDC 800577DC */ .asciz "(%d)\n"
    /* 282564290A000000 */
.align 2
.align 2
    /* 47FE4 800577E4 */ .asciz ""
    /* 00000000 */
.align 2
enddlabel D_800577DC