.include "macro.inc"
/* W65-A5: residual segment of rdata_80010000 -- the non-jump-table blob records.
 * Linked by BOTH lanes. */

.section .rodata, "a"

/* Generated by spimdisasm 1.40.2 */

.align 2

.align 2
nonmatching D_800110A8

dlabel D_800110A8
    /* 18A8 800110A8 */ .asciz "SimpleMem"
    /* 53696D706C654D656D000000 */
.align 2
.align 2
    /* 18B4 800110B4 */ .asciz ""
    /* 00000000 */
.align 2
.align 2
    /* 18B8 800110B8 */ .asciz "SimpleMem"
    /* 53696D706C654D656D000000 */
.align 2
.align 2
    /* 18C4 800110C4 */ .asciz ""
    /* 00000000 */
.align 2
enddlabel D_800110A8

nonmatching _vt_5tMenu

dlabel _vt_5tMenu
    /* 18C8 800110C8 00000000 */ .word 0x00000000
    /* 18CC 800110CC 00000000 */ .word 0x00000000
    /* 18D0 800110D0 00000000 */ .word 0x00000000
    /* 18D4 800110D4 B0540280 */ .word ___5tMenu
    /* 18D8 800110D8 00000000 */ .word 0x00000000
    /* 18DC 800110DC E4540280 */ .word Initialize__5tMenu
    /* 18E0 800110E0 00000000 */ .word 0x00000000
    /* 18E4 800110E4 78550280 */ .word ProcessInput__5tMenu7tPlayerR13tInputKeyTypeR12tMenuCommand
    /* 18E8 800110E8 00000000 */ .word 0x00000000
    /* 18EC 800110EC 5C5A0280 */ .word DebounceKeys__5tMenu
    /* 18F0 800110F0 00000000 */ .word 0x00000000
    /* 18F4 800110F4 3C5A0280 */ .word TransitionOff__5tMenu
    /* 18F8 800110F8 00000000 */ .word 0x00000000
    /* 18FC 800110FC 445A0280 */ .word TransitionOn__5tMenu
    /* 1900 80011100 00000000 */ .word 0x00000000
    /* 1904 80011104 4C5A0280 */ .word TransitionIsFinished__5tMenu
    /* 1908 80011108 00000000 */ .word 0x00000000
    /* 190C 8001110C 545A0280 */ .word IsSubMenu__5tMenu
    /* 1910 80011110 00000000 */ .word 0x00000000
    /* 1914 80011114 FC580280 */ .word Draw__5tMenu
    /* 1918 80011118 00000000 */ .word 0x00000000
    /* 191C 8001111C A8590280 */ .word UpdateTransition__5tMenu
enddlabel _vt_5tMenu

nonmatching _vt_23tMenuItemGoToMenuButton

dlabel _vt_23tMenuItemGoToMenuButton
    /* 1920 80011120 00000000 */ .word 0x00000000
    /* 1924 80011124 00000000 */ .word 0x00000000
    /* 1928 80011128 00000000 */ .word 0x00000000
    /* 192C 8001112C 7C530280 */ .word ___23tMenuItemGoToMenuButton
    /* 1930 80011130 00000000 */ .word 0x00000000
    /* 1934 80011134 98470280 */ .word DebounceKeys__9tMenuItem
    /* 1938 80011138 00000000 */ .word 0x00000000
    /* 193C 8001113C A4530280 */ .word ProcessInput__23tMenuItemGoToMenuButton7tPlayerR13tInputKeyTypeR12tMenuCommand
    /* 1940 80011140 00000000 */ .word 0x00000000
    /* 1944 80011144 54430E80 */ .word __pure_virtual
    /* 1948 80011148 00000000 */ .word 0x00000000
    /* 194C 8001114C 28480280 */ .word Draw__9tMenuItemiib
    /* 1950 80011150 00000000 */ .word 0x00000000
    /* 1954 80011154 64480280 */ .word Draw__9tMenuItemiiib
    /* 1958 80011158 00000000 */ .word 0x00000000
    /* 195C 8001115C B05A0280 */ .word TransitionOff__9tMenuItem
    /* 1960 80011160 00000000 */ .word 0x00000000
    /* 1964 80011164 A85A0280 */ .word TransitionOn__9tMenuItem
    /* 1968 80011168 00000000 */ .word 0x00000000
    /* 196C 8001116C C8470280 */ .word TransitionIsFinished__9tMenuItem
    /* 1970 80011170 00000000 */ .word 0x00000000
    /* 1974 80011174 A8470280 */ .word UpdateTransition__9tMenuItemb
enddlabel _vt_23tMenuItemGoToMenuButton

nonmatching _vt_24tMenuItemLeftRightSlider

dlabel _vt_24tMenuItemLeftRightSlider
    /* 1978 80011178 00000000 */ .word 0x00000000
    /* 197C 8001117C 00000000 */ .word 0x00000000
    /* 1980 80011180 00000000 */ .word 0x00000000
    /* 1984 80011184 544B0280 */ .word ___24tMenuItemLeftRightSlider
    /* 1988 80011188 00000000 */ .word 0x00000000
    /* 198C 8001118C 7C4B0280 */ .word DebounceKeys__24tMenuItemLeftRightSlider
    /* 1990 80011190 00000000 */ .word 0x00000000
    /* 1994 80011194 844B0280 */ .word ProcessInput__24tMenuItemLeftRightSlider7tPlayerR13tInputKeyTypeR12tMenuCommand
    /* 1998 80011198 00000000 */ .word 0x00000000
    /* 199C 8001119C E4510280 */ .word Draw__24tMenuItemLeftRightSliderb
    /* 19A0 800111A0 00000000 */ .word 0x00000000
    /* 19A4 800111A4 28480280 */ .word Draw__9tMenuItemiib
    /* 19A8 800111A8 00000000 */ .word 0x00000000
    /* 19AC 800111AC 64480280 */ .word Draw__9tMenuItemiiib
    /* 19B0 800111B0 00000000 */ .word 0x00000000
    /* 19B4 800111B4 B05A0280 */ .word TransitionOff__9tMenuItem
    /* 19B8 800111B8 00000000 */ .word 0x00000000
    /* 19BC 800111BC A85A0280 */ .word TransitionOn__9tMenuItem
    /* 19C0 800111C0 00000000 */ .word 0x00000000
    /* 19C4 800111C4 C8470280 */ .word TransitionIsFinished__9tMenuItem
    /* 19C8 800111C8 00000000 */ .word 0x00000000
    /* 19CC 800111CC A8470280 */ .word UpdateTransition__9tMenuItemb
enddlabel _vt_24tMenuItemLeftRightSlider

nonmatching _vt_24tMenuItemLeftRightChoice

dlabel _vt_24tMenuItemLeftRightChoice
    /* 19D0 800111D0 00000000 */ .word 0x00000000
    /* 19D4 800111D4 00000000 */ .word 0x00000000
    /* 19D8 800111D8 00000000 */ .word 0x00000000
    /* 19DC 800111DC 54490280 */ .word ___24tMenuItemLeftRightChoice
    /* 19E0 800111E0 00000000 */ .word 0x00000000
    /* 19E4 800111E4 98470280 */ .word DebounceKeys__9tMenuItem
    /* 19E8 800111E8 00000000 */ .word 0x00000000
    /* 19EC 800111EC 7C490280 */ .word ProcessInput__24tMenuItemLeftRightChoice7tPlayerR13tInputKeyTypeR12tMenuCommand
    /* 19F0 800111F0 00000000 */ .word 0x00000000
    /* 19F4 800111F4 2C4A0280 */ .word Draw__24tMenuItemLeftRightChoiceb
    /* 19F8 800111F8 00000000 */ .word 0x00000000
    /* 19FC 800111FC 28480280 */ .word Draw__9tMenuItemiib
    /* 1A00 80011200 00000000 */ .word 0x00000000
    /* 1A04 80011204 64480280 */ .word Draw__9tMenuItemiiib
    /* 1A08 80011208 00000000 */ .word 0x00000000
    /* 1A0C 8001120C B05A0280 */ .word TransitionOff__9tMenuItem
    /* 1A10 80011210 00000000 */ .word 0x00000000
    /* 1A14 80011214 A85A0280 */ .word TransitionOn__9tMenuItem
    /* 1A18 80011218 00000000 */ .word 0x00000000
    /* 1A1C 8001121C C8470280 */ .word TransitionIsFinished__9tMenuItem
    /* 1A20 80011220 00000000 */ .word 0x00000000
    /* 1A24 80011224 A8470280 */ .word UpdateTransition__9tMenuItemb
enddlabel _vt_24tMenuItemLeftRightChoice

nonmatching _vt_20tMenuItemInteractive

dlabel _vt_20tMenuItemInteractive
    /* 1A28 80011228 00000000 */ .word 0x00000000
    /* 1A2C 8001122C 00000000 */ .word 0x00000000
    /* 1A30 80011230 00000000 */ .word 0x00000000
    /* 1A34 80011234 DC480280 */ .word ___20tMenuItemInteractive
    /* 1A38 80011238 00000000 */ .word 0x00000000
    /* 1A3C 8001123C 98470280 */ .word DebounceKeys__9tMenuItem
    /* 1A40 80011240 00000000 */ .word 0x00000000
    /* 1A44 80011244 A0470280 */ .word ProcessInput__9tMenuItem7tPlayerR13tInputKeyTypeR12tMenuCommand
    /* 1A48 80011248 00000000 */ .word 0x00000000
    /* 1A4C 8001124C 54430E80 */ .word __pure_virtual
    /* 1A50 80011250 00000000 */ .word 0x00000000
    /* 1A54 80011254 28480280 */ .word Draw__9tMenuItemiib
    /* 1A58 80011258 00000000 */ .word 0x00000000
    /* 1A5C 8001125C 64480280 */ .word Draw__9tMenuItemiiib
    /* 1A60 80011260 00000000 */ .word 0x00000000
    /* 1A64 80011264 B05A0280 */ .word TransitionOff__9tMenuItem
    /* 1A68 80011268 00000000 */ .word 0x00000000
    /* 1A6C 8001126C A85A0280 */ .word TransitionOn__9tMenuItem
    /* 1A70 80011270 00000000 */ .word 0x00000000
    /* 1A74 80011274 C8470280 */ .word TransitionIsFinished__9tMenuItem
    /* 1A78 80011278 00000000 */ .word 0x00000000
    /* 1A7C 8001127C A8470280 */ .word UpdateTransition__9tMenuItemb
enddlabel _vt_20tMenuItemInteractive

nonmatching _vt_9tMenuItem

dlabel _vt_9tMenuItem
    /* 1A80 80011280 00000000 */ .word 0x00000000
    /* 1A84 80011284 00000000 */ .word 0x00000000
    /* 1A88 80011288 00000000 */ .word 0x00000000
    /* 1A8C 8001128C 64470280 */ .word ___9tMenuItem
    /* 1A90 80011290 00000000 */ .word 0x00000000
    /* 1A94 80011294 98470280 */ .word DebounceKeys__9tMenuItem
    /* 1A98 80011298 00000000 */ .word 0x00000000
    /* 1A9C 8001129C A0470280 */ .word ProcessInput__9tMenuItem7tPlayerR13tInputKeyTypeR12tMenuCommand
    /* 1AA0 800112A0 00000000 */ .word 0x00000000
    /* 1AA4 800112A4 54430E80 */ .word __pure_virtual
    /* 1AA8 800112A8 00000000 */ .word 0x00000000
    /* 1AAC 800112AC 28480280 */ .word Draw__9tMenuItemiib
    /* 1AB0 800112B0 00000000 */ .word 0x00000000
    /* 1AB4 800112B4 64480280 */ .word Draw__9tMenuItemiiib
    /* 1AB8 800112B8 00000000 */ .word 0x00000000
    /* 1ABC 800112BC B05A0280 */ .word TransitionOff__9tMenuItem
    /* 1AC0 800112C0 00000000 */ .word 0x00000000
    /* 1AC4 800112C4 A85A0280 */ .word TransitionOn__9tMenuItem
    /* 1AC8 800112C8 00000000 */ .word 0x00000000
    /* 1ACC 800112CC C8470280 */ .word TransitionIsFinished__9tMenuItem
    /* 1AD0 800112D0 00000000 */ .word 0x00000000
    /* 1AD4 800112D4 A8470280 */ .word UpdateTransition__9tMenuItemb
enddlabel _vt_9tMenuItem

nonmatching _vt_25tListIteratorRangeIndexed

dlabel _vt_25tListIteratorRangeIndexed
    /* 1AD8 800112D8 00000000 */ .word 0x00000000
    /* 1ADC 800112DC 00000000 */ .word 0x00000000
    /* 1AE0 800112E0 00000000 */ .word 0x00000000
    /* 1AE4 800112E4 70460280 */ .word ___25tListIteratorRangeIndexed
    /* 1AE8 800112E8 00000000 */ .word 0x00000000
    /* 1AEC 800112EC 98460280 */ .word Value__25tListIteratorRangeIndexed7tPlayer
    /* 1AF0 800112F0 00000000 */ .word 0x00000000
    /* 1AF4 800112F4 CC450280 */ .word TextValue__18tListIteratorRange7tPlayer
    /* 1AF8 800112F8 00000000 */ .word 0x00000000
    /* 1AFC 800112FC BC460280 */ .word Increment__25tListIteratorRangeIndexed7tPlayer
    /* 1B00 80011300 00000000 */ .word 0x00000000
    /* 1B04 80011304 F8460280 */ .word Decrement__25tListIteratorRangeIndexed7tPlayer
enddlabel _vt_25tListIteratorRangeIndexed

nonmatching _vt_18tListIteratorRange

dlabel _vt_18tListIteratorRange
    /* 1B08 80011308 00000000 */ .word 0x00000000
    /* 1B0C 8001130C 00000000 */ .word 0x00000000
    /* 1B10 80011310 00000000 */ .word 0x00000000
    /* 1B14 80011314 90450280 */ .word ___18tListIteratorRange
    /* 1B18 80011318 00000000 */ .word 0x00000000
    /* 1B1C 8001131C B8450280 */ .word Value__18tListIteratorRange7tPlayer
    /* 1B20 80011320 00000000 */ .word 0x00000000
    /* 1B24 80011324 CC450280 */ .word TextValue__18tListIteratorRange7tPlayer
    /* 1B28 80011328 00000000 */ .word 0x00000000
    /* 1B2C 8001132C D4450280 */ .word Increment__18tListIteratorRange7tPlayer
    /* 1B30 80011330 00000000 */ .word 0x00000000
    /* 1B34 80011334 FC450280 */ .word Decrement__18tListIteratorRange7tPlayer
enddlabel _vt_18tListIteratorRange

nonmatching _vt_24tListIteratorMultiPlayer

dlabel _vt_24tListIteratorMultiPlayer
    /* 1B38 80011338 00000000 */ .word 0x00000000
    /* 1B3C 8001133C 00000000 */ .word 0x00000000
    /* 1B40 80011340 00000000 */ .word 0x00000000
    /* 1B44 80011344 90430280 */ .word ___24tListIteratorMultiPlayer
    /* 1B48 80011348 00000000 */ .word 0x00000000
    /* 1B4C 8001134C B8430280 */ .word Value__24tListIteratorMultiPlayer7tPlayer
    /* 1B50 80011350 00000000 */ .word 0x00000000
    /* 1B54 80011354 E0430280 */ .word TextValue__24tListIteratorMultiPlayer7tPlayer
    /* 1B58 80011358 00000000 */ .word 0x00000000
    /* 1B5C 8001135C 30440280 */ .word Increment__24tListIteratorMultiPlayer7tPlayer
    /* 1B60 80011360 00000000 */ .word 0x00000000
    /* 1B64 80011364 94440280 */ .word Decrement__24tListIteratorMultiPlayer7tPlayer
enddlabel _vt_24tListIteratorMultiPlayer

nonmatching _vt_26tListIteratorDoubleIndexed

dlabel _vt_26tListIteratorDoubleIndexed
    /* 1B68 80011368 00000000 */ .word 0x00000000
    /* 1B6C 8001136C 00000000 */ .word 0x00000000
    /* 1B70 80011370 00000000 */ .word 0x00000000
    /* 1B74 80011374 54410280 */ .word ___26tListIteratorDoubleIndexed
    /* 1B78 80011378 00000000 */ .word 0x00000000
    /* 1B7C 8001137C 7C410280 */ .word Value__26tListIteratorDoubleIndexed7tPlayer
    /* 1B80 80011380 00000000 */ .word 0x00000000
    /* 1B84 80011384 B8410280 */ .word TextValue__26tListIteratorDoubleIndexed7tPlayer
    /* 1B88 80011388 00000000 */ .word 0x00000000
    /* 1B8C 8001138C 08420280 */ .word Increment__26tListIteratorDoubleIndexed7tPlayer
    /* 1B90 80011390 00000000 */ .word 0x00000000
    /* 1B94 80011394 A4420280 */ .word Decrement__26tListIteratorDoubleIndexed7tPlayer
enddlabel _vt_26tListIteratorDoubleIndexed

nonmatching _vt_20tListIteratorIndexed

dlabel _vt_20tListIteratorIndexed
    /* 1B98 80011398 00000000 */ .word 0x00000000
    /* 1B9C 8001139C 00000000 */ .word 0x00000000
    /* 1BA0 800113A0 00000000 */ .word 0x00000000
    /* 1BA4 800113A4 A43F0280 */ .word ___20tListIteratorIndexed
    /* 1BA8 800113A8 00000000 */ .word 0x00000000
    /* 1BAC 800113AC CC3F0280 */ .word Value__20tListIteratorIndexed7tPlayer
    /* 1BB0 800113B0 00000000 */ .word 0x00000000
    /* 1BB4 800113B4 F03F0280 */ .word TextValue__20tListIteratorIndexed7tPlayer
    /* 1BB8 800113B8 00000000 */ .word 0x00000000
    /* 1BBC 800113BC 40400280 */ .word Increment__20tListIteratorIndexed7tPlayer
    /* 1BC0 800113C0 00000000 */ .word 0x00000000
    /* 1BC4 800113C4 A8400280 */ .word Decrement__20tListIteratorIndexed7tPlayer
enddlabel _vt_20tListIteratorIndexed

nonmatching _vt_13tListIterator

dlabel _vt_13tListIterator
    /* 1BC8 800113C8 00000000 */ .word 0x00000000
    /* 1BCC 800113CC 00000000 */ .word 0x00000000
    /* 1BD0 800113D0 00000000 */ .word 0x00000000
    /* 1BD4 800113D4 F43D0280 */ .word ___13tListIterator
    /* 1BD8 800113D8 00000000 */ .word 0x00000000
    /* 1BDC 800113DC 283E0280 */ .word Value__13tListIterator7tPlayer
    /* 1BE0 800113E0 00000000 */ .word 0x00000000
    /* 1BE4 800113E4 3C3E0280 */ .word TextValue__13tListIterator7tPlayer
    /* 1BE8 800113E8 00000000 */ .word 0x00000000
    /* 1BEC 800113EC 8C3E0280 */ .word Increment__13tListIterator7tPlayer
    /* 1BF0 800113F0 00000000 */ .word 0x00000000
    /* 1BF4 800113F4 D83E0280 */ .word Decrement__13tListIterator7tPlayer
enddlabel _vt_13tListIterator

.align 2
nonmatching D_800113F8

dlabel D_800113F8
    /* 1BF8 800113F8 */ .asciz "z%s"
    /* 7A257300 */
.align 2
enddlabel D_800113F8

.align 2
nonmatching D_800113FC

dlabel D_800113FC
    /* 1BFC 800113FC */ .asciz "%s"
    /* 25730000 */
.align 2
enddlabel D_800113FC

.align 2
nonmatching D_80011400

dlabel D_80011400
    /* 1C00 80011400 */ .asciz "%s%s.psh"
    /* 257325732E70736800000000 */
.align 2
enddlabel D_80011400

.align 2
nonmatching D_8001140C

dlabel D_8001140C
    /* 1C0C 8001140C */ .asciz "Shapes"
    /* 5368617065730000 */
.align 2
.align 2
    /* 1C14 80011414 */ .asciz ""
    /* 00000000 */
.align 2
enddlabel D_8001140C

nonmatching _vt_7tScreen

dlabel _vt_7tScreen
    /* 1C18 80011418 00000000 */ .word 0x00000000
    /* 1C1C 8001141C 00000000 */ .word 0x00000000
    /* 1C20 80011420 00000000 */ .word 0x00000000
    /* 1C24 80011424 08600280 */ .word GetShapeInfo__7tScreenRsT1PPcT3
    /* 1C28 80011428 00000000 */ .word 0x00000000
    /* 1C2C 8001142C E8680280 */ .word DrawBackground__7tScreen
    /* 1C30 80011430 00000000 */ .word 0x00000000
    /* 1C34 80011434 E0680280 */ .word DrawForeground__7tScreen
    /* 1C38 80011438 00000000 */ .word 0x00000000
    /* 1C3C 8001143C 78600280 */ .word ___7tScreen
    /* 1C40 80011440 00000000 */ .word 0x00000000
    /* 1C44 80011444 80670280 */ .word PreLoad__7tScreen
    /* 1C48 80011448 00000000 */ .word 0x00000000
    /* 1C4C 8001144C AC600280 */ .word Initialize__7tScreen
    /* 1C50 80011450 00000000 */ .word 0x00000000
    /* 1C54 80011454 A0610280 */ .word Cleanup__7tScreen
    /* 1C58 80011458 00000000 */ .word 0x00000000
    /* 1C5C 8001145C C0680280 */ .word TransitionIsFinished__7tScreen
    /* 1C60 80011460 00000000 */ .word 0x00000000
    /* 1C64 80011464 D8680280 */ .word ProcessInput__7tScreen7tPlayerR13tInputKeyTypeR12tMenuCommand
    /* 1C68 80011468 53696D70 */ .word 0x706D6953
    /* 1C6C 8001146C 6C654D65 */ .word 0x654D656C
    /* 1C70 80011470 6D000000 */ .word 0x0000006D
enddlabel _vt_7tScreen

.align 2
nonmatching D_80011474

dlabel D_80011474
    /* 1C74 80011474 */ .asciz "%stiny.pfn"
    /* 257374696E792E70666E0000 */
.align 2
enddlabel D_80011474

.align 2
nonmatching D_80011480

dlabel D_80011480
    /* 1C80 80011480 */ .asciz "%ssmall.pfn"
    /* 2573736D616C6C2E70666E00 */
.align 2
enddlabel D_80011480

.align 2
nonmatching D_8001148C

dlabel D_8001148C
    /* 1C8C 8001148C */ .asciz "%stitle.pfn"
    /* 25737469746C652E70666E00 */
.align 2
.align 2
    /* 1C98 80011498 */ .asciz "SimpleMem"
    /* 53696D706C654D656D000000 */
.align 2
enddlabel D_8001148C

.align 2
nonmatching D_800114A4

dlabel D_800114A4
    /* 1CA4 800114A4 */ .asciz "%szzFE.viv"
    /* 25737A7A46452E7669760000 */
.align 2
enddlabel D_800114A4

.align 2
nonmatching D_800114B0

dlabel D_800114B0
    /* 1CB0 800114B0 */ .asciz "ymus"
    /* 796D757300000000 */
.align 2
enddlabel D_800114B0

.align 2
nonmatching D_800114B8

dlabel D_800114B8
    /* 1CB8 800114B8 */ .asciz "game*"
    /* 67616D652A000000 */
.align 2
enddlabel D_800114B8

.align 2
nonmatching D_800114C0

dlabel D_800114C0
    /* 1CC0 800114C0 */ .asciz "amus"
    /* 616D757300000000 */
.align 2
.align 2
    /* 1CC8 800114C8 */ .asciz "SimpleMem"
    /* 53696D706C654D656D000000 */
.align 2
.align 2
    /* 1CD4 800114D4 */ .asciz ""
    /* 00000000 */
.align 2
enddlabel D_800114C0

nonmatching D_800114D8

dlabel D_800114D8
    /* 1CD8 800114D8 00000000 */ .word 0x00000000
    /* 1CDC 800114DC 00000000 */ .word 0x00000000
    /* 1CE0 800114E0 00000000 */ .word 0x00000000
    /* 1CE4 800114E4 D8210380 */ .word ___32tBlankMenuItemGoToMenuNFS4Button
    /* 1CE8 800114E8 00000000 */ .word 0x00000000
    /* 1CEC 800114EC 98470280 */ .word DebounceKeys__9tMenuItem
    /* 1CF0 800114F0 00000000 */ .word 0x00000000
    /* 1CF4 800114F4 A4530280 */ .word ProcessInput__23tMenuItemGoToMenuButton7tPlayerR13tInputKeyTypeR12tMenuCommand
    /* 1CF8 800114F8 00000000 */ .word 0x00000000
    /* 1CFC 800114FC D0210380 */ .word Draw__32tBlankMenuItemGoToMenuNFS4Buttonb
    /* 1D00 80011500 00000000 */ .word 0x00000000
    /* 1D04 80011504 C8210380 */ .word Draw__32tBlankMenuItemGoToMenuNFS4Buttoniib
    /* 1D08 80011508 00000000 */ .word 0x00000000
    /* 1D0C 8001150C 64480280 */ .word Draw__9tMenuItemiiib
    /* 1D10 80011510 00000000 */ .word 0x00000000
    /* 1D14 80011514 C8A70180 */ .word TransitionOff__27tMenuItemGoToMenuNFS4Button
    /* 1D18 80011518 00000000 */ .word 0x00000000
    /* 1D1C 8001151C B8A70180 */ .word TransitionOn__27tMenuItemGoToMenuNFS4Button
    /* 1D20 80011520 00000000 */ .word 0x00000000
    /* 1D24 80011524 C0210380 */ .word TransitionIsFinished__32tBlankMenuItemGoToMenuNFS4Button
    /* 1D28 80011528 00000000 */ .word 0x00000000
    /* 1D2C 8001152C E0A70180 */ .word UpdateTransition__27tMenuItemGoToMenuNFS4Buttonb
enddlabel D_800114D8

nonmatching D_80011530

dlabel D_80011530
    /* 1D30 80011530 00000000 */ .word 0x00000000
    /* 1D34 80011534 00000000 */ .word 0x00000000
    /* 1D38 80011538 00000000 */ .word 0x00000000
    /* 1D3C 8001153C 08220380 */ .word ___33tBlankMenuItemNFS4LeftRightChoice
    /* 1D40 80011540 00000000 */ .word 0x00000000
    /* 1D44 80011544 98470280 */ .word DebounceKeys__9tMenuItem
    /* 1D48 80011548 00000000 */ .word 0x00000000
    /* 1D4C 8001154C 7C490280 */ .word ProcessInput__24tMenuItemLeftRightChoice7tPlayerR13tInputKeyTypeR12tMenuCommand
    /* 1D50 80011550 00000000 */ .word 0x00000000
    /* 1D54 80011554 2C4A0280 */ .word Draw__24tMenuItemLeftRightChoiceb
    /* 1D58 80011558 00000000 */ .word 0x00000000
    /* 1D5C 8001155C 00220380 */ .word Draw__33tBlankMenuItemNFS4LeftRightChoiceiib
    /* 1D60 80011560 00000000 */ .word 0x00000000
    /* 1D64 80011564 64480280 */ .word Draw__9tMenuItemiiib
    /* 1D68 80011568 00000000 */ .word 0x00000000
    /* 1D6C 8001156C 6CAB0180 */ .word TransitionOff__28tMenuItemNFS4LeftRightChoice
    /* 1D70 80011570 00000000 */ .word 0x00000000
    /* 1D74 80011574 5CAB0180 */ .word TransitionOn__28tMenuItemNFS4LeftRightChoice
    /* 1D78 80011578 00000000 */ .word 0x00000000
    /* 1D7C 8001157C F8210380 */ .word TransitionIsFinished__33tBlankMenuItemNFS4LeftRightChoice
    /* 1D80 80011580 00000000 */ .word 0x00000000
    /* 1D84 80011584 84AB0180 */ .word UpdateTransition__28tMenuItemNFS4LeftRightChoiceb
    /* 1D88 80011588 53696D70 */ .word 0x706D6953
    /* 1D8C 8001158C 6C654D65 */ .word 0x654D656C
    /* 1D90 80011590 6D000000 */ .word 0x0000006D
enddlabel D_80011530

.align 2
nonmatching D_80011594

dlabel D_80011594
    /* 1D94 80011594 */ .asciz "%s%s"
    /* 2573257300000000 */
.align 2
enddlabel D_80011594

.align 2
nonmatching D_8001159C

dlabel D_8001159C
    /* 1D9C 8001159C */ .asciz "tourn.trn"
    /* 746F75726E2E74726E000000 */
.align 2
enddlabel D_8001159C

.align 2
nonmatching D_800115A8

dlabel D_800115A8
    /* 1DA8 800115A8 */ .asciz "Tourney"
    /* 546F75726E657900 */
.align 2
enddlabel D_800115A8

nonmatching D_800115B0

dlabel D_800115B0
    /* 1DB0 800115B0 1E050000 */ .word 0x0000051E
    /* 1DB4 800115B4 1E050000 */ .word 0x0000051E
    /* 1DB8 800115B8 1E050000 */ .word 0x0000051E
    /* 1DBC 800115BC 1E050000 */ .word 0x0000051E
    /* 1DC0 800115C0 1E050000 */ .word 0x0000051E
    /* 1DC4 800115C4 1E050000 */ .word 0x0000051E
    /* 1DC8 800115C8 1E050000 */ .word 0x0000051E
    /* 1DCC 800115CC 1E050000 */ .word 0x0000051E
    /* 1DD0 800115D0 1E050000 */ .word 0x0000051E
    /* 1DD4 800115D4 1E050000 */ .word 0x0000051E
    /* 1DD8 800115D8 1E050000 */ .word 0x0000051E
    /* 1DDC 800115DC 1E050000 */ .word 0x0000051E
    /* 1DE0 800115E0 AE070000 */ .word 0x000007AE
    /* 1DE4 800115E4 AE070000 */ .word 0x000007AE
    /* 1DE8 800115E8 AE070000 */ .word 0x000007AE
    /* 1DEC 800115EC AE070000 */ .word 0x000007AE
    /* 1DF0 800115F0 AE070000 */ .word 0x000007AE
    /* 1DF4 800115F4 AE070000 */ .word 0x000007AE
    /* 1DF8 800115F8 3D0A0000 */ .word 0x00000A3D
    /* 1DFC 800115FC 3D0A0000 */ .word 0x00000A3D
    /* 1E00 80011600 3D0A0000 */ .word 0x00000A3D
    /* 1E04 80011604 3D0A0000 */ .word 0x00000A3D
    /* 1E08 80011608 3D0A0000 */ .word 0x00000A3D
    /* 1E0C 8001160C 3D0A0000 */ .word 0x00000A3D
    /* 1E10 80011610 AE070000 */ .word 0x000007AE
    /* 1E14 80011614 AE070000 */ .word 0x000007AE
    /* 1E18 80011618 AE070000 */ .word 0x000007AE
    /* 1E1C 8001161C AE070000 */ .word 0x000007AE
    /* 1E20 80011620 AE070000 */ .word 0x000007AE
    /* 1E24 80011624 AE070000 */ .word 0x000007AE
    /* 1E28 80011628 AE070000 */ .word 0x000007AE
    /* 1E2C 8001162C AE070000 */ .word 0x000007AE
    /* 1E30 80011630 AE070000 */ .word 0x000007AE
    /* 1E34 80011634 AE070000 */ .word 0x000007AE
    /* 1E38 80011638 AE070000 */ .word 0x000007AE
    /* 1E3C 8001163C AE070000 */ .word 0x000007AE
    /* 1E40 80011640 AE070000 */ .word 0x000007AE
    /* 1E44 80011644 AE070000 */ .word 0x000007AE
    /* 1E48 80011648 AE070000 */ .word 0x000007AE
    /* 1E4C 8001164C AE070000 */ .word 0x000007AE
    /* 1E50 80011650 AE070000 */ .word 0x000007AE
    /* 1E54 80011654 AE070000 */ .word 0x000007AE
enddlabel D_800115B0

.align 2
nonmatching D_80011658

dlabel D_80011658
    /* 1E58 80011658 */ .asciz "SML"
    /* 534D4C00 */
.align 2
enddlabel D_80011658

nonmatching D_8001165C

dlabel D_8001165C
    /* 1E5C 8001165C 57475342 */ .word 0x42534757
enddlabel D_8001165C

.align 2
nonmatching D_80011660

dlabel D_80011660
    /* 1E60 80011660 */ .asciz "TR%c%02d%c"
    /* 545225632530326425630000 */
.align 2
.align 2
    /* 1E6C 8001166C */ .asciz ""
    /* 00000000 */
.align 2
enddlabel D_80011660

nonmatching _vt_23tListIteratorTournament

dlabel _vt_23tListIteratorTournament
    /* 1E70 80011670 00000000 */ .word 0x00000000
    /* 1E74 80011674 00000000 */ .word 0x00000000
    /* 1E78 80011678 00000000 */ .word 0x00000000
    /* 1E7C 8001167C EC3D0380 */ .word ___23tListIteratorTournament
    /* 1E80 80011680 00000000 */ .word 0x00000000
    /* 1E84 80011684 143E0380 */ .word Value__23tListIteratorTournament7tPlayer
    /* 1E88 80011688 00000000 */ .word 0x00000000
    /* 1E8C 8001168C 283E0380 */ .word TextValue__23tListIteratorTournament7tPlayer
    /* 1E90 80011690 00000000 */ .word 0x00000000
    /* 1E94 80011694 803E0380 */ .word Increment__23tListIteratorTournament7tPlayer
    /* 1E98 80011698 00000000 */ .word 0x00000000
    /* 1E9C 8001169C 203F0380 */ .word Decrement__23tListIteratorTournament7tPlayer
enddlabel _vt_23tListIteratorTournament

.align 2
nonmatching D_800116A0

dlabel D_800116A0
    /* 1EA0 800116A0 */ .asciz "%s%s"
    /* 2573257300000000 */
.align 2
enddlabel D_800116A0

.align 2
nonmatching D_800116A8

dlabel D_800116A8
    /* 1EA8 800116A8 */ .asciz "zHPurs.mis"
    /* 7A48507572732E6D69730000 */
.align 2
enddlabel D_800116A8

.align 2
nonmatching D_800116B4

dlabel D_800116B4
    /* 1EB4 800116B4 */ .asciz "zHPurs2.mis"
    /* 7A4850757273322E6D697300 */
.align 2
enddlabel D_800116B4

.align 2
nonmatching D_800116C0

dlabel D_800116C0
    /* 1EC0 800116C0 */ .asciz "Missions"
    /* 4D697373696F6E7300000000 */
.align 2
.align 2
    /* 1ECC 800116CC */ .asciz ""
    /* 00000000 */
.align 2
.align 2
    /* 1ED0 800116D0 */ .asciz "SimpleMem"
    /* 53696D706C654D656D000000 */
.align 2
enddlabel D_800116C0

.align 2
nonmatching D_800116DC

dlabel D_800116DC
    /* 1EDC 800116DC */ .asciz "NFS4"
    /* 4E46533400000000 */
.align 2
enddlabel D_800116DC

.align 2
nonmatching D_800116E4

dlabel D_800116E4
    /* 1EE4 800116E4 */ .asciz "%s%s"
    /* 2573257300000000 */
.align 2
enddlabel D_800116E4

nonmatching D_800116EC

dlabel D_800116EC
    /* 1EEC 800116EC 25737A4D */ .word 0x4D7A7325
    /* 1EF0 800116F0 656D2E70 */ .word 0x702E6D65
    /* 1EF4 800116F4 73680000 */ .word 0x00006873
enddlabel D_800116EC