.include "macro.inc"
/* ============================================================
 * W65-A5  THE .L LOCALIZE CUT -- SPLAT-LANE FILLER ONLY
 *
 * jtbl_80056690: the retail jump table of a switch inside
 *     build/recon/game/common/track.cpp.o
 * (retail 0x80056690..0x80056724, 37 entries).
 *
 * OWNERSHIP PROOF: word-for-word identical to the owner's own .rodata run at +0x1a0 (E5)
 *
 * The `.word .L<VA>` operands below are the SRC lane's local labels.  The
 * RECON lane must NOT link this file: the recon TU emits this very table into
 * its own `.rodata`, and no recon object defines a `.L<VA>` symbol, so
 * linking it here is exactly the 350-name undefined `.L` class.
 * It stays in the tree so the legacy splat-lane script (linkers/nfs4.ld,
 * which links build/src/**) keeps producing a byte-identical image.
 * ============================================================ */

.section .rodata, "a"

/* Generated by spimdisasm 1.40.2 */


.align 3
nonmatching jtbl_80056690

dlabel jtbl_80056690
    /* 46E90 80056690 14A70B80 */ .word .L800BA714
    /* 46E94 80056694 BCA70B80 */ .word .L800BA7BC
    /* 46E98 80056698 BCA70B80 */ .word .L800BA7BC
    /* 46E9C 8005669C BCA70B80 */ .word .L800BA7BC
    /* 46EA0 800566A0 BCA70B80 */ .word .L800BA7BC
    /* 46EA4 800566A4 70A70B80 */ .word .L800BA770
    /* 46EA8 800566A8 8CA70B80 */ .word .L800BA78C
    /* 46EAC 800566AC BCA70B80 */ .word .L800BA7BC
    /* 46EB0 800566B0 BCA70B80 */ .word .L800BA7BC
    /* 46EB4 800566B4 BCA70B80 */ .word .L800BA7BC
    /* 46EB8 800566B8 BCA70B80 */ .word .L800BA7BC
    /* 46EBC 800566BC BCA70B80 */ .word .L800BA7BC
    /* 46EC0 800566C0 BCA70B80 */ .word .L800BA7BC
    /* 46EC4 800566C4 34A70B80 */ .word .L800BA734
    /* 46EC8 800566C8 BCA70B80 */ .word .L800BA7BC
    /* 46ECC 800566CC BCA70B80 */ .word .L800BA7BC
    /* 46ED0 800566D0 BCA70B80 */ .word .L800BA7BC
    /* 46ED4 800566D4 BCA70B80 */ .word .L800BA7BC
    /* 46ED8 800566D8 BCA70B80 */ .word .L800BA7BC
    /* 46EDC 800566DC BCA70B80 */ .word .L800BA7BC
    /* 46EE0 800566E0 BCA70B80 */ .word .L800BA7BC
    /* 46EE4 800566E4 BCA70B80 */ .word .L800BA7BC
    /* 46EE8 800566E8 BCA70B80 */ .word .L800BA7BC
    /* 46EEC 800566EC BCA70B80 */ .word .L800BA7BC
    /* 46EF0 800566F0 BCA70B80 */ .word .L800BA7BC
    /* 46EF4 800566F4 BCA70B80 */ .word .L800BA7BC
    /* 46EF8 800566F8 BCA70B80 */ .word .L800BA7BC
    /* 46EFC 800566FC BCA70B80 */ .word .L800BA7BC
    /* 46F00 80056700 BCA70B80 */ .word .L800BA7BC
    /* 46F04 80056704 BCA70B80 */ .word .L800BA7BC
    /* 46F08 80056708 BCA70B80 */ .word .L800BA7BC
    /* 46F0C 8005670C BCA70B80 */ .word .L800BA7BC
    /* 46F10 80056710 BCA70B80 */ .word .L800BA7BC
    /* 46F14 80056714 BCA70B80 */ .word .L800BA7BC
    /* 46F18 80056718 54A70B80 */ .word .L800BA754
    /* 46F1C 8005671C BCA70B80 */ .word .L800BA7BC
    /* 46F20 80056720 A8A70B80 */ .word .L800BA7A8
enddlabel jtbl_80056690