.include "macro.inc"
/* ============================================================
 * W65-A5  THE .L LOCALIZE CUT -- SPLAT-LANE FILLER ONLY
 *
 * jtbl_80010990: the retail jump table of a switch inside
 *     build/recon/frontend/common/femenuoptions.cpp.o
 * (retail 0x80010990..0x80010a00, 28 entries).
 *
 * OWNERSHIP PROOF: word-for-word identical to the owner's own .rodata run at +0x28 (E5)
 *
 * The `.word .L<VA>` operands below are the SRC lane's local labels.  The
 * RECON lane must NOT link this file: the recon TU emits this very table into
 * its own `.rodata`, and no recon object defines a `.L<VA>` symbol, so
 * linking it here is exactly the 350-name undefined `.L` class.
 * It stays in the tree so the legacy splat-lane script (linkers/nfs4.ld,
 * which links build/src/**) keeps producing a byte-identical image.
 * ============================================================ */

.section .rodata, "a"

/* Generated by spimdisasm 1.40.2 */

.align 2

.align 3
nonmatching jtbl_80010990

dlabel jtbl_80010990
    /* 1190 80010990 48010280 */ .word .L80020148
    /* 1194 80010994 74010280 */ .word .L80020174
    /* 1198 80010998 74010280 */ .word .L80020174
    /* 119C 8001099C 20010280 */ .word .L80020120
    /* 11A0 800109A0 70010280 */ .word .L80020170
    /* 11A4 800109A4 74010280 */ .word .L80020174
    /* 11A8 800109A8 74010280 */ .word .L80020174
    /* 11AC 800109AC 40010280 */ .word .L80020140
    /* 11B0 800109B0 38010280 */ .word .L80020138
    /* 11B4 800109B4 74010280 */ .word .L80020174
    /* 11B8 800109B8 74010280 */ .word .L80020174
    /* 11BC 800109BC 74010280 */ .word .L80020174
    /* 11C0 800109C0 50010280 */ .word .L80020150
    /* 11C4 800109C4 74010280 */ .word .L80020174
    /* 11C8 800109C8 74010280 */ .word .L80020174
    /* 11CC 800109CC 74010280 */ .word .L80020174
    /* 11D0 800109D0 68010280 */ .word .L80020168
    /* 11D4 800109D4 74010280 */ .word .L80020174
    /* 11D8 800109D8 58010280 */ .word .L80020158
    /* 11DC 800109DC 74010280 */ .word .L80020174
    /* 11E0 800109E0 74010280 */ .word .L80020174
    /* 11E4 800109E4 28010280 */ .word .L80020128
    /* 11E8 800109E8 74010280 */ .word .L80020174
    /* 11EC 800109EC 74010280 */ .word .L80020174
    /* 11F0 800109F0 74010280 */ .word .L80020174
    /* 11F4 800109F4 60010280 */ .word .L80020160
    /* 11F8 800109F8 74010280 */ .word .L80020174
    /* 11FC 800109FC 30010280 */ .word .L80020130
enddlabel jtbl_80010990