.include "macro.inc"
/* W65-A5: residual segment of rdata_80054548 -- the non-jump-table blob records.
 * Linked by BOTH lanes. */

.section .rodata, "a"

/* Generated by spimdisasm 1.40.2 */


.align 2
nonmatching D_800568A8

dlabel D_800568A8
    /* 470A8 800568A8 */ .asciz "SimpleMem"
    /* 53696D706C654D656D000000 */
.align 2
enddlabel D_800568A8

.align 2
nonmatching D_800568B4

dlabel D_800568B4
    /* 470B4 800568B4 */ .asciz "starCols"
    /* 73746172436F6C7300000000 */
.align 2
enddlabel D_800568B4

.align 2
nonmatching D_800568C0

dlabel D_800568C0
    /* 470C0 800568C0 */ .asciz "gRngCoordTop"
    /* 67526E67436F6F7264546F7000000000 */
.align 2
.align 2
    /* 470D0 800568D0 */ .asciz "SimpleMem"
    /* 53696D706C654D656D000000 */
.align 2
enddlabel D_800568C0

.align 2
nonmatching D_800568DC

dlabel D_800568DC
    /* 470DC 800568DC */ .asciz "AUD %d.%d/%d.%d"
    /* 4155442025642E25642F25642E256400 */
.align 2
enddlabel D_800568DC

.align 2
nonmatching D_800568EC

dlabel D_800568EC
    /* 470EC 800568EC */ .asciz "00M00S00"
    /* 30304D303053303000000000 */
.align 2
enddlabel D_800568EC

.align 2
nonmatching D_800568F8

dlabel D_800568F8
    /* 470F8 800568F8 */ .asciz "%1d%c%02d"
    /* 253164256325303264000000 */
.align 2
enddlabel D_800568F8

.align 2
nonmatching D_80056904

dlabel D_80056904
    /* 47104 80056904 */ .asciz "%01d%c%02d%c%02d"
    /* 2530316425632530326425632530326400000000 */
.align 2
enddlabel D_80056904

.align 2
nonmatching D_80056918

dlabel D_80056918
    /* 47118 80056918 */ .asciz " - %c - - %c - -"
    /* 202D202563202D202D202563202D202D00000000 */
.align 2
.align 2
    /* 4712C 8005692C */ .asciz "SimpleMem"
    /* 53696D706C654D656D000000 */
.align 2
enddlabel D_80056918

.align 2
nonmatching D_80056938

dlabel D_80056938
    /* 47138 80056938 */ .asciz "%sLoad%d%c.qps"
    /* 25734C6F6164256425632E7170730000 */
.align 2
enddlabel D_80056938

.align 2
nonmatching D_80056948

dlabel D_80056948
    /* 47148 80056948 */ .asciz "%sLoada.psh"
    /* 25734C6F6164612E70736800 */
.align 2
enddlabel D_80056948

.align 2
nonmatching D_80056954

dlabel D_80056954
    /* 47154 80056954 */ .asciz "%sLoadb.psh"
    /* 25734C6F6164622E70736800 */
.align 2
.align 2
    /* 47160 80056960 */ .asciz "SimpleMem"
    /* 53696D706C654D656D000000 */
.align 2
enddlabel D_80056954

.align 2
nonmatching D_8005696C

dlabel D_8005696C
    /* 4716C 8005696C */ .asciz "%snight.psh"
    /* 25736E696768742E70736800 */
.align 2
enddlabel D_8005696C

.align 2
nonmatching D_80056978

dlabel D_80056978
    /* 47178 80056978 */ .asciz "night.psh"
    /* 6E696768742E707368000000 */
.align 2
.align 2
    /* 47184 80056984 */ .asciz "SimpleMem"
    /* 53696D706C654D656D000000 */
.align 2
.align 2
    /* 47190 80056990 */ .asciz "SimpleMem"
    /* 53696D706C654D656D000000 */
.align 2
enddlabel D_80056978