.include "macro.inc"
/* ============================================================
 * W65-A5  THE .L LOCALIZE CUT -- SPLAT-LANE FILLER ONLY
 *
 * jtbl_800125F0: the retail jump table of a switch inside
 *     build/recon/frontend/common/screenusername.cpp.o
 * (retail 0x800125f0..0x800126e8, 62 entries).
 *
 * OWNERSHIP PROOF: the owner's text window CONTAINS every target; its own table has drifted because the owning function is a near-miss (per-word diff: scratchpad/w65a5/jtbl_diag.txt)
 *
 * The `.word .L<VA>` operands below are the SRC lane's local labels.  The
 * RECON lane must NOT link this file: the recon TU emits this very table into
 * its own `.rodata`, and no recon object defines a `.L<VA>` symbol, so
 * linking it here is exactly the 350-name undefined `.L` class.
 * It stays in the tree so the legacy splat-lane script (linkers/nfs4.ld,
 * which links build/src/**) keeps producing a byte-identical image.
 * ============================================================ */

.section .rodata, "a"

/* Generated by spimdisasm 1.40.2 */

.align 2

.align 3
nonmatching jtbl_800125F0

dlabel jtbl_800125F0
    /* 2DF0 800125F0 D4B30480 */ .word .L8004B3D4
    /* 2DF4 800125F4 E0B50480 */ .word .L8004B5E0
    /* 2DF8 800125F8 68B40480 */ .word .L8004B468
    /* 2DFC 800125FC 70B40480 */ .word .L8004B470
    /* 2E00 80012600 E0B50480 */ .word .L8004B5E0
    /* 2E04 80012604 FCB40480 */ .word .L8004B4FC
    /* 2E08 80012608 E0B50480 */ .word .L8004B5E0
    /* 2E0C 8001260C E0B50480 */ .word .L8004B5E0
    /* 2E10 80012610 E0B50480 */ .word .L8004B5E0
    /* 2E14 80012614 E0B50480 */ .word .L8004B5E0
    /* 2E18 80012618 E0B50480 */ .word .L8004B5E0
    /* 2E1C 8001261C E0B50480 */ .word .L8004B5E0
    /* 2E20 80012620 04B60480 */ .word .L8004B604
    /* 2E24 80012624 E0B50480 */ .word .L8004B5E0
    /* 2E28 80012628 E0B50480 */ .word .L8004B5E0
    /* 2E2C 8001262C E0B50480 */ .word .L8004B5E0
    /* 2E30 80012630 E0B50480 */ .word .L8004B5E0
    /* 2E34 80012634 E0B50480 */ .word .L8004B5E0
    /* 2E38 80012638 E0B50480 */ .word .L8004B5E0
    /* 2E3C 8001263C E0B50480 */ .word .L8004B5E0
    /* 2E40 80012640 E0B50480 */ .word .L8004B5E0
    /* 2E44 80012644 E0B50480 */ .word .L8004B5E0
    /* 2E48 80012648 E0B50480 */ .word .L8004B5E0
    /* 2E4C 8001264C E0B50480 */ .word .L8004B5E0
    /* 2E50 80012650 E0B50480 */ .word .L8004B5E0
    /* 2E54 80012654 E0B50480 */ .word .L8004B5E0
    /* 2E58 80012658 E0B50480 */ .word .L8004B5E0
    /* 2E5C 8001265C E0B50480 */ .word .L8004B5E0
    /* 2E60 80012660 E0B50480 */ .word .L8004B5E0
    /* 2E64 80012664 E0B50480 */ .word .L8004B5E0
    /* 2E68 80012668 E0B50480 */ .word .L8004B5E0
    /* 2E6C 8001266C DCB30480 */ .word .L8004B3DC
    /* 2E70 80012670 E0B50480 */ .word .L8004B5E0
    /* 2E74 80012674 E0B50480 */ .word .L8004B5E0
    /* 2E78 80012678 E0B50480 */ .word .L8004B5E0
    /* 2E7C 8001267C E0B50480 */ .word .L8004B5E0
    /* 2E80 80012680 E0B50480 */ .word .L8004B5E0
    /* 2E84 80012684 E0B50480 */ .word .L8004B5E0
    /* 2E88 80012688 E0B50480 */ .word .L8004B5E0
    /* 2E8C 8001268C E0B50480 */ .word .L8004B5E0
    /* 2E90 80012690 E0B50480 */ .word .L8004B5E0
    /* 2E94 80012694 E0B50480 */ .word .L8004B5E0
    /* 2E98 80012698 E0B50480 */ .word .L8004B5E0
    /* 2E9C 8001269C E0B50480 */ .word .L8004B5E0
    /* 2EA0 800126A0 E0B50480 */ .word .L8004B5E0
    /* 2EA4 800126A4 E0B50480 */ .word .L8004B5E0
    /* 2EA8 800126A8 E0B50480 */ .word .L8004B5E0
    /* 2EAC 800126AC E0B50480 */ .word .L8004B5E0
    /* 2EB0 800126B0 E0B50480 */ .word .L8004B5E0
    /* 2EB4 800126B4 E0B50480 */ .word .L8004B5E0
    /* 2EB8 800126B8 E0B50480 */ .word .L8004B5E0
    /* 2EBC 800126BC E0B50480 */ .word .L8004B5E0
    /* 2EC0 800126C0 E0B50480 */ .word .L8004B5E0
    /* 2EC4 800126C4 E0B50480 */ .word .L8004B5E0
    /* 2EC8 800126C8 E0B50480 */ .word .L8004B5E0
    /* 2ECC 800126CC E0B50480 */ .word .L8004B5E0
    /* 2ED0 800126D0 E0B50480 */ .word .L8004B5E0
    /* 2ED4 800126D4 E0B50480 */ .word .L8004B5E0
    /* 2ED8 800126D8 E0B50480 */ .word .L8004B5E0
    /* 2EDC 800126DC E0B50480 */ .word .L8004B5E0
    /* 2EE0 800126E0 E0B50480 */ .word .L8004B5E0
    /* 2EE4 800126E4 54B50480 */ .word .L8004B554
enddlabel jtbl_800125F0