.include "macro.inc"
/* W65-A5: residual segment of rdata_80010000 -- the non-jump-table blob records.
 * Linked by BOTH lanes. */

.section .rodata, "a"

/* Generated by spimdisasm 1.40.2 */

.align 2

.align 2
nonmatching D_8001214C

dlabel D_8001214C
    /* 294C 8001214C */ .asciz "zAudio"
    /* 7A417564696F0000 */
.align 2
.align 2
    /* 2954 80012154 */ .asciz ""
    /* 00000000 */
.align 2
enddlabel D_8001214C

nonmatching _vt_12tScreenAudio

dlabel _vt_12tScreenAudio
    /* 2958 80012158 00000000 */ .word 0x00000000
    /* 295C 8001215C 00000000 */ .word 0x00000000
    /* 2960 80012160 00000000 */ .word 0x00000000
    /* 2964 80012164 40610480 */ .word GetShapeInfo__12tScreenAudioRsT1PPcT3
    /* 2968 80012168 00000000 */ .word 0x00000000
    /* 296C 8001216C D85E0480 */ .word DrawBackground__12tScreenAudio
    /* 2970 80012170 00000000 */ .word 0x00000000
    /* 2974 80012174 C85D0480 */ .word DrawForeground__12tScreenAudio
    /* 2978 80012178 00000000 */ .word 0x00000000
    /* 297C 8001217C FC620480 */ .word ___12tScreenAudio
    /* 2980 80012180 00000000 */ .word 0x00000000
    /* 2984 80012184 80670280 */ .word PreLoad__7tScreen
    /* 2988 80012188 00000000 */ .word 0x00000000
    /* 298C 8001218C A4610480 */ .word Initialize__12tScreenAudio
    /* 2990 80012190 00000000 */ .word 0x00000000
    /* 2994 80012194 04620480 */ .word Cleanup__12tScreenAudio
    /* 2998 80012198 00000000 */ .word 0x00000000
    /* 299C 8001219C C0680280 */ .word TransitionIsFinished__7tScreen
    /* 29A0 800121A0 00000000 */ .word 0x00000000
    /* 29A4 800121A4 D8680280 */ .word ProcessInput__7tScreen7tPlayerR13tInputKeyTypeR12tMenuCommand
    /* 29A8 800121A8 53696D70 */ .word 0x706D6953
    /* 29AC 800121AC 6C654D65 */ .word 0x654D656C
    /* 29B0 800121B0 6D000000 */ .word 0x0000006D
enddlabel _vt_12tScreenAudio

.align 2
nonmatching D_800121B4

dlabel D_800121B4
    /* 29B4 800121B4 */ .asciz "zmemcrd"
    /* 7A6D656D63726400 */
.align 2
.align 2
    /* 29BC 800121BC */ .asciz ""
    /* 00000000 */
.align 2
enddlabel D_800121B4