.include "macro.inc"
/* W64-A18: residual segment of sdata_8013C54C -- labels no recon TU defines
 * (or a record tail a recon TU's section stops short of).
 * Linked by BOTH lanes. */

.section .sdata, "wa"

/* Generated by spimdisasm 1.40.2 */

nonmatching D_8013D504

dlabel D_8013D504
    /* 12DD04 8013D504 */ .asciz "amus"
    /* 616D757300000000 */
.align 2
.align 2
    /* 12DD0C 8013D50C */ .asciz "game*"
    /* 67616D652A000000 */
.align 2
enddlabel D_8013D504

.align 2
nonmatching D_8013D514

dlabel D_8013D514
    /* 12DD14 8013D514 */ .asciz ".bnk"
    /* 2E626E6B00000000 */
.align 2
enddlabel D_8013D514

nonmatching gMusicHandle

dlabel gMusicHandle
    /* 12DD1C 8013D51C 00000000 */ .word 0x00000000
enddlabel gMusicHandle

.align 2

.section .sdata_post_cario

.align 2

.section .sdata_post_cario_post_device

.align 2
nonmatching D_8013D798

dlabel D_8013D798
    /* 12DF98 8013D798 */ .asciz "ot0"
    /* 6F743000 */
.align 2
enddlabel D_8013D798

.align 2
nonmatching D_8013D79C

dlabel D_8013D79C
    /* 12DF9C 8013D79C */ .asciz "ot1"
    /* 6F743100 */
.align 2
enddlabel D_8013D79C

.align 2
nonmatching D_8013D7A0

dlabel D_8013D7A0
    /* 12DFA0 8013D7A0 */ .asciz "ps0"
    /* 70733000 */
.align 2
enddlabel D_8013D7A0

.align 2
nonmatching D_8013D7A4

dlabel D_8013D7A4
    /* 12DFA4 8013D7A4 */ .asciz "ps1"
    /* 70733100 */
.align 2
enddlabel D_8013D7A4

nonmatching Draw_gDoVSync

dlabel Draw_gDoVSync
    /* 12DFA8 8013D7A8 00000000 */ .word 0x00000000
enddlabel Draw_gDoVSync

nonmatching Draw_gNumView

dlabel Draw_gNumView
    /* 12DFAC 8013D7AC 00000000 */ .word 0x00000000
enddlabel Draw_gNumView

nonmatching Draw_gViewOtSize

dlabel Draw_gViewOtSize
    /* 12DFB0 8013D7B0 00000000 */ .word 0x00000000
enddlabel Draw_gViewOtSize

nonmatching gFlip

dlabel gFlip
    /* 12DFB4 8013D7B4 00000000 */ .word 0x00000000
enddlabel gFlip

nonmatching gLoop

dlabel gLoop
    /* 12DFB8 8013D7B8 00000000 */ .word 0x00000000
enddlabel gLoop

nonmatching Draw_gMidGroundOtz

dlabel Draw_gMidGroundOtz
    /* 12DFBC 8013D7BC 00000000 */ .word 0x00000000
enddlabel Draw_gMidGroundOtz

nonmatching Draw_gMaxPrim

dlabel Draw_gMaxPrim
    /* 12DFC0 8013D7C0 00000000 */ .word 0x00000000
enddlabel Draw_gMaxPrim

nonmatching gTotalMem

dlabel gTotalMem
    /* 12DFC4 8013D7C4 00000000 */ .word 0x00000000
enddlabel gTotalMem
