.include "macro.inc"
/* W63-A19: residual segment of sdata_8013C54C -- labels no recon TU defines.
 * Linked by BOTH lanes. */

.section .sdata, "wa"

/* Generated by spimdisasm 1.40.2 */

nonmatching trackMusicState

dlabel trackMusicState
    /* 12CE28 8013C628 */ .byte 0x04
    /* 12CE29 8013C629 */ .byte 0x00
    /* 12CE2A 8013C62A */ .byte 0x00
    /* 12CE2B 8013C62B */ .byte 0x00
enddlabel trackMusicState

nonmatching audioBackwardsDirection

dlabel audioBackwardsDirection
    /* 12CE2C 8013C62C 00000000 */ .word 0x00000000
enddlabel audioBackwardsDirection

nonmatching intensityFalseLapCounter

dlabel intensityFalseLapCounter
    /* 12CE30 8013C630 00000000 */ .word 0x00000000
enddlabel intensityFalseLapCounter

nonmatching falseLapCounter

dlabel falseLapCounter
    /* 12CE34 8013C634 00000000 */ .word 0x00000000
enddlabel falseLapCounter

nonmatching gMusicStyle

dlabel gMusicStyle
    /* 12CE38 8013C638 00000000 */ .word 0x00000000
enddlabel gMusicStyle

nonmatching countdown

dlabel countdown
    /* 12CE3C 8013C63C */ .byte 0x00
enddlabel countdown

nonmatching FadingMusic

dlabel FadingMusic
    /* 12CE3D 8013C63D */ .byte 0x00
enddlabel FadingMusic

nonmatching StartedNewMusic

dlabel StartedNewMusic
    /* 12CE3E 8013C63E */ .byte 0x00
    /* 12CE3F 8013C63F */ .byte 0x00
enddlabel StartedNewMusic

nonmatching recordLapTime

dlabel recordLapTime
    /* 12CE40 8013C640 00000000 */ .word 0x00000000
enddlabel recordLapTime

nonmatching AudioCmn_kAudioOn

dlabel AudioCmn_kAudioOn
    /* 12CE44 8013C644 01000000 */ .word 0x00000001
enddlabel AudioCmn_kAudioOn

nonmatching AudioCmn_kAudioStreamingOn

dlabel AudioCmn_kAudioStreamingOn
    /* 12CE48 8013C648 01000000 */ .word 0x00000001
enddlabel AudioCmn_kAudioStreamingOn

.align 2
nonmatching SgameSFXvol

dlabel SgameSFXvol
    /* 12CE4C 8013C64C */ .asciz "("
    /* 28000000 */
.align 2
enddlabel SgameSFXvol

nonmatching gMasterMusicLevel

dlabel gMasterMusicLevel
    /* 12CE50 8013C650 7F000000 */ .word 0x0000007F
enddlabel gMasterMusicLevel

nonmatching gMasterSFXLevel

dlabel gMasterSFXLevel
    /* 12CE54 8013C654 7F000000 */ .word 0x0000007F
enddlabel gMasterSFXLevel

nonmatching gMasterEngineLevel

dlabel gMasterEngineLevel
    /* 12CE58 8013C658 */ .byte 0x7F
    /* 12CE59 8013C659 */ .byte 0x00
    /* 12CE5A 8013C65A */ .byte 0x00
    /* 12CE5B 8013C65B */ .byte 0x00
enddlabel gMasterEngineLevel

nonmatching gMasterFENarrationLevel

dlabel gMasterFENarrationLevel
    /* 12CE5C 8013C65C 7F000000 */ .word 0x0000007F
enddlabel gMasterFENarrationLevel

nonmatching gMasterAmbientLevel

dlabel gMasterAmbientLevel
    /* 12CE60 8013C660 7F000000 */ .word 0x0000007F
enddlabel gMasterAmbientLevel

nonmatching previousSFXLevel

dlabel previousSFXLevel
    /* 12CE64 8013C664 7F000000 */ .word 0x0000007F
enddlabel previousSFXLevel

nonmatching AudioCmn_musicInteractive

dlabel AudioCmn_musicInteractive
    /* 12CE68 8013C668 01000000 */ .word 0x00000001
enddlabel AudioCmn_musicInteractive

nonmatching gFEmusicON

dlabel gFEmusicON
    /* 12CE6C 8013C66C 01000000 */ .word 0x00000001
enddlabel gFEmusicON

nonmatching NumSFXOn

dlabel NumSFXOn
    /* 12CE70 8013C670 00000000 */ .word 0x00000000
enddlabel NumSFXOn

nonmatching gStereoMode

dlabel gStereoMode
    /* 12CE74 8013C674 01000000 */ .word 0x00000001
enddlabel gStereoMode

nonmatching fReverbOn

dlabel fReverbOn
    /* 12CE78 8013C678 */ .byte 0x00
enddlabel fReverbOn

nonmatching fReverbLevel

dlabel fReverbLevel
    /* 12CE79 8013C679 */ .byte 0x00
    /* 12CE7A 8013C67A */ .byte 0x00
    /* 12CE7B 8013C67B */ .byte 0x00
enddlabel fReverbLevel

.align 2
nonmatching D_8013C67C

dlabel D_8013C67C
    /* 12CE7C 8013C67C */ .asciz "SFXHDR"
    /* 5346584844520000 */
.align 2
enddlabel D_8013C67C

.align 2
nonmatching D_8013C684

dlabel D_8013C684
    /* 12CE84 8013C684 */ .asciz "fesfx"
    /* 6665736678000000 */
.align 2
enddlabel D_8013C684

.align 2
nonmatching D_8013C68C

dlabel D_8013C68C
    /* 12CE8C 8013C68C */ .asciz "eng"
    /* 656E6700 */
.align 2
enddlabel D_8013C68C

.align 2
nonmatching D_8013C690

dlabel D_8013C690
    /* 12CE90 8013C690 */ .asciz "ger"
    /* 67657200 */
.align 2
enddlabel D_8013C690

.align 2
nonmatching D_8013C694

dlabel D_8013C694
    /* 12CE94 8013C694 */ .asciz "frn"
    /* 66726E00 */
.align 2
enddlabel D_8013C694

.align 2
nonmatching D_8013C698

dlabel D_8013C698
    /* 12CE98 8013C698 */ .asciz "spn"
    /* 73706E00 */
.align 2
enddlabel D_8013C698

.align 2
nonmatching D_8013C69C

dlabel D_8013C69C
    /* 12CE9C 8013C69C */ .asciz "itl"
    /* 69746C00 */
.align 2
enddlabel D_8013C69C

.align 2
nonmatching D_8013C6A0

dlabel D_8013C6A0
    /* 12CEA0 8013C6A0 */ .asciz "Gen"
    /* 47656E00 */
.align 2
enddlabel D_8013C6A0

.align 2
nonmatching D_8013C6A4

dlabel D_8013C6A4
    /* 12CEA4 8013C6A4 */ .asciz "brt"
    /* 62727400 */
.align 2
enddlabel D_8013C6A4

.align 2
nonmatching D_8013C6A8

dlabel D_8013C6A8
    /* 12CEA8 8013C6A8 */ .asciz "fre"
    /* 66726500 */
.align 2
enddlabel D_8013C6A8

nonmatching D_8013C6AC

dlabel D_8013C6AC
    /* 12CEAC 8013C6AC 63000000 */ .word 0x00000063
enddlabel D_8013C6AC

nonmatching D_8013C6B0

dlabel D_8013C6B0
    /* 12CEB0 8013C6B0 00000000 */ .word 0x00000000
enddlabel D_8013C6B0

nonmatching falseLapTrigCur

dlabel falseLapTrigCur
    /* 12CEB4 8013C6B4 00000000 */ .word 0x00000000
enddlabel falseLapTrigCur

nonmatching flaseLapTrigTrack

dlabel flaseLapTrigTrack
    /* 12CEB8 8013C6B8 00000000 */ .word 0x00000000
enddlabel flaseLapTrigTrack

nonmatching currentLap

dlabel currentLap
    /* 12CEBC 8013C6BC 00000000 */ .word 0x00000000
enddlabel currentLap

nonmatching bestLapTime

dlabel bestLapTime
    /* 12CEC0 8013C6C0 00000000 */ .word 0x00000000
    /* 12CEC4 8013C6C4 00000000 */ .word 0x00000000
enddlabel bestLapTime

nonmatching gtotallaptimes

dlabel gtotallaptimes
    /* 12CEC8 8013C6C8 00000000 */ .word 0x00000000
    /* 12CECC 8013C6CC 00000000 */ .word 0x00000000
enddlabel gtotallaptimes

nonmatching AudioCmn_gPlayerArrested

dlabel AudioCmn_gPlayerArrested
    /* 12CED0 8013C6D0 00000000 */ .word 0x00000000
    /* 12CED4 8013C6D4 00000000 */ .word 0x00000000
enddlabel AudioCmn_gPlayerArrested

nonmatching AudioCmn_gCursorSndHandle

dlabel AudioCmn_gCursorSndHandle
    /* 12CED8 8013C6D8 00000000 */ .word 0x00000000
enddlabel AudioCmn_gCursorSndHandle

nonmatching AudioCmn_gLastFade

dlabel AudioCmn_gLastFade
    /* 12CEDC 8013C6DC 00000000 */ .word 0x00000000
enddlabel AudioCmn_gLastFade

nonmatching AudioCmn_gLoadTables

dlabel AudioCmn_gLoadTables
    /* 12CEE0 8013C6E0 00000000 */ .word 0x00000000
enddlabel AudioCmn_gLoadTables

nonmatching AudioCmn_gCruiseTables

dlabel AudioCmn_gCruiseTables
    /* 12CEE4 8013C6E4 00000000 */ .word 0x00000000
enddlabel AudioCmn_gCruiseTables

nonmatching AudioCmn_gResume

dlabel AudioCmn_gResume
    /* 12CEE8 8013C6E8 00000000 */ .word 0x00000000
enddlabel AudioCmn_gResume

nonmatching AudioCmn_gStreamRestartTimer

dlabel AudioCmn_gStreamRestartTimer
    /* 12CEEC 8013C6EC 00000000 */ .word 0x00000000
enddlabel AudioCmn_gStreamRestartTimer

nonmatching fMysticWindON

dlabel fMysticWindON
    /* 12CEF0 8013C6F0 00000000 */ .word 0x00000000
enddlabel fMysticWindON

nonmatching fAmbientRangeON

dlabel fAmbientRangeON
    /* 12CEF4 8013C6F4 00000000 */ .word 0x00000000
enddlabel fAmbientRangeON

nonmatching currentWindVal

dlabel currentWindVal
    /* 12CEF8 8013C6F8 00000000 */ .word 0x00000000
    /* 12CEFC 8013C6FC 00000000 */ .word 0x00000000
enddlabel currentWindVal

nonmatching nextWindVal

dlabel nextWindVal
    /* 12CF00 8013C700 00000000 */ .word 0x00000000
    /* 12CF04 8013C704 00000000 */ .word 0x00000000
enddlabel nextWindVal

nonmatching currentWindPan

dlabel currentWindPan
    /* 12CF08 8013C708 00000000 */ .word 0x00000000
enddlabel currentWindPan

nonmatching nextWindPan

dlabel nextWindPan
    /* 12CF0C 8013C70C 00000000 */ .word 0x00000000
enddlabel nextWindPan

nonmatching gQuickSirenCount

dlabel gQuickSirenCount
    /* 12CF10 8013C710 00000000 */ .word 0x00000000
enddlabel gQuickSirenCount

nonmatching AudioCmn_ThunderAmp

dlabel AudioCmn_ThunderAmp
    /* 12CF14 8013C714 00000000 */ .word 0x00000000
enddlabel AudioCmn_ThunderAmp

nonmatching AudioCmn_ThunderAzi

dlabel AudioCmn_ThunderAzi
    /* 12CF18 8013C718 00000000 */ .word 0x00000000
enddlabel AudioCmn_ThunderAzi

nonmatching AudioCmn_ThunderDel

dlabel AudioCmn_ThunderDel
    /* 12CF1C 8013C71C 00000000 */ .word 0x00000000
enddlabel AudioCmn_ThunderDel
