.include "macro.inc"
/* ============================================================
 * W64-A18  BLOB-vs-TU OWNERSHIP SWEEP -- SPLAT-LANE FILLER ONLY
 *
 * This segment's data is OWNED by
 *     build/recon/game/common/object.cpp.o
 * (section .sdata, retail 0x8013d2c8..0x8013d2e0), whose own bytes were
 * proved byte-identical to retail before the cut (ownmap2 E1-E5, with
 * R_MIPS_32 relocations RESOLVED against the retail VA map).
 *
 * The RECON-lane linker script must link that object's .sdata here and must
 * NOT link this file -- otherwise every label below is multiply defined.
 * It stays in the tree only so the legacy splat-lane script
 * (linkers/nfs4.ld, which links build/src/**, where no recon object exists)
 * keeps producing a byte-identical image.
 * ============================================================ */

.section .sdata, "wa"

/* Generated by spimdisasm 1.40.2 */

nonmatching Object_customObjInst

dlabel Object_customObjInst
    /* 12DAC8 8013D2C8 00000000 */ .word 0x00000000
enddlabel Object_customObjInst

nonmatching Object_customSimObjs

dlabel Object_customSimObjs
    /* 12DACC 8013D2CC 00000000 */ .word 0x00000000
enddlabel Object_customSimObjs

nonmatching Object_customSFXInst

dlabel Object_customSFXInst
    /* 12DAD0 8013D2D0 00000000 */ .word 0x00000000
enddlabel Object_customSFXInst

nonmatching Object_customSliceNum

dlabel Object_customSliceNum
    /* 12DAD4 8013D2D4 00000000 */ .word 0x00000000
enddlabel Object_customSliceNum

nonmatching Object_IMassObjInst

dlabel Object_IMassObjInst
    /* 12DAD8 8013D2D8 00000000 */ .word 0x00000000
enddlabel Object_IMassObjInst

nonmatching gNumIMassObjects

dlabel gNumIMassObjects
    /* 12DADC 8013D2DC 00000000 */ .word 0x00000000
enddlabel gNumIMassObjects

.align 2