.include "macro.inc"
/* ============================================================
 * W64-A18  BLOB-vs-TU OWNERSHIP SWEEP -- SPLAT-LANE FILLER ONLY
 *
 * This segment's data is OWNED by
 *     build/recon/game/psx/force.cpp.o
 * (section .sdata, retail 0x8013d840..0x8013d854), whose own bytes were
 * proved byte-identical to retail before the cut (ownmap2 E1-E5, with
 * R_MIPS_32 relocations RESOLVED against the retail VA map).
 *
 * The RECON-lane linker script must link that object's .sdata here and must
 * NOT link this file -- otherwise every label below is multiply defined.
 * It stays in the tree only so the legacy splat-lane script
 * (linkers/nfs4.ld, which links build/src/**, where no recon object exists)
 * keeps producing a byte-identical image.
 * ============================================================ */

.section .sdata, "wa"

/* Generated by spimdisasm 1.40.2 */

nonmatching Force_gActAlign

dlabel Force_gActAlign
    /* 12E040 8013D840 0001FFFF */ .word 0xFFFF0100
    /* 12E044 8013D844 FFFF0000 */ .word 0x0000FFFF
enddlabel Force_gActAlign

nonmatching Force_gOffAlign

dlabel Force_gOffAlign
    /* 12E048 8013D848 FFFFFFFF */ .word 0xFFFFFFFF
    /* 12E04C 8013D84C */ .short 0xFFFF
enddlabel Force_gOffAlign

nonmatching Force_gTick

dlabel Force_gTick
    /* 12E04E 8013D84E */ .short 0x0000
enddlabel Force_gTick

nonmatching Force_gVblHandle

dlabel Force_gVblHandle
    /* 12E050 8013D850 00000000 */ .word 0x00000000
enddlabel Force_gVblHandle
