.include "macro.inc"
/* ============================================================
 * W63-A19  BLOB-vs-TU OWNERSHIP SWEEP -- SPLAT-LANE FILLER ONLY
 *
 * This segment's data is OWNED by
 *     build/recon/game/psx/texture.cpp.o
 * (section .sdata, retail 0x8013db08..0x8013db3c), whose own bytes were
 * proved byte-identical to retail before the cut (ownmap.py E5).
 *
 * The RECON-lane linker script must link that object's .sdata here and must
 * NOT link this file -- otherwise every label below is multiply defined.
 * It stays in the tree only so the legacy splat-lane script
 * (linkers/nfs4.ld, which links build/src/**, where no recon object exists)
 * keeps producing a byte-identical .sdata image.
 * ============================================================ */

.section .sdata, "wa"

/* Generated by spimdisasm 1.40.2 */

nonmatching Texture_CarColor

dlabel Texture_CarColor
    /* 12E308 8013DB08 00000000 */ .word 0x00000000
enddlabel Texture_CarColor

nonmatching Texture_palCopy

dlabel Texture_palCopy
    /* 12E30C 8013DB0C 00000000 */ .word 0x00000000
enddlabel Texture_palCopy

nonmatching Texture_palNum

dlabel Texture_palNum
    /* 12E310 8013DB10 */ .short 0x0000
    /* 12E312 8013DB12 */ .short 0x0000
enddlabel Texture_palNum

nonmatching Texture_gNum4bitPal

dlabel Texture_gNum4bitPal
    /* 12E314 8013DB14 00000000 */ .word 0x00000000
enddlabel Texture_gNum4bitPal

nonmatching Texture_gNum8bitPal

dlabel Texture_gNum8bitPal
    /* 12E318 8013DB18 00000000 */ .word 0x00000000
enddlabel Texture_gNum8bitPal

nonmatching Texture_gP4bitPmx

dlabel Texture_gP4bitPmx
    /* 12E31C 8013DB1C 00000000 */ .word 0x00000000
enddlabel Texture_gP4bitPmx

nonmatching Texture_gP8bitPmx

dlabel Texture_gP8bitPmx
    /* 12E320 8013DB20 00000000 */ .word 0x00000000
enddlabel Texture_gP8bitPmx

nonmatching Texture_gPalette4bit

dlabel Texture_gPalette4bit
    /* 12E324 8013DB24 00000000 */ .word 0x00000000
enddlabel Texture_gPalette4bit

nonmatching Texture_gPalette8bit

dlabel Texture_gPalette8bit
    /* 12E328 8013DB28 00000000 */ .word 0x00000000
enddlabel Texture_gPalette8bit

nonmatching gFreePal4

dlabel gFreePal4
    /* 12E32C 8013DB2C 00000000 */ .word 0x00000000
enddlabel gFreePal4

nonmatching gNbFreePal4

dlabel gNbFreePal4
    /* 12E330 8013DB30 00000000 */ .word 0x00000000
enddlabel gNbFreePal4

nonmatching gFreePal8

dlabel gFreePal8
    /* 12E334 8013DB34 00000000 */ .word 0x00000000
enddlabel gFreePal8

nonmatching gNbFreePal8

dlabel gNbFreePal8
    /* 12E338 8013DB38 00000000 */ .word 0x00000000
enddlabel gNbFreePal8
