.include "macro.inc"
/* ============================================================
 * W64-A18  BLOB-vs-TU OWNERSHIP SWEEP -- SPLAT-LANE FILLER ONLY
 *
 * This segment's data is OWNED by
 *     build/recon/game/common/genericpmx.cpp.o
 * (section .sdata, retail 0x8013d10c..0x8013d220), whose own bytes were
 * proved byte-identical to retail before the cut (ownmap2 E1-E5, with
 * R_MIPS_32 relocations RESOLVED against the retail VA map).
 *
 * The RECON-lane linker script must link that object's .sdata here and must
 * NOT link this file -- otherwise every label below is multiply defined.
 * It stays in the tree only so the legacy splat-lane script
 * (linkers/nfs4.ld, which links build/src/**, where no recon object exists)
 * keeps producing a byte-identical image.
 * ============================================================ */

.section .sdata, "wa"

/* Generated by spimdisasm 1.40.2 */

nonmatching D_8013D10C

dlabel D_8013D10C
    /* 12D90C 8013D10C */ .asciz "LIN%d"
    /* 4C494E2564000000 */
.align 2
enddlabel D_8013D10C

.align 2
nonmatching D_8013D114

dlabel D_8013D114
    /* 12D914 8013D114 */ .asciz "spik"
    /* 7370696B00000000 */
.align 2
enddlabel D_8013D114

.align 2
nonmatching D_8013D11C

dlabel D_8013D11C
    /* 12D91C 8013D11C */ .asciz "DEBG"
    /* 4445424700000000 */
.align 2
enddlabel D_8013D11C

.align 2
nonmatching D_8013D124

dlabel D_8013D124
    /* 12D924 8013D124 */ .asciz "SHAD"
    /* 5348414400000000 */
.align 2
enddlabel D_8013D124

.align 2
nonmatching D_8013D12C

dlabel D_8013D12C
    /* 12D92C 8013D12C */ .asciz "SKD0"
    /* 534B443000000000 */
.align 2
enddlabel D_8013D12C

.align 2
nonmatching D_8013D134

dlabel D_8013D134
    /* 12D934 8013D134 */ .asciz "SKD1"
    /* 534B443100000000 */
.align 2
enddlabel D_8013D134

.align 2
nonmatching D_8013D13C

dlabel D_8013D13C
    /* 12D93C 8013D13C */ .asciz "FLAK"
    /* 464C414B00000000 */
.align 2
enddlabel D_8013D13C

.align 2
nonmatching D_8013D144

dlabel D_8013D144
    /* 12D944 8013D144 */ .asciz "FLA1"
    /* 464C413100000000 */
.align 2
enddlabel D_8013D144

.align 2
nonmatching D_8013D14C

dlabel D_8013D14C
    /* 12D94C 8013D14C */ .asciz "SPLT"
    /* 53504C5400000000 */
.align 2
enddlabel D_8013D14C

.align 2
nonmatching D_8013D154

dlabel D_8013D154
    /* 12D954 8013D154 */ .asciz "SMX0"
    /* 534D583000000000 */
.align 2
enddlabel D_8013D154

.align 2
nonmatching D_8013D15C

dlabel D_8013D15C
    /* 12D95C 8013D15C */ .asciz "SMX1"
    /* 534D583100000000 */
.align 2
enddlabel D_8013D15C

.align 2
nonmatching D_8013D164

dlabel D_8013D164
    /* 12D964 8013D164 */ .asciz "SMOK"
    /* 534D4F4B00000000 */
.align 2
enddlabel D_8013D164

.align 2
nonmatching D_8013D16C

dlabel D_8013D16C
    /* 12D96C 8013D16C */ .asciz "DIRT"
    /* 4449525400000000 */
.align 2
enddlabel D_8013D16C

.align 2
nonmatching D_8013D174

dlabel D_8013D174
    /* 12D974 8013D174 */ .asciz "GRX0"
    /* 4752583000000000 */
.align 2
enddlabel D_8013D174

.align 2
nonmatching D_8013D17C

dlabel D_8013D17C
    /* 12D97C 8013D17C */ .asciz "GRX1"
    /* 4752583100000000 */
.align 2
enddlabel D_8013D17C

.align 2
nonmatching D_8013D184

dlabel D_8013D184
    /* 12D984 8013D184 */ .asciz "GRAV"
    /* 4752415600000000 */
.align 2
enddlabel D_8013D184

.align 2
nonmatching D_8013D18C

dlabel D_8013D18C
    /* 12D98C 8013D18C */ .asciz "GRAS"
    /* 4752415300000000 */
.align 2
enddlabel D_8013D18C

.align 2
nonmatching D_8013D194

dlabel D_8013D194
    /* 12D994 8013D194 */ .asciz "SNOW"
    /* 534E4F5700000000 */
.align 2
enddlabel D_8013D194

.align 2
nonmatching D_8013D19C

dlabel D_8013D19C
    /* 12D99C 8013D19C */ .asciz "SHX%d"
    /* 5348582564000000 */
.align 2
enddlabel D_8013D19C

.align 2
nonmatching D_8013D1A4

dlabel D_8013D1A4
    /* 12D9A4 8013D1A4 */ .asciz "LF%02d"
    /* 4C46253032640000 */
.align 2
enddlabel D_8013D1A4

.align 2
nonmatching D_8013D1AC

dlabel D_8013D1AC
    /* 12D9AC 8013D1AC */ .asciz "DAMG"
    /* 44414D4700000000 */
.align 2
enddlabel D_8013D1AC

.align 2
nonmatching D_8013D1B4

dlabel D_8013D1B4
    /* 12D9B4 8013D1B4 */ .asciz "LNG%d"
    /* 4C4E472564000000 */
.align 2
enddlabel D_8013D1B4

.align 2
nonmatching D_8013D1BC

dlabel D_8013D1BC
    /* 12D9BC 8013D1BC */ .asciz "MONF"
    /* 4D4F4E4600000000 */
.align 2
enddlabel D_8013D1BC

.align 2
nonmatching D_8013D1C4

dlabel D_8013D1C4
    /* 12D9C4 8013D1C4 */ .asciz "FLR0"
    /* 464C523000000000 */
.align 2
enddlabel D_8013D1C4

.align 2
nonmatching D_8013D1CC

dlabel D_8013D1CC
    /* 12D9CC 8013D1CC */ .asciz "FLR1"
    /* 464C523100000000 */
.align 2
enddlabel D_8013D1CC

.align 2
nonmatching D_8013D1D4

dlabel D_8013D1D4
    /* 12D9D4 8013D1D4 */ .asciz "RBOW"
    /* 52424F5700000000 */
.align 2
enddlabel D_8013D1D4

nonmatching gDPixmap

dlabel gDPixmap
    /* 12D9DC 8013D1DC 00000000 */ .word 0x00000000
enddlabel gDPixmap

nonmatching gSpikeBeltPixmap

dlabel gSpikeBeltPixmap
    /* 12D9E0 8013D1E0 00000000 */ .word 0x00000000
enddlabel gSpikeBeltPixmap

nonmatching gShadowPixmap

dlabel gShadowPixmap
    /* 12D9E4 8013D1E4 00000000 */ .word 0x00000000
    /* 12D9E8 8013D1E8 00000000 */ .word 0x00000000
enddlabel gShadowPixmap

nonmatching gSkidMarkPixmap

dlabel gSkidMarkPixmap
    /* 12D9EC 8013D1EC 00000000 */ .word 0x00000000
enddlabel gSkidMarkPixmap

nonmatching D_8013D1F0

dlabel D_8013D1F0
    /* 12D9F0 8013D1F0 00000000 */ .word 0x00000000
enddlabel D_8013D1F0

nonmatching gSMokePixmap

dlabel gSMokePixmap
    /* 12D9F4 8013D1F4 00000000 */ .word 0x00000000
enddlabel gSMokePixmap

nonmatching D_8013D1F8

dlabel D_8013D1F8
    /* 12D9F8 8013D1F8 00000000 */ .word 0x00000000
enddlabel D_8013D1F8

nonmatching gSMokePalette

dlabel gSMokePalette
    /* 12D9FC 8013D1FC 00000000 */ .word 0x00000000
enddlabel gSMokePalette

nonmatching gDirtPalette

dlabel gDirtPalette
    /* 12DA00 8013D200 00000000 */ .word 0x00000000
enddlabel gDirtPalette

nonmatching gGravelPixmap

dlabel gGravelPixmap
    /* 12DA04 8013D204 00000000 */ .word 0x00000000
enddlabel gGravelPixmap

nonmatching D_8013D208

dlabel D_8013D208
    /* 12DA08 8013D208 00000000 */ .word 0x00000000
enddlabel D_8013D208

nonmatching gGravelPalette

dlabel gGravelPalette
    /* 12DA0C 8013D20C 00000000 */ .word 0x00000000
enddlabel gGravelPalette

nonmatching gGrassPalette

dlabel gGrassPalette
    /* 12DA10 8013D210 00000000 */ .word 0x00000000
enddlabel gGrassPalette

nonmatching gSnowPalette

dlabel gSnowPalette
    /* 12DA14 8013D214 00000000 */ .word 0x00000000
enddlabel gSnowPalette

nonmatching gLeafPixmap

dlabel gLeafPixmap
    /* 12DA18 8013D218 00000000 */ .word 0x00000000
enddlabel gLeafPixmap

nonmatching gDamagePixmap

dlabel gDamagePixmap
    /* 12DA1C 8013D21C 00000000 */ .word 0x00000000
enddlabel gDamagePixmap
