.include "macro.inc"
/* W64-A18: residual segment of sdata_8013C54C -- labels no recon TU defines
 * (or a record tail a recon TU's section stops short of).
 * Linked by BOTH lanes. */

.section .sdata.r10_pre_new, "wa"

/* Generated by spimdisasm 1.40.2 */

nonmatching gMPauseUpdateNextTime

dlabel gMPauseUpdateNextTime
    /* 12DA40 8013D240 00000000 */ .word 0x00000000
enddlabel gMPauseUpdateNextTime

nonmatching InGameSelectListAudioMode

dlabel InGameSelectListAudioMode
    /* 12DA44 8013D244 12001100 */ .word 0x00110012
    /* 12DA48 8013D248 13000000 */ .word 0x00000013
enddlabel InGameSelectListAudioMode

nonmatching SelectListConfig

dlabel SelectListConfig
    /* 12DA4C 8013D24C 17001800 */ .word 0x00180017
    /* 12DA50 8013D250 19000000 */ .word 0x00000019
enddlabel SelectListConfig

nonmatching D_8013D254

dlabel D_8013D254
    /* 12DA54 8013D254 00000000 */ .word 0x00000000
enddlabel D_8013D254

nonmatching D_8013D258

dlabel D_8013D258
    /* 12DA58 8013D258 7F000000 */ .word 0x0000007F
enddlabel D_8013D258

nonmatching D_8013D25C

dlabel D_8013D25C
    /* 12DA5C 8013D25C 00000000 */ .word 0x00000000
enddlabel D_8013D25C

nonmatching D_8013D260

dlabel D_8013D260
    /* 12DA60 8013D260 00000000 */ .word 0x00000000
enddlabel D_8013D260

nonmatching gMPauseUpdate

dlabel gMPauseUpdate
    /* 12DA64 8013D264 00000000 */ .word 0x00000000
enddlabel gMPauseUpdate

nonmatching gPauseMenuDefs

dlabel gPauseMenuDefs
    /* 12DA68 8013D268 00000000 */ .word 0x00000000
enddlabel gPauseMenuDefs

.section .sdata.r10_new_legacy, "wa"

nonmatching New_cplusplus_heap

dlabel New_cplusplus_heap
    /* 12DA6C 8013D26C 00000000 */ .word 0x00000000
enddlabel New_cplusplus_heap

/* P882: NFS3's following 0x58-byte source-owned span is a separate oracle piece. */
