.include "macro.inc"
/* ============================================================
 * W63-A19  BLOB-vs-TU OWNERSHIP SWEEP -- SPLAT-LANE FILLER ONLY
 *
 * This segment's data is OWNED by
 *     build/recon/game/psx/audio.cpp.o
 * (section .sdata, retail 0x8013d4fc..0x8013d504), whose own bytes were
 * proved byte-identical to retail before the cut (ownmap.py E5).
 *
 * The RECON-lane linker script must link that object's .sdata here and must
 * NOT link this file -- otherwise every label below is multiply defined.
 * It stays in the tree only so the legacy splat-lane script
 * (linkers/nfs4.ld, which links build/src/**, where no recon object exists)
 * keeps producing a byte-identical .sdata image.
 * ============================================================ */

.section .sdata, "wa"

/* Generated by spimdisasm 1.40.2 */

nonmatching Audio_direct3davail

dlabel Audio_direct3davail
    /* 12DCFC 8013D4FC 00000000 */ .word 0x00000000
enddlabel Audio_direct3davail

nonmatching Audio_gHeap

dlabel Audio_gHeap
    /* 12DD00 8013D500 00000000 */ .word 0x00000000
enddlabel Audio_gHeap

.align 2