.include "macro.inc"
/* Legacy splat-lane filler.  The reconstruction lane now gets these exact
 * bytes from paths.cpp, their SYM-owning translation unit. */

.section .sdata, "wa"

/* Generated by spimdisasm 1.40.2 */

nonmatching burnPath

dlabel burnPath
    /* 12DAE0 8013D2E0 */ .asciz "z"
    /* 7A000000 */
.align 2
enddlabel burnPath

nonmatching fePath

dlabel fePath
    /* 12DAE4 8013D2E4 00000000 */ .word 0x00000000
enddlabel fePath
