.include "macro.inc"
/* W64-A18: residual segment of sdata_8013C54C -- labels no recon TU defines
 * (or a record tail a recon TU's section stops short of).
 * Linked by BOTH lanes. */

.section .sdata, "wa"

/* Generated by spimdisasm 1.40.2 */

nonmatching Replay_ReplayCounter

dlabel Replay_ReplayCounter
    /* 12DC00 8013D400 00000000 */ .word 0x00000000
enddlabel Replay_ReplayCounter

nonmatching D_8013D404

dlabel D_8013D404
    /* 12DC04 8013D404 00000000 */ .word 0x00000000
enddlabel D_8013D404
