.include "macro.inc"
/* W64-A18: residual segment of sdata_8013C54C -- labels no recon TU defines
 * (or a record tail a recon TU's section stops short of).
 * Linked by BOTH lanes. */

.section .sdata, "wa"

/* Generated by spimdisasm 1.40.2 */

nonmatching D_8013C5B0

dlabel D_8013C5B0
    /* 12CDB0 8013C5B0 00000000 */ .word 0x00000000
enddlabel D_8013C5B0

nonmatching D_8013C5B4

dlabel D_8013C5B4
    /* 12CDB4 8013C5B4 00000000 */ .word 0x00000000
enddlabel D_8013C5B4

nonmatching Track0Speeds

dlabel Track0Speeds
    /* 12CDB8 8013C5B8 1027E31C */ .word 0x1CE32710
enddlabel Track0Speeds

nonmatching Track1Speeds

dlabel Track1Speeds
    /* 12CDBC 8013C5BC 1027E31C */ .word 0x1CE32710
enddlabel Track1Speeds

nonmatching Track4Speeds

dlabel Track4Speeds
    /* 12CDC0 8013C5C0 10273816 */ .word 0x16382710
enddlabel Track4Speeds

nonmatching Track8Speeds

dlabel Track8Speeds
    /* 12CDC4 8013C5C4 1027712C */ .word 0x2C712710
enddlabel Track8Speeds

nonmatching Track9Speeds

dlabel Track9Speeds
    /* 12CDC8 8013C5C8 1027712C */ .word 0x2C712710
enddlabel Track9Speeds

nonmatching Track10Speeds

dlabel Track10Speeds
    /* 12CDCC 8013C5CC 1027712C */ .word 0x2C712710
enddlabel Track10Speeds

.align 2
nonmatching D_8013C5D0

dlabel D_8013C5D0
    /* 12CDD0 8013C5D0 */ .asciz "aiwther"
    /* 6169777468657200 */
.align 2
enddlabel D_8013C5D0

.align 2
nonmatching D_8013C5D8

dlabel D_8013C5D8
    /* 12CDD8 8013C5D8 */ .asciz "SBUS"
    /* 5342555300000000 */
.align 2
enddlabel D_8013C5D8

.align 2
nonmatching D_8013C5E0

dlabel D_8013C5E0
    /* 12CDE0 8013C5E0 */ .asciz "TBUS"
    /* 5442555300000000 */
.align 2
enddlabel D_8013C5E0
