.include "macro.inc"
/* W64-A18: residual segment of sdata_8013C54C -- labels no recon TU defines
 * (or a record tail a recon TU's section stops short of).
 * Linked by BOTH lanes. */

.section .sdata, "wa"

/* Generated by spimdisasm 1.40.2 */

nonmatching gContrastScale

dlabel gContrastScale
    /* 12E33C 8013DB3C 00000100 */ .word 0x00010000
enddlabel gContrastScale

nonmatching Texture_gContrastColor

dlabel Texture_gContrastColor
    /* 12E340 8013DB40 80808000 */ .word 0x00808080
enddlabel Texture_gContrastColor

nonmatching Texture_gWorldColor

dlabel Texture_gWorldColor
    /* 12E344 8013DB44 FFFFFF00 */ .word 0x00FFFFFF
enddlabel Texture_gWorldColor

nonmatching TP_gColorMode

dlabel TP_gColorMode
    /* 12E348 8013DB48 00000000 */ .word 0x00000000
enddlabel TP_gColorMode

/* P886: TextureProcess's40-byte literal prefix now leads o34's complete
 * oracle .sdata run. These four preceding globals remain independent. */
