.include "macro.inc"
/* W64-A18: residual segment of sdata_8013C54C -- labels no recon TU defines
 * (or a record tail a recon TU's section stops short of).
 * Linked by BOTH lanes. */

.section .sdata, "wa"

/* Generated by spimdisasm 1.40.2 */

nonmatching D_8013C588

dlabel D_8013C588
    /* 12CD88 8013C588 */ .asciz "dist=%d"
    /* 646973743D256400 */
.align 2
enddlabel D_8013C588

nonmatching D_8013C590

dlabel D_8013C590
    /* 12CD90 8013C590 8C64503C */ .word 0x3C50648C
enddlabel D_8013C590

nonmatching AIPhysic_iTime

dlabel AIPhysic_iTime
    /* 12CD94 8013C594 00000000 */ .word 0x00000000
enddlabel AIPhysic_iTime

nonmatching AIPhysic_time

dlabel AIPhysic_time
    /* 12CD98 8013C598 00000000 */ .word 0x00000000
enddlabel AIPhysic_time

nonmatching AIPhysic_elapsedTime

dlabel AIPhysic_elapsedTime
    /* 12CD9C 8013C59C 00000000 */ .word 0x00000000
enddlabel AIPhysic_elapsedTime
