.include "macro.inc"
/* W63-A19: residual segment of sdata_8013C54C -- labels no recon TU defines.
 * Linked by BOTH lanes. */

.section .sdata, "wa"

/* Generated by spimdisasm 1.40.2 */

nonmatching loadfilecallback

dlabel loadfilecallback
    /* 12E560 8013DD60 00000000 */ .word 0x00000000
enddlabel loadfilecallback

nonmatching videopages

dlabel videopages
    /* 12E564 8013DD64 00000000 */ .word 0x00000000
enddlabel videopages

nonmatching videopage

dlabel videopage
    /* 12E568 8013DD68 00000000 */ .word 0x00000000
enddlabel videopage

nonmatching windowpage

dlabel windowpage
    /* 12E56C 8013DD6C 00000000 */ .word 0x00000000
enddlabel windowpage

nonmatching gpusetdispenv

dlabel gpusetdispenv
    /* 12E570 8013DD70 00000000 */ .word 0x00000000
enddlabel gpusetdispenv

nonmatching vblsetdispenv

dlabel vblsetdispenv
    /* 12E574 8013DD74 00000000 */ .word 0x00000000
enddlabel vblsetdispenv

nonmatching vsdeferred

dlabel vsdeferred
    /* 12E578 8013DD78 00000000 */ .word 0x00000000
enddlabel vsdeferred
