.include "macro.inc"
/* ============================================================
 * W63-A19  BLOB-vs-TU OWNERSHIP SWEEP -- SPLAT-LANE FILLER ONLY
 *
 * This segment's data is OWNED by
 *     build/recon/game/psx/trsproj.cpp.o
 * (section .sdata, retail 0x8013db9c..0x8013dba0), whose own bytes were
 * proved byte-identical to retail before the cut (ownmap.py E5).
 *
 * The RECON-lane linker script must link that object's .sdata here and must
 * NOT link this file -- otherwise every label below is multiply defined.
 * It stays in the tree only so the legacy splat-lane script
 * (linkers/nfs4.ld, which links build/src/**, where no recon object exists)
 * keeps producing a byte-identical .sdata image.
 * ============================================================ */

.section .sdata, "wa"

/* Generated by spimdisasm 1.40.2 */

nonmatching TrsProj_precision

dlabel TrsProj_precision
    /* 12E39C 8013DB9C 0A000000 */ .word 0x0000000A
enddlabel TrsProj_precision
