.include "macro.inc"
/* W64-A18: residual segment of sdata_8013C54C -- labels no recon TU defines
 * (or a record tail a recon TU's section stops short of).
 * Linked by BOTH lanes. */

.section .sdata, "wa"

/* Generated by spimdisasm 1.40.2 */

nonmatching font_clutx

dlabel font_clutx
    /* 12E054 8013D854 */ .short 0xFFFF
    /* 12E056 8013D856 */ .short 0xFFFF
enddlabel font_clutx

nonmatching font_cluty

dlabel font_cluty
    /* 12E058 8013D858 FFFFFFFF */ .word 0xFFFFFFFF
enddlabel font_cluty

nonmatching font_tint

dlabel font_tint
    /* 12E05C 8013D85C 80808066 */ .word 0x66808080
enddlabel font_tint

nonmatching font_abr

dlabel font_abr
    /* 12E060 8013D860 00000000 */ .word 0x00000000
enddlabel font_abr

nonmatching gFontClut

dlabel gFontClut
    /* 12E064 8013D864 */ .short 0x0000
enddlabel gFontClut

nonmatching gFontSpaceWidth

dlabel gFontSpaceWidth
    /* 12E066 8013D866 */ .byte 0x00
    /* 12E067 8013D867 */ .byte 0x00
enddlabel gFontSpaceWidth

nonmatching font_currentTPage

dlabel font_currentTPage
    /* 12E068 8013D868 */ .short 0x0000
    /* 12E06A 8013D86A */ .short 0x0000
enddlabel font_currentTPage
