.include "macro.inc"
/* W64-A18: residual segment of sdata_8013C54C -- labels no recon TU defines
 * (or a record tail a recon TU's section stops short of).
 * Linked by BOTH lanes. */

.section .sdata, "wa"

/* Generated by spimdisasm 1.40.2 */

nonmatching D_8013C5FC

dlabel D_8013C5FC
    /* 12CDFC 8013C5FC */ .asciz "%sA.viv"
    /* 2573412E76697600 */
.align 2
enddlabel D_8013C5FC

.align 2
nonmatching D_8013C604

dlabel D_8013C604
    /* 12CE04 8013C604 */ .asciz "Tr"
    /* 54720000 */
.align 2
enddlabel D_8013C604
