.include "macro.inc"
/* ============================================================
 * W64-A18  BLOB-vs-TU OWNERSHIP SWEEP -- SPLAT-LANE FILLER ONLY
 *
 * This segment's data is OWNED by
 *     build/recon/game/common/input.cpp.o
 * (section .sdata, retail 0x8013d220..0x8013d240), whose own bytes were
 * proved byte-identical to retail before the cut (ownmap2 E1-E5, with
 * R_MIPS_32 relocations RESOLVED against the retail VA map).
 *
 * The RECON-lane linker script must link that object's .sdata here and must
 * NOT link this file -- otherwise every label below is multiply defined.
 * It stays in the tree only so the legacy splat-lane script
 * (linkers/nfs4.ld, which links build/src/**, where no recon object exists)
 * keeps producing a byte-identical image.
 * ============================================================ */

.section .sdata, "wa"

/* Generated by spimdisasm 1.40.2 */

nonmatching Input_gTime

dlabel Input_gTime
    /* 12DA20 8013D220 00000000 */ .word 0x00000000
enddlabel Input_gTime

nonmatching Input_gResults

dlabel Input_gResults
    /* 12DA24 8013D224 00000000 */ .word 0x00000000
enddlabel Input_gResults

nonmatching D_8013D228

dlabel D_8013D228
    /* 12DA28 8013D228 00000000 */ .word 0x00000000
enddlabel D_8013D228

nonmatching Input_gSim

dlabel Input_gSim
    /* 12DA2C 8013D22C */ .byte 0x00
enddlabel Input_gSim

nonmatching D_8013D22D

dlabel D_8013D22D
    /* 12DA2D 8013D22D */ .byte 0x00
enddlabel D_8013D22D

nonmatching D_8013D22E

dlabel D_8013D22E
    /* 12DA2E 8013D22E */ .byte 0x00
enddlabel D_8013D22E

nonmatching D_8013D22F

dlabel D_8013D22F
    /* 12DA2F 8013D22F */ .byte 0x00
enddlabel D_8013D22F

nonmatching Input_gLookBehind

dlabel Input_gLookBehind
    /* 12DA30 8013D230 00000000 */ .word 0x00000000
    /* 12DA34 8013D234 00000000 */ .word 0x00000000
enddlabel Input_gLookBehind

nonmatching Input_gMode

dlabel Input_gMode
    /* 12DA38 8013D238 00000000 */ .word 0x00000000
    /* 12DA3C 8013D23C 00000000 */ .word 0x00000000
enddlabel Input_gMode
