.include "macro.inc"
/* W63-A19: residual segment of sdata_8013C54C -- labels no recon TU defines.
 * Linked by BOTH lanes. */

.section .sdata, "wa"

/* Generated by spimdisasm 1.40.2 */

nonmatching __sdata_org

dlabel __sdata_org
    /* 12CD4C 8013C54C 01000000 */ .word 0x00000001
enddlabel __sdata_org
