.include "macro.inc"
/* Legacy splat-lane filler.  The reconstruction lane now gets this exact
 * four-byte BOOL from pausemenu.cpp, its SYM-owning translation unit. */

.section .sdata, "wa"

/* Generated by spimdisasm 1.40.2 */

nonmatching ChangedEnabling

dlabel ChangedEnabling
    /* 12DAEC 8013D2EC 00000000 */ .word 0x00000000
enddlabel ChangedEnabling
