.include "macro.inc"
/* ============================================================
 * W64-A18  BLOB-vs-TU OWNERSHIP SWEEP -- SPLAT-LANE FILLER ONLY
 *
 * This segment's data is OWNED by
 *     build/recon/game/common/chunk.cpp.o
 * (section .sdata, retail 0x8013c818..0x8013c820), whose own bytes were
 * proved byte-identical to retail before the cut (ownmap2 E1-E5, with
 * R_MIPS_32 relocations RESOLVED against the retail VA map).
 *
 * The RECON-lane linker script must link that object's .sdata here and must
 * NOT link this file -- otherwise every label below is multiply defined.
 * It stays in the tree only so the legacy splat-lane script
 * (linkers/nfs4.ld, which links build/src/**, where no recon object exists)
 * keeps producing a byte-identical image.
 * ============================================================ */

.section .sdata, "wa"

/* Generated by spimdisasm 1.40.2 */

nonmatching Chunk_lightTable

dlabel Chunk_lightTable
    /* 12D018 8013C818 00000000 */ .word 0x00000000
enddlabel Chunk_lightTable

nonmatching Chunk_chunkCenters

dlabel Chunk_chunkCenters
    /* 12D01C 8013C81C 00000000 */ .word 0x00000000
enddlabel Chunk_chunkCenters
