.include "macro.inc"
/* W64-A18: residual segment of sdata_8013C54C -- labels no recon TU defines
 * (or a record tail a recon TU's section stops short of).
 * Linked by BOTH lanes. */

.section .sdata.r10_pre_new, "wa"

/* Generated by spimdisasm 1.40.2 */

nonmatching gMPauseUpdateNextTime

dlabel gMPauseUpdateNextTime
    /* 12DA40 8013D240 00000000 */ .word 0x00000000
enddlabel gMPauseUpdateNextTime

nonmatching InGameSelectListAudioMode

dlabel InGameSelectListAudioMode
    /* 12DA44 8013D244 12001100 */ .word 0x00110012
    /* 12DA48 8013D248 13000000 */ .word 0x00000013
enddlabel InGameSelectListAudioMode

nonmatching SelectListConfig

dlabel SelectListConfig
    /* 12DA4C 8013D24C 17001800 */ .word 0x00180017
    /* 12DA50 8013D250 19000000 */ .word 0x00000019
enddlabel SelectListConfig

nonmatching D_8013D254

dlabel D_8013D254
    /* 12DA54 8013D254 00000000 */ .word 0x00000000
enddlabel D_8013D254

nonmatching D_8013D258

dlabel D_8013D258
    /* 12DA58 8013D258 7F000000 */ .word 0x0000007F
enddlabel D_8013D258

nonmatching D_8013D25C

dlabel D_8013D25C
    /* 12DA5C 8013D25C 00000000 */ .word 0x00000000
enddlabel D_8013D25C

nonmatching D_8013D260

dlabel D_8013D260
    /* 12DA60 8013D260 00000000 */ .word 0x00000000
enddlabel D_8013D260

nonmatching gMPauseUpdate

dlabel gMPauseUpdate
    /* 12DA64 8013D264 00000000 */ .word 0x00000000
enddlabel gMPauseUpdate

nonmatching gPauseMenuDefs

dlabel gPauseMenuDefs
    /* 12DA68 8013D268 00000000 */ .word 0x00000000
enddlabel gPauseMenuDefs

.section .sdata.r10_new_legacy, "wa"

nonmatching New_cplusplus_heap

dlabel New_cplusplus_heap
    /* 12DA6C 8013D26C 00000000 */ .word 0x00000000
enddlabel New_cplusplus_heap

.section .sdata.r10_after_new, "wa"

nonmatching gMusicInSimIsOn

dlabel gMusicInSimIsOn
    /* 12DA70 8013D270 01000000 */ .word 0x00000001
enddlabel gMusicInSimIsOn

nonmatching gUseFrontend

dlabel gUseFrontend
    /* 12DA74 8013D274 01000000 */ .word 0x00000001
enddlabel gUseFrontend

nonmatching gFECheats

dlabel gFECheats
    /* 12DA78 8013D278 00000000 */ .word 0x00000000
enddlabel gFECheats

nonmatching gFEBonus

dlabel gFEBonus
    /* 12DA7C 8013D27C 00000000 */ .word 0x00000000
enddlabel gFEBonus

nonmatching gFEBigHandle

dlabel gFEBigHandle
    /* 12DA80 8013D280 00000000 */ .word 0x00000000
enddlabel gFEBigHandle

nonmatching MEMCARDFRONTENDISINITTED

dlabel MEMCARDFRONTENDISINITTED
    /* 12DA84 8013D284 00000000 */ .word 0x00000000
enddlabel MEMCARDFRONTENDISINITTED

nonmatching gCheckTotalTime

dlabel gCheckTotalTime
    /* 12DA88 8013D288 */ .byte 0x01
enddlabel gCheckTotalTime

nonmatching gCheckLapTime

dlabel gCheckLapTime
    /* 12DA89 8013D289 */ .byte 0x01
enddlabel gCheckLapTime

nonmatching gUpdateTournamentInfoFlag

dlabel gUpdateTournamentInfoFlag
    /* 12DA8A 8013D28A */ .byte 0x01
enddlabel gUpdateTournamentInfoFlag

nonmatching gUpdateKnockoutInfoFlag

dlabel gUpdateKnockoutInfoFlag
    /* 12DA8B 8013D28B */ .byte 0x01
enddlabel gUpdateKnockoutInfoFlag

nonmatching gKnockOutSpeechFlag

dlabel gKnockOutSpeechFlag
    /* 12DA8C 8013D28C */ .byte 0x01
enddlabel gKnockOutSpeechFlag

nonmatching gCalculateVictory

dlabel gCalculateVictory
    /* 12DA8D 8013D28D */ .byte 0x01
    /* 12DA8E 8013D28E */ .short 0x0000
enddlabel gCalculateVictory

nonmatching gPlayerEnteredNameAlready

dlabel gPlayerEnteredNameAlready
    /* 12DA90 8013D290 00000000 */ .word 0x00000000
enddlabel gPlayerEnteredNameAlready

.align 2
nonmatching D_8013D294

dlabel D_8013D294
    /* 12DA94 8013D294 */ .asciz "%s%s"
    /* 2573257300000000 */
.align 2
enddlabel D_8013D294

.align 2
nonmatching D_8013D29C

dlabel D_8013D29C
    /* 12DA9C 8013D29C */ .asciz "ymus"
    /* 796D757300000000 */
.align 2
enddlabel D_8013D29C

.align 2
nonmatching D_8013D2A4

dlabel D_8013D2A4
    /* 12DAA4 8013D2A4 */ .asciz "win*"
    /* 77696E2A00000000 */
.align 2
enddlabel D_8013D2A4

.align 2
nonmatching D_8013D2AC

dlabel D_8013D2AC
    /* 12DAAC 8013D2AC */ .asciz "lose*"
    /* 6C6F73652A000000 */
.align 2
enddlabel D_8013D2AC

nonmatching nfs_sysInfo

dlabel nfs_sysInfo
    /* 12DAB4 8013D2B4 00000000 */ .word 0x00000000
enddlabel nfs_sysInfo

nonmatching missionManager

dlabel missionManager
    /* 12DAB8 8013D2B8 00000000 */ .word 0x00000000
    /* 12DABC 8013D2BC 00000000 */ .word 0x00000000
enddlabel missionManager

nonmatching finishOrder

dlabel finishOrder
    /* 12DAC0 8013D2C0 00000000 */ .word 0x00000000
    /* 12DAC4 8013D2C4 00000000 */ .word 0x00000000
enddlabel finishOrder
