.include "macro.inc"
/* W64-A18: residual segment of sdata_8013C54C -- labels no recon TU defines
 * (or a record tail a recon TU's section stops short of).
 * Linked by BOTH lanes. */

.section .sdata.r15_pre_simqueue, "wa"

/* Generated by spimdisasm 1.40.2 */

nonmatching InBetween

dlabel InBetween
    /* 12DC0C 8013D40C 00000000 */ .word 0x00000000
enddlabel InBetween

.align 2
nonmatching D_8013D410

dlabel D_8013D410
    /* 12DC10 8013D410 */ .asciz "Sc32-1"
    /* 536333322D310000 */
.align 2
enddlabel D_8013D410

.align 2
nonmatching D_8013D418

dlabel D_8013D418
    /* 12DC18 8013D418 */ .asciz "Sc32-2"
    /* 536333322D320000 */
.align 2
enddlabel D_8013D418

.align 2
nonmatching D_8013D420

dlabel D_8013D420
    /* 12DC20 8013D420 */ .asciz "Sc64"
    /* 5363363400000000 */
.align 2
enddlabel D_8013D420

nonmatching unPauseDelay

dlabel unPauseDelay
    /* 12DC28 8013D428 00000000 */ .word 0x00000000
enddlabel unPauseDelay

nonmatching skipRender

dlabel skipRender
    /* 12DC2C 8013D42C 00000000 */ .word 0x00000000
enddlabel skipRender

nonmatching quitType

dlabel quitType
    /* 12DC30 8013D430 00000000 */ .word 0x00000000
enddlabel quitType

.section .sdata.r15_simqueue_legacy, "wa"

nonmatching gSimQueue_Ticker

dlabel gSimQueue_Ticker
    /* 12DC34 8013D434 FFFFFFFF */ .word 0xFFFFFFFF
enddlabel gSimQueue_Ticker

nonmatching gSimQueue_BlockSelf

dlabel gSimQueue_BlockSelf
    /* 12DC38 8013D438 01000000 */ .word 0x00000001
enddlabel gSimQueue_BlockSelf

nonmatching gSimQueue_BlockOther

dlabel gSimQueue_BlockOther
    /* 12DC3C 8013D43C 01000000 */ .word 0x00000001
enddlabel gSimQueue_BlockOther

.section .sdata.r15_after_simqueue, "wa"

.align 2
nonmatching D_8013D440

dlabel D_8013D440
    /* 12DC40 8013D440 */ .asciz "souffle"
    /* 736F7566666C6500 */
.align 2
enddlabel D_8013D440
