.include "macro.inc"
/* W63-A19: residual segment of sdata_8013C54C -- labels no recon TU defines.
 * Linked by BOTH lanes. */

.section .sdata, "wa"

/* Generated by spimdisasm 1.40.2 */

nonmatching R3DCar_InMenu

dlabel R3DCar_InMenu
    /* 12DB24 8013D324 00000000 */ .word 0x00000000
enddlabel R3DCar_InMenu

.align 2
nonmatching D_8013D328

dlabel D_8013D328
    /* 12DB28 8013D328 */ .asciz "sub_ot0"
    /* 7375625F6F743000 */
.align 2
enddlabel D_8013D328

.align 2
nonmatching D_8013D330

dlabel D_8013D330
    /* 12DB30 8013D330 */ .asciz "sub_ot1"
    /* 7375625F6F743100 */
.align 2
enddlabel D_8013D330

.align 2
nonmatching D_8013D338

dlabel D_8013D338
    /* 12DB38 8013D338 */ .asciz ".geo"
    /* 2E67656F00000000 */
.align 2
enddlabel D_8013D338

.align 2
nonmatching D_8013D340

dlabel D_8013D340
    /* 12DB40 8013D340 */ .asciz ".psh"
    /* 2E70736800000000 */
.align 2
enddlabel D_8013D340

.align 2
nonmatching D_8013D348

dlabel D_8013D348
    /* 12DB48 8013D348 */ .asciz "bigfile"
    /* 62696766696C6500 */
.align 2
enddlabel D_8013D348

.align 2
nonmatching D_8013D350

dlabel D_8013D350
    /* 12DB50 8013D350 */ .asciz "zz%s"
    /* 7A7A257300000000 */
.align 2
enddlabel D_8013D350

.align 2
nonmatching D_8013D358

dlabel D_8013D358
    /* 12DB58 8013D358 */ .asciz "h"
    /* 68000000 */
.align 2
enddlabel D_8013D358

.align 2
nonmatching D_8013D35C

dlabel D_8013D35C
    /* 12DB5C 8013D35C */ .asciz "s"
    /* 73000000 */
.align 2
enddlabel D_8013D35C

.align 2
nonmatching D_8013D360

dlabel D_8013D360
    /* 12DB60 8013D360 */ .asciz ".viv"
    /* 2E76697600000000 */
.align 2
enddlabel D_8013D360

.align 2
nonmatching D_8013D368

dlabel D_8013D368
    /* 12DB68 8013D368 */ .asciz "palCopy"
    /* 70616C436F707900 */
.align 2
enddlabel D_8013D368

nonmatching D_8013D370

dlabel D_8013D370
    /* 12DB70 8013D370 00000000 */ .word 0x00000000
enddlabel D_8013D370

.align 2
nonmatching D_8013D374

dlabel D_8013D374
    /* 12DB74 8013D374 */ .asciz "i"
    /* 69000000 */
.align 2
enddlabel D_8013D374

.align 2
nonmatching D_8013D378

dlabel D_8013D378
    /* 12DB78 8013D378 */ .asciz "d"
    /* 64000000 */
.align 2
enddlabel D_8013D378

.align 2
nonmatching D_8013D37C

dlabel D_8013D37C
    /* 12DB7C 8013D37C */ .asciz "l"
    /* 6C000000 */
.align 2
enddlabel D_8013D37C

.align 2
nonmatching D_8013D380

dlabel D_8013D380
    /* 12DB80 8013D380 */ .asciz "g"
    /* 67000000 */
.align 2
enddlabel D_8013D380

nonmatching R3DCar_aSyncLoading

dlabel R3DCar_aSyncLoading
    /* 12DB84 8013D384 00000000 */ .word 0x00000000
enddlabel R3DCar_aSyncLoading

nonmatching R3DCar_orientMat

dlabel R3DCar_orientMat
    /* 12DB88 8013D388 00000000 */ .word 0x00000000
enddlabel R3DCar_orientMat

nonmatching R3DCar_position

dlabel R3DCar_position
    /* 12DB8C 8013D38C 00000000 */ .word 0x00000000
enddlabel R3DCar_position

nonmatching R3DCar_center

dlabel R3DCar_center
    /* 12DB90 8013D390 00000000 */ .word 0x00000000
    /* 12DB94 8013D394 00000000 */ .word 0x00000000
enddlabel R3DCar_center

nonmatching R3DCar_shadowFlag

dlabel R3DCar_shadowFlag
    /* 12DB98 8013D398 00000000 */ .word 0x00000000
enddlabel R3DCar_shadowFlag

nonmatching R3DCar_shadowColour

dlabel R3DCar_shadowColour
    /* 12DB9C 8013D39C */ .byte 0x00
enddlabel R3DCar_shadowColour

nonmatching D_8013D39D

dlabel D_8013D39D
    /* 12DB9D 8013D39D */ .byte 0x00
enddlabel D_8013D39D

nonmatching D_8013D39E

dlabel D_8013D39E
    /* 12DB9E 8013D39E */ .byte 0x00
    /* 12DB9F 8013D39F */ .byte 0x00
enddlabel D_8013D39E

nonmatching R3DCar_eMapColour

dlabel R3DCar_eMapColour
    /* 12DBA0 8013D3A0 */ .byte 0x00
enddlabel R3DCar_eMapColour

nonmatching D_8013D3A1

dlabel D_8013D3A1
    /* 12DBA1 8013D3A1 */ .byte 0x00
enddlabel D_8013D3A1

nonmatching D_8013D3A2

dlabel D_8013D3A2
    /* 12DBA2 8013D3A2 */ .byte 0x00
    /* 12DBA3 8013D3A3 */ .byte 0x00
enddlabel D_8013D3A2

nonmatching R3DCar_yawCam

dlabel R3DCar_yawCam
    /* 12DBA4 8013D3A4 */ .short 0x0000
    /* 12DBA6 8013D3A6 */ .short 0x0000
enddlabel R3DCar_yawCam

nonmatching R3DCar_Clock

dlabel R3DCar_Clock
    /* 12DBA8 8013D3A8 00000000 */ .word 0x00000000
enddlabel R3DCar_Clock

nonmatching R3DCar_ClockLast

dlabel R3DCar_ClockLast
    /* 12DBAC 8013D3AC 00000000 */ .word 0x00000000
enddlabel R3DCar_ClockLast

nonmatching R3DCar_BigFile

dlabel R3DCar_BigFile
    /* 12DBB0 8013D3B0 00000000 */ .word 0x00000000
enddlabel R3DCar_BigFile

nonmatching R3DCar_LicenseShapeFile

dlabel R3DCar_LicenseShapeFile
    /* 12DBB4 8013D3B4 00000000 */ .word 0x00000000
enddlabel R3DCar_LicenseShapeFile

nonmatching R3DCar_subOt

dlabel R3DCar_subOt
    /* 12DBB8 8013D3B8 00000000 */ .word 0x00000000
enddlabel R3DCar_subOt

nonmatching R3DCar_rightHandDrive

dlabel R3DCar_rightHandDrive
    /* 12DBBC 8013D3BC 00000000 */ .word 0x00000000
enddlabel R3DCar_rightHandDrive

nonmatching Render_gBlurEffectDepth1

dlabel Render_gBlurEffectDepth1
    /* 12DBC0 8013D3C0 00000000 */ .word 0x00000000
enddlabel Render_gBlurEffectDepth1

nonmatching Render_gBlurEffectDepth2

dlabel Render_gBlurEffectDepth2
    /* 12DBC4 8013D3C4 00000000 */ .word 0x00000000
enddlabel Render_gBlurEffectDepth2

nonmatching Render_gBlurEffectMode

dlabel Render_gBlurEffectMode
    /* 12DBC8 8013D3C8 00000000 */ .word 0x00000000
enddlabel Render_gBlurEffectMode

nonmatching Draw_gPlayer1View

dlabel Draw_gPlayer1View
    /* 12DBCC 8013D3CC 00000000 */ .word 0x00000000
enddlabel Draw_gPlayer1View

nonmatching Draw_gPlayer2View

dlabel Draw_gPlayer2View
    /* 12DBD0 8013D3D0 00000000 */ .word 0x00000000
enddlabel Draw_gPlayer2View

nonmatching gPauseMenuRect

dlabel gPauseMenuRect
    /* 12DBD4 8013D3D4 */ .short 0x0000
enddlabel gPauseMenuRect

nonmatching D_8013D3D6

dlabel D_8013D3D6
    /* 12DBD6 8013D3D6 */ .short 0x0000
enddlabel D_8013D3D6

nonmatching D_8013D3D8

dlabel D_8013D3D8
    /* 12DBD8 8013D3D8 */ .short 0x0000
enddlabel D_8013D3D8

nonmatching D_8013D3DA

dlabel D_8013D3DA
    /* 12DBDA 8013D3DA */ .short 0x0000
enddlabel D_8013D3DA

nonmatching gPauseRender

dlabel gPauseRender
    /* 12DBDC 8013D3DC 00000000 */ .word 0x00000000
enddlabel gPauseRender

nonmatching Draw_gRearView

dlabel Draw_gRearView
    /* 12DBE0 8013D3E0 00000000 */ .word 0x00000000
enddlabel Draw_gRearView

nonmatching Render_gDebugView

dlabel Render_gDebugView
    /* 12DBE4 8013D3E4 00000000 */ .word 0x00000000
enddlabel Render_gDebugView

nonmatching Render_gPauseMenuView

dlabel Render_gPauseMenuView
    /* 12DBE8 8013D3E8 00000000 */ .word 0x00000000
enddlabel Render_gPauseMenuView

nonmatching Replay_Size

dlabel Replay_Size
    /* 12DBEC 8013D3EC 00000000 */ .word 0x00000000
enddlabel Replay_Size

nonmatching numValidCams

dlabel numValidCams
    /* 12DBF0 8013D3F0 00000000 */ .word 0x00000000
enddlabel numValidCams

nonmatching Replay_ReplayMode

dlabel Replay_ReplayMode
    /* 12DBF4 8013D3F4 00000000 */ .word 0x00000000
enddlabel Replay_ReplayMode

nonmatching Replay_ReplayStorePtr

dlabel Replay_ReplayStorePtr
    /* 12DBF8 8013D3F8 00000000 */ .word 0x00000000
enddlabel Replay_ReplayStorePtr

nonmatching Replay_ReplayGetPtr

dlabel Replay_ReplayGetPtr
    /* 12DBFC 8013D3FC 00000000 */ .word 0x00000000
enddlabel Replay_ReplayGetPtr

nonmatching Replay_ReplayCounter

dlabel Replay_ReplayCounter
    /* 12DC00 8013D400 00000000 */ .word 0x00000000
enddlabel Replay_ReplayCounter

nonmatching D_8013D404

dlabel D_8013D404
    /* 12DC04 8013D404 00000000 */ .word 0x00000000
enddlabel D_8013D404
