.include "macro.inc"
/* W64-A18: residual segment of sdata_8013C54C -- labels no recon TU defines
 * (or a record tail a recon TU's section stops short of).
 * Linked by BOTH lanes. */

.section .sdata, "wa"

/* Generated by spimdisasm 1.40.2 */

nonmatching wordFile

dlabel wordFile
    /* 12DC58 8013D458 00000000 */ .word 0x00000000
enddlabel wordFile

.align 2
nonmatching D_8013D45C

dlabel D_8013D45C
    /* 12DC5C 8013D45C */ .asciz "%s%s"
    /* 2573257300000000 */
.align 2
enddlabel D_8013D45C

.align 2
nonmatching D_8013D464

dlabel D_8013D464
    /* 12DC64 8013D464 */ .asciz "p"
    /* 70000000 */
.align 2
enddlabel D_8013D464

.align 2
nonmatching D_8013D468

dlabel D_8013D468
    /* 12DC68 8013D468 */ .asciz "S0.psh"
    /* 53302E7073680000 */
.align 2
enddlabel D_8013D468

.align 2
nonmatching D_8013D470

dlabel D_8013D470
    /* 12DC70 8013D470 */ .asciz "N0.psh"
    /* 4E302E7073680000 */
.align 2
enddlabel D_8013D470

.align 2
nonmatching D_8013D478

dlabel D_8013D478
    /* 12DC78 8013D478 */ .asciz "W0.psh"
    /* 57302E7073680000 */
.align 2
enddlabel D_8013D478

.align 2
nonmatching D_8013D480

dlabel D_8013D480
    /* 12DC80 8013D480 */ .asciz "0.psh"
    /* 302E707368000000 */
.align 2
enddlabel D_8013D480

.align 2
nonmatching D_8013D488

dlabel D_8013D488
    /* 12DC88 8013D488 */ .asciz "r.psh"
    /* 722E707368000000 */
.align 2
enddlabel D_8013D488

.align 2
nonmatching D_8013D490

dlabel D_8013D490
    /* 12DC90 8013D490 */ .asciz "%s"
    /* 25730000 */
.align 2
enddlabel D_8013D490

.align 2
nonmatching D_8013D494

dlabel D_8013D494
    /* 12DC94 8013D494 */ .asciz ".grp"
    /* 2E67727000000000 */
.align 2
enddlabel D_8013D494

.align 2
nonmatching D_8013D49C

dlabel D_8013D49C
    /* 12DC9C 8013D49C */ .asciz "bsphere"
    /* 6273706865726500 */
.align 2
enddlabel D_8013D49C

.align 2
nonmatching D_8013D4A4

dlabel D_8013D4A4
    /* 12DCA4 8013D4A4 */ .asciz ".kil"
    /* 2E6B696C00000000 */
.align 2
enddlabel D_8013D4A4

nonmatching Track_gInViewList

dlabel Track_gInViewList
    /* 12DCAC 8013D4AC 00000000 */ .word 0x00000000
enddlabel Track_gInViewList

nonmatching Track_gInViewCount

dlabel Track_gInViewCount
    /* 12DCB0 8013D4B0 00000000 */ .word 0x00000000
enddlabel Track_gInViewCount

nonmatching Track_header

dlabel Track_header
    /* 12DCB4 8013D4B4 00000000 */ .word 0x00000000
enddlabel Track_header

nonmatching Track_chunkList

dlabel Track_chunkList
    /* 12DCB8 8013D4B8 00000000 */ .word 0x00000000
enddlabel Track_chunkList

nonmatching gPersistObjDef

dlabel gPersistObjDef
    /* 12DCBC 8013D4BC 00000000 */ .word 0x00000000
enddlabel gPersistObjDef

nonmatching gPersistObjInst

dlabel gPersistObjInst
    /* 12DCC0 8013D4C0 00000000 */ .word 0x00000000
enddlabel gPersistObjInst

nonmatching gPersistMidgroundObjInst

dlabel gPersistMidgroundObjInst
    /* 12DCC4 8013D4C4 00000000 */ .word 0x00000000
enddlabel gPersistMidgroundObjInst

nonmatching gPersistObjDefBoundingSpheres

dlabel gPersistObjDefBoundingSpheres
    /* 12DCC8 8013D4C8 00000000 */ .word 0x00000000
enddlabel gPersistObjDefBoundingSpheres

nonmatching Track_gSaveSurface

dlabel Track_gSaveSurface
    /* 12DCCC 8013D4CC 00000000 */ .word 0x00000000
enddlabel Track_gSaveSurface

nonmatching Track_materials

dlabel Track_materials
    /* 12DCD0 8013D4D0 00000000 */ .word 0x00000000
enddlabel Track_materials

nonmatching Track_gObjDefs

dlabel Track_gObjDefs
    /* 12DCD4 8013D4D4 00000000 */ .word 0x00000000
enddlabel Track_gObjDefs

nonmatching Track_mem

dlabel Track_mem
    /* 12DCD8 8013D4D8 00000000 */ .word 0x00000000
enddlabel Track_mem

nonmatching gtrackNumber

dlabel gtrackNumber
    /* 12DCDC 8013D4DC 00000000 */ .word 0x00000000
enddlabel gtrackNumber

nonmatching gObjDefOffsetsGroup

dlabel gObjDefOffsetsGroup
    /* 12DCE0 8013D4E0 00000000 */ .word 0x00000000
enddlabel gObjDefOffsetsGroup

nonmatching Track_gControllerCount

dlabel Track_gControllerCount
    /* 12DCE4 8013D4E4 00000000 */ .word 0x00000000
enddlabel Track_gControllerCount

nonmatching Track_gMatController

dlabel Track_gMatController
    /* 12DCE8 8013D4E8 00000000 */ .word 0x00000000
enddlabel Track_gMatController

nonmatching Chunk_numLight

dlabel Chunk_numLight
    /* 12DCEC 8013D4EC 00000000 */ .word 0x00000000
enddlabel Chunk_numLight
