.include "macro.inc"
/* ============================================================
 * W64-A18  BLOB-vs-TU OWNERSHIP SWEEP -- SPLAT-LANE FILLER ONLY
 *
 * This segment's data is OWNED by
 *     build/recon/game/common/cars.cpp.o
 * (section .sdata, retail 0x8013c7e0..0x8013c818), whose own bytes were
 * proved byte-identical to retail before the cut (ownmap2 E1-E5, with
 * R_MIPS_32 relocations RESOLVED against the retail VA map).
 *
 * The RECON-lane linker script must link that object's .sdata here and must
 * NOT link this file -- otherwise every label below is multiply defined.
 * It stays in the tree only so the legacy splat-lane script
 * (linkers/nfs4.ld, which links build/src/**, where no recon object exists)
 * keeps producing a byte-identical image.
 * ============================================================ */

.section .sdata, "wa"

/* Generated by spimdisasm 1.40.2 */

nonmatching D_8013C7E0

dlabel D_8013C7E0
    /* 12CFE0 8013C7E0 00000000 */ .word 0x00000000
enddlabel D_8013C7E0

nonmatching frontLimit

dlabel frontLimit
    /* 12CFE4 8013C7E4 00800000 */ .word 0x00008000
enddlabel frontLimit

nonmatching rearLimit

dlabel rearLimit
    /* 12CFE8 8013C7E8 00000100 */ .word 0x00010000
enddlabel rearLimit

.align 2
nonmatching D_8013C7EC

dlabel D_8013C7EC
    /* 12CFEC 8013C7EC */ .asciz "p%s.dat"
    /* 7025732E64617400 */
.align 2
enddlabel D_8013C7EC

nonmatching Cars_gNumCars

dlabel Cars_gNumCars
    /* 12CFF4 8013C7F4 00000000 */ .word 0x00000000
enddlabel Cars_gNumCars

nonmatching Cars_gNumRaceCars

dlabel Cars_gNumRaceCars
    /* 12CFF8 8013C7F8 */ .short 0x0000
    /* 12CFFA 8013C7FA */ .short 0x0000
enddlabel Cars_gNumRaceCars

nonmatching Cars_gNumAICars

dlabel Cars_gNumAICars
    /* 12CFFC 8013C7FC 00000000 */ .word 0x00000000
enddlabel Cars_gNumAICars

nonmatching Cars_gNumHumanRaceCars

dlabel Cars_gNumHumanRaceCars
    /* 12D000 8013C800 00000000 */ .word 0x00000000
enddlabel Cars_gNumHumanRaceCars

nonmatching Cars_gNumAIRaceCars

dlabel Cars_gNumAIRaceCars
    /* 12D004 8013C804 00000000 */ .word 0x00000000
enddlabel Cars_gNumAIRaceCars

nonmatching Cars_gNumTrafficCars

dlabel Cars_gNumTrafficCars
    /* 12D008 8013C808 00000000 */ .word 0x00000000
enddlabel Cars_gNumTrafficCars

nonmatching Cars_gNumCopCars

dlabel Cars_gNumCopCars
    /* 12D00C 8013C80C 00000000 */ .word 0x00000000
enddlabel Cars_gNumCopCars

nonmatching Cars_gNumLifeBasisCars

dlabel Cars_gNumLifeBasisCars
    /* 12D010 8013C810 00000000 */ .word 0x00000000
enddlabel Cars_gNumLifeBasisCars

nonmatching accidentSlice

dlabel accidentSlice
    /* 12D014 8013C814 00000000 */ .word 0x00000000
enddlabel accidentSlice
