.include "macro.inc"
/* W64-A18: residual segment of sdata_8013C54C -- labels no recon TU defines
 * (or a record tail a recon TU's section stops short of).
 * Linked by BOTH lanes. */

.section .sdata, "wa"

/* Generated by spimdisasm 1.40.2 */

nonmatching SceneLoaded

dlabel SceneLoaded
    /* 12CF58 8013C758 00000000 */ .word 0x00000000
enddlabel SceneLoaded

nonmatching D_8013C75C

dlabel D_8013C75C
    /* 12CF5C 8013C75C 00000000 */ .word 0x00000000
enddlabel D_8013C75C

nonmatching D_8013C760

dlabel D_8013C760
    /* 12CF60 8013C760 00000000 */ .word 0x00000000
enddlabel D_8013C760

.align 2
nonmatching D_8013C764

dlabel D_8013C764
    /* 12CF64 8013C764 */ .asciz "bworld"
    /* 62776F726C640000 */
.align 2
enddlabel D_8013C764

.align 2
nonmatching D_8013C76C

dlabel D_8013C76C
    /* 12CF6C 8013C76C */ .asciz "S.grp"
    /* 532E677270000000 */
.align 2
enddlabel D_8013C76C

.align 2
nonmatching D_8013C774

dlabel D_8013C774
    /* 12CF74 8013C774 */ .asciz "N.grp"
    /* 4E2E677270000000 */
.align 2
enddlabel D_8013C774

.align 2
nonmatching D_8013C77C

dlabel D_8013C77C
    /* 12CF7C 8013C77C */ .asciz "W.grp"
    /* 572E677270000000 */
.align 2
enddlabel D_8013C77C

.align 2
nonmatching D_8013C784

dlabel D_8013C784
    /* 12CF84 8013C784 */ .asciz ".grp"
    /* 2E67727000000000 */
.align 2
enddlabel D_8013C784

nonmatching D_8013C78C

dlabel D_8013C78C
    /* 12CF8C 8013C78C 00000000 */ .word 0x00000000
enddlabel D_8013C78C

nonmatching gCurrContext

dlabel gCurrContext
    /* 12CF90 8013C790 00000000 */ .word 0x00000000
enddlabel gCurrContext

nonmatching gSpikeBelt

dlabel gSpikeBelt
    /* 12CF94 8013C794 00000000 */ .word 0x00000000
enddlabel gSpikeBelt

nonmatching gSpikeBeltSlice

dlabel gSpikeBeltSlice
    /* 12CF98 8013C798 00000000 */ .word 0x00000000
enddlabel gSpikeBeltSlice

nonmatching gSpikeBeltChunk

dlabel gSpikeBeltChunk
    /* 12CF9C 8013C79C 00000000 */ .word 0x00000000
enddlabel gSpikeBeltChunk

nonmatching gSpikeBeltX

dlabel gSpikeBeltX
    /* 12CFA0 8013C7A0 00000000 */ .word 0x00000000
enddlabel gSpikeBeltX

nonmatching gBWSlice

dlabel gBWSlice
    /* 12CFA4 8013C7A4 00000000 */ .word 0x00000000
enddlabel gBWSlice

nonmatching BWorld_gChunkCount

dlabel BWorld_gChunkCount
    /* 12CFA8 8013C7A8 00000000 */ .word 0x00000000
enddlabel BWorld_gChunkCount

nonmatching gSpikeBeltWidth

dlabel gSpikeBeltWidth
    /* 12CFAC 8013C7AC 00000000 */ .word 0x00000000
enddlabel gSpikeBeltWidth

nonmatching gSpikeBeltColourTableIndex

dlabel gSpikeBeltColourTableIndex
    /* 12CFB0 8013C7B0 00000000 */ .word 0x00000000
enddlabel gSpikeBeltColourTableIndex

nonmatching BW_gCopCarObj

dlabel BW_gCopCarObj
    /* 12CFB4 8013C7B4 00000000 */ .word 0x00000000
enddlabel BW_gCopCarObj

nonmatching gVi2

dlabel gVi2
    /* 12CFB8 8013C7B8 00000000 */ .word 0x00000000
enddlabel gVi2
