.include "macro.inc"
/* W63-A19: residual segment of sdata_8013C54C -- labels no recon TU defines.
 * Linked by BOTH lanes. */

.section .sdata, "wa"

/* Generated by spimdisasm 1.40.2 */

nonmatching gBlockadeTypes

dlabel gBlockadeTypes
    /* 12CD68 8013C568 05060402 */ .word 0x02040605
    /* 12CD6C 8013C56C 00000000 */ .word 0x00000000
enddlabel gBlockadeTypes
