.include "macro.inc"
/* W64-A18: residual segment of sdata_8013C54C -- labels no recon TU defines
 * (or a record tail a recon TU's section stops short of).
 * Linked by BOTH lanes. */

.section .sdata, "wa"

/* Generated by spimdisasm 1.40.2 */

nonmatching burnPath

dlabel burnPath
    /* 12DAE0 8013D2E0 */ .asciz "z"
    /* 7A000000 */
.align 2
enddlabel burnPath

nonmatching fePath

dlabel fePath
    /* 12DAE4 8013D2E4 00000000 */ .word 0x00000000
enddlabel fePath
