.include "macro.inc"
/* W63-A19: residual segment of sdata_8013C54C -- labels no recon TU defines.
 * Linked by BOTH lanes. */

.section .sdata, "wa"

/* Generated by spimdisasm 1.40.2 */

nonmatching D_8013DD2C

dlabel D_8013DD2C
    /* 12E52C 8013DD2C */ .asciz "cdrom:"
    /* 6364726F6D3A0000 */
.align 2
enddlabel D_8013DD2C

nonmatching D_8013DD34

dlabel D_8013DD34
    /* 12E534 8013DD34 2CDD1380 */ .word D_8013DD2C
enddlabel D_8013DD34

.align 2
nonmatching D_8013DD38

dlabel D_8013DD38
    /* 12E538 8013DD38 */ .asciz "sim:"
    /* 73696D3A00000000 */
.align 2
enddlabel D_8013DD38

nonmatching D_8013DD40

dlabel D_8013DD40
    /* 12E540 8013DD40 38DD1380 */ .word D_8013DD38
enddlabel D_8013DD40

.align 2
nonmatching D_8013DD44

dlabel D_8013DD44
    /* 12E544 8013DD44 */ .asciz "\\"
    /* 5C000000 */
.align 2
enddlabel D_8013DD44

.align 2
nonmatching D_8013DD48

dlabel D_8013DD48
    /* 12E548 8013DD48 */ .asciz "RAM"
    /* 52414D00 */
.align 2
enddlabel D_8013DD48

nonmatching timerflag

dlabel timerflag
    /* 12E54C 8013DD4C 00000000 */ .word 0x00000000
enddlabel timerflag

nonmatching textntabstops

dlabel textntabstops
    /* 12E550 8013DD50 00000000 */ .word 0x00000000
enddlabel textntabstops

nonmatching texttabstops

dlabel texttabstops
    /* 12E554 8013DD54 00000000 */ .word 0x00000000
enddlabel texttabstops

nonmatching showmissingcharacters

dlabel showmissingcharacters
    /* 12E558 8013DD58 00000000 */ .word 0x00000000
enddlabel showmissingcharacters
