#include "common.h"

INCLUDE_ASM("asm/nonmatchings/main", Flare_Tri__FPlN20i);
INCLUDE_ASM("asm/nonmatchings/main", Flare_SetMatrix__FP10matrixtdef);
INCLUDE_ASM("asm/nonmatchings/main", Flare_OctFlare__FPli);
INCLUDE_ASM("asm/nonmatchings/main", Flare_OctFlareSpikes__FPli);
INCLUDE_ASM("asm/nonmatchings/main", Flare_Spikes__FPli);
INCLUDE_ASM("asm/nonmatchings/main", Flare_HexFlare__FPli);
INCLUDE_ASM("asm/nonmatchings/main", Flare_ReflectHexFlare__FPli);
INCLUDE_ASM("asm/nonmatchings/main", Flare_QuadFlare__FPli);
INCLUDE_ASM("asm/nonmatchings/main", Flare_CarShapedHalo__FiP7COORD16N21siP15Draw_FlareCache);
INCLUDE_ASM("asm/nonmatchings/main", Flare_Halo2__FP13DRender_tViewiiP8coorddefT3P15Draw_FlareCache);
INCLUDE_ASM("asm/nonmatchings/main", Flare_Halo__FP13DRender_tViewiiP8coorddefP15Draw_FlareCache);
INCLUDE_ASM("asm/nonmatchings/main", Flare_2DSpike__FPlT0i);
INCLUDE_ASM("asm/nonmatchings/main", Flare_2DHalo__Fiiiii);
INCLUDE_ASM("asm/nonmatchings/main", Flare_PreCalcHexLightBeam__FPli);
INCLUDE_ASM("asm/nonmatchings/main", Flare_Quad__FPlP7CVECTORi);
INCLUDE_ASM("asm/nonmatchings/main", Flare_QuadNotTransparent__FPlP7CVECTORi);
INCLUDE_ASM("asm/nonmatchings/main", Flare_QuadRing__FPlP7CVECTORi);
INCLUDE_ASM("asm/nonmatchings/main", Flare_TextureQuad__FPlP7CVECTORci);
INCLUDE_ASM("asm/nonmatchings/main", Flare_SingleColorTex__FP7DVECTORP7CVECTORiici);
INCLUDE_ASM("asm/nonmatchings/main", Flare_SingleColorHex__FP7DVECTORP7CVECTORiii);
INCLUDE_ASM("asm/nonmatchings/main", Flare_SingleColorOct__FP7DVECTORP7CVECTORiii);
INCLUDE_ASM("asm/nonmatchings/main", Flare_SingleColorOctRing__FP7DVECTORP7CVECTORiii);
INCLUDE_ASM("asm/nonmatchings/main", Flare_InitLensFlare__Fv);
INCLUDE_ASM("asm/nonmatchings/main", Flare_LensFlare__FP7DVECTORP15Draw_FlareCache);
INCLUDE_ASM("asm/nonmatchings/main", Flare_Sun__FP7SVECTORP15Draw_FlareCache);
INCLUDE_ASM("asm/nonmatchings/main", Flare_Moon__FP7SVECTORP15Draw_FlareCache);
INCLUDE_ASM("asm/nonmatchings/main", Flare_IdentMatrix__FP6MATRIX);
