#include "common.h"

INCLUDE_ASM("asm/nonmatchings/main", MemCardInit);
INCLUDE_ASM("asm/nonmatchings/main", MemCardEnd);
INCLUDE_ASM("asm/nonmatchings/main", MemCardStart);
INCLUDE_ASM("asm/nonmatchings/main", MemCardStop);
INCLUDE_ASM("asm/nonmatchings/main", MemCardExist);
INCLUDE_ASM("asm/nonmatchings/main", MemCardExist_cb);
INCLUDE_ASM("asm/nonmatchings/main", MemCardAccept);
INCLUDE_ASM("asm/nonmatchings/main", MemCardCmd_cb);
INCLUDE_ASM("asm/nonmatchings/main", MemCardReadData);
INCLUDE_ASM("asm/nonmatchings/main", MemCardReadData_cb);
INCLUDE_ASM("asm/nonmatchings/main", MemCardWriteData);
INCLUDE_ASM("asm/nonmatchings/main", MemCardWriteData_cb);
INCLUDE_ASM("asm/nonmatchings/main", MemCardReadFile);
INCLUDE_ASM("asm/nonmatchings/main", MemCardReadFile_cb);
INCLUDE_ASM("asm/nonmatchings/main", MemCardWriteFile);
INCLUDE_ASM("asm/nonmatchings/main", MemCardWriteFile_cb);
INCLUDE_ASM("asm/nonmatchings/main", MemCardGetDirentry);
INCLUDE_ASM("asm/nonmatchings/main", MemCardCallback);
INCLUDE_ASM("asm/nonmatchings/main", MemCardSync);
INCLUDE_ASM("asm/nonmatchings/main", MemCardCreateFile);
INCLUDE_ASM("asm/nonmatchings/main", MemCardDeleteFile);
INCLUDE_ASM("asm/nonmatchings/main", MemCardFormat);
INCLUDE_ASM("asm/nonmatchings/main", MemCardUnformat);
INCLUDE_ASM("asm/nonmatchings/main", MemCardEventToRslt);
INCLUDE_ASM("asm/nonmatchings/main", MemCardStart_cb);
INCLUDE_ASM("asm/nonmatchings/main", MemCardMakeDevname);
