/* game/common/fei.cpp -- RECONSTRUCTED data TU (src nfs4\GAME\COMMON\FEI.obj; sld FEL.H).
 *   DATA-ONLY: defines FEI_gList[114] (FEI_tList = {int v; int *p}) -- the FE input-binding table
 *   mapping an input value to a pointer-to-editable-global. EXT data @0x8011279c, 912 B, .data
 *   P906: all108 non-null pointers use typed native SYM names/field paths. The full912-byte
 *   table and every relocation match CPE/raw; exact original macro/token spellings remain unknown.
 *   Walk-skipped (data-only, no .text); found during library/runtime inventory closure. */
#include "../../nfs4_types.h"
#include "fei_externs.h"

FEI_tList FEI_gList[114] = {   /* @0x8011279c */
  { 1, (int *)0 },
  { 3, (int *)0 },
  { 4, (int *)0 },
  { 5, (int *)0 },
  { 6, &gUseFrontend },
  { 7, &GameSetup_gData.raceType },
  { 8, &GameSetup_gData.numLaps },
  { 9, &GameSetup_gData.skill },
  { 10, &GameSetup_gData.commMode },
  { 11, &GameSetup_gData.tournamentMultiplier },
  { 12, &GameSetup_gData.cops },
  { 13, &GameSetup_gData.trafficDensity },
  { 14, &GameSetup_gData.localCar },
  { 15, &GameSetup_gData.catchupLogic },
  { 16, &GameSetup_gData.sgge },
  { 17, &GameSetup_gData.easter },
  { 18, &GameSetup_gData.track },
  { 19, &GameSetup_gData.song },
  { 20, &GameSetup_gData.Weather },
  { 21, &GameSetup_gData.Fog },
  { 22, &GameSetup_gData.Damage },
  { 23, &GameSetup_gData.Time },
  { 24, &GameSetup_gData.mirrorTrack },
  { 25, &GameSetup_gData.reverseTrack },
  { 26, &GameSetup_gData.measurement },
  { 27, &GameSetup_gData.randSeed },
  { 28, &GameSetup_gData.numCars },
  { 29, &GameSetup_gData.numPlayerRaceCars },
  { 30, &GameSetup_gData.numOpponentRaceCars },
  { 31, &GameSetup_gData.opponentCarType },
  { 32, &GameSetup_gData.checkpointType },
  { 33, &GameSetup_gData.pinkSlipsForfeit },
  { 34, &GameSetup_gData.dispatchSpeech },
  { 35, &GameSetup_gData.reverseCallSpeech },
  { 36, &GameSetup_gData.languageSpeech },
  { 37, &GameSetup_gData.numPerps },
  { 38, &GameSetup_gData.stageOffset },
  { 39, &GameSetup_gData.userSetting.language },
  { 40, &GameSetup_gData.userSetting.display },
  { 41, &GameSetup_gData.userSetting.bestlap },
  { 42, &GameSetup_gData.userSetting.audioMode },
  { 43, &GameSetup_gData.userSetting.musicLevel },
  { 44, &GameSetup_gData.userSetting.sfxLevel },
  { 45, &GameSetup_gData.userSetting.engineLevel },
  { 46, &GameSetup_gData.userSetting.speechLevel },
  { 47, &GameSetup_gData.userSetting.ambientLevel },
  { 48, &GameSetup_gData.userSetting.numplaylistsongs },
  { 49, &GameSetup_gData.userSetting.interactive },
  { 50, &GameSetup_gData.checkpointHUD[0] },
  { 51, &GameSetup_gData.checkpointHUD[1] },
  { 52, &GameSetup_gData.controllerData.controllerConfig[0] },
  { 53, &GameSetup_gData.controllerData.deadSpot[0] },
  { 54, &GameSetup_gData.controllerData.steeringRange[0] },
  { 55, &GameSetup_gData.controllerData.IImaxRange[0] },
  { 56, &GameSetup_gData.controllerData.ImaxRange[0] },
  { 57, &GameSetup_gData.controllerData.J1MAX[0] },
  { 58, &GameSetup_gData.controllerData.J1MIN[0] },
  { 59, &GameSetup_gData.controllerData.J2MAX[0] },
  { 60, &GameSetup_gData.controllerData.J2MIN[0] },
  { 61, &GameSetup_gData.controllerData.shockMode[0] },
  { 62, &GameSetup_gData.controllerData.shockImpact[0] },
  { 63, &GameSetup_gData.controllerData.controllerConfig[1] },
  { 64, &GameSetup_gData.controllerData.deadSpot[1] },
  { 65, &GameSetup_gData.controllerData.steeringRange[1] },
  { 66, &GameSetup_gData.controllerData.IImaxRange[1] },
  { 67, &GameSetup_gData.controllerData.ImaxRange[1] },
  { 68, &GameSetup_gData.controllerData.J1MAX[1] },
  { 69, &GameSetup_gData.controllerData.J1MIN[1] },
  { 70, &GameSetup_gData.controllerData.J2MAX[1] },
  { 71, &GameSetup_gData.controllerData.J2MIN[1] },
  { 72, &GameSetup_gData.controllerData.shockMode[1] },
  { 73, &GameSetup_gData.controllerData.shockImpact[1] },
  { 74, &GameSetup_gData.replayMode },
  { 76, &GameSetup_gData.userSetting.playlist[0] },
  { 259, (int *)0 },
  { 260, &GameSetup_gData.carInfo[0].carType },
  { 261, &GameSetup_gData.carInfo[0].carClass },
  { 262, &GameSetup_gData.carInfo[0].Transmission },
  { 263, &GameSetup_gData.carInfo[0].RampSteering },
  { 264, &GameSetup_gData.carInfo[0].RampGas },
  { 265, &GameSetup_gData.carInfo[0].RampBrake },
  { 266, &GameSetup_gData.carInfo[0].Colour },
  { 267, &GameSetup_gData.carInfo[0].ColourSV },
  { 268, &GameSetup_gData.carInfo[0].ColourChange },
  { 269, &GameSetup_gData.carInfo[0].GroundEffects },
  { 270, &GameSetup_gData.carInfo[0].BrakeBias },
  { 271, &GameSetup_gData.carInfo[0].GearRatio },
  { 272, &GameSetup_gData.carInfo[0].EngineMods },
  { 273, &GameSetup_gData.carInfo[0].ABS },
  { 274, &GameSetup_gData.carInfo[0].WeightTransfer },
  { 275, &GameSetup_gData.carInfo[0].TireType },
  { 276, &GameSetup_gData.carInfo[0].carNameIndex },
  { 277, &GameSetup_gData.carInfo[0].Traction },
  { 278, &GameSetup_gData.carInfo[0].BrakeAssist },
  { 279, &GameSetup_gData.carInfo[0].Bestline },
  { 280, &GameSetup_gData.carInfo[0].Personality },
  { 281, &GameSetup_gData.carInfo[0].StartingPos },
  { 282, &GameSetup_gData.carInfo[0].HudSpeed },
  { 283, &GameSetup_gData.carInfo[0].HudTach },
  { 284, &GameSetup_gData.carInfo[0].HudMap },
  { 285, &GameSetup_gData.carInfo[0].HudOpponentID },
  { 286, &GameSetup_gData.carInfo[0].HudTime },
  { 287, &GameSetup_gData.carInfo[0].HudLapnum },
  { 288, &GameSetup_gData.carInfo[0].HudPosition },
  { 289, &GameSetup_gData.carInfo[0].HudMirror },
  { 290, &GameSetup_gData.carInfo[0].HudColour },
  { 291, &GameSetup_gData.carInfo[0].HudTachColour },
  { 292, &GameSetup_gData.carInfo[0].SpeechColour },
  { 293, &GameSetup_gData.carInfo[0].Country },
  { 294, &GameSetup_gData.carInfo[0].Camera[0] },
  { 295, &GameSetup_gData.carInfo[0].Camera[1] },
  { 296, &GameSetup_gData.carInfo[0].Camera[2] },
  { 297, &GameSetup_gData.carInfo[0].Camera[3] },
  { 0, (int *)0 },
};
