#!/usr/bin/env python3
"""W67-A5 -- port the W62-A19 .text spine to the SRC lane's linkers/nfs4.ld.

For every build/src object with a non-empty .text, compute the IMPLIED RETAIL
BASE (retail VA - our section offset, mode over the object's .text symbols --
exactly tools/probe_link.py's spine rule), sort ascending, drop objects that
would drive the location counter backwards (the 18-interleaver rule), and
rewrite the ordered per-object input-section list between the two W67-A5
markers in linkers/nfs4.ld.

EVERY generated entry is a WILDCARD pattern (`*/src/<rel>(.text)`), never an
exact filename: an exact filename inside SECTIONS that is not already a loaded
input is OPENED BY LD AS AN ADDITIONAL INPUT (the W65-A7 absolute-path trap).
tools/build.py's splat link passes no object list, so exact per-module names
would drag all 460 src objects INTO the splat image and break byte-identity.
A wildcard never loads a file; in the splat lane it matches nothing and the
image is byte-identical BY CONSTRUCTION (still proven by ldneutral.py).

usage: python scratchpad/w67a5/gen_text_spine.py [--dry]
"""
import re
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OBJDUMP = r"C:/Tools/mips-ps1/mips/bin/mipsel-none-elf-objdump"
LDS = ROOT / "linkers" / "nfs4.ld"

BEGIN = "        /* W67-A5 .text spine BEGIN (generated by scratchpad/w67a5/gen_text_spine.py"
END = "        /* W67-A5 .text spine END */"

HDRRE = re.compile(r"^(\S+):\s+file format")
SYMRE = re.compile(r"^([0-9a-f]{8})\s(.{7})\s+(\S+)\s+([0-9a-f]{8})\s(.*)$")
SECRE = re.compile(r"^\s*\d+\s+(\S+)\s+([0-9a-f]{8})\s+")
PLACEHOLDER = re.compile(r"(?:func|D|lbl)_([0-9A-Fa-f]{8})$")


def batched(seq, n):
    for i in range(0, len(seq), n):
        yield seq[i:i + n]


def symbol_vas():
    vas, dup = {}, set()
    for ln in (ROOT / "configs" / "symbol_addrs.txt").open(
            encoding="utf-8", errors="replace"):
        m = re.match(r"(\S+?)\s*=\s*(0x[0-9A-Fa-f]+);\s*//\s*type:func", ln)
        if m:
            n, v = m.group(1), int(m.group(2), 16)
            if n in vas and vas[n] != v:
                dup.add(n)
            vas.setdefault(n, v)
    for n in dup:
        del vas[n]
    return vas, dup


def scan(objs):
    data = {}
    cur = None
    for b in batched(objs, 40):
        rel = [p.relative_to(ROOT).as_posix() for p in b]
        r = subprocess.run([OBJDUMP, "-t"] + rel, capture_output=True,
                           text=True, cwd=ROOT)
        for ln in r.stdout.splitlines():
            m = HDRRE.match(ln)
            if m:
                cur = m.group(1).replace("\\", "/")
                data.setdefault(cur, {"syms": [], "secs": {}})
                continue
            m = SYMRE.match(ln)
            if m and cur:
                val, flags, sec, size, name = m.groups()
                if sec != ".text" or " d " in flags or " df " in flags:
                    continue
                data[cur]["syms"].append({"off": int(val, 16),
                                          "name": name.strip()})
    cur = None
    for b in batched(objs, 40):
        rel = [p.relative_to(ROOT).as_posix() for p in b]
        r = subprocess.run([OBJDUMP, "-h"] + rel, capture_output=True,
                           text=True, cwd=ROOT)
        for ln in r.stdout.splitlines():
            m = HDRRE.match(ln)
            if m:
                cur = m.group(1).replace("\\", "/")
                data.setdefault(cur, {"syms": [], "secs": {}})
                continue
            m = SECRE.match(ln)
            if m and cur:
                data[cur]["secs"][m.group(1)] = int(m.group(2), 16)
    return data


def main():
    dry = "--dry" in sys.argv
    objs = sorted((ROOT / "build" / "src").rglob("*.o"))
    assert objs, "no build/src objects -- refusing a vacuous spine"
    # front/main are pinned by the existing exact-name entries; skip here.
    objs = [o for o in objs
            if o.relative_to(ROOT / "build" / "src").as_posix()
            not in ("front.c.o", "main.c.o")]
    data = scan(objs)
    vas, multiva = symbol_vas()

    rows, nobase, notext = [], [], 0
    for o, d in sorted(data.items()):
        tsz = d.get("secs", {}).get(".text", 0)
        if not tsz:
            notext += 1
            continue
        bases = defaultdict(int)
        for s in d["syms"]:
            va = vas.get(s["name"])
            if va is None:
                m = PLACEHOLDER.match(s["name"])
                if m:
                    va = int(m.group(1), 16)
            if va is not None:
                bases[va - s["off"]] += 1
        if bases:
            rows.append((max(bases.items(), key=lambda kv: kv[1])[0], tsz, o))
        else:
            nobase.append(o)
    rows.sort()

    placed, dropped, cur = [], [], 0
    for base, sz, o in rows:
        if base < cur:
            dropped.append((base, sz, o))
            continue
        placed.append((base, sz, o))
        cur = base + sz
    print(f"[spine] with .text={len(rows)}  placed={len(placed)}  "
          f"dropped(interleaved)={len(dropped)}  no-base={len(nobase)}  "
          f"no-text={notext}  (multi-VA names excluded: {len(multiva)})")
    for base, sz, o in dropped:
        print(f"    dropped {base:#010x} +{sz:#x}  {o}")
    for o in nobase:
        print(f"    no-base {o}")

    inter = {o for _, _, o in dropped}
    lines = [BEGIN + ";",
             "         * order = implied retail base (VA - section offset, mode over each",
             "         * object's .text symbols) -- the W62-A19 spine rule.  Entries",
             "         * marked `interleaver' are the objects probe_link's ABSOLUTE",
             "         * placement would drop (location counter backwards); in this",
             "         * CONTIGUOUS region relative order is all there is, so they sit",
             "         * at their sorted position (the strict spine stays a subsequence).",
             "         * WILDCARD patterns on purpose: an exact filename here would be",
             "         * OPENED AS AN INPUT by the splat link (no object list ->",
             "         * byte-identity would break, W65-A7 absolute-path trap). */"]
    for base, sz, o in rows:
        rel = o.split("build/", 1)[1]
        tag = " interleaver" if o in inter else ""
        lines.append(f"        */{rel}(.text);  /* {base:#010x} +{sz:#x}{tag} */")
    lines.append(END)

    txt = LDS.read_text()
    assert "\r\n" not in txt, "nfs4.ld went CRLF -- refusing"
    if BEGIN.split("(")[0] in txt:
        # regenerate between markers
        pre, rest = txt.split(BEGIN.split(";")[0], 1)
        pre = pre.rstrip("\n") + "\n"
        _, post = rest.split(END, 1)
        new = pre + "\n".join(lines) + post
    else:
        anchor = "        build/src/main.c.o(.text);\n"
        assert anchor in txt, "text anchor not found in nfs4.ld"
        new = txt.replace(anchor, anchor + "\n".join(lines) + "\n", 1)
    if dry:
        print("[dry] not writing; generated", len(placed), "entries")
        (Path(__file__).parent / "spine_preview.txt").write_text(
            "\n".join(lines) + "\n")
        return
    LDS.write_text(new, newline="\n")
    print(f"[write] {LDS} -- {len(rows)} ordered entries "
          f"({len(placed)} spine + {len(dropped)} interleavers in-position)")
    (Path(__file__).parent / "spine_placed.txt").write_text(
        "\n".join(f"{b:#010x} {s:#x} {o}" for b, s, o in placed) + "\n")
    (Path(__file__).parent / "spine_all.txt").write_text(
        "\n".join(f"{b:#010x} {s:#x} {o}" for b, s, o in rows) + "\n")


if __name__ == "__main__":
    main()
