#include "common.h"

INCLUDE_ASM("asm/nonmatchings/front", MakeWayForMemoryCard__Fv);
INCLUDE_ASM("asm/nonmatchings/front", BringThatBeatBack__Fv);
INCLUDE_ASM("asm/nonmatchings/front", Init_Memcard__FbT0);
INCLUDE_ASM("asm/nonmatchings/front", DeInit_Memcard__Fv);
INCLUDE_ASM("asm/nonmatchings/front", SaveGame__Fs);
INCLUDE_ASM("asm/nonmatchings/front", SavePinkSlipsCars__Fss);
INCLUDE_ASM("asm/nonmatchings/front", SavePinkSlipsCarsWithErrorDialogs__Fsss);
INCLUDE_ASM("asm/nonmatchings/front", ChecksumData__FP12tMemCardData);
INCLUDE_ASM("asm/nonmatchings/front", VerifySuccessfulRead__FP12tMemCardData);
INCLUDE_ASM("asm/nonmatchings/front", Confirm__Fii);
INCLUDE_ASM("asm/nonmatchings/front", OverwriteConfirm__Fv);
INCLUDE_ASM("asm/nonmatchings/front", OverwriteAlwaysYes__Fv);
INCLUDE_ASM("asm/nonmatchings/front", FormatConfirm__Fv);
INCLUDE_ASM("asm/nonmatchings/front", LoadingRedrawProc__Fv);
INCLUDE_ASM("asm/nonmatchings/front", SavingProc__Fv);
INCLUDE_ASM("asm/nonmatchings/front", Init_MemcardFile__FR12MCRDFILE_defsb);
INCLUDE_ASM("asm/nonmatchings/front", LoadGame__FsbT1);
