#include "common.h"

INCLUDE_ASM("asm/nonmatchings/front", Cleanup__15tScreenCongrats);
INCLUDE_ASM("asm/nonmatchings/front", GetShapeInfo__15tScreenCongratsRsT1PPcT3);
INCLUDE_ASM("asm/nonmatchings/front", GetCar__15tScreenCongratsR8tCarInfo);
INCLUDE_ASM("asm/nonmatchings/front", DrawBackground__15tScreenCongrats);
INCLUDE_ASM("asm/nonmatchings/front", CalculatePrizes__15tScreenCongrats);
INCLUDE_ASM("asm/nonmatchings/front", Initialize__15tScreenCongrats);
INCLUDE_ASM("asm/nonmatchings/front", ProcessInput__15tScreenCongrats7tPlayerR13tInputKeyTypeR12tMenuCommand);
INCLUDE_ASM("asm/nonmatchings/front", ___15tScreenCongrats);
INCLUDE_ASM("asm/nonmatchings/front", DrawCongratsMessage__23tScreenPinkSlipCongrats);
INCLUDE_ASM("asm/nonmatchings/front", GetCar__23tScreenPinkSlipCongratsR8tCarInfo);
INCLUDE_ASM("asm/nonmatchings/front", CalculatePrizes__23tScreenPinkSlipCongrats);
INCLUDE_ASM("asm/nonmatchings/front", Initialize__23tScreenPinkSlipCongrats);
INCLUDE_ASM("asm/nonmatchings/front", Cleanup__23tScreenPinkSlipCongrats);
INCLUDE_ASM("asm/nonmatchings/front", ___23tScreenPinkSlipCongrats);
INCLUDE_ASM("asm/nonmatchings/front", ProcessInput__23tScreenTournamentTrophy7tPlayerR13tInputKeyTypeR12tMenuCommand);
INCLUDE_ASM("asm/nonmatchings/front", GetCar__23tScreenTournamentTrophyR8tCarInfo);
INCLUDE_ASM("asm/nonmatchings/front", DrawCongratsMessage__23tScreenTournamentTrophy);
INCLUDE_ASM("asm/nonmatchings/front", CalculatePrizes__23tScreenTournamentTrophy);
INCLUDE_ASM("asm/nonmatchings/front", ___23tScreenTournamentTrophy);
INCLUDE_ASM("asm/nonmatchings/front", GetCar__23tScreenBeTheCopCongratsR8tCarInfo);
INCLUDE_ASM("asm/nonmatchings/front", CalculatePrizes__23tScreenBeTheCopCongrats);
INCLUDE_ASM("asm/nonmatchings/front", DrawCongratsMessage__23tScreenBeTheCopCongrats);
INCLUDE_ASM("asm/nonmatchings/front", ___23tScreenBeTheCopCongrats);
INCLUDE_ASM("asm/nonmatchings/front", GetCar__25tScreenTournamentCongratsR8tCarInfo);
INCLUDE_ASM("asm/nonmatchings/front", CalculatePrizes__25tScreenTournamentCongrats);
INCLUDE_ASM("asm/nonmatchings/front", DrawCongratsMessage__25tScreenTournamentCongrats);
INCLUDE_ASM("asm/nonmatchings/front", ___25tScreenTournamentCongrats);
