#include "common.h"

INCLUDE_ASM("asm/nonmatchings/front", ClearActuators__23tScreenControllerConfig);
INCLUDE_ASM("asm/nonmatchings/front", SetActuators__23tScreenControllerConfigi);
INCLUDE_ASM("asm/nonmatchings/front", Controller_SetRamp__Fv);
INCLUDE_ASM("asm/nonmatchings/front", TurnOffShakers__23tScreenControllerConfig);
INCLUDE_ASM("asm/nonmatchings/front", ShakeIt__23tScreenControllerConfig);
INCLUDE_ASM("asm/nonmatchings/front", AnimKeyPoints__23tScreenControllerConfigbT1);
INCLUDE_ASM("asm/nonmatchings/front", CheckConfigs__23tScreenControllerConfig);
INCLUDE_ASM("asm/nonmatchings/front", SwapInController__23tScreenControllerConfig);
INCLUDE_ASM("asm/nonmatchings/front", SetCurrentController__23tScreenControllerConfigb);
INCLUDE_ASM("asm/nonmatchings/front", CalcAnimFrame__23tScreenControllerConfigi);
INCLUDE_ASM("asm/nonmatchings/front", ActualDrawController__23tScreenControllerConfigiiiii);
INCLUDE_ASM("asm/nonmatchings/front", DrawController__23tScreenControllerConfig);
INCLUDE_ASM("asm/nonmatchings/front", HorzVertLine__23tScreenControllerConfigPsb);
INCLUDE_ASM("asm/nonmatchings/front", DrawArrow__23tScreenControllerConfigPs);
INCLUDE_ASM("asm/nonmatchings/front", DrawBackground__23tScreenControllerConfig);
INCLUDE_ASM("asm/nonmatchings/front", DrawForeground__23tScreenControllerConfig);
INCLUDE_ASM("asm/nonmatchings/front", GetShapeInfo__23tScreenControllerConfigRsT1PPcT3);
INCLUDE_ASM("asm/nonmatchings/front", Initialize__23tScreenControllerConfig);
INCLUDE_ASM("asm/nonmatchings/front", Cleanup__23tScreenControllerConfig);
INCLUDE_ASM("asm/nonmatchings/front", __23tScreenControllerConfig);
INCLUDE_ASM("asm/nonmatchings/front", GetHelpText__23tScreenControllerConfig);
INCLUDE_ASM("asm/nonmatchings/front", ___23tScreenControllerConfig);
