#!/usr/bin/env python3
"""Build Route-D stage C from the syslib-mod compact libcd sources.

The normal Route-D driver intentionally scans only recon/mod.  Keep the compact
library implementation in recon/syslib-mod and feed its four linkable objects
to Route D through a generated manifest, without modifying tools/route_d.py or
the user's recon/mod/manifest.json.
"""

import json
import os
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[3]
OUT = ROOT / "build/route_d"
MANIFEST = OUT / "syslib_mod_stage_c_manifest.json"
CORE_SOURCES = (
    ROOT / "recon/syslib-mod/psx/libcd/core_api.c",
    ROOT / "recon/syslib-mod/psx/libcd/media_api.c",
    ROOT / "recon/syslib-mod/psx/libcd/drv_core.c",
    ROOT / "recon/syslib-mod/psx/libcd/movie_bridge.c",
    ROOT / "recon/syslib-mod/psx/libcd/route_d_exports.c",
)
RELOCATION_SOURCES = (
    ROOT / "recon/syslib-mod/psx/eaclib_bridge/savegp.c",
)
EXACT_PUBLIC_SOURCES = (
    ROOT / "recon/syslib-mod/psx/libcd/debug_names.c",
    ROOT / "recon/syslib/psx/libcd/cdcont.c",
    ROOT / "recon/syslib/psx/libcd/event.c",
    ROOT / "recon/syslib/psx/libcd/TYPE.c",
    ROOT / "recon/syslib/psx/libcd/toc.c",
)
RETAIL_DRIVER_SOURCE = ROOT / "recon/syslib/psx/libcd/drv.c"
SOURCES = CORE_SOURCES + RELOCATION_SOURCES + EXACT_PUBLIC_SOURCES + (RETAIL_DRIVER_SOURCE,)


def object_name(source: Path) -> str:
    return source.relative_to(ROOT).as_posix().replace("/", "__") + ".obj"


def prepare_route_d() -> None:
    subprocess.run(
        [sys.executable, "tools/route_d.py", "--stage", "B", "--no-cpe"],
        cwd=ROOT,
        check=True,
    )


def compile_sources() -> None:
    sys.path.insert(0, str(ROOT / "tools"))
    import build

    for source in SOURCES:
        relative = source.relative_to(ROOT).as_posix()
        build.PER_TU_FLAGS[relative] = {"cc1_272": True, "g_value": "0"}
        build.compile_c(source, False)


def assemble_sources() -> None:
    os.environ.update(
        NFS4_LANE_OFFICIAL="1",
        NFS4_LANE_OUT=str(OUT.relative_to(ROOT)).replace("\\", "/"),
    )
    saved_argv = sys.argv
    sys.argv = ["psylink_lane.py", "--noop"]
    sys.path.insert(0, str(ROOT / "tools/psyq_pipe"))
    sys.path.insert(0, str(ROOT / "tools"))
    try:
        import psylink_lane as lane
    finally:
        sys.argv = saved_argv

    for source in SOURCES:
        relative = source.relative_to(ROOT).as_posix()
        source_asm = ROOT / "build" / (relative + ".s")
        lane_asm = OUT / (relative.replace("/", "__") + ".s")
        output = OUT / object_name(source)
        lane.crlf(source_asm, lane_asm, front=False, pads=None, g=0)
        if output.exists():
            output.unlink()
        result = subprocess.run(
            [lane.ASPSX, "-q", "-G0", str(lane_asm), "-o", str(output)],
            cwd=ROOT,
            capture_output=True,
            text=True,
        )
        if result.returncode or not output.is_file():
            raise SystemExit(result.stdout + result.stderr)


def write_manifest(syslib_only: bool, stage_sources) -> None:
    if syslib_only:
        manifest = {
            "schema": "nfs4-route-d-manifest-v1",
            "comment": (
                "Syslib-only stage-C gate: the proven Route-C object set plus compact libcd; "
                "no recon/mod game overrides or additions."
            ),
            "override": {},
            "add_game": [],
            "add_before_libs": [],
            "fixes_before_libs": [],
            "front_libs": [],
        }
    else:
        manifest = json.loads((ROOT / "recon/mod/manifest.json").read_text())
    manifest["add_before_libs_stage_c"] = [
        source.relative_to(ROOT).as_posix() for source in stage_sources
    ]
    fixes = manifest.setdefault("fixes_before_libs", [])
    for source in RELOCATION_SOURCES:
        relative = source.relative_to(ROOT).as_posix()
        if relative not in fixes:
            fixes.append(relative)
    manifest["syslib_mod_note"] = (
        "Generated by recon/syslib-mod/tools/build_route_d_stage_c.py; "
        "the user's recon/mod manifest remains untouched."
    )
    MANIFEST.write_text(json.dumps(manifest, indent=2) + "\n")


def link_stage_c(make_cpe: bool) -> None:
    command = [
        sys.executable,
        "tools/route_d.py",
        "--stage",
        "C",
        "--no-compile",
        "--no-assemble",
        "--manifest",
        str(MANIFEST),
    ]
    if not make_cpe:
        command.append("--no-cpe")
    subprocess.run(command, cwd=ROOT, check=True)


def main() -> None:
    make_cpe = "--cpe" in sys.argv
    syslib_only = "--syslib-only" in sys.argv
    driver_only = "--driver-only" in sys.argv
    exact_public = "--exact-public" in sys.argv
    retail_driver = "--retail-driver" in sys.argv
    bridge_only = "--bridge-only" in sys.argv
    if not syslib_only:
        prepare_route_d()
    else:
        OUT.mkdir(parents=True, exist_ok=True)
    compile_sources()
    assemble_sources()
    if bridge_only:
        stage_sources = ()
    elif retail_driver:
        stage_sources = (RETAIL_DRIVER_SOURCE,) + EXACT_PUBLIC_SOURCES[1:]
    elif exact_public:
        stage_sources = (CORE_SOURCES[2],) + EXACT_PUBLIC_SOURCES
    elif driver_only:
        stage_sources = (CORE_SOURCES[2],)
    else:
        stage_sources = CORE_SOURCES
    write_manifest(syslib_only, stage_sources)
    link_stage_c(make_cpe)


if __name__ == "__main__":
    main()
