#!/usr/bin/env python3
"""Generate and verify the exact quarter-wave table from retail PsyQ CSTBL source."""
import argparse, json, re
from pathlib import Path

ROOT=Path(__file__).resolve().parents[3]
SOURCE=ROOT/'recon/syslib/psx/libgte/CSTBL.c'
DEFAULT_OUT=ROOT/'recon/syslib-mod/psx/libgte/quarter_table.inc'

def signed16(value):
    value &= 0xffff
    return value-0x10000 if value&0x8000 else value

def read_table():
    text=SOURCE.read_text(encoding='utf-8');body=text[text.index('{',text.index('rcossin_tbl[4096]'))+1:]
    body=body[:body.index('};')];words=[int(x,16) for x in re.findall(r'0x[0-9a-fA-F]{8}',body)][-4096:]
    if len(words)!=4096:raise ValueError('CSTBL parse failed')
    sine=[signed16(x) for x in words];cos=[signed16(x>>16) for x in words]
    if any(cos[i]!=sine[(i+1024)&4095] for i in range(4096)):raise ValueError('cosine shift proof failed')
    quarter=sine[:1025]
    rebuilt=[]
    for angle in range(4096):
        quadrant,pos=divmod(angle,1024)
        value=quarter[pos if not(quadrant&1) else 1024-pos]
        rebuilt.append(-value if quadrant&2 else value)
    mismatches=[i for i,(a,b) in enumerate(zip(sine,rebuilt)) if a!=b]
    if mismatches:raise ValueError(f'quarter symmetry failed at {mismatches[:8]}')
    return words,sine,quarter

def main():
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--output',type=Path,default=DEFAULT_OUT);p.add_argument('--report',type=Path);a=p.parse_args()
    words,sine,quarter=read_table();a.output.parent.mkdir(parents=True,exist_ok=True)
    lines=['/* Generated by recon/syslib-mod/tools/gen_gte_quarter.py; exact retail values. */']
    for i in range(0,len(quarter),12):lines.append(', '.join(str(x) for x in quarter[i:i+12])+(',' if i+12<len(quarter) else ''))
    a.output.write_text('\n'.join(lines)+'\n',encoding='ascii',newline='\n')
    report=dict(schema='nfs4-gte-quarter-v1',source=str(SOURCE),entries=len(quarter),bytes=len(quarter)*2,
                original_bytes=len(words)*4,saving=len(words)*4-len(quarter)*2,cosine_shift_mismatches=0,
                quarter_rebuild_mismatches=0,min=min(quarter),max=max(quarter))
    target=a.report or a.output.with_suffix('.json');target.write_text(json.dumps(report,indent=2)+'\n',encoding='utf-8')
    print(json.dumps(report,indent=2))
if __name__=='__main__':main()

