#include "common.h"

INCLUDE_ASM("asm/nonmatchings/main", _padSetAct);
INCLUDE_ASM("asm/nonmatchings/main", _padSendAtLoadInfo);
INCLUDE_ASM("asm/nonmatchings/main", _padGetActSize);
INCLUDE_ASM("asm/nonmatchings/main", _padRecvAtLoadInfo);
INCLUDE_ASM("asm/nonmatchings/main", _padLoadActInfo);
INCLUDE_ASM("asm/nonmatchings/main", _padSetActAlign);
INCLUDE_ASM("asm/nonmatchings/main", _padSetMainMode);
INCLUDE_ASM("asm/nonmatchings/main", _padCmdGetStatus);
INCLUDE_ASM("asm/nonmatchings/main", _padCmdSetMap);
INCLUDE_ASM("asm/nonmatchings/main", _padCmdGetDescR0);
INCLUDE_ASM("asm/nonmatchings/main", _padCmdGetDescR1);
INCLUDE_ASM("asm/nonmatchings/main", _padCmd4B);
INCLUDE_ASM("asm/nonmatchings/main", _padLoadActInfo_snd);
INCLUDE_ASM("asm/nonmatchings/main", _padLoadActInfo_rcv);
INCLUDE_ASM("asm/nonmatchings/main", _padSetActAlign_snd);
INCLUDE_ASM("asm/nonmatchings/main", _padSetActAlign_rcv);
INCLUDE_ASM("asm/nonmatchings/main", _padSetMainMode_snd);
INCLUDE_ASM("asm/nonmatchings/main", _padSetMainMode_rcv);
