#include "common.h"

INCLUDE_ASM("asm/nonmatchings/front", Movie_Init__Fc);
INCLUDE_ASM("asm/nonmatchings/front", Movie_DeInit__Fv);
INCLUDE_ASM("asm/nonmatchings/front", Movie_SetDecodeOffset__Fssss);
INCLUDE_ASM("asm/nonmatchings/front", Movie_Load__Fc);
INCLUDE_ASM("asm/nonmatchings/front", Movie_NextFrame__Fv);
INCLUDE_ASM("asm/nonmatchings/front", Movie_DownloadFrame__Fv);
INCLUDE_ASM("asm/nonmatchings/front", Movie_Stop__Fv);
INCLUDE_ASM("asm/nonmatchings/front", Movie_Finished__Fv);
INCLUDE_ASM("asm/nonmatchings/front", Movie_Play__Fc);
INCLUDE_ASM("asm/nonmatchings/front", play_movie__Fc);
INCLUDE_ASM("asm/nonmatchings/front", strSetDefDecEnv__FP6DECENV);
INCLUDE_ASM("asm/nonmatchings/front", strInit__FP6CdlLOCiPFe_vT2);
INCLUDE_ASM("asm/nonmatchings/front", strCallback__Fv);
INCLUDE_ASM("asm/nonmatchings/front", strNextVlc__FP6DECENV);
INCLUDE_ASM("asm/nonmatchings/front", strNext__FP6DECENV);
INCLUDE_ASM("asm/nonmatchings/front", strSync__FP6DECENVi);
INCLUDE_ASM("asm/nonmatchings/front", strKickCD__FP6CdlLOC);
