#!/usr/bin/env python3
"""W64-A19  gen_ld.py -- generate the RECON-lane linker script.

Inputs
  * scratchpad/w63a19/objdata.json      (run scratchpad/w63a19/scan.py first --
                                         a stale objdata is worth ~1% (15E))
  * configs/symbol_addrs.txt            (retail VA per text symbol)
  * linkers/nfs4_recon.data.ldfrag      (W63-A19 recon ordering of .data)
  * linkers/nfs4_recon.sdata.ldfrag     (W63-A19 recon ordering of .sdata)
Output
  * linkers/nfs4_recon.ld               (the recon-lane script)
  * scratchpad/w64a19/genld_report.txt  (spine + exclusion receipts)

The text spine is W62-A19's: each object's base is the mode of
(retail VA - our section offset) over its text symbols; objects are emitted in
base order and an object that would drive the location counter BACKWARDS is
dropped (an interleaved retail object -- see the report).

Usage:
    python scratchpad/w64a19/gen_ld.py            # write the script
    python scratchpad/w64a19/gen_ld.py --link     # ...and link it for real
"""
import json
import re
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
HERE = ROOT / "scratchpad" / "w64a19"
LD = r"C:/Tools/mips-ps1/mips/bin/mipsel-none-elf-ld.exe"
OBJDATA = ROOT / "scratchpad" / "w63a19" / "objdata.json"
TEXT_START = 0x800128F0
DATA_START = 0x8010CCD4
SDATA_START = 0x8013C54C
OVERLAY_START = 0x80010000

# ---------------------------------------------------------------- retail VAs
vas, dup = {}, set()
for ln in open(ROOT / "configs" / "symbol_addrs.txt", errors="replace"):
    m = re.match(r"(\S+?)\s*=\s*(0x[0-9A-Fa-f]+);\s*//\s*type:func", ln)
    if m:
        n, v = m.group(1), int(m.group(2), 16)
        if n in vas and vas[n] != v:
            dup.add(n)
        vas.setdefault(n, v)
for n in dup:
    del vas[n]

objdata = json.load(open(OBJDATA))

# ------------------------------------------------------------- the text spine
rows = []
nobase = []
for o, d in objdata.items():
    tsz = d.get("secs", {}).get(".text", 0)
    if not tsz:
        continue
    bases = defaultdict(int)
    for s in d["syms"]:
        if s["sec"] != ".text":
            continue
        va = vas.get(s["name"])
        if va is None:
            m = re.match(r"(?:func|D|lbl)_([0-9A-Fa-f]{8})$", s["name"])
            if m:
                va = int(m.group(1), 16)
        if va is not None:
            bases[va - s["off"]] += 1
    if bases:
        rows.append((max(bases.items(), key=lambda kv: kv[1])[0], tsz, o))
    else:
        nobase.append((tsz, o))
rows.sort()

placed, dropped, cur = [], [], 0
for base, sz, o in rows:
    if base < cur:
        dropped.append((base, sz, o))
        continue
    placed.append((base, sz, o))
    cur = base + sz

# split the spine at the FRONT overlay boundary: everything below the resident
# text start belongs to the 0x80010000 overlay window, not to the main .text.
front = [r for r in placed if r[0] < TEXT_START]
main = [r for r in placed if r[0] >= TEXT_START]

# -------------------------------------------------------------- data fragments
def frag(p):
    out = []
    for L in (ROOT / p).read_text().splitlines():
        s = L.strip()
        if s and not s.startswith("/*") and not s.startswith("*"):
            out.append("        " + s)
    return out


sdata_lines = frag("linkers/nfs4_recon.sdata.ldfrag")
data_lines = frag("linkers/nfs4_recon.data.ldfrag")
assert sdata_lines and data_lines, "empty .ldfrag -- refusing a vacuous script"

# every recon object that owns a window is already named in a fragment; the rest
# of the recon .data/.sdata is appended so nothing is silently dropped.
in_frag = set()
for L in sdata_lines + data_lines:
    m = re.search(r"(build/\S+?\.o)\(", L)
    if m:
        in_frag.add(m.group(1))

extra_data, extra_sdata = [], []
for o, d in sorted(objdata.items()):
    if not o.startswith("build/recon"):
        continue
    if d.get("secs", {}).get(".data", 0) and o not in in_frag:
        extra_data.append(f"        {o}(.data);")
    if d.get("secs", {}).get(".sdata", 0) and o not in in_frag:
        extra_sdata.append(f"        {o}(.sdata);")

# ----------------------------------------------------------------- emit the ld
L = []
A = L.append
A("/* linkers/nfs4_recon.ld -- W64-A19, GENERATED by scratchpad/w64a19/gen_ld.py.")
A(" * The RECON-lane counterpart of linkers/nfs4.ld: the ~500 reconstructed")
A(" * objects replace build/src/{front,main}.c.o, each .text placed at its")
A(" * implied retail base (W62-A19 spine), .data/.sdata ordered by the two W63")
A(" * .ldfrag files, everything else swept into trailing catch-alls.")
A(" * DO NOT EDIT BY HAND -- rerun gen_ld.py. */")
A("SECTIONS")
A("{")
A("    __romPos = 0;")
A(f"    _gp = {SDATA_START:#x};")
A("    PROVIDE(ticksA = ticks);")
A("    header_ROM_START = __romPos;")
A("    .header : AT(header_ROM_START) SUBALIGN(16)")
A("    {")
A("        build/asm/header.s.o(.data);")
A("    }")
A("    __romPos += SIZEOF(.header);")
A("")
A(f"    .rodata_front {OVERLAY_START:#x} : SUBALIGN(4)")
A("    {")
A("        build/asm/data/rdata_80010000.rodata.s.o(.rodata);")
A("    }")
for i, (base, sz, o) in enumerate(front):
    A(f"    .tf{i:04d} {base:#x} : SUBALIGN(4) {{ {o}(.text); }}")
A("")
for i, (base, sz, o) in enumerate(main):
    A(f"    .t{i:04d} {base:#x} : SUBALIGN(4) {{ {o}(.text); }}")
A("")
A(f"    .data {DATA_START:#x} : SUBALIGN(4)")
A("    {")
L.extend(data_lines)
L.extend(extra_data)
A("    }")
A("")
A(f"    .sdata {SDATA_START:#x} : SUBALIGN(4)")
A("    {")
L.extend(sdata_lines)
L.extend(extra_sdata)
A("    }")
A("")
A("    .rodata_rest : SUBALIGN(4) { *(.rodata); *(.rodata.*); }")
A("    .sbss  : SUBALIGN(4) { *(.sbss); }")
A("    .bss   : SUBALIGN(4) { *(.bss); *(COMMON); }")
A("    .data_rest : SUBALIGN(4) { *(.data); *(.sdata); *(.text); }")
A("    /DISCARD/ : { *(.pdr); *(.reginfo); *(.MIPS.abiflags);"
  " *(.gnu.attributes); *(.comment); *(.mdebug*); }")
A("}")
(ROOT / "linkers" / "nfs4_recon.ld").write_text("\n".join(L) + "\n")

rep = [f"objects with text            : {len(rows)}",
       f"  placed (front overlay)     : {len(front)}",
       f"  placed (resident .text)    : {len(main)}",
       f"  DROPPED (interleaved)      : {len(dropped)}",
       f"objects with text but NO base: {len(nobase)}",
       f".data  fragment lines        : {len(data_lines)} (+{len(extra_data)} appended)",
       f".sdata fragment lines        : {len(sdata_lines)} (+{len(extra_sdata)} appended)",
       ""]
rep.append("== DROPPED (would move the location counter backwards) ==")
for b, s, o in dropped:
    rep.append(f"  {b:#010x} {s:6d} {o}")
rep.append("")
rep.append("== TEXT BUT NO IMPLIED BASE ==")
for s, o in nobase:
    rep.append(f"  {s:6d} {o}")
(HERE / "genld_report.txt").write_text("\n".join(rep) + "\n")
print("\n".join(rep[:8]))
print("-> linkers/nfs4_recon.ld, scratchpad/w64a19/genld_report.txt")

# ----------------------------------------------------------------------- link
if "--link" in sys.argv:
    objs = sorted(objdata) + [str(p.relative_to(ROOT)).replace("\\", "/")
                              for p in sorted((ROOT / "build/asm").rglob("*.o"))]
    objs = [o for o in dict.fromkeys(objs)]
    rsp = HERE / "recon_link.rsp"
    rsp.write_text("\n".join('"%s"' % o for o in objs))
    for label, extra in (("strict", []),
                         ("multdef-ok", ["--allow-multiple-definition"])):
        cmd = [LD, "-T", str(ROOT / "linkers/nfs4_recon.ld")]
        for auto in ("undefined_syms_auto.txt", "undefined_funcs_auto.txt"):
            p = ROOT / "linkers" / auto
            if p.exists():
                cmd += ["-T", str(p)]
        cmd += extra + ["--no-check-sections", "--noinhibit-exec",
                        "-Map", str(HERE / f"recon_{label}.map"),
                        "-o", str(HERE / f"recon_{label}.elf"), "@" + str(rsp)]
        r = subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True)
        errs = [e for e in r.stderr.splitlines() if e.strip()]
        und = sorted(set(re.findall(r"undefined reference to [`']([^'\"]+)'", r.stderr)))
        mult = [e for e in errs if "multiple definition" in e]
        trunc = [e for e in errs if "relocation truncated" in e]
        (HERE / f"recon_{label}.err").write_text(r.stderr)
        print(f"[{label}] rc={r.returncode} stderr={len(errs)} "
              f"undefined-names={len(und)} multiple-def={len(mult)} "
              f"reloc-truncated={len(trunc)}")
        (HERE / f"recon_{label}_undef.txt").write_text("\n".join(und) + "\n")
