OLD = '          __asm__("" : : "i"(0));\n          scale = true;\n          __asm__("" : : "r"(scale));\n          spinTicks = ticks[0];\n          this->framenum = 0x14;\n          if ((spinTicks - this->starttick / 4) % 0x5dc < 0x2d) {\n            this->InExtraSpinTick = ticks[0];\n            this->InExtraSpin = 1;\n          }'
VARIANTS = [
  ('V1 ticks-first', OLD, '          spinTicks = ticks[0];\n          scale = true;\n          this->framenum = 0x14;\n          if ((spinTicks - this->starttick / 4) % 0x5dc < 0x2d) {\n            this->InExtraSpinTick = ticks[0];\n            this->InExtraSpin = 1;\n          }'),
  ('V2 framenum-before-ticks', OLD, '          scale = true;\n          this->framenum = 0x14;\n          spinTicks = ticks[0];\n          if ((spinTicks - this->starttick / 4) % 0x5dc < 0x2d) {\n            this->InExtraSpinTick = ticks[0];\n            this->InExtraSpin = 1;\n          }'),
  ('V3 framenum-after-if', OLD, '          scale = true;\n          spinTicks = ticks[0];\n          if ((spinTicks - this->starttick / 4) % 0x5dc < 0x2d) {\n            this->InExtraSpinTick = ticks[0];\n            this->InExtraSpin = 1;\n          }\n          this->framenum = 0x14;'),
  ('V4 starttick-temp', OLD, '          scale = true;\n          spinTicks = ticks[0];\n          {\n            int startT = this->starttick;\n            this->framenum = 0x14;\n            if ((spinTicks - startT / 4) % 0x5dc < 0x2d) {\n              this->InExtraSpinTick = ticks[0];\n              this->InExtraSpin = 1;\n            }\n          }'),
  ('V5 scale-last', OLD, '          spinTicks = ticks[0];\n          this->framenum = 0x14;\n          scale = true;\n          if ((spinTicks - this->starttick / 4) % 0x5dc < 0x2d) {\n            this->InExtraSpinTick = ticks[0];\n            this->InExtraSpin = 1;\n          }'),
  ('V6 framenum via var', OLD, '          scale = true;\n          spinTicks = ticks[0];\n          this->framenum = (short)0x14;\n          if ((spinTicks - this->starttick / 4) % 0x5dc < 0x2d) {\n            this->InExtraSpinTick = ticks[0];\n            this->InExtraSpin = 1;\n          }'),
]
