OLD = '  unsigned long carCXBits = 0x40800000;\n  __asm__("" : : "r"(carCXBits));\n  unsigned long carCYBits = 0xc0eccccd;\n\n  this->congratsMessage = kScreenCongrats_Congrats;\n  this->trophy = kTrophyNone;\n  this->smallSpinningThing = kSpinningNone;\n  this->fCarPlayer = 0;\n  this->TotalCash = 0;\n  this->CashAwarded = -1;\n  this->fCarX = 0x116;\n  *(unsigned long *)&this->fCarCX = carCXBits;\n  *(volatile short *)&this->fCarY = 0x3f;\n  *(volatile unsigned long *)&this->fCarCY = carCYBits;\n  if (this->congratsMessage == kScreenCongrats_Eliminated) {\n    this->fCarX = 0x120;\n    this->fCarY = 0x49;\n    this->fCarCY = -8.2;\n  }\n  __asm__("" : : "r"(carCXBits));\n  return;'
VARIANTS = [
  ('W1 natural floats', OLD, '  this->congratsMessage = kScreenCongrats_Congrats;\n  this->trophy = kTrophyNone;\n  this->smallSpinningThing = kSpinningNone;\n  this->fCarPlayer = 0;\n  this->TotalCash = 0;\n  this->CashAwarded = -1;\n  this->fCarX = 0x116;\n  this->fCarCX = 4.0;\n  this->fCarY = 0x3f;\n  this->fCarCY = -7.4;\n  if (this->congratsMessage == kScreenCongrats_Eliminated) {\n    this->fCarX = 0x120;\n    this->fCarY = 0x49;\n    this->fCarCY = -8.2;\n  }\n  return;'),
  ('W2 CX last', OLD, '  this->congratsMessage = kScreenCongrats_Congrats;\n  this->trophy = kTrophyNone;\n  this->smallSpinningThing = kSpinningNone;\n  this->fCarPlayer = 0;\n  this->TotalCash = 0;\n  this->CashAwarded = -1;\n  this->fCarX = 0x116;\n  this->fCarY = 0x3f;\n  this->fCarCY = -7.4;\n  this->fCarCX = 4.0;\n  if (this->congratsMessage == kScreenCongrats_Eliminated) {\n    this->fCarX = 0x120;\n    this->fCarY = 0x49;\n    this->fCarCY = -8.2;\n  }\n  return;'),
  ('W3 retail store order', OLD, '  this->trophy = kTrophyNone;\n  this->CashAwarded = -1;\n  this->fCarX = 0x116;\n  this->congratsMessage = kScreenCongrats_Congrats;\n  this->fCarY = 0x3f;\n  this->fCarCY = -7.4;\n  this->smallSpinningThing = kSpinningNone;\n  this->fCarPlayer = 0;\n  this->TotalCash = 0;\n  this->fCarCX = 4.0;\n  if (this->congratsMessage == kScreenCongrats_Eliminated) {\n    this->fCarX = 0x120;\n    this->fCarY = 0x49;\n    this->fCarCY = -8.2;\n  }\n  return;'),
  ('W4 bits, no devices', OLD, '  unsigned long carCXBits = 0x40800000;\n  unsigned long carCYBits = 0xc0eccccd;\n\n  this->congratsMessage = kScreenCongrats_Congrats;\n  this->trophy = kTrophyNone;\n  this->smallSpinningThing = kSpinningNone;\n  this->fCarPlayer = 0;\n  this->TotalCash = 0;\n  this->CashAwarded = -1;\n  this->fCarX = 0x116;\n  *(unsigned long *)&this->fCarCX = carCXBits;\n  this->fCarY = 0x3f;\n  *(unsigned long *)&this->fCarCY = carCYBits;\n  if (this->congratsMessage == kScreenCongrats_Eliminated) {\n    this->fCarX = 0x120;\n    this->fCarY = 0x49;\n    this->fCarCY = -8.2;\n  }\n  return;'),
  ('W5 bits CX-last no devices', OLD, '  unsigned long carCXBits = 0x40800000;\n  unsigned long carCYBits = 0xc0eccccd;\n\n  this->congratsMessage = kScreenCongrats_Congrats;\n  this->trophy = kTrophyNone;\n  this->smallSpinningThing = kSpinningNone;\n  this->fCarPlayer = 0;\n  this->TotalCash = 0;\n  this->CashAwarded = -1;\n  this->fCarX = 0x116;\n  this->fCarY = 0x3f;\n  *(unsigned long *)&this->fCarCY = carCYBits;\n  *(unsigned long *)&this->fCarCX = carCXBits;\n  if (this->congratsMessage == kScreenCongrats_Eliminated) {\n    this->fCarX = 0x120;\n    this->fCarY = 0x49;\n    this->fCarCY = -8.2;\n  }\n  return;'),
  ('W6 keep volatiles drop fences', OLD, '  unsigned long carCXBits = 0x40800000;\n  unsigned long carCYBits = 0xc0eccccd;\n\n  this->congratsMessage = kScreenCongrats_Congrats;\n  this->trophy = kTrophyNone;\n  this->smallSpinningThing = kSpinningNone;\n  this->fCarPlayer = 0;\n  this->TotalCash = 0;\n  this->CashAwarded = -1;\n  this->fCarX = 0x116;\n  *(unsigned long *)&this->fCarCX = carCXBits;\n  *(volatile short *)&this->fCarY = 0x3f;\n  *(volatile unsigned long *)&this->fCarCY = carCYBits;\n  if (this->congratsMessage == kScreenCongrats_Eliminated) {\n    this->fCarX = 0x120;\n    this->fCarY = 0x49;\n    this->fCarCY = -8.2;\n  }\n  return;'),
]
