import os

p = r'C:\Temp\nfs4-decomp\scratchpad\w64a6\RECEIPTS.md'
d = open(p, 'rb').read()

old = (b"**ORCHESTRATOR CANDIDATE, 1 TEXT_MOVES row (15D):** take `sw $19,0($16)` into the\n"
       b"  following `jal`'s slot with `drop_nop`. Semantically identical; objdump-verify per the\n"
       b"  `_padInitDirSeq` rule.\n")
assert d.count(old) == 1, ("a", d.count(old))
new = (b"**ORCHESTRATOR ROW -- DERIVED, PROBED AND OBJDUMP-PROVEN: see section 2a below.**\n")
d = d.replace(old, new, 1)

anchor = b"---\n\n## 3. `StCdInterrupt` 27"
assert d.count(anchor) == 1, ("b", d.count(anchor))

sec = """---

## 2a. FINISHED SPEC -- `PER_FN_TEXT_MOVES` row for CdRead's `jal CdSyncCallback` slot

**File: `scratchpad/w64a6/tm_cdread.json`** (generated by `mk_tm.py`, which asserts the
JSON round-trips back to the original regex strings -- the 14F escape hazard).

```json
{"recon/syslib/psx/libcd/cdread.c": {"CdRead": [{
   "take":  "\\\\tsw\\\\t\\\\$20,0\\\\(\\\\$16\\\\)\\\\n(?=\\\\t#\\\\.set\\\\tnovolatile\\\\n\\\\tjal\\\\tCdSyncCallback\\\\n)",
   "after": "\\\\tjal\\\\tCdSyncCallback\\\\n(?=\\\\tmove\\\\t\\\\$4,\\\\$0\\\\n)",
   "slot":  true }]}}
```

### REGISTER RECONCILED AGAINST RETAIL FIRST (the coordinator's correction is right)
`asm/nonmatchings/main/CdRead.s:80-83`:
```
sw   $s3, 0x4($s0)      ; w04 = buf
jal  CdSyncCallback
 sw  $s4, 0x0($s0)      ; DELAY SLOT  <- THIS is the store retail slots
```
`$19 = $s3` (buf, displacement 4) and `$20 = $s4` (sectors, displacement 0), `$16 = $s0`.
So the take line is **`sw $20,0($16)`**. My earlier receipt said `$19` -- that is the *w04*
store and would have moved the wrong instruction. Corrected here and in-source.

### DERIVED FROM THE CURRENT PIPELINE `.s`
`_apply_fn_splice` runs BEFORE `_apply_text_moves` (build.py:2197 then :2201), so the
moves see the POST-`-mno-split-addresses`-splice text. Region as built:
```
	#.set	volatile
	sw	$19,4($16)
	#.set	novolatile
	#.set	volatile
	sw	$20,0($16)      <- take
	#.set	novolatile
	jal	CdSyncCallback  <- after
	move	$4,$0           <- (CdReadyCallback's arg, the pin)
```
`slot: true` emits `.set noreorder / <after> / <take> / .set reorder`. **No `drop_nop`**:
the `.s` carries no nop there (maspsx materialises the branch nop itself in `is_reorder`
mode), and the TAB-form `.set\\tnoreorder` wrapper is exactly what suppresses it.

### ANCHOR LAWS (15D / 12F) -- all satisfied, verified by `tm_count.py`
| law | status |
|---|---|
| NUMERIC registers, never ABI names | `$20` / `$16` / `$4` |
| label-agnostic | neither anchor mentions a `$L...` (the splice renames them all to `$Lnosplit3_NN`) |
| lookahead-pin the TAKE | `(?=\\t#\\.set\\tnovolatile\\n\\tjal\\tCdSyncCallback\\n)` |
| lookahead-pin the AFTER | `(?=\\tmove\\t\\$4,\\$0\\n)` |
| `count == 1` over the `.ent`/`.end` region | TAKE 1, AFTER 1 |
🔴 **The AFTER pin is LOAD-BEARING, not cosmetic.** Unpinned, `\\tjal\\tCdSyncCallback\\n`
matches **twice** in the CdRead region and `_apply_text_moves` takes the FIRST -- the
watchdog arm's call, already inside `.set noreorder/.set nomacro` with
`addu $16,$16,-40` in its slot. That is precisely the 12F silently-wrong-splice hazard.

### PROBED 2x VIA vprobe (`W60_TEXT_MOVES_FILE`), WHOLE TU, ZERO PASS->FAIL
| fn | control | with the row (run 1) | with the row (run 2) |
|---|---|---|---|
| **CdRead** | FAIL 5 (104/103) | **FAIL 2 (103/103) COUNT-EXACT** | **FAIL 2 (103/103)** |
| CdReadSync | PASS (65) | PASS (65) | PASS (65) |
| _read_data_int | PASS (52) | PASS (52) | PASS (52) |
| _read_int | FAIL 15 | FAIL 15 | FAIL 15 |
| _read_issue | FAIL 8 | FAIL 8 | FAIL 8 |
| _read_sync | PASS (13) | PASS (13) | PASS (13) |

### OBJDUMP SEMANTICS PROOF (`tm_objproof.py`, the `_padInitDirSeq` trap)
Spliced object vs the retail words decoded from the oracle `.s` comment column. A word
diff counts as a reloc site ONLY where `objdump -dr` prints a relocation on that exact
address (12H anti-vacuity), never by mnemonic.
```
== leg 1: count + words
   insn count: ours 103  retail 103   EXACT
   word diffs at NON-reloc addresses (= REAL): 1
      [ 91] ours 00a03021 move a2,a1  | retail 00003021 addu $a2,$zero,$zero
== leg 2: delay slot of the 2nd `jal CdSyncCallback`
   ours   jal @insn 67, slot = ae140000  sw s4,0(s0)
   retail jal @insn 67, slot = ae140000  sw $s4,0x0($s0)
   PASS -- the w00 store IS the executed delay slot in both (not parked after it)
== leg 3: conditional-branch words (no reloc -> must be EXACT)
   compared 8, mismatches 0  PASS
== leg 4: intra-.text j/jal targets, function-relative
   ok [41] j +0xe4 | +0xe4   ok [49] j +0x7c | +0x7c
   ok [52] j +0xf0 | +0xf0   ok [55] j +0xf0 | +0xf0
   compared 4, mismatches 0  PASS
```
* **Same instruction INDEX (67) and the same WORD (`0xAE140000`) in both streams** -- the
  store executes in the delay slot; nothing became dead code.
* The single REAL residual word is `move $a2,$a1` vs `addu $a2,$zero,$zero` -- the known
  11B cse-shared-live-zero class, i.e. **the row leaves exactly one instruction between
  us and a byte-exact CdRead**, and the gate's 2 diffs are that one pair.
* **The proof tool is not vacuous:** run on the CONTROL object (no row) it reports
  `count 104 vs 103 MISMATCH` and 27 REAL word diffs from insn 67 onward, correctly
  localising the un-slotted store. Both objects are kept: `cdread_tm.o` / `cdread_ctl.o`.

### VERDICT
The row is **semantics-safe and ready to wire**. `build.py` was NOT edited; the spec is
`scratchpad/w64a6/tm_cdread.json` and reproduces with
`W60_TEXT_MOVES_FILE=scratchpad/w64a6/tm_cdread.json python tools/vprobe.py recon/syslib/psx/libcd/cdread.c <fns>`.
Note for wiring: `cdread.c` **already has** a `PER_FN_TEXT_MOVES` entry (build.py:1664) --
per 12F the `rel` key is a python dict literal, so this row must be MERGED into that
existing entry's dict, never added as a second `"recon/syslib/psx/libcd/cdread.c":` key
(a duplicate key is silently shadowed; that hazard has fired four times in the campaign).

"""
d = d.replace(anchor, sec.encode('utf-8') + anchor, 1)

tmp = p + '.tmp'
open(tmp, 'wb').write(d)
assert os.path.getsize(tmp) > 100
os.replace(tmp, p)
b = open(p, 'rb').read()
print('ok CR', b.count(13), 'NUL', b.count(0), 'size', len(b))
