#!/usr/bin/env python3
"""prepend the 2026-09-16d session checkpoint to the NFS4 hub memory file (byte-safe)"""
from pathlib import Path
P = Path('C:/Users/Vyacheslav/.claude/projects/C--Temp-claud/memory/00_current_nfs4.md')
block = """## SESSION SAVE 2026-09-16d (PSYLINK lane = PRIMARY measurement lane; dialect rewrite landed; drift oracle live)
- STATE: nfs4-decomp local HEAD ceeece10 (4e2aec52 = dialect rewrite of 35 recon files + asm/cert/, gated 90/90 objects byte-identical via scratchpad/psyq_pipe/dialect_baseline.py; ceeece10 = lane tooling). NOT pushed. GNU lane honest still 99.858%/414 (unchanged by construction). 11729 stray untracked files in the repo root (`-G0`, cta*/ct* probe leftovers) -- ask user before deleting.
- DONE (user "do" on the 3-item plan): (2) all 90 ASPSX-rejected TUs now dialect-neutral: numeric registers ($t2->$10; cc1 never emits names), `.set push/pop` -> `.set noreorder`...`.set reorder`+`.set at` (SPACE forms = maspsx passthrough), `.local` dropped, cert `.include`s -> macro-free asm/cert/{FntFlush,MemCardGetDirentry,MemCardFormat,_st_dma}.s. `X = Y` aliases STAY in source (gcc-2.8 lane defers every function body past ALL file-scope asm, so a co-located label cannot be placed from source; the 2.7.2 lane emits in order) -> psylink_lane.sn_text turns them into a label after Y's label. ASPSX 2.77: 564/564 TUs assemble. (1)+(3): LNK fully DERIVED: retail SYM order; 62 unmatched objects (56 vtables_*.cpp, drv.c=libcd BIOS.obj, cdcont.c=libcd SYS.obj, stcdint.c=C_011.obj, COUNTER_data.c, snddata.c, game/common/spchevnt.c=front half of Speech.obj) slotted right after their honest-map predecessor (consecutive split of one object is layout-neutral in a sectioned link); 19 retail-only members (unitvect, window, textsubs, hypot, hypot3d, pageflip, vsync, sdasync, P20, P26, CHCLRPAD, PATCH, A18-A21, libmcrd BIOS...) = gap objects from ROM bytes in the honest-map windows (gap_windows.json); 170 symbols nobody defines (asm/data residual labels, D_80000004-style absolutes, _gp) `equ`'d in the LNK to honest-link addresses (equ_symbols.json). PSYLINK 2.73 links 571 objects, 0 errors -> build/psyq/nfs4.{cpe,sym,map}.
- LANE TRANSLATION (sn_text, zero-byte metadata + section NAMES only): drop .type/.size; `.set maspsx_gas_reorder`->`.set reorder`; inline `.include`; alias->label; carrier subsections .data.*/.bss.*/.sdata.*/.rodata -> base section; front-overlay objects (lowest honest-map section in front range) get explicit `.section front.text/rdata/data/bss` (NOT -sfront: it would also prefix .sdata, retail keeps front sdata in main .sdata); vtables_*.cpp `.data`->`.rdata` (measurement deviation: retail vtables live in the OWNER TU's .rdata); front objects' .comm/.lcomm emitted explicitly in front.bss.
- 🔑 ASPSX 2.77 / PSYLINK 2.73 LAWS (probed, build/psyq/probe/): numeric registers only; no .set push/pop; .set at/noat/reorder/noreorder/nomacro OK; %hi/%lo OK; `.include "f"` OK; `.section .bss.x,"aw",@nobits` OK; `.section front.text` OK; NOT accepted: .type/.size/.local/.equ/.equiv/`X = Y`/`X equ Y`/bare `.rodata`/bare `.sbss`/`break 0,1` (break 1 OK); column-0 directives fine. 🔴 `.extern sym,size` is IGNORED for gp-relativity (extern small data is accessed ABSOLUTELY; only same-object .sdata/.sbss/.comm<=G symbols get gp-rel) AND `.extern` of a symbol DEFINED in the same file makes it UNDEFINED. COMMON layout per object: [explicit .bss][.lcomm in order][.comm in order], each aligned min(4,size), no size rounding. PSYLINK never aligns objects/sections (pads must be inside objects); NO ASPSX version (2.56/2.77/2.79/2.81) pads sections. LNK: `sym equ $VA` defines absolute symbols; `regs pc=,gp=` works.
- 🔑 MEASUREMENTS (scratchpad/psyq_pipe/fncompare.py --mask --vs-honest; fnwindow.py; drift.py -> drift_full.txt): symbol-anchored reloc-masked compare of our CPE vs the honest GNU image: 2441 functions, 96.114% words identical, 20 functions with shape diffs = 15 trailing 8-byte pads of retail objects (ALL frontend objects: every section padded to 8 [41/41 front .text starts 8-aligned]; Sony syslib objects mostly padded (thunks are 16 bytes = 12+nop), exceptions COUNTER/MSC02/C_004/LIBMCRD; libsn/2mbyte/eaclib/game never) + Stats_TrackEndGame (statement-level __asm__ with hand delay slot in stats.cpp: ASPSX reorder-mode inserts a nop -> C-source rule violation to fix in C++) + RaceSummary/Hud_RenderStatsView (overlays.cpp `extern int X[1] asm("StatsTimer")` carrier emits `.extern StatsTimer,4` after the definition -> ASPSX absolute) + PAD_update (pad after libc C43 thunk) + SubmitRequest (branch layout; likely a GNU-lane residual). .text drift: only 3 change points. DATA-OWNER DRIFT LIST (ours-retail size deltas): .data AIPHYSIC -0x20, bworldSm -0x30, HudPmx +0x18, Track +0x40/-0x58, TrgSfx +0x18, DrawW -0xd70, flare -0x70, night -0x158/+0x10; .sdata aicop +4, AIPHYSIC -0xc, audioclc -8, audedit -8, audioeng +0x18, audiotrk -0x18, CopSpeak +8, souffle -8, CarIO -0x218, device -0x20; .sbss collide -8, simqueue -8; .bss camera +0x3c, hrzsku +8, pad +4; front.data FEColor -8, FEScreen -8, FEMenuDefs +0xe4/-0xec (+ per-object -4 pads). Section totals ours vs retail: .rdata -0xC6C (unowned jtbl/strings), .text +0xA8, .data -0x5B4C, .sdata -0x310, front.rdata -0x2C8, front.text -0x6C, front.data -0x360, front.bss 0x19F0 vs 0x1A10.
- NEXT: (1) model the retail per-object trailing pads (pad8 from honest map: `.space 4` in that section when size%8==4) so drift isolates data ownership; (2) source fixes exposed by the SN lane: overlays.cpp StatsTimer carrier, stats.cpp statement __asm__ -> C++, drv.c/COUNTER_data.c/PAD_data.c zero-init `.data` that retail keeps in .bss, vtables into owner TUs (long-term), then the data-owner drift list above; (3) report findings to user.
- TOOLS: scratchpad/psyq_pipe/{psylink_lane.py [--assemble --link --compare], drift.py N, cpe_compare.py, fncompare.py N [--mask] [--vs-honest], fnwindow.py [--vs-honest] NAME.., images.py, boundary.py, dialect_rewrite.py [--apply], dialect_baseline.py snapshot|compare, cert_neutral.py, asmblocks.py census, classify_undef.py, map_missing.py, padcensus.py, padpairs.py, diralign.py, objalign.py}. Heredocs with backslashes STILL mangle (write scripts with the Write tool).
"""
raw = P.read_bytes()
P.write_bytes(block.encode('utf-8') + raw)
print('prepended', len(block), 'chars')
