#!/usr/bin/env python3
from pathlib import Path
P = Path('C:/Users/Vyacheslav/.claude/projects/C--Temp-claud/memory/00_current_nfs4.md')
block = """## SESSION SAVE 2026-09-17a (drift-list fixes batch 2; honest 99.890%/324; lane drift 15 points)
- STATE: nfs4-decomp HEAD = "data owners batch 2" (on top of 870cd90a). NOT pushed. Honest GNU link 99.890% (324 diff words) -- top remaining diff objects (scratchpad/psyq_pipe/honestdiff.py): screencarselect .text 38, rdata_r08 residual 25, r3dcar .rodata 24, track .text 16, fedialog .rodata 15, collide .text 14 (jtbl/rodata classes + old code residuals). PSYLINK lane: 15 drift points left (drift_full.txt): .text 3 (stats.cpp inline asm, StatsTimer carrier x2), .sdata aicop +4 (aicop.obj .sdata section alignment 8 in ours vs retail 4-aligned start -- find the .align 3), audioclc -8 ("viv"/"Tr" dead literals: needs a dead call with a char* fn; audioclc_externs.h has none), .bss camera/pad +4 (alignment), front.data FeMenuOptions -4 (0x800515a8 zero word after FECars' gCarSelected), FETextRender -4 (0x800515b4), ScreenPinkSlips/ScreenPost (flareextra static must be `= 0` .data before imageTVOrder), ScreenCongrats -4 (carRotate `= 0`), Statchk -4 (0x80052974), memcard -0x88 (Movie.obj data: movienames[5]={"NFS4TITL.XA","DEMO1AV.XA","DEMO2AV.XA","DEMO3AV.XA","EADOLBY.XA"} strings in front.rdata 0x80012754.., movieframes {1358,456,444,480,120}, movie24bit {1,1,1,1,1}, movieheight {240x5}, moviewidth {640x5}, width/height =0 @a24/a28, user_exit(short) skip_all/gPlayerNum(char) download(short) fp(24B) zero).
- 🔑 LAWS: (1) a bare discarded expression `("lit", x);` is DROPPED by the C++ front end (no literal); `if (0) fn("lit", x);` keeps the literal and, for a non-variadic or variadic dead call, adds no frame (probe build/psyq/probe/lit2.i) -- the ailife "dist=%d" was simply the live AILife_Debug call moved into .sdata by -G8. (2) Retail FRONT function statics that are zero sit in .data => they were written `static T x = 0;` (carRotate, flareextra, width/height). (3) PSYLINK honours DATA section alignment (an object whose .sdata/.data contains `.align 3` starts 8-aligned) but NOT text; ASPSX 2.56 vs 2.77 differ in `.lcomm` alignment (12-byte lcomm 4- vs 8-aligned) -- retail corrPt.47 @0x8013dfc4 (4 mod 8) hints at 2.56 rules, but a full 2.56 lane run fails 254/563 (syntax) -- unresolved. (4) The frontend objects' universal 8-byte section alignment is NOT produced by CC1PLPSX 2.8.0 vs 2.8.1-sn (identical .align output) nor by any ASPSX; modeled in the lane by trailing .align 3 on every front section.
- 🔴 gen_ld.py --link FAILS SILENTLY on ld-script ASSERTs / source_data_owners registry asserts (old elf stays): check the elf timestamp; use build/gen_ld/noassert.ld (ASSERT lines stripped) + manual ld to get a map and diff symbol addresses vs SYM to find the shift.
- WORKFLOW ADDITIONS: cutwire.py handles front_data_* stems (front ldfrag); deleting a data_extra/bss_extra JSON row is required when an object becomes ldfrag-native (else double placement); JSON row base/size can be hand-fixed (femenudefs 0x80051970/240). honestdiff.py N = per-object honest diff table.
- NEXT: (1) flareextra/carRotate `= 0` (+ order vs imageTVOrder), Statchk/FETextRender/FeMenuOptions singles, movie.cpp materialization (+ front rdata strings), audioclc dead literals; (2) the 3 .text items (stats.cpp statement asm -> C++, overlays StatsTimer carrier); (3) .bss/.sbss alignment (camera/pad) once the assembler question is settled; (4) then the honest lane's own list (jtbl/rodata residual classes).
"""
raw = P.read_bytes(); P.write_bytes(block.encode('utf-8') + raw); print('prepended', len(block))
