#!/usr/bin/env python3
"""prepend the 2026-09-16e checkpoint (data-owner fixes from the drift list) to the NFS4 hub"""
from pathlib import Path
P = Path('C:/Users/Vyacheslav/.claude/projects/C--Temp-claud/memory/00_current_nfs4.md')
block = """## SESSION SAVE 2026-09-16e (USER: "fix the source issues from the drift list" -- first batch landed; honest 99.878%/360)
- STATE: nfs4-decomp HEAD = "data owners: 20 objects emit their retail data natively" (after b7d7794b). NOT pushed. Honest GNU link (tools/gen_ld.py --link + tools/honest_measure.py) 99.858%/414 -> 99.878%/360, RECON words 290643 -> 294594 (residual bytes handed to native owners). 🔴 LESSON: `gen_ld.py --link` FAILS SILENTLY when the ld-script ASSERTs (native symbol address mismatch) or tools/source_data_owners.py registry asserts fire -- the old elf/map stay and honest_measure re-reports the OLD number. ALWAYS check `ls -la build/gen_ld/recon_multdef-ok.elf` timestamp after a relink.
- WORKFLOW (per drift item): scratchpad/psyq_pipe/objinv.py KEY (retail SYM Def records vs our object's nm), driftwin.py (per drift point: retail bytes we lack / our extra symbols), rombytes.py ADDR LEN (retail words + residual/SYM labels), fix the source, tools/tugate.py TU (all fns PASS), then hand the residual window to the object with scratchpad/psyq_pipe/cutwire.py STEM LO HI OWNER_OBJ SEC --apply (cuts the splat blocks out of asm/data/<stem>.{data,sdata}.s, rewrites the ldfrag: joins an adjacent owner line or splits the residual subsection with a <sub>_post_<tag> marker, reassembles), delete superseded rows in linkers/nfs4_recon.data_extra.json, update tools/source_data_owners.py rows (size/sha256/address) when the object is registered there, `python tools/gen_ld.py --link` (watch the asserts), honest_measure, then psylink_lane.py --assemble --link --compare + drift.py.
- FIXED THIS BATCH (all gated PASS): aiphysic (3 function statics initialized from image: GripLoss/SlowDown .data head, ReactionTime .sdata), bworldSm (sliceOffs +/-), track+trgsfx (carrier sections removed; declaration-order pin; ldfrag windows), night (LightningPauseAreas = {0} -> before the fn-static colorCreationTable), overlays (BTCPerpInfo[2][10] def), loading (static char *loading_languageNames[6] + 6 literals), font (colourRGB[16] values, shpfontclut), psxcontroller (mappings[3][13][3] values, static hoff[2]={0x4d,1}, -G8), device (Device_gDeviceList[5] table + 4 literals), draw (Draw_gView[10], gEnviro[2]), drawc (3 flash tables, static hilight_colors, gScreenMat/gMatA/gOverlay pinned; -G8 with Night_gWeatherColor/Cars_gHumanRaceCarList/Cars_gList UNSIZED in drawc_externs.h -> NightHeadlight 20/20 PASS: the old "drawc must stay -G4" item is CLOSED), textureprocess (4 initialized colour cells head its .sdata; TP_gBlendColor/gClutDepth/Fog_gBuf/openkeys pinned .data), cario (static CarIO_textureName[51] + 6 short tables + 64 literals in first-use order, int inFrontEnd last, block moved ABOVE CarIO_carPixMap), COUNTER (data merged from deleted COUNTER_data.c), ailife (`("dist=%d", dist);` discarded comma expr = compiled-out debug print; `if (0) call()` FAILS (adds a frame); -G8), souffle (-G8 + simGlobal[6]/Replay_ReplayInterface[8] real sizes so they stay absolute).
- LAWS CONFIRMED: gcc puts string literals <= G bytes into .sdata (retail TUs with small literals in .sdata are -G8 TUs); a same-object `.extern` (asm-rename alias trick) makes ASPSX treat the symbol as undefined; at -G8 every extern declared with size <= 8 becomes gp-rel -> retail-absolute ones must be declared unsized/real-sized.
- REMAINING DRIFT (see scratchpad/psyq_pipe/drift_full.txt after the re-measure): audedit "*-%s" literal (audiomus.cpp uses it -> owner question), audioclc "viv"/"Tr" 4-byte literals (not in our source), audioeng/audiotrk "*.bnk/*.tlb/*.ctb" literals (AudioEng_StartUp uses them in ours; retail audiotrk owns them), aicop +4 (phase), femenudefs SelectListNull order, front.data -4/-8 singles (FEColor/FEMenu/FEScreen/Front/ScreenTrophyInfo/ScreenController/ScreenAudio/ScreenMemcard/ScreenCongrats/drawshp), memcard -0x90 (movie.cpp data), .bss/.sbss small items (camera/hrzsku/pad/collide/simqueue `output` carrier), snddata.c/sndbss split TUs (audio engine data materialization), unowned .rdata/.data residual (jtbls/strings ~0xC60/0x5B00).
"""
raw = P.read_bytes(); P.write_bytes(block.encode('utf-8') + raw); print('prepended', len(block))
