#!/usr/bin/env python3
"""gen_ld.py -- THE CANONICAL `linkers/nfs4_recon.ld` GENERATOR (W67-A6).

Folds the three scratchpad generator legs into ONE owner:

  * scratchpad/w65a5/gen_ld.py  -- the base: text spine at implied retail
    bases, the .L LOCALIZE cut (`_jNN` jump-table pieces excluded), per-piece
    residual rodata placement, the .ldfrag data/sdata bodies;
  * scratchpad/w66a3/gen_ld.py  -- the widened `.bss` catch-all
    (`*(.bss.*)`): the canonical C_005/CDROM/BIOS/C_004 owners emit their
    disjoint retail `.bss` runs as separate nobits sections
    (.bss.st_<VA> / .bss.ds_<VA>); backup before the owner split: 3346a726;
  * scratchpad/w66a4/gen_ld.py  -- the `.rodata` legs: `.rodata_main`
    (rdata_80054548 residual pieces) + one `.roNNNN` region per anchored
    recon TU, from linkers/nfs4_recon.rodata_placement.json (the canonical
    copy of w66a4's rodownmap/mkplace output).

🔴 THE LANE-MARKER GUARD (the w66a4 §8 clobber-with-empty-git-diff hazard):
`linkers/nfs4_recon.ld` is a GENERATED SHARED FILE; two lanes' generators
overwrote each other wholesale and the clobber restored the file to HEAD, so
`git status` showed NOTHING.  This generator (a) stamps the file with its own
marker (the `GENERATED by <owner>` header line), and (b) REFUSES to overwrite
a file whose marker names an owner it does not recognise -- the recognised set
is itself + the superseded scratchpad legs (which all stamped
`scratchpad/w65a5/gen_ld.py`).  `--take-over` overrides, loudly.  Every
scratchpad gen_ld variant is superseded by this file: do not run them again.

The object census is RE-SCANNED from build/recon on every run (the 15E
stale-objdata hazard: a cached census has been measured to cost ~1% and, this
wave, to flip a spine row -- fecars vs fedialog).  `--objdata PATH` overrides
for A/B archaeology only and always prints the override loudly.

usage:
    python tools/gen_ld.py                # scan + write the script
    python tools/gen_ld.py --link         # ...and link (strict + multdef-ok)
    python tools/gen_ld.py --no-cut       # control: keep the _jNN pieces
    python tools/gen_ld.py --no-rodata    # control: skip the w66a4 .ro legs
    python tools/gen_ld.py --check-nfs4ld # verify the splat-lane nfs4.ld
                                          # piece lists (read-only; this tool
                                          # NEVER writes linkers/nfs4.ld)
"""
import json
import re
import subprocess
import sys
from collections import defaultdict
from pathlib import Path
from source_data_owners import SOURCE_DATA_OWNERS, oracle_only_objects, validate_source_data_owners, source_auxiliary_windows
from source_zero_owners import SOURCE_ZERO_OWNERS, validate_source_zero_owners, oracle_only_zero_objects

ROOT = Path(__file__).resolve().parents[1]      # tools/ -> repo root (16F!)
LD = r"C:/Tools/mips-ps1/mips/bin/mipsel-none-elf-ld.exe"
OBJDUMP = r"C:/Tools/mips-ps1/mips/bin/mipsel-none-elf-objdump"
OUTDIR = ROOT / "build" / "gen_ld"
TARGET = ROOT / "linkers" / "nfs4_recon.ld"
PLACEMENT = ROOT / "linkers" / "nfs4_recon.rodata_placement.json"
TEXT_START = 0x800128F0
DATA_START = 0x8010CCD4
SDATA_START = 0x8013C54C
OVERLAY_START = 0x80010000
FRONT_RODATA_STEM = "rdata_80010000"
MAIN_RODATA_STEM = "rdata_80054548"
MAIN_RODATA_START = 0x80054548
MAIN_RODATA_END = 0x8005797C


def source_owner_link_errors(stderr):
    """P906: --noinhibit-exec can return success despite ld ASSERT failures.

    These assertions are our exact storage contracts, not tolerated legacy
    blob-duplicate diagnostics. Never report a candidate owner link as valid
    merely because GNU ld still wrote an output image. No output is patched.
    """
    messages = ('native source data symbol address mismatch', 'native source data pointer target mismatch',
                'source data owner size mismatch', 'native zero owner size mismatch',
                'native auxiliary source window mismatch')
    return [line for line in stderr.splitlines() if any(message in line for message in messages)]

MARKER = "tools/gen_ld.py"
# markers this generator recognises as its own lineage and may overwrite;
# every scratchpad leg stamped the w65a5 string verbatim.
SUPERSEDED = {"scratchpad/w65a5/gen_ld.py"}
MARKER_RE = re.compile(r"GENERATED by (\S+)")

VA_RE = re.compile(r"/\*\s*([0-9A-Fa-f]+)\s+([0-9A-Fa-f]{8})\s")
CUT = "--no-cut" not in sys.argv


def arg_value(flag):
    if flag in sys.argv:
        i = sys.argv.index(flag)
        assert i + 1 < len(sys.argv), f"{flag} needs a value"
        return sys.argv[i + 1]
    return None


def marker_guard():
    """refuse to clobber another lane's generated file (w66a4 §8)."""
    if not TARGET.exists():
        return
    head = TARGET.read_text(errors="replace")[:400]
    m = MARKER_RE.search(head)
    owner = m.group(1).rstrip(".,)") if m else "<no marker at all>"
    if owner == MARKER or owner in SUPERSEDED:
        return
    if "--take-over" in sys.argv:
        print(f"[marker] TAKE-OVER: overwriting a file stamped by {owner}")
        return
    sys.exit(f"REFUSING to overwrite {TARGET}: its marker names {owner!r}, "
             f"which this generator does not own (recognised: {MARKER} + "
             f"{sorted(SUPERSEDED)}).  Re-run with --take-over only if that "
             f"lane is really dead.")


# ------------------------------------------------------------- object census
HDRRE = re.compile(r"^(\S+):\s+file format")
SYMRE = re.compile(r"^([0-9a-f]{8})\s(.{7})\s+(\S+)\s+([0-9a-f]{8})\s(.*)$")
SECRE = re.compile(r"^\s*\d+\s+(\S+)\s+([0-9a-f]{8})\s+")


def scan():
    """fresh {obj: {syms:[{off,sec,name}], secs:{}}} census of build/recon
    (the shape scratchpad/w66a4/scan.py produced, minus the reloc dump the
    generator never reads).  Batched objdump; empty output is a hard exit."""
    # P881: source-data ownership must not admit a stale probe/renamed TU's
    # second backing cell. Match build.py/relink.py's live-source census,
    # rather than treating every surviving cache object as a project input.
    # This changes input selection only; no object or instruction is modified.
    sources = [*(ROOT / "recon").rglob("*.cpp"), *(ROOT / "recon").rglob("*.c")]
    objs = sorted(ROOT / "build" / (str(src.relative_to(ROOT)) + ".o")
                  for src in sources
                  if (ROOT / "build" / (str(src.relative_to(ROOT)) + ".o")).is_file())
    assert objs, "no build/recon objects -- run tools/build.py --no-link first"
    data = {}

    def batches(seq, n):
        for i in range(0, len(seq), n):
            yield seq[i:i + n]

    cur = None
    for b in batches(objs, 40):
        r = subprocess.run([OBJDUMP, "-t"] + [str(p) for p in b],
                           capture_output=True, text=True)
        assert r.stdout.strip(), "objdump -t empty batch -- vacuous scan refused"
        for ln in r.stdout.splitlines():
            m = HDRRE.match(ln)
            if m:
                cur = str(Path(m.group(1)).resolve().relative_to(ROOT)).replace("\\", "/")
                data.setdefault(cur, {"syms": []})
                continue
            m = SYMRE.match(ln)
            if m and cur:
                val, flags, sec, _size, name = m.groups()
                if sec in (".reginfo", ".MIPS.abiflags", ".pdr",
                           ".gnu.attributes", ".comment", ".mdebug.abi32"):
                    continue
                if " d " in flags or " df " in flags:
                    continue
                data[cur]["syms"].append({"off": int(val, 16), "sec": sec,
                                          "name": name.strip()})
    cur = None
    for b in batches(objs, 40):
        r = subprocess.run([OBJDUMP, "-h"] + [str(p) for p in b],
                           capture_output=True, text=True)
        for ln in r.stdout.splitlines():
            m = HDRRE.match(ln)
            if m:
                cur = str(Path(m.group(1)).resolve().relative_to(ROOT)).replace("\\", "/")
                data.setdefault(cur, {"syms": []})
                data[cur].setdefault("secs", {})
                continue
            m = SECRE.match(ln)
            if m and cur:
                data[cur].setdefault("secs", {})[m.group(1)] = int(m.group(2), 16)
    return data


def check_nfs4ld():
    """READ-ONLY verification of the splat-lane script: every cut blob's
    pieces appear in linkers/nfs4.ld exactly once, in ascending VA order per
    stem (the relink_nfs4ld.py transformations are all applied and stable, so
    'regenerating' the nfs4.ld leg is a byte-neutral no-op)."""
    ld = (ROOT / "linkers" / "nfs4.ld").read_text(errors="replace")
    dataroot = ROOT / "asm" / "data"
    stems = sorted({re.sub(r"_[rjo]\d\d\..*$", "", p.name)
                    for p in dataroot.glob("*_[rjo][0-9][0-9].*.s")})
    assert stems, "no cut blob pieces under asm/data -- nothing to verify?"
    # nfs4.ld references every object once per SECTION region (.rodata /
    # .data / .bss ...), so the unit of verification is the (piece, section)
    # reference: each present at most once, and within one section region a
    # stem's rNN / jNN / oNN subsequences each ascend (blob order == VA order;
    # r and j legitimately interleave, so only the per-letter order is law).
    refs = defaultdict(list)      # (stem, sec-context) -> [(pos, letter, num)]
    bad = 0
    npieces = 0
    for stem in stems:
        for p in sorted(dataroot.glob(f"{stem}_[rjo][0-9][0-9].*.s")):
            npieces += 1
            m = re.search(r"_([rjo])(\d\d)\.", p.name)
            letter, num = m.group(1), int(m.group(2))
            # SYM ownership seams may split one broad residual into named
            # input subsections (for example .data.r13_pre / _post) so a
            # typed owning TU can replace only the exact retail byte run.
            # Accept dotted section names here; the old `\.\w+` silently
            # ignored those linker rows and weakened this verification gate.
            for r in re.finditer(re.escape(f"build/asm/data/{p.name}.o(")
                                 + r"(\.[\w.]+)\)", ld):
                refs[(stem, r.group(1))].append((r.start(), letter, num))
            seen = ld.count(f"build/asm/data/{p.name}.o(")
            if seen == 0:
                print(f"  [nfs4.ld] {p.name}: NOT referenced at all")
                bad += 1
    for (stem, sec), rr in sorted(refs.items()):
        rr.sort()
        for letter in "rjo":
            nums = [n for _, lt, n in rr if lt == letter]
            if nums != sorted(nums):
                print(f"  [nfs4.ld] {stem} {sec}: {letter}NN pieces out of "
                      f"order: {nums}")
                bad += 1
            dups = {n for n in nums if nums.count(n) > 1}
            if dups:
                print(f"  [nfs4.ld] {stem} {sec}: duplicated {letter}NN "
                      f"pieces: {sorted(dups)}")
                bad += 1
    if bad:
        sys.exit(f"nfs4.ld piece verification FAILED ({bad} rows)")
    print(f"[nfs4.ld] verified -- {npieces} cut-blob pieces over {len(stems)} "
          f"stems: every piece referenced, no per-section duplicates, "
          f"per-letter blob order held (file untouched)")


def main():
    if "--check-nfs4ld" in sys.argv:
        check_nfs4ld()
        if len(sys.argv) == 2:
            return

    marker_guard()

    # ---------------------------------------------------------- retail VAs
    vas, dup = {}, set()
    for ln in open(ROOT / "configs" / "symbol_addrs.txt", errors="replace"):
        m = re.match(r"(\S+?)\s*=\s*(0x[0-9A-Fa-f]+);\s*//\s*type:func", ln)
        if m:
            n, v = m.group(1), int(m.group(2), 16)
            if n in vas and vas[n] != v:
                dup.add(n)
            vas.setdefault(n, v)
    for n in dup:
        del vas[n]

    ov = arg_value("--objdata")
    if ov:
        print(f"[census] OVERRIDE: reading {ov} instead of a fresh scan "
              f"(A/B archaeology only -- the 15E stale-objdata hazard)")
        objdata = json.load(open(ov))
    else:
        objdata = scan()
        print(f"[census] fresh scan: {len(objdata)} objects")

    # --------------------------------------------------------- the text spine
    rows, nobase = [], []
    for o, d in objdata.items():
        tsz = d.get("secs", {}).get(".text", 0)
        if not tsz:
            continue
        bases = defaultdict(int)
        for s in d["syms"]:
            if s["sec"] != ".text":
                continue
            va = vas.get(s["name"])
            if va is None:
                m = re.match(r"(?:func|D|lbl)_([0-9A-Fa-f]{8})$", s["name"])
                if m:
                    va = int(m.group(1), 16)
            if va is not None:
                bases[va - s["off"]] += 1
        if bases:
            rows.append((max(bases.items(), key=lambda kv: kv[1])[0], tsz, o))
        else:
            nobase.append((tsz, o))
    rows.sort()

    placed, dropped, cur = [], [], 0
    for base, sz, o in rows:
        if base < cur:
            dropped.append((base, sz, o))
            continue
        placed.append((base, sz, o))
        cur = base + sz
    front = [r for r in placed if r[0] < TEXT_START]
    main_t = [r for r in placed if r[0] >= TEXT_START]

    # ------------------------------------------------ the front rodata pieces
    def piece_va(p):
        for ln in p.read_text(errors="replace").splitlines():
            m = VA_RE.search(ln)
            if m:
                return int(m.group(2), 16)
        raise AssertionError(f"{p.name}: no VA comment -- cannot place it")

    dataroot = ROOT / "asm" / "data"
    pieces = sorted(dataroot.glob(f"{FRONT_RODATA_STEM}_[rj][0-9][0-9].rodata.s"))
    whole = dataroot / f"{FRONT_RODATA_STEM}.rodata.s"
    front_ro = []
    if pieces:
        assert not whole.exists(), \
            "both the whole blob and its pieces exist -- refusing an ambiguous link"
        for p in pieces:
            front_ro.append((piece_va(p), p.name,
                             re.search(r"_(j)\d\d\.", p.name) is not None))
        front_ro.sort()
        assert front_ro[0][0] == OVERLAY_START, \
            f"first front-rodata piece is at {front_ro[0][0]:#x}, not the blob base"
    else:
        assert whole.exists(), f"no {FRONT_RODATA_STEM} blob or pieces in asm/data"
        front_ro.append((OVERLAY_START, whole.name, False))
    njtbl_front = sum(1 for _, _, j in front_ro if j)

    # every `_jNN` object of EITHER blob is dropped from the recon link
    jtbl_objs = set()
    if CUT:
        for p in sorted(dataroot.glob("*_j[0-9][0-9].*.s")):
            jtbl_objs.add(f"build/asm/data/{p.name}.o")

    # ------------------------------------------- the MAIN (resident) rodata
    mpieces = sorted(dataroot.glob(f"{MAIN_RODATA_STEM}_[rj][0-9][0-9].rodata.s"))
    mwhole = dataroot / f"{MAIN_RODATA_STEM}.rodata.s"
    main_ro = []
    if mpieces:
        assert not mwhole.exists(), \
            "both the whole blob and its pieces exist -- refusing an ambiguous link"
        for p in mpieces:
            main_ro.append((piece_va(p), p.name,
                            re.search(r"_(j)\d\d\.", p.name) is not None))
        main_ro.sort()
        assert main_ro[0][0] == MAIN_RODATA_START, \
            f"first main-rodata piece is at {main_ro[0][0]:#x}, not the blob base"
    else:
        assert mwhole.exists(), f"no {MAIN_RODATA_STEM} blob or pieces in asm/data"
        main_ro.append((MAIN_RODATA_START, mwhole.name, False))
    njtbl_main = sum(1 for _, _, j in main_ro if j)

    # the spine must not reach into the region (anti-vacuity for the region)
    for base, sz, o in placed:
        assert base >= MAIN_RODATA_END or base + sz <= MAIN_RODATA_START, \
            f"text object {o} at {base:#x}+{sz:#x} intersects the rodata-2 span"

    # ----------------------------------- the recon TUs' own .rodata windows
    RO_SPANS = [(OVERLAY_START, TEXT_START), (MAIN_RODATA_START, MAIN_RODATA_END)]
    recon_ro, recon_ro_out = [], []
    if PLACEMENT.exists() and "--no-rodata" not in sys.argv:
        for r in json.load(open(PLACEMENT)):
            row = (r["base"], r["end"], r["obj"], r["ok"])
            if any(lo <= r["base"] and r["end"] <= hi for lo, hi in RO_SPANS):
                recon_ro.append(row)
            else:
                recon_ro_out.append(row)
        recon_ro.sort()
        for a1, b1 in zip(recon_ro, recon_ro[1:]):
            assert a1[1] <= b1[0], \
                f"recon .rodata windows overlap: {a1[2]} {a1[0]:#x}..{a1[1]:#x} vs " \
                f"{b1[2]} {b1[0]:#x}..{b1[1]:#x}"
        assert recon_ro, "placement file present but no window inside a rodata span"

    # ---------------------------------------------------------- data fragments
    def frag(p):
        out = []
        for L in (ROOT / p).read_text().splitlines():
            s = L.strip()
            if s and not s.startswith("/*") and not s.startswith("*"):
                out.append("        " + s)
        return out

    sdata_lines = frag("linkers/nfs4_recon.sdata_8013C54C.ldfrag")
    data_lines = frag("linkers/nfs4_recon.data_8010CCD4.ldfrag")
    # NOTE: linkers/nfs4_recon.front_data.ldfrag is deliberately NOT read here
    # (unchanged from w65a5/w66a4: placing front_data is a separate,
    # separately-measured landing -- see the w66a4 continuation cursor).
    assert sdata_lines and data_lines, "empty .ldfrag -- refusing a vacuous script"

    # P881: native local-static storage is source-owned even though the full
    # frontend fragment above remains a separate layout task. Validate exact
    # payload and global/local offsets before removing the raw duplicate.
    # Protected-tool backups: scratchpad/p881_lasttick/backups.
    validate_source_data_owners(ROOT / "build")
    # P887: NOBITS reservations have no initialized payload to hash. Validate
    # their own source extent/symbol contract before native BSS placement.
    validate_source_zero_owners(ROOT / "build")
    # P907: a split compiler template can leave real, pre-existing raw
    # alignment bytes. Discover only explicitly validated retained pieces;
    # never append them to the shortened packed prefix at the wrong address.
    auxiliary_windows = source_auxiliary_windows()
    for window in auxiliary_windows:
        padding = window.get("retained_raw_padding")
        if padding:
            path = Path(padding["source"])
            assert path.parent.as_posix() == "asm/data" and padding["section"] == ".rodata"
            assert MAIN_RODATA_START <= padding["address"] < padding["address"] + padding["size"] <= MAIN_RODATA_END
            assert all(name != path.name for _,name,_ in main_ro)
            main_ro.append((padding["address"], path.name, False))
    main_ro.sort()

    fragment_sections = set()
    for L in sdata_lines + data_lines:
        for m in re.finditer(r"(build/\S+?\.o)\(([^)]*)\)", L):
            fragment_sections.update((m.group(1), section) for section in m.group(2).split())
    in_frag = set(fragment_sections)
    for owner in SOURCE_DATA_OWNERS:
        pair = ("build/" + owner["source"] + ".o", owner["section"])
        if owner.get("placement") == "fragment":
            assert pair in fragment_sections, f"source-data owner missing from fragment: {pair}"
        in_frag.add(pair)

    # P882: ownership is per input SECTION, not per object. Placing .data
    # must not suppress that TU's unplaced .sdata; the old object-only set
    # stranded those cells after .bss and produced real GP16 overflows.
    # Backup/diagnostic receipts: scratchpad/p882_gprel. This fixes omitted
    # section handling, not every section's still-unrecovered native address.

    extra_data, extra_sdata = [], []
    for o, d in sorted(objdata.items()):
        if not o.startswith("build/recon"):
            continue
        if d.get("secs", {}).get(".data", 0) and (o, ".data") not in in_frag:
            extra_data.append(f"        {o}(.data);")
        if d.get("secs", {}).get(".sdata", 0) and (o, ".sdata") not in in_frag:
            extra_sdata.append(f"        {o}(.sdata);")

    # --------------------------------------------------------- emit the ld
    L = []
    A = L.append
    A("/* linkers/nfs4_recon.ld -- GENERATED by tools/gen_ld.py (W67-A6 canonical;")
    A(" * folds scratchpad/{w65a5,w66a3,w66a4}/gen_ld.py -- those legs are dead).")
    A(" * The RECON-lane counterpart of linkers/nfs4.ld: the ~500 reconstructed")
    A(" * objects replace build/src/{front,main}.c.o, each .text placed at its")
    A(" * implied retail base (W62-A19 spine), .data/.sdata ordered by the three")
    A(" * per-blob-STEM .ldfrag files, everything else swept into trailing")
    A(" * catch-alls.")
    A(" *")
    A(" * .L LOCALIZE CUT (W65-A5): the splat blobs' `_jNN` jump-table pieces are")
    A(" * DUPLICATES of tables the recon TUs emit into their own .rodata")
    A(" * (scratchpad/w65a5/jtbl_own.txt: 48 byte-proven, 6 owned by containment")
    A(" * with a near-miss owner).  They are NOT linked here -- their `.L<VA>`")
    A(" * operands are src-lane local labels that no recon object defines.  Each")
    A(" * surviving residual piece is placed at its own retail VA, so dropping a")
    A(" * piece shifts nothing.")
    A(" * DO NOT EDIT BY HAND -- rerun tools/gen_ld.py. */")
    A("SECTIONS")
    A("{")
    A("    __romPos = 0;")
    A(f"    _gp = {SDATA_START:#x};")
    A("    PROVIDE(ticksA = ticks);")
    A("    header_ROM_START = __romPos;")
    A("    .header : AT(header_ROM_START) SUBALIGN(16)")
    A("    {")
    A("        build/asm/header.s.o(.data);")
    A("    }")
    A("    __romPos += SIZEOF(.header);")
    A("")
    A(f"    .rodata_front {OVERLAY_START:#x} : SUBALIGN(4)")
    A("    {")
    for va, name, isj in front_ro:
        if isj and CUT:
            A(f"        /* {va:#010x} {name} -- JUMP TABLE, recon TU owns it */")
            continue
        A(f"        . = {va - OVERLAY_START:#x};")
        A(f"        build/asm/data/{name}.o(.rodata);")
    A("    }")
    A("")
    A(f"    .rodata_main {MAIN_RODATA_START:#x} : SUBALIGN(4)")
    A("    {")
    for va, name, isj in main_ro:
        if isj and CUT:
            A(f"        /* {va:#010x} {name} -- JUMP TABLE, recon TU owns it */")
            continue
        A(f"        . = {va - MAIN_RODATA_START:#x};")
        A(f"        build/asm/data/{name}.o(.rodata);")
    A("    }")
    A("")
    A("    /* W66-A4: each anchored recon TU's OWN .rodata at its retail VA -- the")
    A("     * other half of the W65-A5 .L LOCALIZE cut.  Without these the TU's")
    A("     * jump table lands in .rodata_rest and every %hi/%lo(.rodata+N) switch")
    A("     * dispatch in its .text resolves to a non-retail address. */")
    for i, (base, end, o, ok) in enumerate(recon_ro):
        A(f"    .ro{i:04d} {base:#x} : SUBALIGN(4) {{ {o}(.rodata); }}"
          f"   /* {end - base} B{'' if ok else '  (anchor-only, E1-E5 not clean)'} */")
    # P907 auxiliary checks never select or split .rodata a second time.
    # Assert the actual selected source output, not merely the placement JSON.
    for window in auxiliary_windows:
        obj = "build/" + window["source"] + ".o"
        choices = [(i,base) for i,(base,end,o,ok) in enumerate(recon_ro) if o == obj]
        assert len(choices) == 1, "auxiliary window requires its native source rodata selection"
        i,base = choices[0]
        assert base == window["section_address"]
        assert objdata[obj]["secs"][".rodata"] == window["section_size"]
        A(f"    ASSERT(ADDR(.ro{i:04d}) == {base:#x} && SIZEOF(.ro{i:04d}) == {window['section_size']}, \"native auxiliary source window mismatch\")")
        A(f"    ASSERT(ADDR(.ro{i:04d}) + {window['offset']} == {window['address']:#x}, \"native auxiliary source window mismatch\")")
    A("")
    for i, (base, sz, o) in enumerate(front):
        A(f"    .tf{i:04d} {base:#x} : SUBALIGN(4) {{ {o}(.text); }}")
    A("")
    for i, (base, sz, o) in enumerate(main_t):
        A(f"    .t{i:04d} {base:#x} : SUBALIGN(4) {{ {o}(.text); }}")
    A("")
    A("    /* P881: source-owned native data; raw copies are oracle-only. */")
    for i, owner in enumerate(SOURCE_DATA_OWNERS):
        if owner.get("placement") == "fragment":
            # P882: selected at its native slot inside the ordered .sdata
            # fragment. Do not consume it again in a second output section.
            assert ("build/" + owner["source"] + ".o", owner["section"]) in fragment_sections
            continue
        obj = "build/" + owner["source"] + ".o"
        section = owner["section"]
        A(f"    .source_data_{i} {owner['address']:#x} : SUBALIGN(4) {{ {obj}({section}); }}")
        A(f"    ASSERT(SIZEOF(.source_data_{i}) == {owner['size']}, \"source data owner size mismatch\")")
    A("")
    A(f"    .data {DATA_START:#x} : SUBALIGN(4)")
    A("    {")
    L.extend(data_lines)
    L.extend(extra_data)
    A("    }")
    A("")
    A(f"    .sdata {SDATA_START:#x} : SUBALIGN(4)")
    A("    {")
    # P896: the first byte is now source-owned firstTime, not a raw object
    # masquerading as the section boundary. Preserve the native linker marker.
    # Backup: scratchpad/p896_checkpoint/backups/gen_ld.py.
    A("        __sdata_org = .;")
    L.extend(sdata_lines)
    L.extend(extra_sdata)
    A("    }")
    A("")
    # P906: fragment membership alone does not prove final byte placement.
    # Opted-in source owners assert each exact public symbol at its native
    # address, including Replay's real three-byte inter-section alignment.
    for owner in SOURCE_DATA_OWNERS:
        anchors = owner.get("assert_native_symbols")
        if not anchors:
            continue
        selected = owner["symbols"]
        if anchors is not True:
            # P906 AudioCmn: named public anchors locate its whole source
            # section; LOCAL statics retain their original file scope and
            # their validated in-section offsets, never exported aliases.
            assert isinstance(anchors, (tuple,list)) and len(anchors) == len(set(anchors))
            selected = [s for s in selected if s[0] in anchors]
            assert len(selected) == len(anchors), "missing public source-data anchor"
        for name,offset,size,bind,mode in selected:
            assert bind == 1 and mode == "exact", "native linker assertion needs an exact public symbol"
            A(f"    ASSERT({name} == {owner['address'] + offset:#x}, \"native source data symbol address mismatch: {name}\")")
        if owner.get("assert_native_relocation_targets"):
            for name,address,size in owner["relocation_targets"]:
                A(f"    ASSERT({name} == {address:#x}, \"native source data pointer target mismatch: {name}\")")
    A("")
    # SYM-backed tail layout exception (2026-08-21): the retail linker places
    # a second initialized-data run immediately after the primary .sdata run.
    # Keeping this explicit prevents the generic catch-all from relocating
    # simqueue.obj's STAT output/maxTicks objects and its BSS queue. Protected
    # tooling backup: scratchpad/root_sym_audit/simqueue_static_ownership_20260821/
    # gen_ld.py.before_tail_layout_20260821.bak.
    A("    /* SYM tail-data seam: simqueue.obj file-static output and maxTicksPerFrame. */")
    A("    .tail_data 0x8013dd7c : SUBALIGN(4)")
    A("    {")
    A("        build/asm/data/tail.data.s.o(.data.tail_pre_simqueue);")
    A("        build/recon/game/common/simqueue.cpp.o(.bss.simqueue_output);")
    A("        build/recon/game/common/simqueue.cpp.o(.sbss);")
    A("        build/asm/data/tail.data.s.o(.data.tail_after_simqueue);")
    A("    }")
    # P910: HUD's intervening76-byte native SBSS is selected from its real
    # NOBITS source owner below. Keep the unrelated raw suffix at its native
    # VA, not packed against the shortened prefix. No padding is invented.
    A("    .tail_after_hud_sbss 0x8013de4c : SUBALIGN(4)")
    A("    {")
    A("        build/asm/data/tail.data.s.o(.data.tail_after_hud_sbss);")
    A("    }")
    # P905: primate's intervening40 bytes are native NOBITS, not loaded tail
    # data. Its source owner is selected below; resume the following raw range
    # at its independently fixed VA without inventing a padding reservation.
    A("    .tail_after_primate 0x8013de90 : SUBALIGN(4)")
    A("    {")
    A("        build/asm/data/tail.data.s.o(.data.tail_after_primate);")
    A("    }")
    A("")
    # SYM-backed Newton BSS ownership seam (2026-08-21): the two function-local
    # static coorddef scratch objects start at 0x8013e0d8/0x8013e0e8. Their
    # 12-byte payloads retain the retail 4-byte inter-object alignment hole.
    # Without this anchor the generic .bss catch-all appends them after unrelated
    # recon objects. Protected-tooling backup:
    # scratchpad/root_sym_audit/newton_bss_ownership_20260821/
    # gen_ld.py.before_newton_bss_seam.bak.
    A("    /* SYM BSS seam: newton.obj function-local static dummy.124. */")
    A("    .newton_bss_124 0x8013e0d8 : SUBALIGN(4)")
    A("    {")
    A("        build/recon/game/common/newton.cpp.o(.bss.newton_dummy_124);")
    A("    }")
    A("")
    A("    /* SYM BSS seam: newton.obj function-local static dummy.133. */")
    A("    .newton_bss_133 0x8013e0e8 : SUBALIGN(4)")
    A("    {")
    A("        build/recon/game/common/newton.cpp.o(.bss.newton_dummy_133);")
    A("    }")
    A("")
    A("    /* SYM BSS anchor: simqueue.obj's 524-byte file-static queue. */")
    A("    .simqueue_bss 0x8013e0f4 : SUBALIGN(4)")
    A("    {")
    A("        build/recon/game/common/simqueue.cpp.o(.bss.simqueue_input_queue);")
    A("    }")
    A("")
    A("    .rodata_rest : SUBALIGN(4) { *(.rodata); *(.rodata.*); }")
    # P887: place the complete native stream/ISO/stream BSS sequence before
    # the generic catch-all can consume it. Restore the unplaced cursor;
    # do not add an invented padding reservation at the old wrong ISO site.
    # Remaining catch-all packing is explicit layout debt, regression-audited.
    # Exact backups/primary proofs: scratchpad/p887_iso and source_zero_owners.
    A("    __unplaced_zero_cursor = .;")
    for owner in SOURCE_ZERO_OWNERS:
        obj = "build/" + owner["source"] + ".o"
        out, section = owner["output"], owner["section"]
        # P910: retain an explicitly verified input alignment in the output.
        # All older owners stay at4; HUD's native76-byte block requires8.
        # Protected backup and exact alignment probes: p910_hud_sbss/backups.
        alignment = owner.get("alignment", 4)
        A(f"    {out} {owner['address']:#x} (NOLOAD) : SUBALIGN({alignment}) {{ {obj}({section}); }}")
        A(f"    ASSERT(SIZEOF({out}) == {owner['size']}, \"native zero owner size mismatch\")")
    A("    . = __unplaced_zero_cursor;")
    A("    .sbss  : SUBALIGN(4) { *(.sbss); }")
    A("    .bss   : SUBALIGN(4) { *(.bss); *(.bss.*); *(COMMON); }")
    A("    .data_rest : SUBALIGN(4) { *(.data); *(.sdata); *(.text); }")
    A("    /DISCARD/ : { *(.pdr); *(.reginfo); *(.MIPS.abiflags);"
      " *(.gnu.attributes); *(.comment); *(.mdebug*); }")
    A("}")
    TARGET.write_text("\n".join(L) + "\n")

    OUTDIR.mkdir(parents=True, exist_ok=True)
    rep = [f"cut enabled                  : {CUT}",
           f"objects with text            : {len(rows)}",
           f"  placed (front overlay)     : {len(front)}",
           f"  placed (resident .text)    : {len(main_t)}",
           f"  DROPPED (interleaved)      : {len(dropped)}",
           f"objects with text but NO base: {len(nobase)}",
           f"front rodata pieces          : {len(front_ro)} "
           f"({njtbl_front} jump-table, excluded={CUT})",
           f"_jNN objects excluded        : {len(jtbl_objs)}",
           f"main rodata pieces           : {len(main_ro)} "
           f"({njtbl_main} jump-table, excluded={CUT})",
           f"recon .rodata windows placed : {len(recon_ro)} "
           f"(+{len(recon_ro_out)} outside a rodata blob span -> data-lane ldfrag)",
           f".data  fragment lines        : {len(data_lines)} (+{len(extra_data)}"
           f" appended; front_data NOT placed -- see the w66a4 cursor)",
           f".sdata fragment lines        : {len(sdata_lines)} (+{len(extra_sdata)})",
           ""]
    rep.append("== DROPPED (would move the location counter backwards) ==")
    for b, s, o in dropped:
        rep.append(f"  {b:#010x} {s:6d} {o}")
    rep.append("")
    rep.append("== TEXT BUT NO IMPLIED BASE ==")
    for s, o in nobase:
        rep.append(f"  {s:6d} {o}")
    (OUTDIR / "genld_report.txt").write_text("\n".join(rep) + "\n")
    print("\n".join(rep[:12]))
    print(f"-> {TARGET}, {OUTDIR / 'genld_report.txt'}")

    # ------------------------------------------------------------------- link
    if "--link" in sys.argv:
        # Same live-source rule for raw inputs: removed/renamed cache objects
        # must not reintroduce an oracle copy under a different filename.
        asm_sources = [*(ROOT / "asm").glob("*.s"), *(ROOT / "asm/data").glob("*.s")]
        asm_objects = ["build/" + p.relative_to(ROOT).as_posix() + ".o"
                       for p in sorted(asm_sources)
                       if (ROOT / "build" / (p.relative_to(ROOT).as_posix() + ".o")).is_file()]
        objs = sorted(objdata) + asm_objects
        oracle_only = oracle_only_objects(ROOT / "build")
        oracle_only |= oracle_only_zero_objects(ROOT / "build")
        objs = [o for o in dict.fromkeys(objs)
                if o not in jtbl_objs and (ROOT / o).resolve() not in oracle_only]
        assert objs, "empty object list -- vacuous link refused"
        rsp = OUTDIR / "recon_link.rsp"
        rsp.write_text("\n".join('"%s"' % o for o in objs))
        tag = "" if CUT else "_nocut"
        for label, extra in (("strict", []),
                             ("multdef-ok", ["--allow-multiple-definition"])):
            cmd = [LD, "-T", str(TARGET)]
            # P881: use the same recovered linker-owned data/boundary names
            # as the standing relink/source lane. PROVIDE yields to real
            # source definitions and allocates no duplicate storage.
            for auto in ("undefined_syms_auto.txt", "undefined_funcs_auto.txt",
                         "retail_data_symbols.ld"):
                p = ROOT / "linkers" / auto
                if p.exists():
                    cmd += ["-T", str(p)]
            cmd += extra + ["--no-check-sections", "--noinhibit-exec",
                            "-Map", str(OUTDIR / f"recon_{label}{tag}.map"),
                            "-o", str(OUTDIR / f"recon_{label}{tag}.elf"),
                            "@" + str(rsp)]
            r = subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True)
            errs = [e for e in r.stderr.splitlines() if e.strip()]
            und = sorted(set(re.findall(
                r"undefined reference to [`']([^'\"]+)'", r.stderr)))
            dotl = [u for u in und if u.startswith(".L")]
            mult = [e for e in errs if "multiple definition" in e]
            trunc = [e for e in errs if "relocation truncated" in e]
            (OUTDIR / f"recon_{label}{tag}.err").write_text(r.stderr)
            print(f"[{label}{tag}] rc={r.returncode} stderr={len(errs)} "
                  f"undefined-names={len(und)} (.L={len(dotl)}) "
                  f"multiple-def={len(mult)} reloc-truncated={len(trunc)}")
            (OUTDIR / f"recon_{label}{tag}_undef.txt").write_text("\n".join(und) + "\n")
            owner_errors = source_owner_link_errors(r.stderr)
            if owner_errors:
                sys.exit('source-owner linker contract failed:\n' + '\n'.join(owner_errors))


if __name__ == "__main__":
    main()
