#!/usr/bin/env python3
"""gen_map_provide.py -- emit linkers/map_symbols_provide.ld from NFS4.MAP.

A PROVIDE(sym = retail_addr); line for every symbol in the dev-disc linker
map (== our oracle build's map).  PROVIDE yields to any real placed
definition, so this only supplies addresses for symbols the probe link does
NOT place (interleaved/dropped functions, unplaced data) -- making every
relocation in a placed object resolve to its exact retail address.  That
turns the layout probe's address-resolution diffs into the true floor
(genuine code/data byte diffs + the certificate functions).
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MAP = ROOT / 'rom' / 'NFS4.MAP'   # retail link map off the disc; not committed
OUT = ROOT / 'linkers' / 'map_symbols_provide.ld'

VALID = re.compile(r'^[A-Za-z_$.][A-Za-z0-9_$.]*$')
seen = {}
for ln in MAP.read_text(errors='replace').splitlines():
    m = re.match(r'^ ([0-9A-F]{8}) (\S+)\s*$', ln)
    if not m:
        continue
    addr, name = int(m.group(1), 16), m.group(2)
    if not VALID.match(name):
        continue
    # skip linker-reserved / section-boundary names ld defines itself
    if name in ('_gp', '__romPos', '_ftext', 'etext', '_fdata', 'edata',
                '_fbss', 'end', '_end', '_start'):
        continue
    seen.setdefault(name, addr)      # first (address order) wins; dup names identical

# Also PROVIDE every name-encoded symbol referenced (undefined) by the recon
# objects -- func_/D_/DAT_/lbl_<hex8> carry their VA in the name and are NOT in
# the MAP (mechanical names).  Scan nm -u across build/recon.
import subprocess
NM = r'C:/Tools/mips-ps1/mips/bin/mipsel-none-elf-nm.exe'
NAMEVA = re.compile(r'^(?:func|D|DAT|lbl)_([0-9A-Fa-f]{8})$')
objs = [p for p in (ROOT / 'build' / 'recon').rglob('*.o') if '__' not in p.stem]
enc = {}
for i in range(0, len(objs), 40):
    r = subprocess.run([NM, '-u'] + [str(o) for o in objs[i:i+40]],
                       capture_output=True, text=True)
    for ln in r.stdout.splitlines():
        p = ln.split()
        nm = p[-1] if p else ''
        m = NAMEVA.match(nm)
        if m and nm not in seen:
            enc.setdefault(nm, int(m.group(1), 16))

lines = ['/* GENERATED by tools/gen_map_provide.py from NFS4.MAP + name-encoded refs.',
         ' * PROVIDE(sym=retail_addr) for every map symbol AND every undefined',
         ' * func_/D_/DAT_/lbl_<hex8> the recon objects reference; yields to real',
         ' * placed definitions.  Drives probe_link reloc resolution to retail. */']
for name, addr in sorted(seen.items()):
    lines.append(f'PROVIDE({name} = 0x{addr:08X});')
for name, addr in sorted(enc.items()):
    lines.append(f'PROVIDE({name} = 0x{addr:08X});')
OUT.write_text('\n'.join(lines) + '\n')
print(f'{len(seen)} map symbols + {len(enc)} name-encoded refs -> {OUT}')
