#include "common.h"

INCLUDE_ASM("asm/nonmatchings/main", R3DCar_ChangeTrafficColor__FP8Car_tObji);
INCLUDE_ASM("asm/nonmatchings/main", R3DCar_StartUp__Fv);
INCLUDE_ASM("asm/nonmatchings/main", R3DCar_PostStartUp__Fv);
INCLUDE_ASM("asm/nonmatchings/main", R3DCar_Restart__Fv);
INCLUDE_ASM("asm/nonmatchings/main", R3DCar_CleanUp__Fv);
INCLUDE_ASM("asm/nonmatchings/main", R3DCar_ReadInCarData__FPcP8Car_tObj);
INCLUDE_ASM("asm/nonmatchings/main", R3DCcar_ReadeMapData__Fv);
INCLUDE_ASM("asm/nonmatchings/main", R3DCcar_ReadTrackShadow__Fv);
INCLUDE_ASM("asm/nonmatchings/main", R3DCar_CalcCarDimensions__FP8Car_tObjP18Transformer_zScenei);
INCLUDE_ASM("asm/nonmatchings/main", R3DCar_DeInstantiate3DCar__FP8Car_tObj);
INCLUDE_ASM("asm/nonmatchings/main", R3DCar_DeInstantiate3DCarMenu__FP8Car_tObj);
INCLUDE_ASM("asm/nonmatchings/main", R3DCar_GetFileName__FPcN20);
INCLUDE_ASM("asm/nonmatchings/main", R3DCar_LoadFileAdr__FPc);
INCLUDE_ASM("asm/nonmatchings/main", R3DCar_GetCarName__FPcii);
INCLUDE_ASM("asm/nonmatchings/main", R3DCar_Instantiate3DCar__FP8Car_tObji);
INCLUDE_ASM("asm/nonmatchings/main", R3DCar_Visibilty__FP8Car_tObjP13DRender_tView);
INCLUDE_ASM("asm/nonmatchings/main", R3DCar_TurnHeadLightOn__FP8Car_tObji);
INCLUDE_ASM("asm/nonmatchings/main", R3DCar_TurnHeadLightOff__FP8Car_tObji);
INCLUDE_ASM("asm/nonmatchings/main", R3DCar_InsertCarFacet__FP8Car_tObjP13DRender_tView);
INCLUDE_ASM("asm/nonmatchings/main", R3DCar_ReadInCarTextureMenu__FP8Car_tObjPcii);
INCLUDE_ASM("asm/nonmatchings/main", R3DCar_InsertCarFacetMenu__FP8Car_tObjP13DRender_tView);
INCLUDE_ASM("asm/nonmatchings/main", R3DCar_InsertCarFacetII__FP8Car_tObj);
INCLUDE_ASM("asm/nonmatchings/main", R3DCar_InsertCarFacetMenuII__FP8Car_tObji);
INCLUDE_ASM("asm/nonmatchings/main", R3DCar_Showroom__FP13DRender_tView);
INCLUDE_ASM("asm/nonmatchings/main", R3DCar_InsertCarFacetZ__FP8Car_tObjP13DRender_tView);
INCLUDE_ASM("asm/nonmatchings/main", R3DCar_InsertAllListFacet__FP13DRender_tView);
